/* Graph-reading questions for Parts II–IV */
[
["t9s3", 4, "gHeight", "The histogram shows the heights of S5 students. What type of variation does it show, and why?", ["Continuous: heights form a range with a bell-shaped distribution", "Discontinuous: there are clear separate groups", "No variation", "Environmental only, with no genes involved"], "Look at the shape.", "Height varies over a range with most students near the middle: continuous variation (many genes + environment)."],
["t9s3", 3, "gBlood", "Using the bar chart, which blood group is least common?", ["AB", "O", "A", "B"], "Shortest bar.", "Only 7 % of this population is group AB."],
["t11s2", 4, "gResist", "The graph shows resistant bacteria after antibiotic use began. Why does the percentage rise?", ["Selection of resistant survivors", "The antibiotic makes the bacteria resistant by changing their DNA", "The bacteria learn to resist the antibiotic after a few doses", "Resistant bacteria are killed first"], "Selection, not learning.", "This is natural selection: the antibiotic selects the resistant bacteria, which multiply."],
["t12s2", 4, "gTranspire", "The graph shows transpiration over a day. Why is it highest at about 2 pm?", ["Bright and warm: fastest evaporation", "Stomata are closed at 2 pm, so water builds up inside", "Humidity is highest at 2 pm, which speeds up evaporation", "Plants transpire most at night, but less is measured"], "Light + temperature.", "Open stomata and high temperature give the fastest water loss in the early afternoon."],
["t13s2", 3, "gSpirometer", "Using the spirometer trace, what is the tidal volume?", ["0.5 dm³", "4.5 dm³", "3 dm³", "5.8 dm³"], "Size of a normal breath.", "Normal breaths go from 3 to 3.5 dm³, so tidal volume = 0.5 dm³."],
["t13s2", 4, "gSpirometer", "Using the spirometer trace, what is the vital capacity?", ["4.5 dm³", "0.5 dm³", "5.8 dm³", "1.3 dm³"], "Deepest breath in to deepest breath out.", "5.8 − 1.3 = 4.5 dm³."],
["t14s1", 4, "gPressure", "The bar chart shows blood pressure in different vessels. Why do veins need valves?", ["Pressure in veins is very low, so valves stop blood flowing backwards", "Pressure in veins is the highest", "Valves raise the pressure", "Veins carry blood away from the heart"], "Look at the vein bar.", "At only 8 mmHg, blood could flow backwards; valves keep it moving to the heart."],
["t14s1", 4, "gPressure", "Look at the bar chart. Why does pressure fall so much in the capillaries?", ["Blood has passed through many narrow vessels", "Capillaries pump the blood more slowly than the arteries do", "Capillaries have thick walls, which press on the blood and slow it", "Blood stops completely in the capillaries before moving into the veins"], "Friction and spreading out.", "Resistance in narrow vessels and their large total area reduce pressure, which helps exchange."],
["t15s3", 4, "gHumanGrowth", "The graph shows a human growth curve. Between which ages is the growth spurt?", ["About 12 to 16 years", "0 to 2 years only", "18 to 20 years", "There is no spurt"], "Steepest part in the teens.", "The curve steepens between about 12 and 16 years: the puberty growth spurt."],
["t15s3", 4, "gSeedMass", "The graph shows the dry mass of a seedling. Why is dry mass lowest at M?", ["Stored food was used in respiration; after M the leaves photosynthesise faster than the seedling respires", "The seedling absorbed water, which made its dry mass fall", "The seed coat fell off, which is a large part of the dry mass", "Photosynthesis started on day 0, using up the stored food"], "Food used, then food made.", "Before M, respiration uses stored food; after M, photosynthesis adds more dry mass than respiration uses."],
["t17s1", 4, "gGlucose", "The graph shows blood glucose after a glucose drink. Which person is most likely diabetic?", ["Person B, because glucose rises higher and stays high", "Person A, because glucose returns to normal", "Both", "Neither"], "Who fails to return to normal?", "Person B's glucose stays high for hours, suggesting poor insulin production or response."],
["t17s2", 4, "gBreathRate", "The graph shows breathing rate. Exercise starts at S and ends at E. Why does breathing stay high briefly after E?", ["Extra CO₂ (and lactic acid) must still be removed before levels return to normal", "The lungs are damaged by the exercise, so breathing stays fast", "The person is still exercising after point E", "Oxygen levels are too high after exercise"], "Recovery.", "Breathing stays fast until CO₂ returns to normal and the oxygen debt is repaid."],
["t18s1", 4, "gPredPrey", "The graph shows hare and lynx populations. Why do lynx numbers peak after hare numbers?", ["Lynx breed after food (hares) increases", "Lynx eat plants, so their numbers depend on the season, not on hares", "Hares eat lynx, so lynx only increase after hares have died out", "The two populations are unrelated and change at random"], "Food first, then predators.", "Predator numbers lag behind prey numbers."],
["t18s2", 3, "gEnergyLevels", "Using the bar chart, what fraction of the producers' energy reaches the secondary consumers?", ["1/100 (1 %)", "1/10", "1/2", "All of it"], "10000 → 100.", "100 ÷ 10000 = 1/100: about 10 % passes at each of two steps."],
["t19s2", 4, "gAntibody", "The graph shows antibody levels after two doses of a vaccine. Why is the response to the 2nd dose faster and larger?", ["Memory cells from the 1st dose respond quickly (secondary response)", "The 2nd dose contains antibodies", "The 1st dose failed", "Antibodies are made only after the 2nd dose"], "Memory.", "The first dose produced memory cells, which trigger a rapid, strong secondary response."],
["t19s1", 4, "gDengue", "The bar chart shows Hong Kong rainfall. Why are dengue cases usually higher from May to September?", ["Heavy rain leaves stagnant water where Aedes mosquitoes breed", "Mosquitoes hate rain", "The virus grows in rainwater itself", "People drink more water"], "Where do mosquitoes breed?", "Rain creates breeding sites, so the mosquito vector population and dengue transmission rise."]
].forEach(([sid, b, svg, q, choices, hint, explain]) => QB[sid].push({ b, svg: svg === "gSpirometer" ? "gSpiro" : svg, q, choices, answer: 0, hint, explain, graph: true }));
