
/* 🔥 Hard formats, part 1: Topics 1–5 (format: see q_h0.js). */

/* ---------- Topic 1: Molecules of Life ---------- */
KH("t1s1", [
["R", "c", 5, "Ice forms on top of a pond in winter. Which statements explain how this helps fish survive?", ["Ice is less dense than liquid water, so it floats.", "The ice layer insulates the water below it.", "Ice has a higher specific heat capacity than water, so it warms the water below."], 0, ["True: hydrogen bonds hold the molecules further apart in ice, so it floats.", "True: the water below stays liquid at about 4 °C.", "False: ice does not warm the water; it only slows heat loss."], "Check each statement on its own, then pick the combination.", "Floating ice forms an insulating lid, so the water below stays liquid."],
["T", "d", 5, "A farmer tested nitrate fertiliser on wheat. Which conclusion is best supported by the results?", ["Yield rises with nitrate up to about 100–150 kg/ha; beyond that, nitrate is no longer the limiting factor", "The highest yield was 5.1 t/ha at 150 kg/ha", "Above 150 kg/ha, nitrate becomes toxic and kills the wheat", "The more nitrate is added, the higher the yield"], ["A true reading of the table, but it quotes one value: it doesn't describe the trend or explain why it levels off.", "Overclaiming: yield barely changes (5.1 to 5.0). Nothing shows plants dying.", "Incomplete: ignores the levelling off after 100 kg/ha, where another factor limits growth."], "Describe the trend, then the change in the trend.", "Yield climbs steeply at first, then levels off. Once nitrate is plentiful, something else (light, water, another mineral) limits growth.", [["Nitrate added (kg/ha)", "0", "50", "100", "150", "200"], ["Yield (t/ha)", "2.1", "3.8", "4.9", "5.1", "5.0"]]],
{ f: "K", k: "c", b: 6, q: "Kai collapsed at a summer football match. Which explanation links ALL the evidence?", case: [["🌡️", "Conditions", "34 °C and humid. Kai played for 80 minutes."], ["🥤", "Drank", "2 litres of plain water, nothing else."], ["🩸", "Blood test", "Sodium 125 mmol/L (normal 135–145)."], ["🧠", "Symptoms", "Headache, confusion, puffy fingers."]], choices: ["Sweat removed sodium; plain water replaced only the water, diluting the blood, so water entered body cells by osmosis and they swelled", "Kai was dehydrated because he didn't drink enough", "The heat denatured the proteins in his blood", "Too much salt made his cells shrink"], why: ["He drank 2 litres, and his blood sodium is LOW: the opposite of dehydration.", "Body temperature stays near 37 °C; nothing here shows denaturation.", "He drank only water. Low blood sodium makes cells swell, not shrink."], hint: "Low sodium in the blood: what does that do to water movement into cells?", explain: "Sweating loses sodium as well as water. Replacing only water dilutes the blood, so its water potential rises above that of cells; water enters cells by osmosis and they swell (including brain cells, causing headache and confusion). Sports drinks contain sodium for this reason." },
["N", "c", 6, "Marathon runners on a hot day who drink only plain water can develop dangerously low blood sodium. What is the best explanation?", ["Sodium lost in sweat is not replaced, and the extra water dilutes the sodium left in the blood", "Water contains no sodium, so drinking it removes sodium from the body", "They sweat a lot", "Their kidneys make extra sodium"], ["Drinking water does not remove sodium; it dilutes it.", "True, but only half the story: it ignores the dilution by the water they drink.", "Kidneys cannot make ions; they can only keep or excrete them."], "Two things happen at once: loss and dilution.", "Sweat removes sodium ions. Plain water replaces the water but not the ions, so the sodium concentration in the blood falls. Sports drinks contain sodium for this reason."]
]);
KH("t1s2", [
["A", "c", 5, "Triglycerides are better long-term energy stores than glycogen.", "Triglycerides release more energy per gram when respired and are insoluble in water.", 0, "Join them with 'because'.", "Fats store about twice as much energy per gram, and being insoluble they do not affect osmosis, so the 2nd statement explains the 1st."],
["E", "i", 5, "A student compared reducing sugar in three juices: 2 cm³ of juice + 2 cm³ of Benedict's solution in a boiling water bath. Juice A was heated for 2 minutes; B and C for 5 minutes. A turned green; B and C turned orange. The student concluded A has the least sugar. What is the main flaw?", ["Heating time was not controlled, so A's colour may be due to the shorter heating", "Benedict's solution should be added after heating", "Each juice should use a different volume", "Benedict's test cannot detect glucose"], ["Benedict's must be heated WITH the sample, so this isn't a flaw.", "Volumes must be the SAME; changing them adds another variable.", "Glucose is a reducing sugar, so Benedict's does detect it."], "Which variable changed apart from the juice?", "Only the type of juice should change. Juice A was heated for less time, so it had less time to form precipitate; the conclusion is not valid."],
["C", "c", 5, "Which is a valid comparison of starch and cellulose?", ["Starch is a compact store that amylase can digest, whereas cellulose forms straight chains bundled into strong fibres that humans cannot digest", "Starch is a storage molecule. Cellulose is found in cell walls.", "Starch is made of glucose, whereas cellulose is made of fructose", "Starch is found in plants, whereas cellulose is found in animals"], ["Two separate descriptions with no comparative link ('whereas'): 0 marks for a compare question.", "Both are made of glucose; the difference is how the glucose units are joined and arranged.", "Cellulose is in plant cell walls; animals make neither."], "A comparison pairs the SAME feature for both, with 'whereas'.", "Good comparisons pair one feature for both molecules with a linking word. Both are glucose polymers, but their structure suits storage vs support."],
["L", "c", 5, "Put the steps in order: how does the fat in a camel's hump help it survive in the desert?", ["Fat in the hump is respired", "Respiration releases energy and metabolic water", "The camel can go longer without food or drinking"], "Fat is turned straight into water by osmosis", "Start with what happens to the fat.", "Respiring fat releases energy, and water is a product of respiration. The trap step is wrong: osmosis moves water, it doesn't make it from fat."]
]);
KH("t1s3", [
["R", "c", 5, "Which of the following could change the 3D shape of an enzyme's active site?", ["A change in pH", "A mutation that changes one amino acid in the active site", "Keeping the enzyme at 5 °C"], 0, ["True: pH changes the charges that hold the folded shape.", "True: a different amino acid can fold differently.", "False: cold slows the enzyme but doesn't change its shape; activity returns when warmed."], "Low temperature is not the same as denaturing.", "Shape depends on the amino acid sequence and on the bonds holding the fold, which pH and heat (not cold) can disturb."],
["T", "d", 5, "Four foods were tested. Which sample contains BOTH protein and reducing sugar?", ["Sample Z", "Sample W", "Sample X", "Sample Y"], ["W has reducing sugar (brick-red), but biuret stayed blue: no protein.", "X has starch and protein, but Benedict's stayed blue: no reducing sugar.", "Y only has lipid (a cloudy emulsion)."], "Read across each row for two positive results.", "Z: Benedict's green (a little reducing sugar) and biuret purple (protein).", [["Sample", "Iodine", "Benedict's", "Biuret", "Ethanol test"], ["W", "brown", "brick-red", "blue", "clear"], ["X", "blue-black", "blue", "purple", "clear"], ["Y", "brown", "blue", "blue", "cloudy white"], ["Z", "brown", "green", "purple", "clear"]]],
{ f: "G", k: "d", b: 6, q: "Samples of a protease were HEATED to different temperatures for 10 minutes, cooled to 37 °C, and then tested. Which graph shows the activity left?", gch: [{ pts: [[20, 100], [40, 100], [50, 70], [60, 20], [70, 0], [80, 0]], smooth: false }, { pts: [[20, 30], [40, 100], [60, 30], [80, 0]] }, { pts: [[20, 20], [80, 100]], smooth: false }, { pts: [[20, 100], [50, 20], [80, 90]] }], gax: ["heated to (°C)", "activity left"], choices: ["Full activity up to about 40 °C, then a steep fall to zero", "A peak in the middle", "Rises steadily with temperature", "Falls, then recovers at high temperature"], why: ["That's activity measured AT each temperature. Here the test is at 37 °C after heating, so only permanent damage shows.", "Heating never improves an enzyme permanently.", "Denaturation is permanent: activity can't come back."], hint: "Testing at 37 °C removes the 'faster collisions' effect. What damage lasts?", explain: "Because every sample is tested at 37 °C, only lasting damage matters. Up to about 40 °C nothing is damaged; above that, more and more enzyme molecules are denatured, until none work." },
["N", "c", 5, "A fever above 42 °C can be fatal. Which explanation is best?", ["Enzymes and other proteins in body cells denature, so vital reactions slow down or stop", "Enzymes are killed by the heat", "Heat speeds up all reactions too much", "Heat breaks proteins down into amino acids"], ["Enzymes are not alive, so they can't be killed. Say 'denatured'.", "Incomplete: rates rise only up to the optimum. The danger is denaturation.", "Heat breaks the weak bonds that hold the shape, not the peptide bonds."], "What happens to protein shape at high temperature?", "Above about 40 °C, the bonds holding many proteins' shapes break. Enzymes lose their active sites and cell reactions fail."]
]);

/* ---------- Topic 2: Cellular Organisation ---------- */
KH("t2s1", [
["A", "c", 5, "An electron microscope can show the internal structure of mitochondria.", "An electron microscope has a higher magnification than a light microscope.", 1, "Is it magnification or resolution that reveals detail?", "Both are true, but detail depends on RESOLUTION (electrons have a much shorter wavelength). Magnifying without better resolution only gives a bigger blur."],
["E", "i", 5, "A student calibrated an eyepiece graticule at ×100, then measured onion cells at ×400 using the same calibration, and got a length of 400 µm. What is the flaw?", ["The calibration was done at a different magnification, so each graticule unit's value is 4 times too big", "Onion cells must be stained before they can be measured", "The coarse focus should be used at ×400", "Only one cell should be measured"], ["Staining helps you see cells but doesn't change their measured size.", "Using the coarse focus at high power can damage the slide; it's not linked to the size error.", "Measuring several cells and taking a mean is better, not worse."], "Does a graticule unit mean the same length at every magnification?", "At ×400, each graticule unit covers a quarter of the length it did at ×100. Recalibrate at every objective."],
["L", "c", 5, "Put the steps in order: why can't a light microscope show two ribosomes that are 20 nm apart?", ["Visible light has a wavelength of about 400–700 nm", "Points closer than about half the wavelength blur into one", "So the ribosomes can't be seen separately, however much the image is magnified"], "The lenses are not strong enough to magnify them", "Start with the property of light.", "Resolution is limited by wavelength. The trap step confuses magnification with resolution."],
["N", "c", 6, "A virus can't be seen with a school microscope even at ×1500. A student suggests a stronger eyepiece (×25 instead of ×15). What is the best evaluation?", ["It won't help: more magnification without better resolution just gives a bigger blur", "It will work, because enough magnification makes anything visible", "Use a brighter lamp instead", "Stain the virus with iodine instead"], ["Misconception: magnification is not resolution.", "Brightness doesn't change the resolution limit.", "Staining adds contrast but can't beat the resolution limit of light."], "Magnification vs resolution.", "Viruses (about 100 nm) are below the light microscope's resolution (about 200 nm). An electron microscope is needed."]
]);
KH("t2s2", [
["R", "c", 5, "Which organelles would you expect in large amounts in a pancreas cell that secretes digestive enzymes?", ["Rough endoplasmic reticulum", "Golgi apparatus", "Chloroplasts"], 0, ["True: ribosomes on the rough ER make the enzyme proteins.", "True: the Golgi modifies and packages proteins into vesicles for secretion.", "False: animal cells have no chloroplasts."], "Follow an enzyme from where it's made to where it leaves.", "Secretory cells have lots of rough ER and Golgi apparatus (and many mitochondria for energy)."],
["T", "d", 5, "Which cell is most likely a root hair cell?", ["Cell D", "Cell B", "Cell A", "Cell C"], ["B has chloroplasts, so it comes from a part exposed to light, like a leaf.", "No cell wall: A is an animal cell (with many mitochondria, perhaps muscle).", "No mitochondria at all: C is a prokaryote, such as a bacterium."], "Plant cell features, but no light underground.", "D has a cell wall and mitochondria but no chloroplasts: a plant cell living underground.", [["Cell", "Mitochondria", "Chloroplasts", "Cell wall"], ["A", "1500", "0", "no"], ["B", "200", "50", "yes"], ["C", "0", "0", "yes"], ["D", "300", "0", "yes"]]],
["C", "c", 5, "Which is a valid comparison of plant and animal cells?", ["Plant cells have a cellulose cell wall and usually a large permanent vacuole, whereas animal cells have neither", "Plant cells have chloroplasts. Animal cells have a nucleus.", "Plant cells have a cell membrane, whereas animal cells have a cell wall", "All plant cells have chloroplasts, whereas animal cells do not"], ["Not a comparison of the same feature, and plant cells have a nucleus too.", "Both have a membrane; only plant cells have a wall.", "Overgeneralised: root cells have no chloroplasts."], "Same feature, both cells, joined by 'whereas'.", "A comparison must pair the same feature for both cell types. Both have a nucleus, membrane, cytoplasm and mitochondria."],
{ f: "K", k: "c", b: 6, q: "A pond sample contains a mystery organism. Which conclusion is best supported by ALL the evidence?", case: [["🔬", "Microscope", "Single cells about 30 µm long, each with a nucleus."], ["🟢", "Organelles", "Chloroplasts and mitochondria. No cell wall."], ["🏊", "Behaviour", "Swims towards light using a whip-like flagellum."]], choices: ["It is a single-celled eukaryote that can photosynthesise, but it is not a plant cell", "It is a bacterium", "It is a plant cell, because it has chloroplasts", "It is an animal cell, because it moves"], why: ["It has a nucleus and chloroplasts, so it is eukaryotic.", "There is no cell wall. Chloroplasts alone don't make it a plant cell.", "Animal cells don't have chloroplasts."], hint: "Check every clue against each kingdom.", explain: "Nucleus → eukaryote; chloroplasts → photosynthesis; no cell wall → not a plant cell. Organisms like Euglena don't fit neatly into 'plant' or 'animal', which is why we classify them separately." }
]);
KH("t2s3", [
["A", "c", 5, "Bacteria are prokaryotes.", "Bacteria have no DNA.", 2, "Where is a bacterium's DNA?", "Bacteria are prokaryotes: they have no NUCLEUS, but they do have DNA, as a circular chromosome loose in the cytoplasm (plus plasmids)."],
["N", "c", 5, "Lipid-soluble anaesthetic molecules enter nerve cells much faster than glucose does. Why?", ["They dissolve in the phospholipid bilayer and diffuse straight through it, whereas glucose needs carrier proteins", "Anaesthetic molecules are smaller than water", "They are pumped in by active transport", "The membrane has large pores just for them"], ["Size is not the main reason; solubility in lipid is.", "Lipid-soluble molecules diffuse; no energy is needed.", "There are no pores that size; they cross the lipid layer itself."], "What is most of the membrane made of?", "The membrane's core is lipid. Lipid-soluble substances dissolve in it and diffuse through; glucose is not lipid-soluble."],
["E", "i", 5, "To study the effect of temperature on membranes, a student left one beetroot cube in water at each temperature, but for 10, 20 or 30 minutes. What is the main flaw?", ["Time in the water varied, so more leakage may be due to time, not temperature", "The beetroot should be boiled first", "Distilled water should be used instead of tap water", "The colour should be judged by eye, not with a colorimeter"], ["Boiling first would destroy all the membranes, so there'd be nothing to compare.", "A minor point that doesn't fix the comparison problem.", "Judging by eye is less objective, not more."], "Only one variable should change.", "Time is a second variable. Every cube must stay in the water for the same time."],
["L", "c", 5, "Put the steps in order: why does heating beetroot to 70 °C turn the water red?", ["Heat denatures membrane proteins and disrupts the phospholipid bilayer", "The membranes become much more permeable", "Red pigment leaks out of the vacuole into the water"], "Heat dissolves the cell wall", "Start with what heat does to membrane molecules.", "The pigment is held in the vacuole by membranes. The cell wall is fully permeable anyway, so it isn't what holds the pigment in."]
]);

/* ---------- Topic 3: Movement Across Membranes ---------- */
KH("t3s1", [
["R", "c", 5, "Which features increase the rate at which oxygen diffuses into a tissue?", ["A larger surface area", "A thinner exchange surface", "A smaller concentration gradient"], 0, ["True: more surface, more molecules cross at once.", "True: a shorter distance means faster diffusion.", "False: a STEEPER gradient increases the rate."], "Think of the factors in Fick's law.", "Rate rises with surface area and concentration difference, and falls with distance."],
["T", "d", 5, "Agar cubes were put in dye. Which statement best explains the trend in the results?", ["As cubes get bigger, SA:V falls and the distance to the centre rises, so diffusion takes longer to reach the centre", "The 4 cm cube has the largest surface area (96 cm²)", "Bigger cubes have less surface area, so dye can't get in", "Bigger cubes take longer because they are bigger"], ["True but irrelevant: it's surface area RELATIVE to volume that matters.", "Bigger cubes have MORE surface area; it's the ratio that is smaller.", "This just restates the result without the mechanism (SA:V and distance)."], "Look at the SA:V column.", "Volume grows faster than surface area, and the centre is further away, so the time to colour the whole cube rises steeply.", [["Side (cm)", "Surface area (cm²)", "Volume (cm³)", "SA:V", "Time to colour fully (min)"], ["1", "6", "1", "6 : 1", "4"], ["2", "24", "8", "3 : 1", "15"], ["4", "96", "64", "1.5 : 1", "58"]]],
{ f: "G", k: "d", b: 5, q: "A drop of dye is placed at the centre of a dish of still water. Which graph shows the dye concentration AT THE CENTRE over the next hour?", gch: [{ pts: [[0, 100], [1, 50], [2, 28], [4, 14], [8, 10], [10, 10]] }, { pts: [[0, 100], [10, 0]], smooth: false }, { pts: [[0, 10], [5, 60], [10, 100]] }, { pts: [[0, 100], [2, 50], [10, 50]] }], gax: ["time", "dye at centre"], choices: ["Falls fast at first, then slows and levels off at a low value", "Falls in a straight line to zero", "Rises over time", "Halves, then stays at half"], why: ["Diffusion slows as the gradient shrinks, and it never reaches zero: the dye ends up evenly spread.", "Dye moves AWAY from the centre, down its gradient.", "Spread through the whole dish, the dye is far below half its starting concentration."], hint: "How does the size of the gradient change over time?", explain: "Net movement is fastest when the gradient is steepest (at the start). As the dye spreads, the gradient falls, so diffusion slows, until the concentration is the same everywhere." },
["N", "c", 6, "A fish moves into warmer water, which holds less dissolved oxygen, and it pumps water over its gills faster. How does this help?", ["A faster flow keeps a steep oxygen concentration gradient across the gills, so diffusion continues quickly", "It makes more oxygen", "Warm water contains more oxygen", "It makes the gill membranes thinner"], ["Fish cannot make oxygen.", "Reversed: warm water holds LESS oxygen.", "Ventilation doesn't change membrane thickness."], "Gradient.", "Fresh water constantly replaces water whose oxygen has been taken up, keeping the gradient steep."]
]);
KH("t3s2", [
["A", "c", 5, "A plant cell placed in pure water does not burst.", "The plant cell wall is fully permeable.", 1, "Does permeability stop bursting?", "Both are true, but the cell doesn't burst because the cell wall is STRONG and resists expansion. Its permeability is not the reason."],
["T", "d", 6, "Potato strips were left in sucrose solutions. Why is the change at 0.8 M almost the same as at 0.6 M?", ["The cells are already plasmolysed at 0.6 M, so little more water can leave", "The strips gained water at 0.8 M", "Plant cells can never lose more than 13% of their mass", "Sucrose enters the cells at 0.8 M"], ["Misreading: −14% is a loss.", "Overclaiming: no fixed limit is shown; it depends on how much water is left.", "The membrane is partially permeable; sucrose doesn't enter significantly."], "What has happened to the cells by 0.6 M?", "Once most cells are plasmolysed, the remaining water loss is small, so the curve levels off.", [["Sucrose (M)", "0.0", "0.2", "0.4", "0.6", "0.8"], ["Mean % change in mass", "+18", "+6", "−4", "−13", "−14"]]],
["E", "i", 5, "A student cut the potato strips for each concentration from a different potato. What is the flaw?", ["Different potatoes may have different cell sap concentrations, so the potato source is uncontrolled", "Salt should be used instead of sucrose", "The strips should be left in for a shorter time", "The strips only need weighing before soaking"], ["Either solute works; that's not the flaw.", "Time must be the same and long enough; shorter isn't the fix.", "You need masses before AND after to calculate the change."], "What else differed between the strips?", "Cut all strips from the same potato (or mix strips randomly), so only the solution changes."],
["L", "c", 5, "Put the steps in order: why does salad dressed with salty dressing go limp?", ["The dressing has a lower water potential than the cell sap", "Water leaves the cells by osmosis", "The cells lose turgor, so the leaves go soft"], "Salt enters the cells and pushes the water out", "Start with the water potential comparison.", "Water moves out by osmosis. Salt does not need to enter; the trap step has the wrong mechanism."]
]);
KH("t3s3", [
["R", "c", 5, "Which of these processes need energy from respiration?", ["Uptake of mineral ions by root hair cells against a gradient", "Phagocytosis by white blood cells", "Oxygen entering the capillaries around the alveoli"], 0, ["True: active transport uses ATP.", "True: changing membrane shape to engulf a bacterium uses ATP.", "False: oxygen enters by diffusion, which is passive."], "Passive or active?", "Active transport and phagocytosis use ATP; diffusion and osmosis do not."],
{ f: "D", k: "d", b: 6, q: "Barley roots were kept in a solution of potassium ions. A respiratory poison (cyanide) was added to one set at 30 minutes. What does the graph show, and why?", chart: { x: [0, 60, 10, "time / min"], y: [0, 40, 10, "ions absorbed (units)"], series: [{ pts: [[0, 0], [30, 18], [60, 36]], smooth: false, c: G_BLUE, lbl: "no poison", lx: 44, ly: 35 }, { pts: [[0, 0], [30, 18], [60, 19]], smooth: false, c: PINK, lbl: "poison at 30 min", lx: 32, ly: 13 }] }, choices: ["Uptake stopped after the poison was added, because respiration stopped making the ATP needed for active transport", "Uptake carried on by diffusion at the same rate", "The poison destroyed the potassium ions", "The roots were already full of ions at 30 minutes"], why: ["The pink line goes flat: there's no further uptake.", "The ions are still in the solution; the roots stopped taking them in.", "The control roots kept absorbing at the same rate, so they weren't full."], hint: "Compare the two lines after 30 minutes.", explain: "Both sets absorb at the same rate until 30 minutes. Then the poisoned roots stop, because active transport needs ATP from respiration. The control shows the roots could still take up more." },
["N", "c", 6, "Cholera toxin makes gut cells pump chloride ions into the gut. Patients get severe watery diarrhoea. Why?", ["Ions in the gut lower its water potential, so water leaves the gut cells by osmosis", "The toxin destroys the gut wall, so blood leaks out", "Active transport pumps water out of the cells", "Chloride ions kill the gut bacteria"], ["The symptom is water, not blood; the mechanism is osmosis.", "Water moves by osmosis, not by pumps.", "That isn't the mechanism and explains no water movement."], "Where do the ions go, and what follows them?", "Water follows the ions by osmosis. Oral rehydration salts with glucose help patients absorb water again."],
["C", "c", 5, "Which is a valid comparison of diffusion and active transport?", ["Diffusion moves substances down a gradient without ATP, whereas active transport moves them against a gradient using ATP and carrier proteins", "Diffusion is passive. Active transport uses energy.", "Diffusion needs carrier proteins, whereas active transport does not", "Active transport is just faster diffusion"], ["Two separate statements with no comparative link.", "Reversed: active transport needs carrier proteins.", "The Warden's misconception: the direction and mechanism are different."], "Pair direction AND energy with 'whereas'.", "The key differences are direction relative to the gradient, and the need for ATP and carrier proteins."]
]);

/* ---------- Topic 4: Cell Cycle and Division ---------- */
KH("t4s1", [
["A", "c", 5, "Cells in the root tip divide by mitosis.", "Mitosis produces genetically identical cells.", 1, "Is 'identical cells' the REASON root tips divide?", "Both are true, but root tips divide by mitosis for growth. The 2nd statement describes the result, not the reason."],
["T", "d", 6, "Cells in an onion root tip were counted. The whole cell cycle takes 20 hours. About how long does metaphase last?", ["About 48 minutes", "About 8 hours", "About 4 hours", "About 0.04 hours"], ["Used the number of cells as hours.", "That's ALL of mitosis (40 of 200 cells), not just metaphase.", "Forgot to multiply the fraction by the 20-hour cycle."], "Fraction of cells × cycle time.", "8 ÷ 200 = 0.04; 0.04 × 20 h = 0.8 h = 48 minutes.", [["Stage", "Interphase", "Prophase", "Metaphase", "Anaphase", "Telophase"], ["Number of cells", "160", "20", "8", "4", "8"]]],
["E", "i", 5, "To test a chemical on mitosis, a student sampled treated root tips at 3 pm and control root tips at 9 am. What is the flaw?", ["The mitosis rate can change with the time of day, so both should be sampled at the same time", "Only interphase cells should be counted", "Leaf cells should be used instead", "The root tips should not be stained"], ["Interphase cells don't show mitosis.", "Leaves divide little; root tips are ideal.", "Stain is needed to see the chromosomes."], "Time is a hidden variable.", "Sampling time is a confounding variable. Sample both groups at the same time."],
["L", "c", 5, "Put the steps in order: how can a mutation lead to a tumour?", ["A mutation damages a gene that controls cell division", "The cell divides by mitosis uncontrollably", "A mass of abnormal cells (a tumour) forms"], "The tumour causes the mutation", "Cause comes before effect.", "The mutation comes first. The trap step reverses cause and effect."]
]);
KH("t4s2", [
["R", "c", 5, "Which processes produce genetic variation among offspring?", ["Crossing over in meiosis", "Independent assortment of chromosomes in meiosis", "Mitosis in the zygote"], 0, ["True: alleles are swapped between homologous chromosomes.", "True: each pair lines up randomly.", "False: mitosis copies the zygote's genes exactly."], "Which divisions make cells different?", "Meiosis (crossing over and independent assortment) and random fertilisation make variation; mitosis does not."],
["N", "c", 6, "Most bananas sold in shops are grown from cuttings of one variety. A fungus now threatens nearly all of them. Why are they so vulnerable?", ["They are clones with almost no genetic variation, so if one plant is susceptible, nearly all are", "Banana cells divide faster, spreading the fungus", "Bananas have no defences at all", "Cuttings are weaker than seeds"], ["There's no link between how fast cells divide and fungal spread.", "Plants do have defences; the problem is that they all share the same genes.", "Vague; misses the key idea: no variation."], "Think about genetic variation.", "Clones share the same genes, so none may carry resistance. This is why variation matters for survival."],
["C", "c", 5, "Which is a valid comparison of continuous and discontinuous variation?", ["Continuous variation shows a range of values, controlled by many genes and affected by the environment, whereas discontinuous variation falls into distinct groups, usually controlled by one gene", "Height varies. Blood group doesn't change.", "Continuous variation is genetic, whereas discontinuous variation is environmental", "Continuous variation has distinct groups, whereas discontinuous variation has a range"], ["No paired comparison, and 'doesn't change' is not the point.", "Both are genetic; continuous variation is also affected by the environment.", "Reversed."], "Pattern + cause, for both.", "Compare the pattern (range vs groups) and the cause (many genes + environment vs one gene)."],
{ f: "G", k: "d", b: 5, q: "Which graph shows the hand spans of 200 students?", gch: [{ bars: [2, 6, 14, 22, 14, 6, 2] }, { bars: [100, 100] }, { bars: [10, 10, 10, 10, 10] }, { bars: [2, 4, 8, 16, 32] }], gax: ["hand span", "students"], choices: ["A bell shape: most students in the middle, few at the extremes", "Two separate groups", "Equal numbers in every group", "Most students have the largest hands"], why: ["Two groups is discontinuous variation. Hand span varies continuously.", "Most people are near the average, not spread equally.", "Very large hands are rare, not the most common."], hint: "Hand span: continuous or discontinuous?", explain: "Hand span is controlled by many genes plus the environment, so it shows continuous variation: a bell-shaped (normal) distribution." }
]);
KH("t4s3", [
["A", "c", 5, "Meiosis produces four genetically identical cells.", "Meiosis involves two divisions.", 3, "Are the four cells identical?", "Meiosis does have two divisions, but crossing over and independent assortment make the four cells genetically different."],
["T", "d", 6, "Measurements from cells of one animal. Which cell is a gamete?", ["Cell S", "Cell R", "Cell Q", "Cell P"], ["R has half the chromosomes but still double the DNA (two chromatids each): it's after meiosis I, not yet a gamete.", "Q has doubled DNA but the full 8 chromosomes: a cell after DNA replication.", "P is the original diploid cell before copying."], "A gamete has half the chromosomes AND half the DNA.", "S has 4 chromosomes and 5 units of DNA: half of P on both counts.", [["Cell", "DNA (units)", "Chromosomes"], ["P", "10", "8"], ["Q", "20", "8"], ["R", "10", "4"], ["S", "5", "4"]]],
["L", "c", 5, "Put the steps in order: how does crossing over increase variation?", ["Homologous chromosomes pair up in meiosis I", "Chromatids swap sections of DNA", "New combinations of alleles end up in the gametes"], "New alleles are created during crossing over", "Pair, swap, result.", "Crossing over makes new COMBINATIONS of existing alleles; new alleles come only from mutation."],
["E", "i", 5, "A student models meiosis with beads but uses only ONE pair of chromosomes. What can this model NOT show?", ["Independent assortment, which needs at least two pairs", "Crossing over", "Halving of the chromosome number", "Separation of chromatids"], ["Crossing over can be shown with one pair by swapping beads.", "One pair can show 2 becoming 1.", "Meiosis II can be shown with one pair."], "Assortment of what?", "Independent assortment is about how DIFFERENT pairs line up relative to each other, so the model needs two or more pairs."]
]);

/* ---------- Topic 5: Enzymes and Metabolism ---------- */
KH("t5s1", [
["R", "c", 5, "Which statements about enzymes are correct?", ["They lower the activation energy of a reaction.", "They are unchanged at the end of the reaction.", "They make reactions happen that could never happen without them."], 0, ["True: enzymes provide a lower-energy pathway.", "True: an enzyme can be used again and again.", "False: enzymes only SPEED UP reactions that could happen anyway."], "Remember the Key-Makers' Warden.", "Enzymes are catalysts: faster reactions, lower activation energy, not used up."],
{ f: "G", k: "d", b: 6, q: "The dashed line shows product formed over time. The experiment is repeated with TWICE as much enzyme but the same amount of substrate. Which graph shows the new result (pink)?", gch: [{ ref: [[0, 0], [2, 30], [4, 48], [6, 56], [8, 60], [10, 60]], pts: [[0, 0], [1, 30], [2, 48], [3, 56], [4, 60], [10, 60]] }, { ref: [[0, 0], [2, 30], [4, 48], [6, 56], [8, 60], [10, 60]], pts: [[0, 0], [2, 30], [4, 60], [6, 90], [8, 110], [10, 120]] }, { ref: [[0, 0], [2, 30], [4, 48], [6, 56], [8, 60], [10, 60]], pts: [[0, 0], [1, 60], [2, 96], [3, 112], [4, 120], [10, 120]] }, { ref: [[0, 0], [2, 30], [4, 48], [6, 56], [8, 60], [10, 60]], pts: [[0, 0], [2, 30], [4, 48], [6, 56], [8, 60], [10, 60]] }], gax: ["time", "product"], choices: ["Steeper at the start, levelling off at the same height", "Same start, but twice as much product in the end", "Steeper AND twice as much product", "Exactly the same as before"], why: ["The final amount of product is set by the substrate, which is the same.", "The same substrate gives the same final amount of product.", "More active sites make the reaction faster."], hint: "Which variable decides how FAST? Which decides how MUCH?", explain: "Double the enzyme means double the active sites, so the initial rate doubles. But the same substrate can only make the same amount of product, so the curve levels off at the same height, sooner." },
["N", "c", 5, "Lactose-free milk is made by adding the enzyme lactase to milk. Why does it cause no symptoms in people who lack lactase?", ["Its lactose has already been broken down into glucose and galactose, which are absorbed in the small intestine", "The added lactase keeps working in their gut", "Lactose-free milk contains no sugar at all", "Lactase kills the gut bacteria"], ["The point is that the lactose is already gone before drinking.", "It still contains glucose and galactose; it often tastes sweeter.", "That isn't what lactase does."], "What is left in the milk?", "Undigested lactose reaches the large intestine, where bacteria ferment it and cause symptoms. Pre-digested milk avoids this."],
["L", "c", 5, "Put the steps in order: how does amylase digest starch?", ["Starch binds to the complementary active site", "An enzyme-substrate complex forms and activation energy is lowered", "Maltose is released and the active site is free again"], "Amylase is used up as the maltose is made", "Bind, react, release.", "The enzyme is free to work again. The trap step is the 'used up' misconception."]
]);
KH("t5s2", [
["A", "c", 5, "Pepsin works faster at pH 2 than at pH 8.", "At pH 8, the shape of pepsin's active site changes.", 0, "Join them with 'because'.", "Pepsin's optimum is about pH 2. At pH 8 its active site changes shape, so fewer substrate molecules fit: the 2nd explains the 1st."],
["T", "d", 6, "The time for an enzyme to digest its substrate was measured. Which statement best describes and explains the results?", ["The rate (1/time) rises to a peak near 40 °C, then falls as the enzyme denatures; at 60 °C it is fully denatured", "The longest time was 300 s, at 10 °C", "At 60 °C the enzyme was killed", "Time increases as temperature increases"], ["True, but just one reading: no trend and no explanation.", "Enzymes aren't alive; they denature.", "Misreads the data (time FALLS up to 40 °C) and confuses time with rate."], "Short time = fast rate.", "Rate = 1/time. It rises to about 40 °C, then falls as the active sites change shape.", [["Temperature (°C)", "10", "20", "30", "40", "50", "60"], ["Time to digest (s)", "300", "150", "75", "50", "200", "no reaction"]]],
["E", "i", 5, "A student tested pepsin from pH 1 to 7, changing the pH by adding different volumes of acid or alkali to each tube. What is the main flaw?", ["The total volume, and so the enzyme and substrate concentrations, differed; equal volumes of buffer solutions should be used", "The test should be done above 37 °C", "Pepsin doesn't work at any pH", "Starch should be used instead of protein"], ["Temperature should be constant; that's not the flaw.", "False: pepsin works well in acid.", "Pepsin is a protease, so starch is the wrong substrate."], "What else changes when you add different volumes?", "Different volumes dilute the enzyme and substrate by different amounts. Buffers set the pH without this problem."],
["C", "c", 5, "Which is a valid comparison of the effects of low and high temperature on an enzyme?", ["At low temperature the enzyme is inactive but keeps its shape, so it works again when warmed, whereas high temperature denatures the active site permanently", "Low temperature denatures enzymes, whereas high temperature activates them", "Both low and high temperatures kill enzymes", "Low temperature: slow. High temperature: denatured."], ["Reversed and wrong.", "Enzymes aren't alive, and cold doesn't denature them.", "Two fragments with no comparison or explanation."], "Reversible vs irreversible.", "Cold slows molecules but keeps the shape; heat breaks the bonds that hold the shape."]
]);
KH("t5s3", [
["R", "c", 6, "Methanol poisoning is treated with ethanol, which competes with methanol for the same enzyme's active site. Which statements are correct?", ["Ethanol acts as a competitive inhibitor of methanol breakdown.", "A high ethanol concentration slows the conversion of methanol into toxic products.", "Ethanol permanently changes the shape of the active site."], 0, ["True: it occupies the same active site.", "True: more ethanol wins more active sites, so methanol is broken down slowly and excreted.", "False: competitive inhibitors bind reversibly and don't change the shape."], "Competitive = same active site, reversible.", "Ethanol outcompetes methanol for the enzyme, so less toxic product forms while methanol leaves the body."],
["T", "d", 6, "Rates of reaction were measured with no inhibitor, inhibitor X or inhibitor Y. Which conclusion is correct?", ["X is competitive (its effect shrinks at high substrate); Y is non-competitive (the rate stays about half of normal)", "Both are competitive inhibitors", "X is non-competitive because it lowers the rate at low substrate", "Y is the stronger inhibitor at every concentration"], ["Y's rate stays about 50% even at high substrate: more substrate doesn't overcome it.", "Both lower the rate at low substrate; the key is what happens at HIGH substrate.", "At low substrate, X lowers the rate more (8 vs 10)."], "Compare each inhibitor with 'no inhibitor' at the highest substrate.", "At 16 units, X gives 70 of 80 (almost normal) but Y only 40 of 80, so extra substrate overcomes X but not Y.", [["Substrate (units)", "1", "2", "4", "8", "16"], ["No inhibitor", "20", "33", "50", "66", "80"], ["Inhibitor X", "8", "15", "28", "47", "70"], ["Inhibitor Y", "10", "16", "25", "33", "40"]]],
["L", "c", 5, "Put the steps in order: how does biological washing powder remove an egg stain at 40 °C?", ["Proteases bind to the egg proteins in the stain", "They hydrolyse the proteins into soluble peptides and amino acids", "The soluble products wash out of the fabric"], "The enzymes dissolve the fabric fibres", "Bind, break down, wash away.", "Proteases only act on proteins, so cotton and polyester fibres are unharmed. The trap step is wrong."],
{ f: "G", k: "d", b: 6, q: "The dashed line shows the rate of an enzyme reaction at different substrate concentrations. A COMPETITIVE inhibitor is added. Which graph shows the new result (pink)?", gch: [{ ref: [[0, 0], [1, 40], [2, 62], [4, 80], [6, 88], [10, 94]], pts: [[0, 0], [1, 15], [2, 30], [4, 55], [6, 72], [10, 88]] }, { ref: [[0, 0], [1, 40], [2, 62], [4, 80], [6, 88], [10, 94]], pts: [[0, 0], [1, 20], [2, 31], [4, 40], [6, 44], [10, 47]] }, { ref: [[0, 0], [1, 40], [2, 62], [4, 80], [6, 88], [10, 94]], pts: [[0, 0], [1, 40], [2, 62], [4, 80], [6, 88], [10, 94]] }, { ref: [[0, 0], [1, 40], [2, 62], [4, 80], [6, 88], [10, 94]], pts: [[0, 0], [1, 55], [2, 80], [4, 100], [6, 108], [10, 112]] }], gax: ["substrate", "rate"], choices: ["Much lower at low substrate, but nearly catching up at high substrate", "Lower everywhere, levelling off at about half", "No change", "Higher everywhere"], why: ["That's a non-competitive inhibitor: extra substrate can't overcome it.", "An inhibitor slows the reaction.", "Inhibitors never speed up the enzyme."], hint: "With lots of substrate, who wins the active sites?", explain: "A competitive inhibitor competes for the active site. At low substrate it blocks many sites; at high substrate the substrate outcompetes it, so the rate approaches the normal maximum." }
]);
