
/* 🔥 Hard formats, part 2: Photosynthesis, Respiration, Genetics, Molecular Genetics (format: see q_h0.js). */

/* ---------- Topic 6: Photosynthesis ---------- */
KH("t6s1", [
["R", "c", 5, "Which leaf features help gas exchange for photosynthesis?", ["Air spaces between spongy mesophyll cells", "Many stomata on the lower surface", "A thick waxy cuticle on the upper surface"], 0, ["True: gases diffuse quickly through the air spaces to every cell.", "True: CO₂ enters and O₂ leaves through the stomata.", "False: the cuticle cuts water loss; gases can hardly pass through it."], "Which feature is a barrier?", "Air spaces and stomata help gas exchange; the cuticle is waterproofing."],
["T", "d", 6, "Stomatal opening was measured during a hot, dry day. Light was strongest at noon. Why were the stomata partly closed at noon?", ["On a hot, dry midday, guard cells lose water, so stomata partly close to reduce water loss", "The stomata were widest at 9 am (8 µm)", "Strong light closes stomata", "At noon the leaf no longer needs CO₂"], ["A true reading, but it doesn't explain the midday dip.", "Light normally OPENS stomata, as the morning rise shows.", "Photosynthesis is fastest at noon, so CO₂ is still needed: this is a water trade-off."], "Stomata balance CO₂ uptake against water loss.", "When water loss is greatest, guard cells lose turgor and stomata partly close, even though this limits CO₂ uptake.", [["Time", "6 am", "9 am", "12 noon", "3 pm", "6 pm", "9 pm"], ["Stomatal opening (µm)", "2", "8", "6", "7", "3", "0"]]],
["L", "c", 5, "Put the steps in order: how do guard cells open a stoma in the light?", ["Guard cells build up solutes (such as potassium ions)", "Water enters the guard cells by osmosis and they become turgid", "Their thicker inner walls curve apart, opening the stoma"], "Light energy pushes the guard cells apart", "Solutes first, then water.", "Solutes lower the water potential, water follows by osmosis, and the uneven walls bend. Light doesn't push cells."],
["C", "c", 5, "Which is a valid comparison of palisade and spongy mesophyll cells?", ["Palisade cells are column-shaped and packed with chloroplasts to absorb light, whereas spongy cells are irregular, with fewer chloroplasts and large air spaces for gas diffusion", "Palisade cells photosynthesise. Spongy cells do gas exchange.", "Palisade cells have no chloroplasts, whereas spongy cells have many", "They are the same cells in different places"], ["Separate statements, and spongy cells photosynthesise too.", "Reversed.", "Ignores the structural differences that suit their jobs."], "Shape + chloroplasts + spaces, paired.", "Pair the same features for both cell types and link structure to function."]
]);
KH("t6s2", [
["A", "c", 5, "Many tree leaves turn yellow in autumn.", "Chlorophyll is broken down faster than the yellow carotenoids, so they become visible.", 0, "Join them with 'because'.", "Carotenoids were there all summer, hidden by green chlorophyll. When chlorophyll breaks down, the yellow shows."],
["N", "c", 6, "Red seaweeds live deep in the sea, where mainly blue-green light reaches. They have extra pigments that absorb this light. How does this help?", ["These accessory pigments absorb wavelengths chlorophyll absorbs poorly and pass the energy on, so more of the available light is used", "The pigments keep the seaweed warm", "Red light reaches deep water best", "The pigments mean the seaweed doesn't need chlorophyll"], ["Absorbed light is used for photosynthesis, not heating.", "Water absorbs red light first; blue-green goes deepest.", "Chlorophyll is still needed; the accessory pigments pass energy to it."], "Which light is available down there?", "Extra pigments widen the range of wavelengths the seaweed can use: an adaptation to its habitat."],
["E", "i", 5, "In leaf-pigment chromatography, a student's start line ended up below the solvent level. What goes wrong?", ["The pigments dissolve into the solvent in the beaker instead of moving up the paper", "The pencil line runs up the paper", "The pigments move faster and separate better", "Nothing; the start line can be anywhere"], ["Graphite doesn't dissolve, so the line stays put.", "The pigments wash off the paper; they don't separate better.", "The spot must be above the solvent so the solvent carries the pigments up."], "Where should the spot be?", "Keep the start line above the solvent level so the pigments are carried up the paper by the solvent."],
["M", "c", 5, "Exam question: 'Explain why plants grown under green light grow poorly.' [2 marks]. Which answer scores both marks?", ["Chlorophyll absorbs little green light (most is reflected), so less light energy is trapped, giving less photosynthesis and less sugar for growth", "Green light is reflected", "Plants don't like green light", "Green light is too weak"], ["1 mark: missing the consequence for photosynthesis and growth.", "Not scientific.", "Intensity isn't the issue; absorption is."], "Absorption, then the consequence.", "Mark 1: little green light is absorbed by chlorophyll. Mark 2: less photosynthesis, so less sugar for growth."]
]);
KH("t6s3", [
["R", "c", 5, "Which are products of the light-dependent reactions?", ["ATP", "NADPH (reduced NADP)", "Glucose"], 0, ["True: made using light energy.", "True: carries hydrogen to the Calvin cycle.", "False: glucose is made later, in the light-independent reactions."], "Where is glucose made?", "The light-dependent reactions make ATP, NADPH and oxygen; sugar is made in the Calvin cycle."],
["T", "d", 5, "Chloroplasts and blue DCPIP were lit with different colours of light of equal intensity. Which statement is best?", ["Green gives the slowest reaction because chlorophyll absorbs it least, so fewer electrons are released to reduce DCPIP", "In green light the DCPIP took 25 minutes", "Green light destroys DCPIP", "Blue light gives the fastest reaction"], ["A reading, but no explanation.", "No evidence for this: the DCPIP was still reduced, just slowly.", "Misreading: white light (4 min) was fastest."], "Fast decolourising = fast light-dependent reactions.", "Rate follows how well each colour is absorbed by chlorophyll.", [["Light colour", "White", "Red", "Blue", "Green"], ["Time to decolourise DCPIP (min)", "4", "6", "5", "25"]]],
["L", "c", 5, "Put the steps in order: the light-dependent reactions.", ["Light energy is absorbed by chlorophyll", "Water is split into hydrogen ions, electrons and oxygen", "ATP and NADPH are made, and oxygen is released"], "Carbon dioxide is split to release oxygen", "Absorb, split water, make products.", "The oxygen comes from water, not CO₂: the trap step is a classic misconception."],
["E", "i", 5, "To show the reactions need light, a student kept one tube of chloroplasts + DCPIP on the bench in light and another in a warm cupboard in the dark. What is the flaw?", ["Temperature also differed, so it isn't a fair test; wrap one tube in foil and keep both side by side", "More DCPIP should be added to the dark tube", "The chloroplasts in the light tube should be boiled", "Oxygen should be tested with limewater"], ["That changes another variable.", "That would destroy the test.", "Limewater tests for CO₂, not O₂."], "Only light should differ.", "Light and temperature changed together. Keeping both tubes side by side (one in foil) leaves light as the only difference."]
]);
KH("t6s4", [
["A", "c", 5, "In the dark, the Calvin cycle stops quickly.", "The Calvin cycle uses light energy directly.", 2, "What does the Calvin cycle need from the light reactions?", "The Calvin cycle doesn't use light directly, but it needs the ATP and NADPH made in the light. These run out in the dark."],
["T", "d", 6, "Levels of RuBP and GP in a chloroplast were measured in light, then 1 minute after the light was switched off. Which explanation is correct?", ["GP is still made from RuBP and CO₂, but without ATP and NADPH it can't be converted, so GP builds up and RuBP falls", "Darkness breaks down RuBP", "GP is made faster in the dark", "Both changes show photosynthesis speeding up"], ["Darkness doesn't break RuBP: it's used to fix CO₂ but not regenerated.", "GP isn't made faster; it builds up because it isn't used.", "Contradicts the data: sugar production stops."], "Which step needs ATP and NADPH?", "Fixing CO₂ doesn't need light, but turning GP into sugar and regenerating RuBP does.", [["Substance", "In light", "1 min after light off"], ["RuBP (units)", "10", "4"], ["GP (units)", "10", "18"]]],
["M", "c", 5, "Exam question: 'Explain how increasing CO₂ concentration affects the rate of photosynthesis in bright light.' [2 marks]. Which answer scores both marks?", ["CO₂ is fixed in the Calvin cycle, so more CO₂ means more is fixed per minute and more sugar is made, until another factor becomes limiting", "More CO₂, more photosynthesis", "CO₂ gives the plant energy", "CO₂ opens the stomata"], ["Describes, doesn't explain: no mechanism and no limit.", "Energy comes from light; CO₂ is the carbon source.", "Not the mechanism; high CO₂ tends to close stomata."], "Mechanism + limit.", "Mark 1: more CO₂ fixed in the Calvin cycle. Mark 2: the rate rises until another factor limits it."],
["N", "c", 6, "Greenhouse growers often keep CO₂ at about 0.1% (2.5× normal air). Why don't they raise it to 5%?", ["Above about 0.1%, another factor limits the rate, so extra CO₂ gives no benefit, and very high levels are harmful", "CO₂ is poisonous to plants at any level", "More CO₂ always means more growth", "CO₂ blocks light from reaching the leaves"], ["Plants need CO₂ for photosynthesis.", "Ignores limiting factors.", "CO₂ does not block light."], "Limiting factors and cost.", "Once CO₂ stops being limiting, adding more wastes money, and high levels can harm both plants and workers."]
]);
KH("t6s5", [
["R", "c", 5, "A plant is in very bright light at 15 °C and 0.04% CO₂. Which changes could increase its rate of photosynthesis?", ["Raising the CO₂ concentration", "Raising the temperature to 25 °C", "Making the light even brighter"], 0, ["True: CO₂ is likely limiting.", "True: enzymes in the Calvin cycle work faster at 25 °C.", "False: in very bright light, light is already not limiting."], "Which factor is already plentiful?", "Only factors in short supply limit the rate."],
["T", "d", 6, "Rates of photosynthesis were measured. At light intensity 8 and 0.04% CO₂, what limits the rate?", ["CO₂ concentration, because raising CO₂ at the same light raises the rate", "Light intensity", "The rate is 24 units", "Temperature, because it isn't in the table"], ["At 0.04%, the rate is the same at light 4 and 8, so light is not limiting there.", "A true reading, but not an answer about limiting factors.", "The table has no temperature data; the CO₂ rows give the answer."], "Compare the two rows at light 8.", "Rate stays at 24 from light 4 to 8 at 0.04% CO₂, but rises to 42 at 0.1% CO₂, so CO₂ is the limiting factor.", [["Light intensity (a.u.)", "1", "2", "4", "8"], ["Rate at 0.04% CO₂", "10", "18", "24", "24"], ["Rate at 0.1% CO₂", "10", "19", "34", "42"]]],
["L", "c", 5, "Put the steps in order: why does the rate stop rising as light gets brighter?", ["At low light, more light means more ATP and NADPH", "At high light, the Calvin cycle can't use them any faster", "So CO₂ or temperature now limits the rate"], "Strong light destroys the chlorophyll", "What does extra light make, and who uses it?", "The light reactions outpace the Calvin cycle, so another factor becomes limiting."],
["E", "i", 6, "A student counted pondweed bubbles for 1 minute at each of 5 lamp distances, moving the lamp straight to the next distance after each count. What is the best improvement?", ["Let the plant adjust for a few minutes at each distance and repeat the counts to find a mean", "Use a stronger lamp", "Remove the sodium hydrogencarbonate", "Count the bubbles in the dark"], ["A brighter lamp doesn't fix reliability.", "That would make CO₂ limiting.", "There's no photosynthesis in the dark."], "Acclimatise and repeat.", "The rate takes time to settle at each light level, and repeats give reliable means."]
]);
KH("t6s6", [
["A", "c", 5, "A destarched plant is used to show that light is needed to make starch.", "Destarching makes sure any starch found was made during the experiment.", 0, "Join them with 'because'.", "Without destarching, old starch could give a positive result, so the 2nd statement explains the 1st."],
["T", "d", 5, "Sealed tubes of hydrogencarbonate indicator (red at start) were left for 2 hours. Which conclusion is supported?", ["In light, the leaf's photosynthesis removed CO₂ faster than its respiration released it", "The leaf does not respire in the light", "Light alone turns the indicator purple", "Animals photosynthesise in light"], ["It does respire; photosynthesis is just faster (net uptake).", "Tube C (no leaf, light) stayed red.", "D turned yellow: the woodlouse only respires."], "Purple = less CO₂; yellow = more CO₂.", "Compare each tube with the control (C) to see what changed the CO₂ level.", [["Tube", "Contents", "Light", "Colour after 2 h"], ["A", "leaf", "light", "purple"], ["B", "leaf", "dark", "yellow"], ["C", "nothing", "light", "red"], ["D", "woodlouse", "light", "yellow"]]],
["M", "c", 5, "Exam question: 'Explain why a leaf from a plant kept in the dark for 48 hours gives no blue-black colour with iodine.' [2 marks]. Which answer scores both marks?", ["In the dark, no photosynthesis makes new starch, while the stored starch is broken down and used or moved away", "No light", "The iodine was too weak", "The starch was used up"], ["A keyword with no link.", "Not the reason.", "1 mark: missing that no NEW starch is made without light."], "Two halves: none made, old removed.", "Mark 1: no photosynthesis, so no new starch. Mark 2: existing starch is used in respiration or moved away."],
["N", "c", 6, "Astronauts plan to keep algae in a sealed, LED-lit tank to recycle the air. What must be true for the oxygen level in the air to rise?", ["The algae's rate of photosynthesis must be greater than the total respiration of the algae and the crew", "The algae must stop respiring", "The LEDs must be green", "The tank must contain no CO₂"], ["All living cells respire.", "Green light is poorly absorbed.", "CO₂ is needed for photosynthesis."], "Net gain.", "Oxygen rises only if total production by photosynthesis beats total use by respiration."]
]);

/* ---------- Topic 7: Cellular Respiration ---------- */
KH("t7s1", [
["R", "c", 5, "Which statements about aerobic respiration are correct?", ["It happens in all living cells, including plant cells.", "Most of the ATP is made in the mitochondria.", "It only happens when a person is exercising."], 0, ["True: every living cell respires.", "True: the later stages happen in mitochondria.", "False: respiration happens all the time; it just speeds up in exercise."], "Remember the Ember Halls' Warden.", "Respiration never stops in a living cell; plants respire as well as photosynthesise."],
["T", "d", 5, "A respirometer with germinating seeds was kept at different temperatures. Which explanation of the 40 °C result is best?", ["Respiratory enzymes in the seeds begin to denature, so oxygen uptake falls", "The seeds no longer need oxygen at 40 °C", "The liquid moved 17 mm at 30 °C", "Higher temperatures always increase respiration"], ["Living seeds always need oxygen; their enzymes are failing.", "A true reading, but not an explanation.", "Ignores the fall at 40 °C: enzymes have an optimum."], "Respiration is enzyme-controlled.", "The rate rises to 30 °C, then falls as enzymes denature.", [["Temperature (°C)", "10", "20", "30", "40"], ["Distance moved in 5 min (mm)", "4", "9", "17", "6"]]],
["L", "c", 5, "Put the steps in order: why does cyanide stop muscles contracting?", ["Cyanide stops mitochondria using oxygen", "Aerobic respiration stops, so very little ATP is made", "The muscles lack ATP to contract"], "Cyanide stops oxygen entering the lungs", "Start inside the cell.", "Oxygen still reaches the cells; they just can't use it. ATP runs out."],
["C", "c", 5, "Which is a valid comparison of respiration and breathing?", ["Respiration is a chemical process in every cell that releases energy from glucose, whereas breathing is the movement of air into and out of the lungs", "Respiration and breathing are the same thing", "Breathing releases energy, whereas respiration moves air", "Respiration happens in the lungs. Breathing happens in cells."], ["A common misconception.", "Reversed.", "Wrong locations, and no comparative link."], "Chemical vs physical.", "Breathing supplies the oxygen; respiration uses it in cells."]
]);
KH("t7s2", [
["A", "c", 5, "Sprinters build up lactic acid in their muscles.", "Anaerobic respiration releases energy fast when oxygen can't be supplied quickly enough.", 0, "Join them with 'because'.", "During a sprint, muscles need ATP faster than oxygen arrives, so they respire anaerobically, making lactic acid."],
["T", "d", 5, "Yeast was kept in four conditions. Which conclusion is best supported?", ["Yeast respires faster with oxygen; without oxygen it ferments glucose to ethanol and releases less CO₂", "Yeast only makes CO₂ when oxygen is absent", "Yeast can respire without glucose", "Tube B made 4 cm³ of CO₂"], ["Tube A (with oxygen) made the MOST CO₂.", "Tubes C and D made no CO₂.", "A true reading, but not a conclusion."], "Compare A with B, then B with C.", "A vs B shows the effect of oxygen; C and D show glucose is needed.", [["Tube", "Oxygen", "Glucose", "CO₂ in 10 min (cm³)", "Ethanol made"], ["A", "yes", "yes", "12", "no"], ["B", "no", "yes", "4", "yes"], ["C", "no", "no", "0", "no"], ["D", "yes", "no", "0", "no"]]],
["M", "c", 5, "Exam question: 'Explain why muscles tire during a long sprint.' [2 marks]. Which answer scores both marks?", ["Oxygen can't be supplied fast enough, so the muscles respire anaerobically and lactic acid builds up, causing fatigue", "Lactic acid", "The muscles run out of energy", "The muscles respire anaerobically"], ["A keyword only.", "Vague: energy isn't 'used up'; the ATP supply falls and lactic acid builds up.", "1 mark: missing the lactic acid consequence."], "Cause, then consequence.", "Mark 1: not enough oxygen, so anaerobic respiration. Mark 2: lactic acid builds up, causing fatigue."],
["N", "c", 5, "Brewers seal fermentation vessels (with a gas valve) after the first day. Why?", ["Once the oxygen is used up, yeast respires anaerobically and makes ethanol", "To stop CO₂ being made", "To keep the yeast warm", "To make the yeast respire aerobically"], ["CO₂ is still made, which is why there's a valve.", "Not the main reason.", "Reversed."], "What do brewers want to make?", "Keeping air out keeps the yeast respiring anaerobically, which produces ethanol."]
]);
KH("t7s3", [
["R", "c", 5, "Which statements are true of BOTH photosynthesis and aerobic respiration?", ["Both are controlled by enzymes.", "Both happen in plant cells.", "Both release carbon dioxide."], 0, ["True: both are enzyme-controlled pathways.", "True: plants do both.", "False: photosynthesis USES carbon dioxide."], "Check statement III carefully.", "Plants photosynthesise and respire; only respiration releases CO₂."],
["T", "d", 6, "A leaf's net CO₂ uptake was measured at different light intensities. What is happening at light intensity 1?", ["The compensation point: photosynthesis uses CO₂ as fast as respiration releases it", "The leaf neither photosynthesises nor respires", "Photosynthesis has stopped", "The leaf only respires"], ["Both are happening; they balance.", "It is happening, at the same rate as respiration.", "That's at light 0 (−3)."], "Net uptake 0 means balance.", "Zero net CO₂ exchange means the two processes are in balance.", [["Light intensity (a.u.)", "0", "1", "2", "4", "8"], ["Net CO₂ uptake (units)", "−3", "0", "4", "10", "12"]]],
["L", "c", 5, "Put the steps in order: how does a respirometer show oxygen uptake?", ["The seeds take in O₂ and release CO₂", "Soda lime absorbs the CO₂, so the volume of gas falls", "The coloured liquid moves towards the seeds"], "The seeds make the gas expand, pushing the liquid away", "Which gas is removed?", "With CO₂ absorbed, the only change in volume is the oxygen used."],
["E", "i", 5, "To compare respiration of germinating and dry seeds, a student used 10 g of germinating seeds but only 5 g of dry seeds. What is the flaw?", ["The masses differ, so the rates must be compared per gram (or equal masses used)", "Boiled seeds should be used instead of dry seeds", "The soda lime should be removed", "The dry seeds should be kept in a warmer water bath"], ["Boiled seeds are a different control; the flaw is the mass.", "Then oxygen uptake can't be measured.", "That adds another variable."], "Twice the seeds, twice the oxygen.", "Use equal masses, or divide each rate by the mass, so only germination differs."]
]);

/* ---------- Basic Genetics ---------- */
KH("t9s1", [
["A", "c", 5, "Two tall pea plants can produce short offspring.", "Both parents may be heterozygous (Tt).", 0, "Join them with 'because'.", "Tt × Tt gives 1/4 tt (short), so the 2nd statement explains the 1st."],
["T", "d", 5, "Results of three pea crosses. What are the parents' genotypes in cross 2?", ["Tt × tt", "TT × tt", "Tt × Tt", "TT × Tt"], ["TT × tt gives all tall offspring.", "That gives 3 : 1, and one parent here is short, so it must be tt.", "That gives all tall, and a short parent must be tt."], "48 : 52 is about 1 : 1.", "A short parent is tt; a 1 : 1 ratio means the tall parent is Tt.", [["Cross", "Parents", "Offspring"], ["1", "tall × tall", "92 tall"], ["2", "tall × short", "48 tall, 52 short"], ["3", "tall × tall", "74 tall, 26 short"]]],
["L", "c", 5, "Put the steps in order: how does a test cross reveal an unknown genotype?", ["Cross the dominant-looking plant with a homozygous recessive (tt) plant", "Each offspring receives a t allele from the recessive parent", "Any short offspring show the unknown parent carried t, so it is Tt"], "The recessive parent changes the unknown plant's alleles", "The recessive parent 'unmasks' the other alleles.", "The tt parent can only give t, so each offspring's phenotype reveals the allele from the unknown parent."],
["M", "c", 5, "Exam question: 'Explain why 8 offspring from Tt × Tt might not show a 3 : 1 ratio.' [2 marks]. Which answer scores both marks?", ["Fertilisation is random, so which gametes fuse is down to chance, and with small numbers the observed ratio can differ a lot from the expected one", "Mendel was wrong", "Because of mutation", "Chance"], ["Mendel's ratios hold for large numbers.", "Mutation is far too rare to explain it.", "A keyword only."], "Random + small sample.", "Mark 1: random fertilisation (chance). Mark 2: small numbers mean big deviations from the expected ratio."]
]);
KH("t9s2", [
["R", "c", 5, "Two unaffected parents have a child with a genetic condition. What can be concluded?", ["The condition is caused by a recessive allele.", "Both parents are carriers (heterozygous).", "All their future children will be affected."], 0, ["True: a hidden allele showed up in the child.", "True: each parent passed on one recessive allele.", "False: each child has a 1/4 chance of being affected."], "Each birth is independent.", "Unaffected parents with an affected child must both be carriers of a recessive allele."],
["T", "d", 5, "Blood was tested with anti-A and anti-B serum. Which person can receive blood from all four?", ["R (group AB)", "Q (group O)", "P (group A)", "S (group B)"], ["Group O is the universal DONOR (no antigens), not the universal recipient.", "Group A has anti-B antibodies, so can't receive B or AB blood.", "Group B has anti-A antibodies."], "Work out each blood group first.", "R's blood clumps with both sera, so it has A and B antigens (group AB) and makes no anti-A or anti-B antibodies.", [["Person", "With anti-A serum", "With anti-B serum"], ["P", "clumps", "no change"], ["Q", "no change", "no change"], ["R", "clumps", "clumps"], ["S", "no change", "clumps"]]],
["C", "c", 5, "Which is a valid comparison of complete dominance and codominance?", ["In complete dominance the heterozygote shows only the dominant phenotype, whereas in codominance both alleles are expressed in the heterozygote", "In codominance the alleles blend into a new in-between allele", "Dominance: one allele. Codominance: two alleles.", "In codominance neither allele is expressed"], ["The alleles don't change or blend: both are expressed, as in blood group AB.", "Fragments, and both involve two alleles.", "Both are expressed."], "What does the heterozygote look like?", "The difference is in the heterozygote's phenotype."],
["N", "c", 6, "Thalassaemia is a recessive condition common in Hong Kong. Two carriers plan a family. What is the chance their first child is a carrier?", ["1/2", "1/4", "3/4", "2/3"], ["1/4 is the chance of being affected (tt).", "3/4 is the chance of being unaffected.", "2/3 applies only among the unaffected children."], "Punnett square: Tt × Tt.", "Tt × Tt gives TT : Tt : tt = 1 : 2 : 1, so the chance of Tt is 2/4 = 1/2."]
]);
KH("t9s3", [
["A", "c", 5, "Identical twins can differ in height.", "Height is affected by environmental factors such as diet.", 0, "Same genes, different heights: why?", "Identical twins have the same genes, so differences must come from the environment."],
["T", "d", 5, "Tall and short pea plants were crossed, then the F1 were self-pollinated. Which conclusion is supported?", ["Tall is dominant; the F1 are all heterozygous, and the F2 shows about 3 : 1", "The short allele has disappeared from the population", "Tall is recessive", "The F2 ratio is 1 : 1"], ["It reappears in the F2: the allele was hidden in the F1.", "If tall were recessive, the F1 would be short.", "301 : 99 is about 3 : 1."], "What happened in F1 and F2?", "The recessive allele was hidden in the F1 and reappeared in a quarter of the F2.", [["Generation", "Tall", "Short"], ["F1", "100", "0"], ["F2", "301", "99"]]],
["E", "i", 5, "A student surveyed tongue rolling in 10 members of one family and concluded it is controlled by a single dominant allele. What is the main weakness?", ["Ten related people are too few, and not representative, to support a conclusion about inheritance", "Only adults should be surveyed", "Tongue rolling is learned, so it can't be surveyed", "People should practise rolling first"], ["Age isn't the main issue.", "Overclaiming: the survey is possible; the sample is the problem.", "That changes the trait being measured."], "Sample size and independence.", "A tiny family sample can't show an inheritance pattern. Real studies also show tongue rolling isn't simple one-gene inheritance."],
["L", "c", 5, "Put the steps in order: why is the sickle-cell allele common where malaria is common?", ["Carriers (HbᴬHbˢ) resist malaria", "Carriers survive and reproduce more than people without the allele", "The Hbˢ allele is passed on more often"], "Malaria causes the Hbˢ mutation", "Selection acts on alleles that already exist.", "The mutation arises randomly; malaria only selects for carriers."]
]);

/* ---------- Molecular Genetics and Biotechnology ---------- */
KH("t10s1", [
["R", "c", 5, "Which statements about DNA are correct?", ["Its two strands are held together by hydrogen bonds between complementary bases.", "The sequence of bases carries genetic information.", "Adenine pairs with guanine."], 0, ["True: the bases pair across the middle.", "True: the order of bases codes for amino acids.", "False: A pairs with T, and G pairs with C."], "Remember the base pairs.", "DNA's complementary base pairing lets it be copied and read."],
["T", "d", 6, "The base composition of three DNA samples (%). Which conclusion is best supported?", ["Human and wheat DNA are double-stranded (A ≈ T, G ≈ C); virus X's DNA is single-stranded", "All three are double-stranded", "Humans and wheat have the same genes because their ratios are similar", "Human DNA has the most adenine"], ["In virus X, A ≠ T and G ≠ C.", "Base ratios say nothing about the base SEQUENCE.", "A true reading, but not a conclusion about structure."], "Check A vs T and G vs C in each row.", "Equal A and T (and G and C) means the bases are paired, so the DNA is double-stranded.", [["Source", "A", "T", "G", "C"], ["Human", "30.9", "29.4", "19.9", "19.8"], ["Wheat", "27.3", "27.1", "22.7", "22.8"], ["Virus X", "25", "33", "24", "18"]]],
["M", "c", 5, "Exam question: 'Explain why DNA replication produces two identical molecules.' [2 marks]. Which answer scores both marks?", ["Each original strand acts as a template, and free nucleotides pair with it by complementary base pairing, so each new strand matches the old partner", "DNA unzips and copies itself", "Enzymes make it identical", "Complementary base pairing"], ["Describes it, with no mechanism.", "Too vague.", "A keyword only: 1 mark at most."], "Template + pairing.", "Mark 1: each strand is a template. Mark 2: complementary base pairing makes an exact copy."],
["L", "c", 5, "Put the steps in order: how is a long DNA molecule packed into a chromosome?", ["DNA wraps around proteins", "This coils further and condenses", "A visible chromosome forms before cell division"], "DNA is cut into short pieces so it fits", "Wrap, coil, condense.", "DNA stays as one long molecule per chromosome; it is coiled, not cut."]
]);
KH("t10s2", [
["A", "c", 5, "A gene mutation can change the shape of an enzyme.", "A gene mutation can change the sequence of amino acids in a polypeptide.", 0, "Join them with 'because'.", "A changed base sequence can change the amino acid sequence, which changes how the protein folds."],
["T", "d", 6, "An mRNA codon GAA mutates. Using the codon table, which change would have NO effect on the protein?", ["GAA → GAG", "GAA → GUA", "GAA → AAA", "Deleting the first A"], ["That changes Glu to Val, like the sickle-cell mutation.", "That changes Glu to Lys.", "A frameshift: every codon after it changes."], "Look for another codon for the same amino acid.", "GAG also codes for Glu, so the protein is unchanged (a silent mutation).", [["mRNA codon", "GAA", "GAG", "GUA", "AAA"], ["Amino acid", "Glu", "Glu", "Val", "Lys"]]],
["L", "c", 5, "Put the steps in order: how is a gene used to make a protein?", ["Transcription: mRNA is made from the DNA template in the nucleus", "The mRNA moves to a ribosome in the cytoplasm", "Translation: amino acids are joined in the order of the codons"], "The DNA leaves the nucleus and goes to the ribosome", "DNA stays home.", "Only the mRNA copy leaves the nucleus; DNA stays inside."],
["N", "c", 6, "The antibiotic streptomycin binds to bacterial ribosomes but not to human ribosomes. What is its effect?", ["Bacteria can't translate mRNA, so they can't make proteins and stop growing", "It stops bacterial DNA replication", "It harms human cells too", "Bacteria can't transcribe their DNA"], ["Ribosomes make proteins; they don't copy DNA.", "It doesn't bind human ribosomes.", "Transcription doesn't use ribosomes."], "What do ribosomes do?", "Blocking ribosomes stops translation. Bacterial and human ribosomes differ, so humans are not affected."]
]);
KH("t10s3", [
["R", "c", 5, "Which steps are needed to make bacteria produce human insulin?", ["Cut the human insulin gene and the plasmid with the same restriction enzyme.", "Join them with DNA ligase.", "Insert the plasmid into the human pancreas."], 0, ["True: this gives matching sticky ends.", "True: ligase seals the gene into the plasmid.", "False: the plasmid goes into BACTERIA, which then make the insulin."], "Where does the plasmid go?", "Cut with the same enzyme, join with ligase, put the plasmid into bacteria, then grow them in fermenters."],
["E", "i", 6, "A company claims its GM maize gives higher yields. It grew GM maize on a sunny hillside and normal maize in a shaded field. What is the flaw?", ["Light and location differ, so the yield difference can't be put down to the gene", "Only GM plants should be grown", "Different fertilisers should be used for each", "Height should be measured instead of yield"], ["You need a comparison.", "That adds another variable.", "Yield is what is being claimed."], "What else differed?", "Grow both types in the same conditions, randomly placed, with repeats."],
["C", "c", 5, "Which is a valid comparison of selective breeding and genetic engineering?", ["Selective breeding combines genes already in a species over many generations, whereas genetic engineering transfers specific genes, even between species, in one generation", "Selective breeding is natural. Genetic engineering is not.", "Genetic engineering takes many generations, whereas selective breeding is fast", "Both create new species"], ["Not a meaningful paired comparison: selective breeding is directed by humans too.", "Reversed.", "Neither normally does."], "Source of genes + time.", "Compare where the genes come from and how long it takes."],
["M", "c", 6, "Exam question: 'Discuss one benefit and one risk of growing pest-resistant GM crops.' [2 marks]. Which answer scores both marks?", ["Benefit: less pesticide is needed and yields rise. Risk: the gene may spread to wild relatives by cross-pollination, making resistant weeds.", "GM is good and bad", "GM crops are always dangerous to eat", "Benefit: more food"], ["No specifics.", "An overclaim (the Warden's misconception).", "One vague point and no risk: 1 mark at most."], "One specific point each.", "One mark for a specific benefit, one for a specific risk, each with a reason."]
]);
