
/* 🔥 Hard formats, part 3: Evolution, Plants, Nutrition, Gas Exchange, Transport (format: see q_h0.js). */

/* ---------- Biodiversity and Evolution ---------- */
KH("t11s1", [
["R", "c", 5, "Which features would place an unknown animal in the class Mammalia?", ["Hair or fur", "Mammary glands that make milk", "A backbone"], 0, ["True: only mammals have hair.", "True: only mammals feed their young on milk.", "False: every vertebrate has a backbone, so it doesn't pick out mammals."], "Look for features ONLY mammals have.", "Classification uses features shared by a group but not by others."],
["T", "d", 5, "Key: 1. Has 8 legs → spider; has 6 legs → go to 2. 2. Has wings → winged insect; no wings → wingless insect. Using the table, which organism is a wingless insect?", ["R", "P", "Q", "S"], ["P has wings.", "8 legs: a spider (arachnid).", "No legs: it isn't an insect, and this key can't place it."], "Follow the key step by step.", "R has 6 legs (insect) and no wings.", [["Organism", "Legs", "Wings", "Antennae"], ["P", "6", "yes", "yes"], ["Q", "8", "no", "no"], ["R", "6", "no", "yes"], ["S", "0", "no", "no"]]],
["C", "c", 5, "Which is a valid comparison of fungi and plants?", ["Fungi feed by absorbing digested food from their surroundings, whereas plants make their own food by photosynthesis; both have cell walls", "Fungi are plants without chlorophyll", "Plants have cell walls, whereas fungi do not", "Fungi photosynthesise. Plants absorb food."], ["Fungi are a separate kingdom, with walls of chitin, not cellulose.", "Fungi have cell walls too (made of chitin).", "Reversed, and with no comparative link."], "How does each get food?", "Feeding method is a key difference between the kingdoms."],
["N", "c", 6, "A newly found deep-sea organism is multicellular, its cells have nuclei and cell walls, and it absorbs food from dead whales. Which kingdom is it most likely in?", ["Fungi", "Plantae", "Animalia", "Prokaryotae"], ["No photosynthesis: it absorbs its food.", "Animal cells have no cell walls.", "Its cells have nuclei."], "Use each clue to rule out a kingdom.", "Nuclei rule out prokaryotes; cell walls rule out animals; absorbing food rules out plants."]
]);
KH("t11s2", [
["A", "c", 5, "Antibiotic resistance spreads faster when antibiotics are overused.", "Antibiotics cause the mutations that make bacteria resistant.", 2, "Do antibiotics create mutations, or select them?", "Mutations arise randomly. Antibiotics SELECT bacteria that are already resistant, so overuse speeds up the spread."],
["T", "d", 6, "Percentage of dark peppered moths. Which explanation fits ALL the data?", ["Soot darkened city trees, so dark moths were camouflaged and survived; once the air was cleaned, light moths were favoured again", "Soot turned the moths dark", "Dark moths migrated into the city", "Dark moths reached 90% in 1900"], ["A change during life isn't inherited; this is selection of existing variation.", "Migration doesn't explain the fall after the air was cleaned.", "A reading, with no explanation."], "Explain the rise AND the fall.", "Selection changes direction when the environment changes back.", [["Year", "Dark moths in city (%)", "Dark moths in countryside (%)"], ["1850", "2", "1"], ["1900", "90", "5"], ["1990 (clean air)", "15", "3"]]],
["L", "c", 5, "Put the steps in order: natural selection.", ["Individuals in a population vary, partly because of their genes", "Those with better-adapted features survive and reproduce more", "Their alleles become more common in the next generation"], "Individuals change their genes to suit the environment", "Variation, selection, inheritance.", "Individuals cannot choose their genes; populations change because of who survives to breed."],
["M", "c", 5, "Exam question: 'Explain why patients should finish a full course of antibiotics.' [2 marks]. Which answer scores both marks?", ["Stopping early can leave the most resistant bacteria alive, and they multiply and pass on resistance, making the antibiotic less effective", "To kill all the bacteria", "So the body becomes immune to antibiotics", "Because the doctor said so"], ["1 mark: missing the selection of resistant survivors.", "Bacteria, not people, become resistant.", "Not a biological reason."], "Who survives an incomplete course?", "Mark 1: the most resistant survive. Mark 2: they multiply and spread resistance."]
]);
KH("t11s3", [
["R", "c", 5, "Which are evidence for evolution?", ["Fossils showing gradual change over time", "The same bone pattern in the limbs of different vertebrates", "A giraffe stretching its neck during its lifetime"], 0, ["True: the fossil record shows change through rock layers.", "True: homologous structures suggest a common ancestor.", "False: changes during life aren't inherited."], "Inherited vs acquired.", "Fossils and homologous structures support common descent."],
["T", "d", 5, "Fossils of horse ancestors. Which conclusion is best supported?", ["Over time, horse ancestors became taller with fewer toes: a gradual change consistent with evolution", "Horses grew taller by stretching", "55 million years ago, horses had 4 toes", "The fossils show no change"], ["Changes during life aren't inherited.", "One reading, not a conclusion.", "Contradicts the steady trend."], "Describe the trends in both rows.", "A steady series of changes over 55 million years is strong fossil evidence.", [["Age (million years ago)", "55", "35", "25", "5", "0"], ["Height (cm)", "40", "60", "100", "125", "160"], ["Toes per foot", "4", "3", "3", "1", "1"]]],
["E", "i", 5, "A student says lizards on two islands are separate species because they look different. What is the weakness?", ["Looking different isn't enough; they need to be tested for whether they can interbreed to produce fertile offspring", "More lizards should be counted", "Tail lengths should be measured", "Their diets should be compared"], ["Numbers don't test species status.", "More appearance data still doesn't test interbreeding.", "Diet doesn't define a species."], "What defines a species?", "Members of one species can look very different (dogs!). The test is fertile offspring."],
["A", "c", 5, "Transitional fossils such as Archaeopteryx exist.", "Archaeopteryx has features of both reptiles (teeth, bony tail) and birds (feathers, wings).", 0, "What makes a fossil 'transitional'?", "Its mix of reptile and bird features is exactly what makes it transitional. This answers the Warden who says there are no in-between fossils."]
]);

/* ---------- Life Processes in Plants ---------- */
KH("t12s1", [
["R", "c", 5, "Which help a root hair cell take in water?", ["Its long, thin extension gives a large surface area.", "Its cell sap has a lower water potential than the soil water.", "It contains many chloroplasts."], 0, ["True: more surface for uptake.", "True: water enters by osmosis.", "False: root hairs are underground and have no chloroplasts."], "Underground cells and light.", "Surface area and a water potential gradient drive water uptake."],
["T", "d", 5, "Seedlings were grown for 4 weeks in different solutions. Why is the distilled-water plant the lightest?", ["It lacks all minerals, so it can't make proteins, chlorophyll and other substances needed for growth", "Distilled water is poisonous", "It had a dry mass of 1 g", "It lacked only nitrate"], ["No: it just lacks minerals.", "A reading, not a reason.", "It lacked EVERY mineral, so it grew less than the no-nitrate plant."], "What is missing from distilled water?", "Each missing mineral limits growth; with none, growth is least.", [["Solution", "Leaf colour", "Dry mass (g)"], ["Complete", "green", "10"], ["No nitrate", "pale yellow", "3"], ["No magnesium", "yellow between veins", "7"], ["Distilled water", "pale", "1"]]],
["M", "c", 5, "Exam question: 'Explain how root hair cells take up nitrate ions when the soil has a lower concentration than the cell.' [2 marks]. Which answer scores both marks?", ["By active transport through carrier proteins, using ATP from respiration to move the ions against the concentration gradient", "By diffusion", "By osmosis", "By active transport"], ["Diffusion goes DOWN the gradient.", "Osmosis is the movement of water only.", "1 mark: needs the link to energy and the gradient."], "Process + energy + direction.", "Mark 1: active transport (carrier proteins). Mark 2: uses ATP to move ions against the gradient."],
["L", "c", 5, "Put the steps in order: the path of water from soil to stem.", ["Water enters the root hair cell by osmosis", "Water moves across the root cortex, cell to cell", "Water enters the xylem and is carried up the stem"], "Water is pumped into the root hair by active transport", "Root hair → cortex → xylem.", "Water always moves passively, by osmosis; ions may be pumped, but water isn't."]
]);
KH("t12s2", [
["A", "c", 5, "Transpiration helps move water and minerals up the stem.", "Water evaporating from the leaves pulls a continuous column of water up the xylem.", 0, "Join them with 'because'.", "The transpiration pull lifts the water column, and dissolved minerals travel with it."],
["T", "d", 5, "Potometer readings. Which statement is best supported?", ["Wind and higher temperature increase transpiration; humid air (the bag) reduces it greatly", "The bag stops all water uptake", "The fan moved the bubble 35 mm", "Temperature has no effect"], ["4 mm shows some uptake continues.", "A reading, not a conclusion.", "30 °C doubled the reading."], "Compare each condition with still air at 20 °C.", "Each factor changes the water vapour gradient or the rate of evaporation.", [["Condition", "Bubble moved in 5 min (mm)"], ["Still air, 20 °C", "15"], ["Fan, 20 °C", "35"], ["Still air, 30 °C", "30"], ["Plastic bag over shoot, 20 °C", "4"]]],
["E", "i", 5, "A student cut a leafy shoot in air and then fitted it to a potometer. The readings were very slow. What is the most likely cause?", ["Air entered the xylem and broke the water column; the shoot should be cut and fitted under water", "The shoot had too many leaves", "The air bubble should be larger", "The room was too bright"], ["More leaves would speed it up.", "Bubble size doesn't fix a blocked xylem.", "Light increases transpiration."], "What happens when a cut stem meets air?", "Cutting and fitting under water keeps the water column unbroken."],
["C", "c", 5, "Which is a valid comparison of transpiration and translocation?", ["Transpiration moves water and minerals upwards in the xylem, driven by evaporation, whereas translocation moves sugars up and down in the phloem, from sources to sinks", "Transpiration is in the phloem, whereas translocation is in the xylem", "Both carry sugars", "Transpiration: water. Translocation: food."], ["Reversed.", "Xylem carries water and ions, not sugar.", "Fragments with no comparative link."], "Tissue, substance, direction.", "Pair the tissue, what is carried and the direction for both processes."]
]);
KH("t12s3", [
["R", "c", 5, "Which statements about phloem are correct?", ["It carries sucrose.", "It can carry substances both up and down the plant.", "It is made of dead, hollow cells with lignified walls."], 0, ["True: sugars from leaves.", "True: from sources to sinks in any direction.", "False: that describes xylem; sieve tubes are living."], "Living or dead?", "Phloem is living tissue carrying sugars in both directions."],
["M", "c", 5, "Exam question: 'Explain why a young seedling wilts when it loses water.' [2 marks]. Which answer scores both marks?", ["Its cells lose water and become flaccid, so they no longer press against their cell walls, and the soft stem and leaves are not supported", "It dies", "It has no xylem", "Its cells lose turgor"], ["Not an explanation.", "Seedlings do have xylem.", "1 mark: missing the consequence (no support)."], "Cell change, then whole-plant effect.", "Mark 1: cells become flaccid. Mark 2: no turgor pressure, so no support."],
["N", "c", 6, "Farmers notice that plants heavily infested with aphids grow small fruits. Why?", ["Aphids remove sugars from the phloem, so less sucrose reaches the fruits (sinks) to build them", "Aphids drink water from the xylem", "Aphids eat the fruits directly", "Aphids stop photosynthesis completely"], ["Aphids feed on phloem sap.", "They feed from the phloem in stems and leaves.", "Leaves still photosynthesise; the sugar is diverted."], "What's in phloem sap?", "Sugar meant for the fruits is taken by the aphids."],
["L", "c", 5, "Put the steps in order: what happens after a ring of bark is removed from a stem?", ["The phloem in the ring is cut", "Sugars from the leaves can't move down past the ring", "Sugar collects and the bark swells just above the ring"], "Water can't reach the leaves, so they wilt immediately", "Bark contains phloem, not xylem.", "The xylem is deeper, so water still reaches the leaves; only sugar transport is blocked."]
]);

/* ---------- Nutrition in Humans ---------- */
KH("t8s1", [
["R", "c", 5, "A vegan diet needs careful planning. Which nutrients may be low in it?", ["Vitamin B12", "Easily absorbed iron", "Dietary fibre"], 0, ["True: B12 is found almost only in animal foods.", "True: plant iron is absorbed less easily.", "False: plant-based diets are usually HIGH in fibre."], "Which nutrient do plants have plenty of?", "Vegans may need B12 supplements and iron-rich plant foods eaten with vitamin C."],
["T", "d", 5, "Nutrition labels (per 100 g). Which advice is best supported for someone who wants less energy but to stay full?", ["Choose brown rice over fried noodles: less energy and fat, more fibre", "Choose fried noodles, because they have the most protein", "Avoid tofu because it has little fibre", "White rice has 550 kJ"], ["The protein is higher, but the energy and fat are far higher.", "Overclaiming: tofu is a low-energy protein source.", "A reading, not advice."], "Compare energy, fat and fibre.", "Fibre adds bulk without energy; fried foods are energy-dense.", [["Food", "Energy (kJ)", "Protein (g)", "Fat (g)", "Fibre (g)"], ["White rice", "550", "2.7", "0.3", "0.4"], ["Brown rice", "520", "2.6", "0.9", "1.8"], ["Fried noodles", "1900", "6", "22", "2"], ["Tofu", "320", "8", "4.8", "0.3"]]],
["C", "c", 5, "Which is a valid comparison of vitamins and minerals?", ["Vitamins are organic compounds needed in small amounts (e.g. vitamin C for collagen), whereas minerals are inorganic ions (e.g. iron for haemoglobin)", "Vitamins give energy, whereas minerals don't", "Vitamins: fruit. Minerals: rocks.", "Minerals are organic, whereas vitamins are inorganic"], ["Neither provides energy.", "Not a biological comparison.", "Reversed."], "Organic vs inorganic.", "Both are needed in small amounts; they differ in chemical nature."],
["L", "c", 5, "Put the steps in order: how does too little iron in the diet cause tiredness?", ["Too little iron is absorbed", "Less haemoglobin is made", "Less oxygen is carried, so cells release less energy (anaemia)"], "Iron is needed to make white blood cells", "Iron → haemoglobin → oxygen.", "Iron is part of haemoglobin, not white blood cells."]
]);
KH("t8s2", [
["A", "c", 5, "Bile helps lipase digest fats.", "Bile contains enzymes that break down fats.", 2, "Does bile digest anything chemically?", "Bile has no enzymes. It emulsifies fats into small droplets, giving lipase more surface area."],
["T", "d", 5, "Visking tubing with starch and amylase was put in water, which was tested over time. Which conclusion is best supported?", ["Amylase digested starch into sugar, which diffused out; starch is too large to pass through", "Starch passed through the tubing", "Amylase passed out and digested starch outside", "At 30 minutes the Benedict's test was orange"], ["Iodine outside stayed brown: no starch.", "There's no starch outside to digest, and enzymes are large proteins.", "A reading only."], "What appears outside, and what doesn't?", "Sugar appears outside and rises over time; starch never does.", [["Time (min)", "0", "10", "20", "30"], ["Benedict's test on water", "blue", "green", "yellow", "orange"], ["Iodine test on water", "brown", "brown", "brown", "brown"]]],
["M", "c", 5, "Exam question: 'Explain why the stomach does not digest itself.' [2 marks]. Which answer scores both marks?", ["The stomach wall secretes mucus, which forms a barrier so acid and pepsin can't reach and digest the lining cells", "Mucus", "Pepsin can't digest protein", "The stomach wall contains no protein"], ["A keyword only.", "It does: the lining is made of protein.", "Its cells are full of protein."], "Structure + protection.", "Mark 1: mucus is secreted. Mark 2: it stops acid/pepsin reaching the lining."],
["N", "c", 6, "After gall bladder removal, patients are often advised to eat low-fat meals. Why?", ["Bile is no longer stored and released in large amounts, so large fatty meals are emulsified less well and digested more slowly", "The gall bladder makes lipase", "Fat can no longer be absorbed at all", "The liver stops making bile"], ["Lipase comes from the pancreas; the gall bladder only stores bile.", "Overclaiming: fat is still digested, just less efficiently.", "The liver still makes bile; it just isn't stored."], "Making vs storing bile.", "Bile trickles in steadily instead of in a big squirt at mealtimes."]
]);
KH("t8s3", [
["R", "c", 5, "Which features of villi increase absorption?", ["Microvilli on the epithelial cells", "A dense network of blood capillaries", "A thick muscular wall"], 0, ["True: they increase the surface area even more.", "True: blood carries absorbed food away, keeping the gradient steep.", "False: a thick wall would slow diffusion; villus walls are one cell thick."], "Surface, distance, gradient.", "Villi have a huge surface, a thin wall and a good blood supply."],
["T", "d", 5, "Tests on a healthy person and a patient with coeliac disease. Which explanation is best?", ["Flattened villi give a much smaller surface area, so less glucose is absorbed", "Coeliac patients don't eat glucose", "Villus height fell from 500 to 150 µm", "The patient's blood already has too much glucose"], ["Both drank the same test drink.", "Describes the data but doesn't explain the absorption.", "No evidence of this."], "Link villus height to absorption.", "Shorter villi mean less surface area for absorption.", [["Measurement", "Healthy", "Coeliac patient"], ["Villus height (µm)", "500", "150"], ["Glucose absorbed in 1 h (%)", "95", "40"]]],
["E", "i", 5, "To show glucose but not starch passes through Visking tubing, a student tested the outside water after just 1 minute and found no glucose. What is the flaw?", ["One minute is too short for glucose to diffuse out in detectable amounts, so the result may be a false negative", "More starch should be used", "The inside should be tested, not the outside", "The tubing should be heated"], ["More starch doesn't help detect glucose.", "The question is what passes OUT.", "Heating adds a variable and could damage the tubing."], "Diffusion takes time.", "Leave it longer (e.g. 20–30 minutes) and test at intervals."],
["L", "c", 5, "Put the steps in order: what happens to glucose after it is absorbed?", ["Glucose enters the blood capillaries in the villi", "It travels in the hepatic portal vein to the liver", "Extra glucose is stored as glycogen; the rest is used in respiration by cells"], "Glucose travels in the lacteals to the lymph", "Blood, liver, cells.", "Lacteals carry fats, not glucose."]
]);

/* ---------- Gas Exchange in Humans ---------- */
KH("t13s1", [
["R", "c", 5, "Which features make the alveoli efficient at gas exchange?", ["A very large total surface area", "Walls only one cell thick", "Dry walls that stop water loss"], 0, ["True: about 70 m² in an adult.", "True: a short diffusion distance.", "False: a moist lining lets gases dissolve before they diffuse."], "Gases must dissolve first.", "Large area, thin walls, a moist surface and a good blood supply."],
["T", "d", 6, "Composition of air (%). Why does exhaled air contain more oxygen than alveolar air?", ["Exhaled air mixes with air from the trachea and bronchi (dead space), which took no part in gas exchange", "Oxygen moves from the blood into the alveoli as we breathe out", "Exhaled air contains 16% oxygen", "Respiration produces oxygen"], ["Oxygen moves into the blood, never out into the alveoli.", "A reading, not a reason.", "Respiration USES oxygen."], "Where else is air when we breathe out?", "Air in the airways mixes with alveolar air on the way out.", [["Gas", "Inhaled", "Alveolar", "Exhaled"], ["Oxygen", "21", "14", "16"], ["Carbon dioxide", "0.04", "5.5", "4"]]],
["C", "c", 5, "Which is a valid comparison of the trachea and the bronchioles?", ["The trachea is held open by C-shaped rings of cartilage, whereas bronchioles have no cartilage and can narrow, as in an asthma attack", "The trachea carries air. Bronchioles carry air.", "Bronchioles have cartilage, whereas the trachea has none", "Gas exchange happens in the trachea, whereas bronchioles only conduct air"], ["The same function stated twice: no difference.", "Reversed.", "Gas exchange happens in the alveoli."], "Pair one structural feature.", "Cartilage keeps the big airway open; smooth muscle in bronchioles can narrow them."],
["N", "c", 6, "Climbers at 5000 m feel breathless even at rest. Why?", ["The air pressure is lower, so each breath delivers less oxygen and the gradient for diffusion into the blood is smaller", "Air at altitude contains no oxygen", "Their lungs shrink in the cold", "Cold air blocks the alveoli"], ["Air is still about 21% oxygen; it's the pressure that is lower.", "The lungs don't shrink.", "Not a real effect."], "Percentage vs pressure.", "Less oxygen per breath means a smaller gradient into the blood."]
]);
KH("t13s2", [
["A", "c", 5, "When the diaphragm contracts, air enters the lungs.", "Contraction of the diaphragm increases the volume of the thorax and lowers the pressure inside it.", 0, "Join them with 'because'.", "A lower pressure inside the lungs than outside makes air flow in."],
["T", "d", 5, "Pressure in the alveoli relative to the atmosphere. Why does air flow in at mid-inhalation?", ["Alveolar pressure is below atmospheric pressure, so air flows in down the pressure gradient", "The lungs expand by themselves and suck air in", "Alveolar pressure is higher than the atmosphere", "The pressure is −0.2 kPa"], ["Lungs are passive: the thorax expands and they follow.", "Reversed.", "A reading, not a reason."], "Air flows from high to low pressure.", "A negative relative pressure means it is lower inside, so air flows in.", [["Phase", "Start of breath in", "Mid breath in", "End of breath in", "Mid breath out"], ["Alveolar pressure (kPa vs atmosphere)", "0", "−0.2", "0", "+0.2"]]],
["L", "c", 5, "Put the steps in order: breathing in.", ["The external intercostal muscles and diaphragm contract", "The thorax volume increases, so the pressure in the lungs falls", "Air is pushed in by the higher atmospheric pressure"], "The lungs inflate first, pushing the ribs outwards", "Muscles first.", "The lungs follow the chest wall; they don't push it."],
["M", "c", 5, "Exam question: 'Explain why breathing out is usually passive at rest.' [2 marks]. Which answer scores both marks?", ["The diaphragm and external intercostal muscles relax, and the elastic lungs recoil, reducing the thorax volume and raising the pressure so air is forced out", "The muscles relax", "The lungs push air out using muscle", "Because we don't need energy"], ["1 mark: missing recoil, volume and pressure.", "Lungs have no skeletal muscle.", "Too vague."], "Relax + recoil + pressure.", "Mark 1: muscles relax. Mark 2: elastic recoil reduces volume and raises pressure."]
]);
KH("t13s3", [
["R", "c", 5, "Which effects does smoking have on the respiratory system?", ["Cilia are damaged and stop sweeping.", "More mucus is produced.", "Alveolar walls become thicker and stronger."], 0, ["True: tar and chemicals damage cilia.", "True: goblet cells make extra mucus, leading to smoker's cough.", "False: in emphysema, alveolar walls break down."], "Emphysema destroys walls.", "Damaged cilia and extra mucus cause coughing and infections."],
["T", "d", 6, "A study of 1000 people in each group. Which conclusion is best supported?", ["COPD risk rises with the number of cigarettes smoked, and quitting reduces the risk compared with carrying on", "Quitting removes all the risk", "Smoking 10 a day is safe", "250 heavy smokers developed COPD"], ["60 cases vs 20 for never-smokers: some risk remains.", "Six times the never-smoker rate.", "A reading, not a conclusion."], "Compare each group with never-smokers.", "Dose-response, plus the benefit of quitting.", [["Group", "COPD by age 60 (per 1000)"], ["Never smoked", "20"], ["10 a day", "120"], ["20 a day", "250"], ["Quit at 40", "60"]]],
["E", "i", 6, "A study compares smokers recruited from a hospital lung clinic with non-smokers recruited from a gym. What is the main flaw?", ["The groups differ in more than smoking (already ill vs very fit), so the comparison is biased", "More smokers than non-smokers should be included", "Only women should be studied", "The study should last one week"], ["Equal sizes help, but the bias remains.", "That limits the study; it doesn't fix the bias.", "Far too short for lung disease."], "How were the groups chosen?", "Groups should be matched, or chosen from the same population, so smoking is the main difference."],
["A", "c", 5, "Carbon monoxide in cigarette smoke reduces the oxygen carried by the blood.", "Carbon monoxide binds to haemoglobin more strongly than oxygen does.", 0, "Join them with 'because'.", "CO takes up haemoglobin's binding sites, so less oxygen is carried."]
]);

/* ---------- Transport in Humans ---------- */
KH("t14s1", [
["R", "c", 5, "Which are adaptations of capillaries for exchange?", ["Walls only one cell thick", "Very narrow, so red cells pass slowly in single file", "Thick, elastic walls"], 0, ["True: a short diffusion distance.", "True: more time and contact for exchange.", "False: that describes arteries."], "Exchange needs thin and slow.", "Capillaries are built for exchange, not for withstanding pressure."],
["T", "d", 5, "Features of three blood vessels. Which is the vein?", ["B", "A", "C", "It can't be told without pressure data"], ["A thick wall and no valves: an artery.", "A wall one cell thick and a tiny lumen: a capillary.", "Wall, lumen and valves are enough to tell."], "Valves are the giveaway.", "B has a thin wall, a wide lumen and valves.", [["Vessel", "Wall (mm)", "Lumen (mm)", "Valves"], ["A", "2.0", "4", "no"], ["B", "0.5", "5", "yes"], ["C", "0.001", "0.008", "no"]]],
["M", "c", 5, "Exam question: 'Explain why a person with very few platelets bruises easily.' [2 marks]. Which answer scores both marks?", ["Platelets help blood clot at damaged vessels, so with few platelets bleeding under the skin isn't stopped quickly, causing bruises", "Platelets carry oxygen", "Platelets", "Their blood is thinner"], ["Red blood cells carry oxygen.", "A keyword only.", "Too vague."], "Role, then consequence.", "Mark 1: platelets are needed for clotting. Mark 2: without them, bleeding continues, causing bruising."],
["L", "c", 5, "Put the steps in order: blood clotting.", ["A blood vessel is damaged", "Platelets and clotting factors convert fibrinogen into insoluble fibrin", "Fibrin threads trap blood cells, forming a clot"], "Red blood cells stick together into a clot without platelets", "Damage, fibrin, trap.", "Clotting needs platelets and fibrin; red cells are only trapped."]
]);
KH("t14s2", [
["A", "c", 5, "The left ventricle wall is thicker than the right.", "The left ventricle pumps blood to the lungs.", 2, "Where does the left ventricle pump to?", "The LEFT ventricle pumps to the whole body (needing high pressure); the right pumps to the lungs."],
["T", "d", 6, "Pressures (kPa) on the left side of the heart in one heartbeat. When is the aortic (semilunar) valve open?", ["About 0.1–0.2 s, when ventricle pressure is above aortic pressure", "At 0.0 s", "At 0.4 s", "At 0.3 s"], ["Ventricle pressure (0.8) is far below the aorta's: the valve is shut.", "Ventricle 0.5 < aorta 10: shut. The bicuspid valve is open instead.", "Ventricle 4 < aorta 11: shut."], "A valve opens when pressure behind it is higher.", "Compare the ventricle row with the aorta row at each time.", [["Time (s)", "0.0", "0.1", "0.2", "0.3", "0.4"], ["Left atrium", "1.0", "0.8", "0.6", "0.6", "1.2"], ["Left ventricle", "0.8", "13", "16", "4", "0.5"], ["Aorta", "10", "12", "15", "11", "10"]]],
["C", "c", 5, "Which is a valid comparison of arteries and veins?", ["Arteries have thick, muscular, elastic walls to withstand high pressure, whereas veins have thinner walls, a wider lumen and valves to keep low-pressure blood flowing back", "Arteries carry oxygenated blood, whereas veins carry deoxygenated blood", "Arteries have valves, whereas veins do not", "Arteries: thick. Veins: thin."], ["Not always: the pulmonary artery and vein are the other way round.", "Reversed.", "Fragments with no link to function."], "Structure linked to pressure.", "Compare the same features and link them to blood pressure."],
["E", "i", 5, "A student measured their 'resting' heart rate straight after climbing three flights of stairs. What is the flaw?", ["The rate was measured before it returned to rest; they should sit quietly for 5 minutes first", "They should count for only 10 seconds", "They should only measure at the neck", "They should use a different person"], ["Shorter counts are less accurate.", "Where you measure doesn't fix the problem.", "Doesn't fix the timing."], "Is it really resting?", "Heart rate stays high after exercise, so a true resting rate needs rest first."]
]);
KH("t14s3", [
["R", "c", 5, "Which statements about tissue fluid are correct?", ["It forms when plasma is forced out at the arterial end of capillaries.", "It carries oxygen and glucose to the body cells.", "It contains red blood cells."], 0, ["True: high blood pressure pushes plasma out.", "True: cells exchange substances with it.", "False: red cells are too big to leave the capillaries."], "What's too big to leave?", "Tissue fluid is plasma without the cells and large proteins."],
["T", "d", 6, "Coronary heart disease cases per 1000 people. Which conclusion is supported?", ["Each factor raises the risk, and together the risk is greater than their separate effects added up", "Smoking is the only cause of CHD", "High blood pressure has no effect", "Group D has 40 cases"], ["Group A has CHD without either factor.", "C is higher than A.", "A reading, not a conclusion."], "Add the separate increases and compare with D.", "Smoking adds 10 and high blood pressure adds 7 (22 in total), but D has 40: the effects multiply.", [["Group", "Smoker", "High blood pressure", "CHD cases per 1000"], ["A", "no", "no", "5"], ["B", "yes", "no", "15"], ["C", "no", "yes", "12"], ["D", "yes", "yes", "40"]]],
["L", "c", 5, "Put the steps in order: how can a heart attack happen?", ["Fatty plaques build up in a coronary artery wall", "The lumen narrows and less blood reaches the heart muscle", "Heart muscle cells get too little oxygen and may die"], "The heart then pumps harder and clears the plaque", "Plaque, narrowing, starving.", "Plaques don't clear by themselves; that's why lifestyle and treatment matter."],
["M", "c", 5, "Exam question: 'Explain how lymph helps return fluid to the blood.' [2 marks]. Which answer scores both marks?", ["Excess tissue fluid drains into lymph vessels, which carry it as lymph back to the blood in veins near the heart", "Lymph", "Lymph pumps the blood", "Lymph returns fluid"], ["A keyword only.", "Lymph doesn't pump blood.", "1 mark: missing where it comes from and where it goes."], "Where from, where to.", "Mark 1: excess tissue fluid enters lymph vessels. Mark 2: lymph returns it to the blood near the heart."]
]);
