
/* 🔥 Hard formats, part 4: Reproduction, Coordination, Homeostasis, Ecosystems, Health (format: see q_h0.js). */

/* ---------- Reproduction, Growth and Development ---------- */
KH("t15s1", [
["R", "c", 5, "Which features suggest a flower is insect-pollinated?", ["Brightly coloured petals", "Nectar and a scent", "Large feathery stigmas hanging outside the flower"], 0, ["True: colour attracts insects.", "True: nectar and scent are rewards and signals.", "False: feathery, hanging stigmas catch wind-blown pollen."], "Attract insects vs catch the wind.", "Insect flowers advertise; wind flowers expose their anthers and stigmas."],
["T", "d", 5, "Seeds were kept in different conditions for a week. Which conclusion is best supported?", ["Germination needs water, oxygen and a suitable temperature", "Germination needs only water", "Low temperature stops germination completely", "Seeds in A germinated best"], ["C had water but no oxygen: only 3% germinated.", "D still had 15% germination.", "A reading, not a conclusion."], "Compare each tube with A, changing one factor.", "Removing water or oxygen almost stops germination; cold slows it.", [["Tube", "Water", "Oxygen", "Temperature (°C)", "Germinated (%)"], ["A", "yes", "yes", "25", "92"], ["B", "no", "yes", "25", "0"], ["C", "yes", "no", "25", "3"], ["D", "yes", "yes", "5", "15"]]],
["C", "c", 5, "Which is a valid comparison of pollen from insect-pollinated and wind-pollinated flowers?", ["Insect pollen: fewer, larger, sticky; wind pollen: many, small, light", "Wind pollen: light. Insect pollen: sticky.", "Wind-pollinated flowers have big, bright petals", "Insect-pollinated flowers make more pollen"], ["Fragments, not a paired comparison.", "Reversed.", "Reversed."], "Number, size, surface: paired.", "Pollen is adapted to how it travels."],
["L", "c", 5, "Put the steps in order: from pollination to fertilisation.", ["A pollen grain lands on the stigma", "A pollen tube grows down the style to the ovule", "The male nucleus fuses with the egg nucleus in the ovule"], "The whole pollen grain swims down to the ovary", "Land, grow, fuse.", "Only the pollen tube grows down; the male gamete travels inside it."]
]);
KH("t15s2", [
["A", "c", 5, "The contraceptive pill can prevent pregnancy.", "Its hormones stop the release of FSH and LH, so no egg is released (no ovulation).", 0, "Join them with 'because'.", "Without the LH surge there is no ovulation, so there is no egg to fertilise."],
["T", "d", 5, "Hormone levels in one menstrual cycle. On which day is ovulation most likely?", ["Day 14, after the LH surge", "Day 21, when progesterone is at its highest level", "Day 2, when the uterus lining is being shed", "Day 27, just before the next period begins"], ["Progesterone peaks then, after ovulation.", "That's during menstruation.", "Hormones are falling before menstruation."], "LH triggers ovulation.", "The LH surge (day 13) triggers ovulation about a day later.", [["Day", "2", "8", "13", "14", "21", "27"], ["Oestrogen", "low", "rising", "peak", "high", "medium", "low"], ["LH", "low", "low", "peak", "high", "low", "low"], ["Progesterone", "low", "low", "low", "low", "peak", "low"]]],
{ f: "G", k: "d", b: 6, q: "Which graph shows progesterone over a 28-day menstrual cycle in which NO pregnancy happens?", gch: [{ pts: [[0, 1], [12, 1], [16, 4], [21, 9], [26, 3], [28, 1]] }, { pts: [[0, 1], [12, 1], [13.5, 10], [15, 1], [28, 1]] }, { pts: [[0, 1], [12, 1], [16, 4], [21, 9], [28, 10]] }, { pts: [[0, 9], [7, 6], [14, 2], [28, 1]] }], gax: ["day 1 → 28", "progesterone"], choices: ["Low in the first half, rising after ovulation, peaking around day 21, then falling", "A sharp spike on day 14 only", "Rising after ovulation and staying high", "High at the start, falling all month"], why: ["That's the LH surge, which triggers ovulation.", "That's what happens if pregnancy occurs.", "Progesterone is made after ovulation, so it is low at the start."], hint: "Progesterone comes from what's left of the follicle after ovulation.", explain: "After ovulation, progesterone keeps the uterus lining ready. With no pregnancy, it falls near the end of the cycle, and the lining is shed (menstruation)." },
["N", "c", 6, "A medicine taken in pregnancy is made of small, lipid-soluble molecules. Why is it likely to reach the fetus?", ["Small, lipid-soluble molecules can diffuse across the placenta's thin membranes into the fetal blood", "The placenta actively pumps all drugs to the fetus", "Drugs mix in because the bloods join", "Only large molecules can cross the placenta"], ["The placenta doesn't pump every substance across.", "The bloods never join.", "Reversed: small molecules cross most easily."], "Membranes are made of lipid.", "This is why pregnant women are advised to avoid many drugs, alcohol and nicotine."]
]);
KH("t15s3", [
["R", "c", 5, "Which are suitable measures of a seedling's growth?", ["Dry mass", "Length of the shoot over time", "Fresh (wet) mass straight after watering"], 0, ["True: shows only new material.", "True: easy and doesn't kill the plant (though it ignores width).", "False: water content changes, so fresh mass is unreliable."], "Water comes and goes.", "Dry mass is the best measure; length is a useful non-destructive one."],
["T", "d", 6, "A child's height over time. Between which ages was the growth RATE highest?", ["0–2 years", "12–14 years", "The rate was the same throughout", "At 14 years, when the child was tallest"], ["That's the growth spurt (7 cm/year), but it's still slower than infancy (19 cm/year).", "The rate changes a lot.", "Tallest isn't the same as fastest growing."], "Work out cm per year for each interval.", "0–2 years: (88 − 50) ÷ 2 = 19 cm per year, the highest.", [["Age (years)", "0", "2", "4", "6", "8", "10", "12", "14"], ["Height (cm)", "50", "88", "103", "116", "128", "139", "151", "165"]]],
["E", "i", 5, "To track seedling growth, a student picked one seedling at random each day, dried it and weighed it. What is the main weakness?", ["One seedling a day is too few, as seedlings vary; dry a large sample each day and use the mean", "The seedlings should be weighed wet", "The same seedling should be dried every day", "The seedlings should be dried at 300 °C"], ["Wet mass is unreliable.", "A dried seedling is dead and can't keep growing.", "That burns the organic matter."], "Natural variation.", "A mean from many seedlings gives a reliable growth curve."],
["L", "c", 5, "Put the steps in order: how does a seed get the energy to germinate?", ["The seed absorbs water and swells", "Enzymes are activated and break stored starch into sugars", "Sugars are used in respiration, releasing energy for growth"], "The seed photosynthesises underground to make energy", "Water, enzymes, respiration.", "Seeds use stored food until their first leaves can photosynthesise."]
]);

/* ---------- Coordination and Response ---------- */
KH("t16s1", [
["A", "c", 5, "We can't see colours well in dim light.", "Cones need bright light to be stimulated.", 0, "Join them with 'because'.", "Cones detect colour but need bright light; in dim light mainly rods work, giving black-and-white vision."],
["T", "d", 5, "Pupil diameter at different light intensities. Which explanation of the trend is best?", ["Circular muscles contract; pupil narrows", "The pupil shrinks because the light burns it", "At 10 000 lux the pupil is 2 mm", "Radial muscles contract in bright light"], ["The pupil is a hole, and this is a reflex, not damage.", "A reading, not an explanation.", "Reversed: radial muscles contract in DIM light."], "Which muscles narrow the pupil?", "The pupil reflex adjusts how much light enters the eye.", [["Light (lux)", "1", "10", "100", "1000", "10 000"], ["Pupil diameter (mm)", "7.5", "6.5", "4.5", "3", "2"]]],
{ f: "S", k: "c", b: 5, q: "Sort each change in the eye: focusing on something NEAR, or something FAR away?", bins: ["Near object", "Far object"], items: [["Ciliary muscles contract", 0], ["Suspensory ligaments are pulled tight", 1], ["Lens becomes thicker (more convex)", 0], ["Lens bends light less", 1], ["Ciliary muscles relax", 1], ["Suspensory ligaments slacken", 0]], hint: "Near = fat lens.", explain: "Near: ciliary muscles contract, ligaments slacken, the lens rounds up and bends light more. Far: muscles relax, ligaments tighten, and the lens is pulled thin." },
["L", "c", 5, "Put the steps in order: focusing on a NEAR object.", ["The ciliary muscles contract", "The suspensory ligaments slacken", "The lens becomes thicker and bends light more"], "The suspensory ligaments pull tight and squeeze the lens fat", "Muscle, ligament, lens.", "Tight ligaments pull the lens THIN (for distant objects); slack ligaments let it round up."]
]);
KH("t16s2", [
["R", "c", 5, "Which are features of a reflex action?", ["It is rapid.", "It is automatic, without conscious thought.", "It always involves the cerebrum."], 0, ["True: few neurones, short pathway.", "True: you don't decide to do it.", "False: many reflexes pass through the spinal cord only."], "Where does a reflex arc go?", "Reflexes are fast, automatic and protective."],
["T", "d", 5, "Ruler-drop reaction times. Which conclusion is best supported?", ["Tiredness and distraction slow reactions", "Video gaming makes reactions much faster than normal", "Texting gave a catch distance of 25 cm, the biggest result", "Sleep has no effect on reaction time at all"], ["0.15 vs 0.16 s is a tiny difference, likely within error.", "A reading, not a conclusion.", "A sleepless night slowed reactions by 0.04 s."], "Compare each condition with 'rested'.", "Only the big differences (sleepless, texting) are likely to be real effects.", [["Condition", "Mean catch distance (cm)", "Reaction time (s)"], ["Rested", "12", "0.16"], ["After 1 h of video games", "11", "0.15"], ["After a sleepless night", "20", "0.20"], ["While texting", "25", "0.23"]]],
["C", "c", 5, "Which is a valid comparison of nervous and hormonal coordination?", ["Nervous responses are fast, short-lived and precise (impulses along neurones), whereas hormonal responses are slower, longer-lasting and widespread (chemicals in the blood)", "Nerves use electrical signals, whereas hormones use chemical signals; both are equally fast", "Hormonal responses are faster and more precise than nervous responses", "Both nervous and hormonal signals travel in the blood to their target organs"], ["Fragments, and only one feature.", "Reversed.", "Nerve impulses travel along neurones."], "Speed, duration, route.", "Pair several features with linking words."],
["L", "c", 5, "Put the steps in order: the reflex arc when you touch a hot object.", ["A receptor in the skin detects the heat", "An impulse travels along a sensory neurone to a relay neurone in the spinal cord", "A motor neurone carries the impulse to a muscle, which contracts"], "The brain decides to move the hand before the spinal cord acts", "Receptor, sensory, relay, motor, effector.", "The hand moves before the brain is even aware of the pain."]
]);
KH("t16s3", [
["A", "c", 5, "Adrenaline increases heart rate in danger.", "Adrenaline is carried in the blood to its target organs.", 1, "Is being carried in blood the REASON heart rate rises?", "Both are true, but transport in blood only explains how it arrives, not why the heart speeds up."],
["T", "d", 6, "Oat shoots were lit from one side. What does the 'mica on the shaded side' result show?", ["A chemical must move down the shaded side from the tip to cause bending", "Light is detected by the base of the shoot", "Mica produces auxin", "The intact shoot bent towards the light"], ["Removing the tip stops bending, so the tip is needed.", "Mica is an inert barrier.", "A reading, not a conclusion."], "What does mica block?", "Blocking the shaded side stops bending; blocking the lit side doesn't. So auxin moving down the SHADED side causes the bending.", [["Treatment", "Result"], ["Intact shoot", "bends towards light"], ["Tip removed", "no bending"], ["Mica barrier, shaded side", "no bending"], ["Mica barrier, lit side", "bends towards light"]]],
["E", "i", 5, "A student lit 2 seedlings per treatment from a sunny window whose light changed during the day. What is the best improvement?", ["Use a fixed lamp in a dark box and many seedlings per treatment", "Water only the lit side of the seedlings, so they bend towards the water", "Remove all the tips, so the seedlings grow straight and are easier to measure", "Measure after 1 minute, before the light from the window changes"], ["That adds another variable.", "That stops every response.", "Too soon to see any bending."], "Control light and increase the sample.", "A fixed light source controls direction and intensity; more seedlings improve reliability."],
["N", "c", 6, "Gardeners spray lawns with a synthetic auxin weedkiller. Broad-leaved weeds die, but the grass survives. Why?", ["Weeds are more sensitive to the auxin", "Auxin kills all plants equally", "Grass absorbs no chemicals", "Auxin only blocks photosynthesis in weeds"], ["Then the grass would die too.", "Grass absorbs it, but responds less.", "The mechanism is abnormal growth."], "Different plants, different sensitivity.", "Selective weedkillers use the different responses of plant groups to plant hormones."]
]);
KH("t16s4", [
["R", "c", 5, "Which must happen for the arm to bend at the elbow?", ["The biceps contracts.", "The triceps relaxes.", "The biceps pushes the forearm upwards."], 0, ["True: it pulls the radius.", "True: its antagonist must relax.", "False: muscles can only PULL."], "Remember the Signal Towers' Warden.", "Antagonistic pairs: one contracts and pulls while the other relaxes."],
{ f: "K", k: "c", b: 6, q: "A basketball player injures a knee. Which explanation fits ALL the evidence?", case: [["🏀", "Injury", "Landed awkwardly; the knee wobbled sideways."], ["🩻", "Scan", "A torn ligament. Muscles and tendons are fine."], ["🦵", "Symptoms", "Can still straighten the leg, but the joint feels unstable."]], choices: ["Ligament torn: joint unstable, movement intact", "A torn tendon stops the leg straightening", "Torn cartilage stops the muscles contracting", "Ligaments contract to move the bones"], why: ["The tendons are fine, and the leg CAN straighten.", "Cartilage protects the bone ends; it doesn't control muscles.", "Ligaments don't contract; muscles do."], hint: "Ligament vs tendon: what does each join?", explain: "Tendons (muscle to bone) are needed for movement; ligaments (bone to bone) hold the joint in place. That's why the leg moves but feels unstable." },
["C", "c", 5, "Which is a valid comparison of ligaments and tendons?", ["Ligaments join bone to bone and are slightly elastic, whereas tendons join muscle to bone and are inelastic, so the muscle's pull is passed on fully", "Tendons join bone to bone, whereas ligaments join muscle to bone", "Ligaments: joints. Tendons: muscles.", "Both are very elastic"], ["Reversed.", "Fragments.", "Tendons must be inelastic."], "What does each join, and how stretchy is it?", "Structure (elasticity) matches each one's job."],
["L", "c", 5, "Put the steps in order: from nerve impulse to movement.", ["A nerve impulse reaches the muscle", "Muscle fibres use ATP to contract and shorten", "The tendon pulls the bone, moving it at the joint"], "The bone moves first and stretches the muscle", "Signal, contraction, movement.", "The muscle causes the movement, not the other way round."]
]);

/* ---------- Homeostasis ---------- */
KH("t17s1", [
["R", "c", 5, "Which happen after drinking a sugary drink?", ["The pancreas releases more insulin.", "The liver converts glucose into glycogen.", "More glucagon is released."], 0, ["True: insulin rises when glucose rises.", "True: insulin makes the liver store glucose.", "False: glucagon is released when glucose FALLS."], "Which hormone lowers glucose?", "Insulin lowers blood glucose; glucagon raises it."],
["T", "d", 5, "Glucose tolerance test (blood glucose, mmol/L) after a glucose drink. Which interpretation is best?", ["Person B probably has diabetes: their glucose starts high, rises more and stays high, showing a poor insulin response", "Person A has diabetes because their glucose rose to 8", "Both people are normal", "Person B peaked at 15 at 60 minutes"], ["A normal rise after a glucose drink: it returned to 5 within 2 hours.", "B stays far above normal.", "A reading, not an interpretation."], "Who returns to normal?", "A healthy response returns to baseline within about 2 hours.", [["Time (min)", "0", "30", "60", "90", "120"], ["Person A", "5.0", "8.0", "6.5", "5.5", "5.0"], ["Person B", "7.5", "13", "15", "14", "12"]]],
{ f: "P", k: "d", b: 6, q: "Blood glucose of a person who drank a sugary drink at time 0 and then skipped lunch. Tap the point where GLUCAGON secretion was most likely highest.", tap: { chart: { x: [0, 150, 30, "time / min"], y: [3, 10, 1, "blood glucose / mmol/L"], series: [{ pts: [[0, 5], [30, 9], [60, 6], [90, 4.2], [120, 4.8], [150, 5]], dots: true }] }, want: 3 }, hint: "Glucagon is released when glucose is LOW.", explain: "At 90 minutes, glucose dipped below normal (insulin overshot), so the pancreas released glucagon, which made the liver release glucose, bringing it back up by 120 minutes." },
["L", "c", 5, "Put the steps in order: what happens when blood glucose falls?", ["Blood glucose falls below normal", "The pancreas releases glucagon", "The liver breaks glycogen down into glucose, raising blood glucose"], "Insulin is released to raise blood glucose", "Fall, signal, response.", "Glucagon raises glucose; insulin lowers it."]
]);
KH("t17s2", [
["A", "c", 5, "Breathing rate rises during exercise.", "Exercise lowers the CO₂ concentration in the blood.", 2, "What do working muscles release?", "Exercise RAISES blood CO₂, and that rise is detected and drives faster breathing."],
["T", "d", 6, "Breathing rate of a resting person breathing different air mixtures. Which conclusion is best supported?", ["Breathing rate is much more sensitive to a rise in CO₂ than to a fall in O₂", "Low oxygen is the main stimulus for breathing", "CO₂ has no effect", "Breathing 5% CO₂ gave 30 breaths per minute"], ["Halving the oxygen raised the rate only to 18.", "5% CO₂ more than doubled it.", "A reading, not a conclusion."], "Compare the size of each effect.", "A small rise in CO₂ has a big effect; a big fall in O₂ has a small one.", [["Air breathed", "Breaths per minute"], ["Normal air", "12"], ["5% CO₂, normal O₂", "30"], ["15% O₂, normal CO₂", "14"], ["10% O₂, normal CO₂", "18"]]],
["E", "i", 5, "A student counted a friend's breaths for 10 seconds after exercise, while the friend knew they were being counted. What is the best improvement?", ["Count for a full minute, unnoticed", "Measure only before exercise, so the breathing rate is not affected by tiredness", "Count heartbeats instead, because they are easier to count than breaths", "Make the friend exercise for longer, so the breathing is faster and easier to count"], ["You need after-exercise values.", "That's a different variable.", "That doesn't fix the measurement problem."], "Breathing can be controlled on purpose.", "Unnoticed, longer counts give a more valid and accurate rate."],
["N", "c", 6, "Some divers breathe very fast and deep (hyperventilate) before a breath-hold dive. Why is this dangerous?", ["It lowers blood CO₂, so the urge to breathe is delayed even as O₂ falls dangerously low, risking blackout", "It fills the lungs with extra oxygen for safety", "It raises blood CO₂", "It makes the lungs burst"], ["Blood oxygen barely rises; the danger is the low CO₂.", "Reversed.", "Not what happens."], "What triggers the urge to breathe?", "Without the CO₂ warning signal, oxygen can run out before the diver feels the need to surface."]
]);

/* ---------- Ecosystems ---------- */
KH("t18s1", [
["R", "c", 5, "Which are biotic factors?", ["Competition from another species", "Predation", "Soil pH"], 0, ["True: caused by living organisms.", "True: caused by living organisms.", "False: soil pH is abiotic (non-living)."], "Living vs non-living.", "Biotic factors come from organisms; abiotic factors are physical or chemical."],
["T", "d", 6, "Two Paramecium species were grown alone and together. Which conclusion is best supported?", ["A out-competes B", "Species B cannot grow at all, even on its own", "Species A eats species B when they are together", "A reached 125 when grown alone, which is the main result"], ["B grows well alone (up to 90).", "There's no evidence of predation; competition explains it.", "A reading, not a conclusion."], "Compare each species alone vs together.", "Both grow alone; together, only A survives: competitive exclusion.", [["Day", "0", "4", "8", "12", "16"], ["A alone", "10", "60", "120", "125", "125"], ["B alone", "10", "40", "80", "90", "90"], ["A grown with B", "10", "50", "100", "115", "120"], ["B grown with A", "10", "25", "15", "5", "0"]]],
["L", "c", 5, "Put the steps in order: the effects of spraying a field with insecticide.", ["Most of the insects in the field are killed", "Insect-eating birds have less food", "The bird population falls, and birds of prey that eat them may decline too"], "Birds of prey increase because they have less competition", "Follow the food web upwards.", "Effects spread along food chains; predators lose food when their prey declines."],
{ f: "G", k: "d", b: 6, q: "Which graph shows predator (pink) and prey (dashed) numbers over many years?", gch: [{ pts: [[0, 3], [2, 5], [4, 8], [6, 5], [8, 3], [10, 5], [12, 8]], ref: [[0, 6], [2, 12], [4, 8], [6, 4], [8, 6], [10, 12], [12, 8]] }, { pts: [[0, 6], [2, 12], [4, 8], [6, 4], [8, 6], [10, 12], [12, 8]], ref: [[0, 3], [2, 5], [4, 8], [6, 5], [8, 3], [10, 5], [12, 8]] }, { pts: [[0, 2], [12, 10]], ref: [[0, 4], [12, 14]] }, { pts: [[0, 5], [12, 5]], ref: [[0, 6], [2, 12], [4, 8], [6, 4], [8, 6], [10, 12], [12, 8]], smooth: false }], gax: ["years", "numbers"], choices: ["Both cycle, with predator peaks coming AFTER prey peaks", "Predator peaks come BEFORE prey peaks", "Both rise steadily forever", "Predators stay the same while prey cycles"], why: ["Predators increase only after there's plenty of prey to eat.", "Food and space run out; populations can't rise forever.", "Predator numbers depend on their food supply."], hint: "Lots of prey means well-fed predators... a bit later.", explain: "More prey means more food, so predators breed and increase (after a delay). More predators eat more prey, so prey falls, then predators fall. The cycle repeats." }
]);
KH("t18s2", [
["A", "c", 5, "Decomposers are essential to the carbon cycle.", "Decomposers respire, releasing CO₂ from dead organic matter.", 0, "Join them with 'because'.", "Without decomposers, carbon would stay locked in dead bodies and waste."],
["T", "d", 6, "Energy at each trophic level (kJ/m² per year). What is the efficiency of transfer from primary to secondary consumers?", ["9%", "10%", "90%", "0.9%"], ["That's the rule of thumb, not a calculation from these data.", "That's the percentage LOST.", "That divides by the producers' energy instead."], "Secondary ÷ primary × 100.", "180 ÷ 2000 × 100 = 9%.", [["Trophic level", "Energy"], ["Producers", "20 000"], ["Primary consumers", "2000"], ["Secondary consumers", "180"], ["Tertiary consumers", "16"]]],
["E", "i", 5, "To compare decomposition in two woods, a student put 10 g of oak leaves in wood A and 10 g of pine needles in wood B. What is the flaw?", ["Two variables changed; use the same leaves", "The leaves should weigh different amounts", "The bags should be left for one hour", "Only wood A should be used"], ["Equal masses are correct.", "Far too short for decomposition.", "Then there's no comparison."], "Two variables changed.", "Change one variable at a time."],
["L", "c", 5, "Put the steps in order: carbon moving through an ecosystem.", ["Plants take in CO₂ by photosynthesis and make carbohydrates", "Animals eat the plants, so carbon passes along the food chain", "Respiration and decay return CO₂ to the air"], "Animals take in CO₂ from the air to build their bodies", "Producers first.", "Animals get carbon only by eating; they release CO₂, not absorb it."]
]);
KH("t18s3", [
["R", "c", 5, "Which improve the reliability of a quadrat survey?", ["Using more quadrats", "Placing quadrats randomly", "Placing quadrats only where the plant looks thickest"], 0, ["True: a larger sample.", "True: avoids bias.", "False: that's biased sampling (the Warden of the Wilds' trick)."], "Avoid bias.", "Random, repeated sampling gives a representative estimate."],
["T", "d", 6, "A transect from a tree out into open ground. Which conclusion is best supported?", ["Moss falls and grass rises with light", "Light kills moss", "Moss cover was 70% at 0 m", "Grass and moss need the same conditions"], ["A correlation: other factors, such as moisture, change too.", "A reading, not a conclusion.", "Their patterns are opposite."], "Describe the link carefully.", "The data show a correlation with light; an experiment would be needed to show cause.", [["Distance from tree (m)", "0", "2", "4", "6", "8"], ["Light (% of full sun)", "10", "30", "60", "85", "95"], ["Moss cover (%)", "70", "45", "20", "5", "0"], ["Grass cover (%)", "0", "15", "50", "80", "90"]]],
["N", "c", 6, "A plan proposes draining part of Hong Kong's Mai Po wetlands for housing. Which consequence is most likely?", ["Loss of habitat reduces biodiversity, especially for migratory birds that feed on the mudflats", "No effect: the birds will easily move elsewhere", "More biodiversity because of the new gardens", "Only the plants would be affected"], ["Suitable stopover sites are rare and already crowded.", "Gardens don't replace wetland habitats.", "Whole food webs depend on the wetland."], "Habitat loss.", "Wetlands support specialised food webs; losing them hits many species at once."],
{ f: "V", k: "d", b: 5, q: "This 50 cm × 50 cm quadrat (0.25 m²) was placed randomly in a field. Count the DAISIES. Estimate the daisy density per m².", scene: { kind: "quadrat", plants: [{ n: 14, icon: "daisy", seed: 5 }, { n: 9, icon: "clover", seed: 9 }] }, choices: ["56 per m²", "14 per m²", "3.5 per m²", "92 per m²"], why: ["That's per 0.25 m²; there are 4 quadrats in 1 m².", "That divides by 4 instead of multiplying.", "That counts the clover too."], hint: "How many 0.25 m² quadrats fit in 1 m²?", explain: "14 daisies in 0.25 m² → 14 × 4 = 56 per m². In a real survey, many random quadrats are used and the mean is taken." }
]);

/* ---------- Health and Diseases ---------- */
KH("t19s1", [
["R", "c", 5, "Dengue fever is spread by mosquitoes. Which measures reduce its spread?", ["Removing stagnant water", "Using insect repellent and mosquito nets", "Taking antibiotics"], 0, ["True: mosquitoes breed in still water.", "True: these prevent bites.", "False: dengue is caused by a virus, and antibiotics don't work on viruses."], "Break the transmission chain.", "Control the vector and prevent bites."],
["T", "d", 5, "Colonies grew on agar plates touched by hands after different washing methods. Which conclusion is best supported?", ["Soap and water, or alcohol gel, remove far more bacteria than water alone", "Water alone removes all bacteria", "Alcohol gel is 100% effective", "With no washing there were 120 colonies"], ["80 colonies remained.", "10 colonies remained.", "A reading, not a conclusion."], "Compare each method with 'no washing'.", "Soap or gel cut the bacteria by over 85%.", [["Method", "Colonies"], ["No washing", "120"], ["Water only", "80"], ["Soap and water", "15"], ["Alcohol gel", "10"]]],
["L", "c", 5, "Put the steps in order: how influenza spreads.", ["An infected person coughs out droplets containing the virus", "Another person breathes in the droplets", "The virus enters cells lining the airway and replicates"], "The virus is spread mainly by mosquito bites", "Source, route, entry.", "Flu spreads by droplets; that's why masks and covering coughs help."],
["E", "i", 5, "To compare antiseptics, a student incubated the plate with disc A at 37 °C and the plate with disc B at 25 °C. What is wrong?", ["The temperatures differ, so it's not a fair test, and 37 °C risks growing human pathogens in school", "The discs should be different sizes", "The plates should be opened to check every hour", "Only one plate should be used for each"], ["Disc size must be the same.", "Opening plates risks contamination.", "Repeats are better than single plates."], "Fairness and safety.", "Incubate all plates together at 25 °C."]
]);
KH("t19s2", [
["A", "c", 5, "A vaccine can prevent a disease.", "Vaccines contain antibiotics that kill the pathogen.", 2, "What's actually in a vaccine?", "Vaccines contain antigens (dead, weakened or parts of pathogens) that trigger memory cells, not antibiotics."],
["T", "d", 6, "Antibody levels after two doses of a vaccine (day 0 and day 28). Why is the response to the 2nd dose larger?", ["Memory cells made after the 1st dose quickly produce many antibody-secreting cells", "The 2nd dose contains more antigen", "Antibodies from the 1st dose multiply", "The peak was 120 on day 35"], ["Nothing in the data shows this; the difference is memory.", "Antibodies don't multiply; cells do.", "A reading, not a reason."], "What's left over after the 1st dose?", "The secondary response is faster and bigger because of memory cells.", [["Day", "0", "7", "14", "21", "28", "35", "42"], ["Antibody level", "0", "5", "20", "10", "8", "120", "100"]]],
["C", "c", 5, "Which is a valid comparison of active and passive immunity?", ["In active immunity your own lymphocytes make antibodies and memory cells (long-lasting), whereas passive immunity gives ready-made antibodies (fast but short-lived)", "Active immunity comes from a vaccine, whereas passive immunity comes from breast milk", "Passive immunity lasts much longer than active immunity, because the antibodies are ready-made", "Both active and passive immunity produce memory cells that protect for life"], ["Examples only, with no comparison.", "Reversed.", "Passive immunity makes no memory cells."], "Who makes the antibodies, and how long do they last?", "Pair source and duration."],
{ f: "G", k: "d", b: 6, q: "A vaccine is given on day 0 and a booster on day 30. Which graph shows the antibody level?", gch: [{ pts: [[0, 0], [10, 8], [20, 4], [30, 3], [35, 60], [45, 45], [60, 30]] }, { pts: [[0, 0], [10, 20], [20, 8], [30, 3], [40, 20], [50, 8], [60, 3]] }, { pts: [[0, 0], [10, 40], [20, 20], [30, 10], [40, 12], [50, 6], [60, 3]] }, { pts: [[0, 0], [30, 0], [35, 50], [60, 20]] }], gax: ["days (doses at 0 and 30)", "antibody level"], choices: ["A small, slow first peak, then a much bigger, faster second peak", "Two peaks of the same size", "A big first peak and a smaller second one", "No response until the booster"], why: ["Memory cells make the second response faster and bigger.", "Memory cells make the second response BIGGER.", "The first dose also triggers a (smaller) primary response."], hint: "What's left after the first dose?", explain: "The first dose produces a slow primary response and memory cells. At the booster, the memory cells respond fast with many more antibodies: the secondary response." }
]);
KH("t19s3", [
["R", "c", 5, "Which lifestyle changes reduce the risk of type 2 diabetes?", ["Regular exercise", "Keeping a healthy body mass", "Drinking more sugary drinks"], 0, ["True: exercise improves insulin sensitivity.", "True: excess body fat raises the risk.", "False: sugary drinks raise the risk."], "What improves insulin response?", "Exercise and a healthy weight help cells respond to insulin."],
["T", "d", 5, "Salt intake, blood pressure and stroke risk. Which statement is best supported?", ["Higher salt intake is linked to higher blood pressure and a higher stroke risk", "Salt causes all strokes", "Cutting salt to 5 g removes stroke risk completely", "At 15 g, blood pressure is 138"], ["Overclaiming: these are links, and strokes have many causes.", "A relative risk of 1.0 is the baseline, not zero.", "A reading, not a conclusion."], "Links, not proof.", "All three rise together. A dose-response suggests salt matters, but other factors play a part.", [["Salt per day (g)", "5", "10", "15"], ["Mean blood pressure (mmHg)", "118", "128", "138"], ["Relative stroke risk", "1.0", "1.4", "2.0"]]],
["L", "c", 5, "Put the steps in order: how can type 2 diabetes damage the eyes and kidneys over many years?", ["Body cells respond poorly to insulin", "Blood glucose stays high for long periods", "High glucose damages small blood vessels in the eyes and kidneys"], "The pancreas suddenly stops making all its insulin", "Resistance, high glucose, damage.", "Type 2 develops slowly from insulin resistance; type 1 is the loss of insulin production."],
["N", "c", 6, "A student says, 'One fried meal won't matter.' Which reply uses biology best?", ["One meal alone has little effect, but regular high-fat meals raise blood cholesterol over years, building plaques that narrow the arteries", "One fried meal will cause a heart attack", "Fried food is fine because the body needs fat", "Only genes cause heart disease"], ["Overclaiming; the risk builds up over time.", "Some fat is needed; it's the excess saturated fat that's the issue.", "Lifestyle matters as well as genes."], "Habits add up.", "This is the Murk Heart's misconception: small choices repeated over years shape health."]
]);
