
/* 🔥 Hard formats, part 4: Reproduction, Coordination, Homeostasis, Ecosystems, Health (format: see q_h0.js). */

/* ---------- Reproduction, Growth and Development ---------- */
KH("t15s1", [
["R", "c", 5, "Which features suggest a flower is insect-pollinated?", ["Brightly coloured petals", "Nectar and a scent", "Large feathery stigmas hanging outside the flower"], 0, ["True: colour attracts insects.", "True: nectar and scent are rewards and signals.", "False: feathery, hanging stigmas catch wind-blown pollen."], "Attract insects vs catch the wind.", "Insect flowers advertise; wind flowers expose their anthers and stigmas."],
["T", "d", 5, "Seeds were kept in different conditions for a week. Which conclusion is best supported?", ["Germination needs water, oxygen and a suitable temperature", "Germination needs only water", "Low temperature stops germination completely", "Seeds in A germinated best"], ["C had water but no oxygen: only 3% germinated.", "D still had 15% germination.", "A reading, not a conclusion."], "Compare each tube with A, changing one factor.", "Removing water or oxygen almost stops germination; cold slows it.", [["Tube", "Water", "Oxygen", "Temperature (°C)", "Germinated (%)"], ["A", "yes", "yes", "25", "92"], ["B", "no", "yes", "25", "0"], ["C", "yes", "no", "25", "3"], ["D", "yes", "yes", "5", "15"]]],
["C", "c", 5, "Which is a valid comparison of pollen from insect-pollinated and wind-pollinated flowers?", ["Insect-pollinated flowers make fewer, larger, sticky or spiky pollen grains, whereas wind-pollinated flowers make huge numbers of small, light, smooth grains", "Wind pollen: light. Insect pollen: sticky.", "Wind-pollinated flowers have big, bright petals", "Insect-pollinated flowers make more pollen"], ["Fragments, not a paired comparison.", "Reversed.", "Reversed."], "Number, size, surface: paired.", "Pollen is adapted to how it travels."],
["L", "c", 5, "Put the steps in order: from pollination to fertilisation.", ["A pollen grain lands on the stigma", "A pollen tube grows down the style to the ovule", "The male nucleus fuses with the egg nucleus in the ovule"], "The whole pollen grain swims down to the ovary", "Land, grow, fuse.", "Only the pollen tube grows down; the male gamete travels inside it."]
]);
KH("t15s2", [
["A", "c", 5, "The contraceptive pill can prevent pregnancy.", "Its hormones stop the release of FSH and LH, so no egg is released (no ovulation).", 0, "Join them with 'because'.", "Without the LH surge there is no ovulation, so there is no egg to fertilise."],
["T", "d", 5, "Hormone levels in one menstrual cycle. On which day is ovulation most likely?", ["Day 14, just after the LH surge", "Day 21", "Day 2", "Day 27"], ["Progesterone peaks then, after ovulation.", "That's during menstruation.", "Hormones are falling before menstruation."], "LH triggers ovulation.", "The LH surge (day 13) triggers ovulation about a day later.", [["Day", "2", "8", "13", "14", "21", "27"], ["Oestrogen", "low", "rising", "peak", "high", "medium", "low"], ["LH", "low", "low", "peak", "high", "low", "low"], ["Progesterone", "low", "low", "low", "low", "peak", "low"]]],
["M", "c", 5, "Exam question: 'Explain how the fetus gets oxygen through the placenta.' [2 marks]. Which answer scores both marks?", ["Fetal blood in the placental villi is separated from the mother's blood by a thin barrier, and oxygen diffuses from her blood into the fetal blood down a concentration gradient", "The mother's blood flows into the baby", "Diffusion", "The baby breathes in the uterus"], ["The two bloods don't mix.", "A keyword only.", "The lungs aren't used until birth."], "Structure + process.", "Mark 1: thin barrier between the bloods. Mark 2: oxygen diffuses down its gradient."],
["N", "c", 6, "A medicine taken in pregnancy is made of small, lipid-soluble molecules. Why is it likely to reach the fetus?", ["Small, lipid-soluble molecules can diffuse across the placenta's thin membranes into the fetal blood", "The placenta actively pumps all drugs to the fetus", "Drugs mix in because the bloods join", "Only large molecules can cross the placenta"], ["The placenta doesn't pump every substance across.", "The bloods never join.", "Reversed: small molecules cross most easily."], "Membranes are made of lipid.", "This is why pregnant women are advised to avoid many drugs, alcohol and nicotine."]
]);
KH("t15s3", [
["R", "c", 5, "Which are suitable measures of a seedling's growth?", ["Dry mass", "Length of the shoot over time", "Fresh (wet) mass straight after watering"], 0, ["True: shows only new material.", "True: easy and doesn't kill the plant (though it ignores width).", "False: water content changes, so fresh mass is unreliable."], "Water comes and goes.", "Dry mass is the best measure; length is a useful non-destructive one."],
["T", "d", 6, "A child's height over time. Between which ages was the growth RATE highest?", ["0–2 years", "12–14 years", "The rate was the same throughout", "At 14 years, when the child was tallest"], ["That's the growth spurt (7 cm/year), but it's still slower than infancy (19 cm/year).", "The rate changes a lot.", "Tallest isn't the same as fastest growing."], "Work out cm per year for each interval.", "0–2 years: (88 − 50) ÷ 2 = 19 cm per year, the highest.", [["Age (years)", "0", "2", "4", "6", "8", "10", "12", "14"], ["Height (cm)", "50", "88", "103", "116", "128", "139", "151", "165"]]],
["E", "i", 5, "To track seedling growth, a student picked one seedling at random each day, dried it and weighed it. What is the main weakness?", ["One seedling a day is too few, as seedlings vary; dry a large sample each day and use the mean", "The seedlings should be weighed wet", "The same seedling should be dried every day", "The seedlings should be dried at 300 °C"], ["Wet mass is unreliable.", "A dried seedling is dead and can't keep growing.", "That burns the organic matter."], "Natural variation.", "A mean from many seedlings gives a reliable growth curve."],
["L", "c", 5, "Put the steps in order: how does a seed get the energy to germinate?", ["The seed absorbs water and swells", "Enzymes are activated and break stored starch into sugars", "Sugars are used in respiration, releasing energy for growth"], "The seed photosynthesises underground to make energy", "Water, enzymes, respiration.", "Seeds use stored food until their first leaves can photosynthesise."]
]);

/* ---------- Coordination and Response ---------- */
KH("t16s1", [
["A", "c", 5, "We can't see colours well in dim light.", "Cones need bright light to be stimulated.", 0, "Join them with 'because'.", "Cones detect colour but need bright light; in dim light mainly rods work, giving black-and-white vision."],
["T", "d", 5, "Pupil diameter at different light intensities. Which explanation of the trend is best?", ["As light increases, the circular iris muscles contract and the radial muscles relax, so the pupil narrows and protects the retina", "The pupil shrinks because the light burns it", "At 10 000 lux the pupil is 2 mm", "Radial muscles contract in bright light"], ["The pupil is a hole, and this is a reflex, not damage.", "A reading, not an explanation.", "Reversed: radial muscles contract in DIM light."], "Which muscles narrow the pupil?", "The pupil reflex adjusts how much light enters the eye.", [["Light (lux)", "1", "10", "100", "1000", "10 000"], ["Pupil diameter (mm)", "7.5", "6.5", "4.5", "3", "2"]]],
["M", "c", 5, "Exam question: 'Explain why a person with a cataract (cloudy lens) sees blurred images.' [2 marks]. Which answer scores both marks?", ["The cloudy lens scatters and blocks light, so a sharp image is not focused on the retina", "The retina stops working", "Cataract", "The lens can't change shape"], ["The retina is fine; the problem is the lens.", "A keyword only.", "That describes losing accommodation with age, not cloudiness."], "What happens to the light?", "Mark 1: light is scattered by the cloudy lens. Mark 2: no sharp image forms on the retina."],
["L", "c", 5, "Put the steps in order: focusing on a NEAR object.", ["The ciliary muscles contract", "The suspensory ligaments slacken", "The lens becomes thicker and bends light more"], "The suspensory ligaments pull tight and squeeze the lens fat", "Muscle, ligament, lens.", "Tight ligaments pull the lens THIN (for distant objects); slack ligaments let it round up."]
]);
KH("t16s2", [
["R", "c", 5, "Which are features of a reflex action?", ["It is rapid.", "It is automatic, without conscious thought.", "It always involves the cerebrum."], 0, ["True: few neurones, short pathway.", "True: you don't decide to do it.", "False: many reflexes pass through the spinal cord only."], "Where does a reflex arc go?", "Reflexes are fast, automatic and protective."],
["T", "d", 5, "Ruler-drop reaction times. Which conclusion is best supported?", ["Tiredness and distraction lengthen reaction time, which matters for safety, such as crossing roads", "Video gaming makes reactions much faster", "Texting gave a catch distance of 25 cm", "Sleep has no effect on reaction time"], ["0.15 vs 0.16 s is a tiny difference, likely within error.", "A reading, not a conclusion.", "A sleepless night slowed reactions by 0.04 s."], "Compare each condition with 'rested'.", "Only the big differences (sleepless, texting) are likely to be real effects.", [["Condition", "Mean catch distance (cm)", "Reaction time (s)"], ["Rested", "12", "0.16"], ["After 1 h of video games", "11", "0.15"], ["After a sleepless night", "20", "0.20"], ["While texting", "25", "0.23"]]],
["C", "c", 5, "Which is a valid comparison of nervous and hormonal coordination?", ["Nervous responses are fast, short-lived and precise (impulses along neurones), whereas hormonal responses are slower, longer-lasting and widespread (chemicals in the blood)", "Nerves: electrical. Hormones: chemicals.", "Hormones are faster than nerve impulses", "Both travel in the blood"], ["Fragments, and only one feature.", "Reversed.", "Nerve impulses travel along neurones."], "Speed, duration, route.", "Pair several features with linking words."],
["L", "c", 5, "Put the steps in order: the reflex arc when you touch a hot object.", ["A receptor in the skin detects the heat", "An impulse travels along a sensory neurone to a relay neurone in the spinal cord", "A motor neurone carries the impulse to a muscle, which contracts"], "The brain decides to move the hand before the spinal cord acts", "Receptor, sensory, relay, motor, effector.", "The hand moves before the brain is even aware of the pain."]
]);
KH("t16s3", [
["A", "c", 5, "Adrenaline increases heart rate in danger.", "Adrenaline is carried in the blood to its target organs.", 1, "Is being carried in blood the REASON heart rate rises?", "Both are true, but transport in blood only explains how it arrives, not why the heart speeds up."],
["T", "d", 6, "Oat shoots were lit from one side. What does the 'mica on the shaded side' result show?", ["A chemical must move down the shaded side from the tip to cause bending", "Light is detected by the base of the shoot", "Mica produces auxin", "The intact shoot bent towards the light"], ["Removing the tip stops bending, so the tip is needed.", "Mica is an inert barrier.", "A reading, not a conclusion."], "What does mica block?", "Blocking the shaded side stops bending; blocking the lit side doesn't. So auxin moving down the SHADED side causes the bending.", [["Treatment", "Result"], ["Intact shoot", "bends towards light"], ["Tip removed", "no bending"], ["Mica barrier, shaded side", "no bending"], ["Mica barrier, lit side", "bends towards light"]]],
["E", "i", 5, "A student lit 2 seedlings per treatment from a sunny window whose light changed during the day. What is the best improvement?", ["Use a fixed lamp in a dark box and many seedlings per treatment", "Water only the lit side", "Remove all the tips", "Measure after 1 minute"], ["That adds another variable.", "That stops every response.", "Too soon to see any bending."], "Control light and increase the sample.", "A fixed light source controls direction and intensity; more seedlings improve reliability."],
["N", "c", 6, "Gardeners spray lawns with a synthetic auxin weedkiller. Broad-leaved weeds die, but the grass survives. Why?", ["Broad-leaved weeds are more sensitive to the auxin, which makes them grow abnormally fast and die, while grass is little affected", "Auxin kills all plants equally", "Grass absorbs no chemicals", "Auxin only blocks photosynthesis in weeds"], ["Then the grass would die too.", "Grass absorbs it, but responds less.", "The mechanism is abnormal growth."], "Different plants, different sensitivity.", "Selective weedkillers use the different responses of plant groups to plant hormones."]
]);
KH("t16s4", [
["R", "c", 5, "Which must happen for the arm to bend at the elbow?", ["The biceps contracts.", "The triceps relaxes.", "The biceps pushes the forearm upwards."], 0, ["True: it pulls the radius.", "True: its antagonist must relax.", "False: muscles can only PULL."], "Remember the Signal Towers' Warden.", "Antagonistic pairs: one contracts and pulls while the other relaxes."],
["M", "c", 5, "Exam question: 'Explain how the arm bends at the elbow.' [2 marks]. Which answer scores both marks?", ["The biceps contracts and pulls on the radius through a tendon, while the antagonistic triceps relaxes, so the forearm rotates at the elbow joint", "Muscles push the bones", "The biceps relaxes, so the arm bends", "The biceps contracts"], ["Muscles can only pull.", "Reversed.", "1 mark: missing the antagonist and the movement at the joint."], "Contract + pull + antagonist.", "Mark 1: the biceps contracts and pulls the bone. Mark 2: the triceps relaxes, and the forearm moves at the joint."],
["C", "c", 5, "Which is a valid comparison of ligaments and tendons?", ["Ligaments join bone to bone and are slightly elastic, whereas tendons join muscle to bone and are inelastic, so the muscle's pull is passed on fully", "Tendons join bone to bone, whereas ligaments join muscle to bone", "Ligaments: joints. Tendons: muscles.", "Both are very elastic"], ["Reversed.", "Fragments.", "Tendons must be inelastic."], "What does each join, and how stretchy is it?", "Structure (elasticity) matches each one's job."],
["L", "c", 5, "Put the steps in order: from nerve impulse to movement.", ["A nerve impulse reaches the muscle", "Muscle fibres use ATP to contract and shorten", "The tendon pulls the bone, moving it at the joint"], "The bone moves first and stretches the muscle", "Signal, contraction, movement.", "The muscle causes the movement, not the other way round."]
]);

/* ---------- Homeostasis ---------- */
KH("t17s1", [
["R", "c", 5, "Which happen after drinking a sugary drink?", ["The pancreas releases more insulin.", "The liver converts glucose into glycogen.", "More glucagon is released."], 0, ["True: insulin rises when glucose rises.", "True: insulin makes the liver store glucose.", "False: glucagon is released when glucose FALLS."], "Which hormone lowers glucose?", "Insulin lowers blood glucose; glucagon raises it."],
["T", "d", 5, "Glucose tolerance test (blood glucose, mmol/L) after a glucose drink. Which interpretation is best?", ["Person B probably has diabetes: their glucose starts high, rises more and stays high, showing a poor insulin response", "Person A has diabetes because their glucose rose to 8", "Both people are normal", "Person B peaked at 15 at 60 minutes"], ["A normal rise after a glucose drink: it returned to 5 within 2 hours.", "B stays far above normal.", "A reading, not an interpretation."], "Who returns to normal?", "A healthy response returns to baseline within about 2 hours.", [["Time (min)", "0", "30", "60", "90", "120"], ["Person A", "5.0", "8.0", "6.5", "5.5", "5.0"], ["Person B", "7.5", "13", "15", "14", "12"]]],
["M", "c", 6, "Exam question: 'Explain how negative feedback returns blood glucose to normal after a meal.' [3 marks]. Which answer scores all 3 marks?", ["The rise in blood glucose is detected by the pancreas, which releases more insulin, so liver and muscle cells take up glucose and store it as glycogen, lowering the level", "Insulin lowers glucose", "Glucagon is released to store the glucose", "The kidneys remove the extra glucose in urine"], ["1 mark: missing the detection and the mechanism.", "Reversed: glucagon raises glucose.", "That only happens in uncontrolled diabetes, not normal control."], "Detect, respond, effect.", "Mark 1: detected by the pancreas. Mark 2: more insulin. Mark 3: glucose stored as glycogen."],
["L", "c", 5, "Put the steps in order: what happens when blood glucose falls?", ["Blood glucose falls below normal", "The pancreas releases glucagon", "The liver breaks glycogen down into glucose, raising blood glucose"], "Insulin is released to raise blood glucose", "Fall, signal, response.", "Glucagon raises glucose; insulin lowers it."]
]);
KH("t17s2", [
["A", "c", 5, "Breathing rate rises during exercise.", "Exercise lowers the CO₂ concentration in the blood.", 2, "What do working muscles release?", "Exercise RAISES blood CO₂, and that rise is detected and drives faster breathing."],
["T", "d", 6, "Breathing rate of a resting person breathing different air mixtures. Which conclusion is best supported?", ["Breathing rate is much more sensitive to a rise in CO₂ than to a fall in O₂", "Low oxygen is the main stimulus for breathing", "CO₂ has no effect", "Breathing 5% CO₂ gave 30 breaths per minute"], ["Halving the oxygen raised the rate only to 18.", "5% CO₂ more than doubled it.", "A reading, not a conclusion."], "Compare the size of each effect.", "A small rise in CO₂ has a big effect; a big fall in O₂ has a small one.", [["Air breathed", "Breaths per minute"], ["Normal air", "12"], ["5% CO₂, normal O₂", "30"], ["15% O₂, normal CO₂", "14"], ["10% O₂, normal CO₂", "18"]]],
["E", "i", 5, "A student counted a friend's breaths for 10 seconds after exercise, while the friend knew they were being counted. What is the best improvement?", ["Count for a full minute without the person knowing, because breathing can be consciously changed and 10 s is too short", "Only measure before exercise", "Count heartbeats instead", "Exercise for longer"], ["You need after-exercise values.", "That's a different variable.", "That doesn't fix the measurement problem."], "Breathing can be controlled on purpose.", "Unnoticed, longer counts give a more valid and accurate rate."],
["N", "c", 6, "Some divers breathe very fast and deep (hyperventilate) before a breath-hold dive. Why is this dangerous?", ["It lowers blood CO₂, so the urge to breathe is delayed even as O₂ falls dangerously low, risking blackout", "It fills the lungs with extra oxygen for safety", "It raises blood CO₂", "It makes the lungs burst"], ["Blood oxygen barely rises; the danger is the low CO₂.", "Reversed.", "Not what happens."], "What triggers the urge to breathe?", "Without the CO₂ warning signal, oxygen can run out before the diver feels the need to surface."]
]);

/* ---------- Ecosystems ---------- */
KH("t18s1", [
["R", "c", 5, "Which are biotic factors?", ["Competition from another species", "Predation", "Soil pH"], 0, ["True: caused by living organisms.", "True: caused by living organisms.", "False: soil pH is abiotic (non-living)."], "Living vs non-living.", "Biotic factors come from organisms; abiotic factors are physical or chemical."],
["T", "d", 6, "Two Paramecium species were grown alone and together. Which conclusion is best supported?", ["When grown together, A out-competes B for the same resources, so B dies out", "Species B cannot grow at all", "Species A eats species B", "A reached 125 when grown alone"], ["B grows well alone (up to 90).", "There's no evidence of predation; competition explains it.", "A reading, not a conclusion."], "Compare each species alone vs together.", "Both grow alone; together, only A survives: competitive exclusion.", [["Day", "0", "4", "8", "12", "16"], ["A alone", "10", "60", "120", "125", "125"], ["B alone", "10", "40", "80", "90", "90"], ["A grown with B", "10", "50", "100", "115", "120"], ["B grown with A", "10", "25", "15", "5", "0"]]],
["L", "c", 5, "Put the steps in order: the effects of spraying a field with insecticide.", ["Most of the insects in the field are killed", "Insect-eating birds have less food", "The bird population falls, and birds of prey that eat them may decline too"], "Birds of prey increase because they have less competition", "Follow the food web upwards.", "Effects spread along food chains; predators lose food when their prey declines."],
["M", "c", 5, "Exam question: 'Explain why there are fewer organisms at higher trophic levels.' [2 marks]. Which answer scores both marks?", ["Energy is lost at each level, for example as heat from respiration and in undigested waste, so less energy is available to support organisms higher up", "Predators are bigger", "Energy is lost", "Top predators are hunted by humans"], ["Size isn't the reason; energy is.", "1 mark: missing how it's lost and the consequence.", "Not the general biological reason."], "Loss, then consequence.", "Mark 1: energy is lost (respiration/heat, waste). Mark 2: less energy is left for higher levels."]
]);
KH("t18s2", [
["A", "c", 5, "Decomposers are essential to the carbon cycle.", "Decomposers respire, releasing CO₂ from dead organic matter.", 0, "Join them with 'because'.", "Without decomposers, carbon would stay locked in dead bodies and waste."],
["T", "d", 6, "Energy at each trophic level (kJ/m² per year). What is the efficiency of transfer from primary to secondary consumers?", ["9%", "10%", "90%", "0.9%"], ["That's the rule of thumb, not a calculation from these data.", "That's the percentage LOST.", "That divides by the producers' energy instead."], "Secondary ÷ primary × 100.", "180 ÷ 2000 × 100 = 9%.", [["Trophic level", "Energy"], ["Producers", "20 000"], ["Primary consumers", "2000"], ["Secondary consumers", "180"], ["Tertiary consumers", "16"]]],
["E", "i", 5, "To compare decomposition in two woods, a student put 10 g of oak leaves in wood A and 10 g of pine needles in wood B. What is the flaw?", ["Leaf type and wood both differ, so the cause of any difference can't be identified; use the same leaf type in both woods", "The leaves should weigh different amounts", "The bags should be left for one hour", "Only wood A should be used"], ["Equal masses are correct.", "Far too short for decomposition.", "Then there's no comparison."], "Two variables changed.", "Change one variable at a time."],
["L", "c", 5, "Put the steps in order: carbon moving through an ecosystem.", ["Plants take in CO₂ by photosynthesis and make carbohydrates", "Animals eat the plants, so carbon passes along the food chain", "Respiration and decay return CO₂ to the air"], "Animals take in CO₂ from the air to build their bodies", "Producers first.", "Animals get carbon only by eating; they release CO₂, not absorb it."]
]);
KH("t18s3", [
["R", "c", 5, "Which improve the reliability of a quadrat survey?", ["Using more quadrats", "Placing quadrats randomly", "Placing quadrats only where the plant looks thickest"], 0, ["True: a larger sample.", "True: avoids bias.", "False: that's biased sampling (the Warden of the Wilds' trick)."], "Avoid bias.", "Random, repeated sampling gives a representative estimate."],
["T", "d", 6, "A transect from a tree out into open ground. Which conclusion is best supported?", ["Moss cover falls and grass cover rises as light increases, suggesting light affects their distribution", "Light kills moss", "Moss cover was 70% at 0 m", "Grass and moss need the same conditions"], ["A correlation: other factors, such as moisture, change too.", "A reading, not a conclusion.", "Their patterns are opposite."], "Describe the link carefully.", "The data show a correlation with light; an experiment would be needed to show cause.", [["Distance from tree (m)", "0", "2", "4", "6", "8"], ["Light (% of full sun)", "10", "30", "60", "85", "95"], ["Moss cover (%)", "70", "45", "20", "5", "0"], ["Grass cover (%)", "0", "15", "50", "80", "90"]]],
["N", "c", 6, "A plan proposes draining part of Hong Kong's Mai Po wetlands for housing. Which consequence is most likely?", ["Loss of habitat reduces biodiversity, especially for migratory birds that feed on the mudflats", "No effect: the birds will easily move elsewhere", "More biodiversity because of the new gardens", "Only the plants would be affected"], ["Suitable stopover sites are rare and already crowded.", "Gardens don't replace wetland habitats.", "Whole food webs depend on the wetland."], "Habitat loss.", "Wetlands support specialised food webs; losing them hits many species at once."],
["M", "c", 5, "Exam question: 'Explain why mark–release–recapture is used for animals but quadrats for plants.' [2 marks]. Which answer scores both marks?", ["Animals move, so they can't be counted reliably in a fixed area and MRR estimates the whole population, whereas plants stay put and can be counted reliably in quadrats", "Animals are too small", "Quadrats are expensive", "Animals move"], ["Size isn't the reason.", "Not a biological reason.", "1 mark: missing the link to the methods."], "Mobility decides the method.", "Mark 1: animals move, so MRR. Mark 2: plants are fixed, so quadrats work."]
]);

/* ---------- Health and Diseases ---------- */
KH("t19s1", [
["R", "c", 5, "Dengue fever is spread by mosquitoes. Which measures reduce its spread?", ["Removing stagnant water", "Using insect repellent and mosquito nets", "Taking antibiotics"], 0, ["True: mosquitoes breed in still water.", "True: these prevent bites.", "False: dengue is caused by a virus, and antibiotics don't work on viruses."], "Break the transmission chain.", "Control the vector and prevent bites."],
["T", "d", 5, "Colonies grew on agar plates touched by hands after different washing methods. Which conclusion is best supported?", ["Soap and water, or alcohol gel, remove far more bacteria than water alone", "Water alone removes all bacteria", "Alcohol gel is 100% effective", "With no washing there were 120 colonies"], ["80 colonies remained.", "10 colonies remained.", "A reading, not a conclusion."], "Compare each method with 'no washing'.", "Soap or gel cut the bacteria by over 85%.", [["Method", "Colonies"], ["No washing", "120"], ["Water only", "80"], ["Soap and water", "15"], ["Alcohol gel", "10"]]],
["L", "c", 5, "Put the steps in order: how influenza spreads.", ["An infected person coughs out droplets containing the virus", "Another person breathes in the droplets", "The virus enters cells lining the airway and replicates"], "The virus is spread mainly by mosquito bites", "Source, route, entry.", "Flu spreads by droplets; that's why masks and covering coughs help."],
["E", "i", 5, "To compare antiseptics, a student incubated the plate with disc A at 37 °C and the plate with disc B at 25 °C. What is wrong?", ["The temperatures differ, so it's not a fair test, and 37 °C risks growing human pathogens in school", "The discs should be different sizes", "The plates should be opened to check every hour", "Only one plate should be used for each"], ["Disc size must be the same.", "Opening plates risks contamination.", "Repeats are better than single plates."], "Fairness and safety.", "Incubate all plates together at 25 °C."]
]);
KH("t19s2", [
["A", "c", 5, "A vaccine can prevent a disease.", "Vaccines contain antibiotics that kill the pathogen.", 2, "What's actually in a vaccine?", "Vaccines contain antigens (dead, weakened or parts of pathogens) that trigger memory cells, not antibiotics."],
["T", "d", 6, "Antibody levels after two doses of a vaccine (day 0 and day 28). Why is the response to the 2nd dose larger?", ["Memory cells made after the 1st dose quickly produce many antibody-secreting cells", "The 2nd dose contains more antigen", "Antibodies from the 1st dose multiply", "The peak was 120 on day 35"], ["Nothing in the data shows this; the difference is memory.", "Antibodies don't multiply; cells do.", "A reading, not a reason."], "What's left over after the 1st dose?", "The secondary response is faster and bigger because of memory cells.", [["Day", "0", "7", "14", "21", "28", "35", "42"], ["Antibody level", "0", "5", "20", "10", "8", "120", "100"]]],
["C", "c", 5, "Which is a valid comparison of active and passive immunity?", ["In active immunity your own lymphocytes make antibodies and memory cells (long-lasting), whereas passive immunity gives ready-made antibodies (fast but short-lived)", "Active: vaccine. Passive: breast milk.", "Passive immunity lasts longer", "Both produce memory cells"], ["Examples only, with no comparison.", "Reversed.", "Passive immunity makes no memory cells."], "Who makes the antibodies, and how long do they last?", "Pair source and duration."],
["M", "c", 5, "Exam question: 'Explain why a person usually doesn't get chickenpox twice.' [2 marks]. Which answer scores both marks?", ["After the first infection, memory cells remain, so on re-exposure they make antibodies quickly enough to destroy the virus before symptoms appear", "The antibodies stay in the blood forever", "Memory cells", "The virus can't infect them again"], ["Antibody levels fall; memory cells last.", "A keyword only.", "The virus can enter, but it's destroyed fast."], "Memory, then a fast response.", "Mark 1: memory cells remain. Mark 2: a fast, large secondary response destroys the virus."]
]);
KH("t19s3", [
["R", "c", 5, "Which lifestyle changes reduce the risk of type 2 diabetes?", ["Regular exercise", "Keeping a healthy body mass", "Drinking more sugary drinks"], 0, ["True: exercise improves insulin sensitivity.", "True: excess body fat raises the risk.", "False: sugary drinks raise the risk."], "What improves insulin response?", "Exercise and a healthy weight help cells respond to insulin."],
["T", "d", 5, "Salt intake, blood pressure and stroke risk. Which statement is best supported?", ["Higher salt intake is linked to higher blood pressure and a higher stroke risk", "Salt causes all strokes", "Cutting salt to 5 g removes stroke risk completely", "At 15 g, blood pressure is 138"], ["Overclaiming: these are links, and strokes have many causes.", "A relative risk of 1.0 is the baseline, not zero.", "A reading, not a conclusion."], "Links, not proof.", "All three rise together. A dose-response suggests salt matters, but other factors play a part.", [["Salt per day (g)", "5", "10", "15"], ["Mean blood pressure (mmHg)", "118", "128", "138"], ["Relative stroke risk", "1.0", "1.4", "2.0"]]],
["L", "c", 5, "Put the steps in order: how can type 2 diabetes damage the eyes and kidneys over many years?", ["Body cells respond poorly to insulin", "Blood glucose stays high for long periods", "High glucose damages small blood vessels in the eyes and kidneys"], "The pancreas suddenly stops making all its insulin", "Resistance, high glucose, damage.", "Type 2 develops slowly from insulin resistance; type 1 is the loss of insulin production."],
["N", "c", 6, "A student says, 'One fried meal won't matter.' Which reply uses biology best?", ["One meal alone has little effect, but regular high-fat meals raise blood cholesterol over years, building plaques that narrow the arteries", "One fried meal will cause a heart attack", "Fried food is fine because the body needs fat", "Only genes cause heart disease"], ["Overclaiming; the risk builds up over time.", "Some fat is needed; it's the excess saturated fat that's the issue.", "Lifestyle matters as well as genes."], "Habits add up.", "This is the Murk Heart's misconception: small choices repeated over years shape health."]
]);
