
/* ============================================================
   5a-kb. Extra questions written from the core knowledge base (marker wording, common mistakes as distractors).
   Appended to the end of each stage's bank so saved progress stays valid.
   ============================================================ */
const KB = (id, list) => { QB[id] = (QB[id] || []).concat(list); };
KB("t1s1", [
[2, "Which statement about the jobs of water in the body is correct?", ["Water is a solvent and a medium for chemical reactions", "Water gives the body energy", "Water is a store of food", "Water digests food"], "Where do cell reactions take place?", "Water dissolves many substances, so it is a medium for reactions and for transport. It gives no energy."],
[3, "A student feels tired and looks pale. Which mineral is most likely lacking?", ["Iron", "Calcium", "Magnesium", "Sodium"], "Which mineral makes haemoglobin?", "Iron is needed to make haemoglobin. Lack of iron ➔ anaemia ➔ tired and pale. Lack of calcium causes rickets, not anaemia."],
[4, "Why do our bodies need calcium AND vitamin D?", ["Both are needed for strong bones and teeth; lack of either can cause rickets", "Both are needed to make haemoglobin", "Both give the body energy", "Both help digest fats"], "Think of the disease with soft, deformed bones.", "Calcium builds bones and teeth; vitamin D helps the body absorb calcium. Lack of either ➔ rickets."],
[5, "A student writes: 'Minerals and vitamins give us energy when we are tired.' Which is the best judgement?", ["Wrong: vitamins and minerals give no energy; carbohydrates and lipids do", "Correct: all food substances give energy", "Correct for vitamins only", "Correct for minerals only"], "Which food substances are respired?", "Vitamins, minerals, water and dietary fibre give no energy. Carbohydrate (about 4 kcal/g), protein (about 4 kcal/g) and lipid (about 9 kcal/g) do.", "Energy values: lipid ≈ 9 kcal/g; carbohydrate and protein ≈ 4 kcal/g."]
]);
KB("t1s2", [
[1, "Which sugar gives a NEGATIVE Benedict's test?", ["Sucrose", "Glucose", "Maltose", "Fructose"], "One common disaccharide is non-reducing.", "Sucrose is a non-reducing sugar, so Benedict's solution stays blue even after heating."],
[2, "How do you test a food for reducing sugar?", ["Add Benedict's solution, then heat in a boiling water bath: a brick-red precipitate forms", "Add Benedict's solution: a red colour appears straight away without heating", "Add iodine solution: it turns blue-black", "Rub it on filter paper: a translucent spot appears"], "Don't forget one important step.", "Benedict's test needs heating in a boiling water bath. A positive result is a brick-red precipitate."],
[2, "Gram for gram, which food substance gives the MOST energy?", ["Lipid (fat), about 9 kcal per gram", "Carbohydrate, about 4 kcal per gram", "Protein, about 4 kcal per gram", "Dietary fibre"], "Fat is more than twice the others.", "Lipid gives about 9 kcal/g, over twice as much as carbohydrate or protein (about 4 kcal/g). Fibre gives none."],
[3, "How do you test for lipid?", ["Rub the food on filter paper and let it dry: a permanent translucent spot is left", "Add iodine: it turns blue-black", "Add Benedict's solution and heat: brick-red", "Add DCPIP: it turns colourless"], "The grease spot test.", "A lipid leaves a permanent translucent spot on filter paper, even after drying. Water leaves a spot that disappears."],
[4, "Why is dietary fibre important even though it gives no energy?", ["It adds bulk and stimulates peristalsis, which prevents constipation", "It is digested into glucose", "It is a store of energy", "It makes haemoglobin"], "Fibre is mostly cellulose.", "Fibre (cellulose) cannot be digested, so it gives no energy. It adds bulk and stimulates peristalsis ➔ prevents constipation."]
]);
KB("t1s3", [
[2, "What is the positive result of the biuret test for protein?", ["Purple / violet", "Blue-black", "Brick-red precipitate", "Colourless"], "Biuret: think purple.", "Protein gives a purple (violet) colour with the biuret test."],
[3, "How should you carry out the DCPIP test for vitamin C?", ["Add the fruit juice drop by drop into blue DCPIP until it is decolorized", "Add DCPIP drop by drop into the fruit juice until the colour changes", "Heat the juice with DCPIP in a water bath", "Add iodine solution to the juice"], "Which liquid goes into which?", "Juice goes drop by drop INTO the DCPIP. The fewer drops needed to decolorize it, the more vitamin C the juice has."],
[4, "Juice A decolorizes 1 cm³ of DCPIP in 5 drops; juice B needs 15 drops. What can you conclude?", ["Juice A has more vitamin C than juice B", "Juice B has more vitamin C than juice A", "Both have the same amount of vitamin C", "Neither contains vitamin C"], "Fewer drops = more vitamin C.", "Juice A needs fewer drops to decolorize the same volume of DCPIP, so it has a higher vitamin C content."],
[5, "Why should you NOT shake the DCPIP tube hard during the vitamin C test?", ["Vitamin C is oxidised by oxygen in the air, so the result would be too low", "Shaking denatures the DCPIP", "Shaking makes the solution turn blue-black", "Shaking releases vitamin C from the juice"], "What does air do to vitamin C?", "Vitamin C is easily oxidised by oxygen in the air, so shaking would destroy some of it and give a false (lower) result."]
]);
KB("t2s1", [
[2, "What is the formula for magnification?", ["Magnification = image size ÷ actual size", "Magnification = actual size ÷ image size", "Magnification = image size × actual size", "Magnification = eyepiece + objective"], "Bigger image means bigger magnification.", "Magnification = image size ÷ actual size. For a light microscope, total magnification = eyepiece × objective."],
[3, "A cell is 20 µm long. Its image is 10 mm long. What is the magnification?", ["×500", "×200", "×50", "×2000"], "Convert: 10 mm = 10 000 µm.", "10 mm = 10 000 µm. Magnification = 10 000 ÷ 20 = ×500."],
[3, "Why can an electron microscope show ribosomes but a light microscope cannot?", ["The electron microscope has a much higher resolution", "The electron microscope uses coloured light", "Ribosomes are only in dead cells", "The light microscope has a higher resolution"], "Resolution is about seeing two close points separately.", "The electron microscope has a much higher resolution, so small organelles like ribosomes can be seen."],
[2, "When focusing a light microscope, what should you do first?", ["Use the low-power objective and watch from the side while raising the stage", "Use the high-power objective and the coarse knob", "Look down the eyepiece and turn the coarse knob quickly towards the slide", "Remove the eyepiece"], "Safety first: don't crack the slide.", "Start with low power and watch from the side while raising the stage, then focus with the coarse knob, then the fine knob."]
]);
KB("t2s2", [
[1, "Which organelle is the site of protein synthesis?", ["Ribosome", "Golgi apparatus", "Smooth endoplasmic reticulum", "Vacuole"], "Tiny dots on rough ER.", "Ribosomes are the site of protein synthesis."],
[2, "Which statement about the cell wall is correct?", ["It is fully permeable and gives support", "It controls what enters and leaves the cell", "It is found in animal cells", "It is made of protein"], "Which layer is differentially permeable?", "The cellulose cell wall is fully permeable; it gives support and stops the cell bursting. The cell membrane controls what enters and leaves."],
[3, "Pancreas cells secrete lots of enzymes. Which organelles would they have a lot of?", ["Rough endoplasmic reticulum and Golgi apparatus", "Chloroplasts and a large vacuole", "Smooth ER and cell wall", "Centrioles and lysosomes only"], "Enzymes are proteins made for secretion.", "Proteins for secretion are made on rough ER and packaged into vesicles by the Golgi apparatus."],
[3, "Why do muscle cells and sperm cells have many mitochondria?", ["Many mitochondria ➔ more aerobic respiration ➔ more energy released for activity", "Mitochondria produce energy from nothing", "Mitochondria store food", "Mitochondria make proteins"], "Energy is released, not produced.", "Mitochondria are the site of aerobic respiration, which releases energy (ATP). Active cells need lots of it.", "Write 'release energy', never 'produce energy'."],
[4, "Which statement is correct?", ["Root cells have no chloroplasts", "All plant cells have chloroplasts", "Animal cells have a small cell wall", "Bacteria have a nucleus"], "Think about cells underground.", "Root cells do not photosynthesise, so they have no chloroplasts. Animal cells have no cell wall. Bacteria have no nucleus."]
]);
KB("t2s3", [
[2, "In the fluid mosaic model, what does 'mosaic' mean?", ["Proteins are scattered in the phospholipid bilayer like tiles in a mosaic", "The membrane is made of many coloured layers", "The membrane is rigid like a tiled floor", "Water flows through it freely"], "Picture tiles in a floor.", "Proteins are interspersed in the bilayer like mosaic tiles. 'Fluid' means the molecules can move sideways."],
[3, "Why can O₂ cross the membrane directly, but ions cannot?", ["O₂ is small and non-polar; ions are charged so they need channel or carrier proteins", "Ions are too small to be noticed", "O₂ is pumped by active transport", "Ions dissolve in the phospholipid tails"], "Oily middle vs charge.", "The hydrophobic tails block charged particles. Small non-polar molecules like O₂ and CO₂ pass straight through."],
[4, "Which statement about prokaryotic cells is correct?", ["They have no nuclear membrane and no membrane-bound organelles", "They have mitochondria but no ribosomes", "Their DNA is inside a nucleus", "They are larger than eukaryotic cells"], "Pro = before (the nucleus).", "Prokaryotes (e.g. bacteria) have DNA free in the cytoplasm and no membrane-bound organelles, but they do have ribosomes."],
[5, "Why is the fluid mosaic model called a 'model'?", ["It explains a structure too small to observe directly, and it can be refined with new evidence", "It is a plastic toy used in lessons", "It has been proved to be 100% correct", "It was guessed without evidence"], "Nature of science.", "Models explain things that cannot be observed directly, and they are refined when new evidence appears."]
]);
KB("t3s1", [
[2, "Which process moves glucose into a red blood cell?", ["Facilitated diffusion through a carrier protein", "Simple diffusion through the phospholipid bilayer", "Active transport using ATP", "Osmosis"], "Down the gradient, but needs a protein.", "Glucose moves down its concentration gradient through carrier proteins: facilitated diffusion. No ATP is needed."],
[3, "Which statement about facilitated diffusion is correct?", ["It uses carrier or channel proteins but needs no ATP", "It needs energy because it uses proteins", "It moves substances against a concentration gradient", "It only moves water"], "Proteins ≠ energy.", "Facilitated diffusion is passive: substances still move down the gradient, so no ATP is needed."],
[4, "Which change would make diffusion into a cell FASTER?", ["A steeper concentration gradient", "A thicker membrane", "A smaller surface area", "A lower temperature"], "What makes molecules spread faster?", "A steeper gradient, larger surface area, shorter distance and higher temperature all increase the rate of diffusion."]
]);
KB("t3s2", [
[2, "What is osmosis?", ["The net movement of water across a differentially permeable membrane from higher to lower water potential", "The movement of water from high water concentration to low water concentration", "The movement of any substance down a gradient", "The movement of water using ATP"], "Two key words: net, water potential.", "Osmosis is the net movement of water across a differentially permeable membrane, from a region of higher to lower water potential.", "Never write 'water concentration': the marker only accepts water potential."],
[2, "A plant cell is put in distilled water. What happens?", ["Water enters by osmosis and the cell becomes turgid; the cell wall stops it bursting", "Water enters and the cell bursts", "Water leaves and the cell is plasmolysed", "Nothing happens"], "The cell wall resists.", "The vacuole gains water and pushes on the cell wall, which resists: the cell becomes turgid, not burst."],
[3, "A red blood cell is put in distilled water. What happens?", ["Water enters by osmosis; with no cell wall it swells and bursts (haemolysis)", "It becomes turgid", "It shrinks and becomes crenated", "It becomes plasmolysed"], "Animal cells have no cell wall.", "Distilled water has a higher water potential than the cell, so water enters. No cell wall ➔ the cell bursts: haemolysis."],
[4, "In an isotonic solution, what happens to water?", ["Water moves in both directions, but there is no NET movement", "No water molecules move at all", "Water only moves into the cell", "Water only moves out of the cell"], "Same water potential inside and out.", "Water molecules still move both ways, but equally, so there is no net movement."],
[5, "A student says a plasmolysed cell is dead. Which is the best judgement?", ["Wrong: plasmolysis is reversible; in pure water the cell becomes turgid again", "Correct: plasmolysed cells always die", "Correct: the cell wall breaks", "Wrong: plasmolysis only happens in animal cells"], "Can it recover?", "Plasmolysis is reversible. If the cell is put back in water, water enters by osmosis and it becomes turgid again."]
]);
KB("t3s3", [
[2, "Which process can make a cell collect a substance to a HIGHER concentration than outside?", ["Active transport", "Simple diffusion", "Facilitated diffusion", "Osmosis"], "Only one process goes uphill.", "Only active transport moves substances against a concentration gradient, using carrier proteins and ATP."],
[4, "Root cells are given a respiratory inhibitor. What happens to the uptake of mineral ions?", ["It slows down or stops: less respiration ➔ less ATP ➔ less active transport", "It speeds up", "No change: ions enter by diffusion", "Only water uptake stops"], "Follow the chain: respiration ➔ ATP ➔ ...", "Ions are taken up by active transport, which needs ATP from respiration. Less respiration ➔ less ATP ➔ uptake slows or stops."],
[4, "The soil around roots becomes waterlogged (no oxygen). What happens to mineral uptake?", ["It falls: no oxygen ➔ less aerobic respiration ➔ less ATP for active transport", "It rises because water carries the ions in", "No change", "Only oxygen uptake stops"], "Oxygen ➔ respiration ➔ ATP.", "Without oxygen the root cells make much less ATP, so active transport of mineral ions slows down."],
[3, "Which process do white blood cells use to take in bacteria?", ["Phagocytosis: the membrane folds around the bacterium to form a vacuole", "Osmosis", "Simple diffusion", "Facilitated diffusion"], "Cell eating.", "In phagocytosis the membrane engulfs a large particle, forming a food vacuole. It needs energy."]
]);
KB("t4s1", [
[2, "What happens during interphase?", ["The cell grows, makes organelles and replicates its DNA", "Nothing: it is a resting phase", "Chromosomes line up at the equator", "The cytoplasm divides"], "It is NOT a rest.", "Interphase is very active: DNA replication, growth and synthesis of organelles."],
[3, "How does cytokinesis differ in plant cells?", ["A cell plate forms across the middle, because the cell wall is rigid", "A cleavage furrow pinches the cell in two", "Plant cells don't do cytokinesis", "The nucleus divides twice"], "The wall can't pinch in.", "Plant cells build a cell plate. Animal cells form a cleavage furrow."],
[3, "What are sister chromatids?", ["The two identical halves of one duplicated chromosome, joined at the centromere", "A pair of chromosomes, one from each parent", "Two different genes", "The spindle fibres"], "One 'X' shape.", "After DNA replication, each chromosome has two identical sister chromatids joined at the centromere."],
[4, "A DNA-content graph rises, then drops ONCE. Which division is shown?", ["Mitosis", "Meiosis", "Fertilisation", "DNA replication only"], "Count the drops.", "One drop = one division = mitosis. Meiosis has two drops (two divisions)."]
]);
KB("t4s2", [
[2, "In which stage do homologous chromosomes pair up and cross over?", ["Prophase I of meiosis", "Prophase of mitosis", "Anaphase II", "Interphase"], "Pairing only happens in meiosis.", "Homologous chromosomes pair up and cross over in prophase I of meiosis. They never pair in mitosis."],
[3, "Crossing over happens between…", ["non-sister chromatids of homologous chromosomes", "sister chromatids of one chromosome", "two different cells", "the spindle fibres"], "Swapping between mum's and dad's copies.", "Crossing over swaps DNA between non-sister chromatids of a homologous pair ➔ new combinations of alleles."],
[3, "When does independent assortment happen?", ["Metaphase I, when homologous pairs line up randomly at the equator", "Prophase I", "Anaphase II", "Interphase"], "M for middle.", "In metaphase I, each pair lines up randomly, so gametes get random mixtures of chromosomes."],
[4, "What separates in meiosis I?", ["Homologous chromosomes", "Sister chromatids", "Centromeres divide", "Nothing separates"], "XX ➔ X and X.", "Meiosis I separates homologous chromosomes (centromeres do not divide). Meiosis II separates sister chromatids."]
]);
KB("t4s3", [
[2, "How many cells does meiosis make, and what kind?", ["Four genetically different haploid cells", "Two identical diploid cells", "Two haploid cells", "Four identical diploid cells"], "Two divisions.", "Meiosis has two divisions ➔ four genetically different haploid (n) cells."],
[3, "Where does meiosis take place in humans?", ["Only in the gonads (testes and ovaries)", "In all body cells", "In the skin", "In the liver"], "Making gametes.", "Meiosis only happens in the gonads, to make gametes."],
[4, "Why must gametes be haploid?", ["So that fertilisation restores the diploid number and the chromosome number stays constant each generation", "So that they can swim faster", "So that they have more genes", "So that they are identical"], "n + n = 2n.", "If gametes were diploid, the chromosome number would double every generation. Haploid gametes fuse to restore the diploid number."],
[5, "A student says mitosis produces the cells for sexual reproduction. Which is the best judgement?", ["Wrong: mitosis is for growth, repair and asexual reproduction; gametes come from meiosis", "Correct", "Correct only in plants", "Wrong: sexual reproduction needs no cell division"], "Photocopier vs lucky-draw machine.", "Mitosis gives identical cells for growth, repair and asexual reproduction. Meiosis makes the haploid gametes."]
]);
KB("t5s1", [
[2, "How does an enzyme speed up a reaction?", ["It lowers the activation energy", "It gives energy to the reaction", "It is used up in the reaction", "It raises the temperature"], "The energy 'hill'.", "Enzymes are biological catalysts that lower the activation energy. They do not provide energy and are not used up."],
[3, "Which describes the shapes in the lock-and-key hypothesis?", ["The active site is complementary to the substrate", "The active site has the same shape as the substrate", "The substrate changes the enzyme permanently", "Any substrate fits any enzyme"], "Key and lock fit together, but are not the same shape.", "The active site's shape is complementary to the substrate, forming an enzyme–substrate complex.", "Say 'complementary', never 'same shape'."],
[3, "Why is a small amount of enzyme enough for a large amount of substrate?", ["Enzymes are not used up, so each one can be reused many times", "Enzymes multiply during the reaction", "The substrate becomes an enzyme", "Enzymes work without a substrate"], "Catalysts are unchanged at the end.", "An enzyme is unchanged at the end of the reaction, so the same molecule can catalyse the reaction again and again."],
[4, "What is the difference between catabolism and anabolism?", ["Catabolism breaks large molecules down (releases energy); anabolism builds them up (absorbs energy)", "They are the same", "Catabolism builds molecules up", "Anabolism only happens in plants"], "Cata = down.", "Metabolism = catabolism (breakdown, e.g. respiration) + anabolism (synthesis, e.g. protein synthesis)."]
]);
KB("t5s2", [
[2, "What happens to an enzyme at a very high temperature?", ["It is denatured: the active site changes shape permanently", "It is killed", "It works faster forever", "It becomes inactive but recovers when cooled"], "Enzymes are not alive.", "High temperature breaks the bonds holding the 3-D shape, so the active site changes shape permanently: denatured.", "Never write 'killed' or 'destroyed' for an enzyme."],
[3, "An enzyme is kept at 4 °C. What happens?", ["It becomes inactive, but works again when warmed (reversible)", "It is denatured permanently", "It is killed", "It works at its maximum rate"], "Cold = frozen lock, not melted lock.", "At low temperature the molecules have little kinetic energy, so there are few effective collisions. The active site is unchanged, so it recovers."],
[3, "What is the optimum pH of pepsin in the stomach?", ["About pH 2", "About pH 7", "About pH 9", "About pH 12"], "The stomach is very acidic.", "Pepsin works best in the acidic stomach (about pH 2). Salivary amylase works best at about pH 7."],
[5, "The rate of an enzyme reaction levels off even though the enzyme is still at its optimum temperature. Why?", ["All the substrate is used up, or all the active sites are occupied", "The enzyme is denatured", "The enzyme is used up", "The temperature is too low"], "It isn't the enzyme's fault.", "The curve levels off because the substrate runs out or the active sites are saturated, not because the enzyme is denatured."]
]);
KB("t5s3", [
[3, "A boiled enzyme is cooled back to 37 °C. Will it work again?", ["No: denaturation is irreversible", "Yes: cooling repairs the active site", "Yes, but twice as fast", "Only if more substrate is added"], "Melted lock.", "Denaturation permanently changes the shape of the active site, so cooling does not restore activity."],
[4, "In an enzyme experiment, why do we set up a tube with boiled enzyme?", ["As a control, to show the change is caused by the active enzyme only", "To make the reaction faster", "To kill bacteria", "To keep the temperature constant"], "What does a control show?", "The boiled (denatured) enzyme is a control: it shows the result is caused by the active enzyme and not by other factors."],
[4, "Why must we keep the pH and substrate concentration the same when testing the effect of temperature on an enzyme?", ["So that temperature is the only variable changed: a fair (valid) test", "To make the results more reliable by repeating", "To denature the enzyme", "Because pH has no effect"], "Controlled variables.", "Only the independent variable (temperature) is changed; other variables are kept constant so any difference is due to temperature."]
]);
KB("t8s1", [
[2, "What is a balanced diet?", ["All food substances in the right proportions for that person", "The same amount of every food", "Only fruit and vegetables", "Food with no fat at all"], "It depends on age, sex and activity.", "A balanced diet contains all food substances in the right proportions, which differ with age, sex and activity."],
[3, "Which pairing of deficiency and disease is correct?", ["Lack of vitamin C ➔ scurvy", "Lack of calcium ➔ anaemia", "Lack of iron ➔ rickets", "Lack of fibre ➔ scurvy"], "Match the job to the disease.", "Vitamin C ➔ scurvy; iron ➔ anaemia; calcium/vitamin D ➔ rickets; fibre ➔ constipation."],
[4, "Food label: 10 g fat and 20 g carbohydrate. Which gives more energy?", ["The fat: 10 × 9 = 90 kcal vs 20 × 4 = 80 kcal", "The carbohydrate, because there are more grams", "They are equal", "Neither gives energy"], "Multiply by 9 and 4.", "Fat ≈ 9 kcal/g ➔ 90 kcal. Carbohydrate ≈ 4 kcal/g ➔ 80 kcal. The most grams is not always the most energy."]
]);
KB("t8s2", [
[2, "What does bile do?", ["It emulsifies lipids into small droplets, increasing the surface area for lipase", "It digests fats into fatty acids and glycerol", "It contains lipase", "It digests protein"], "Washing-up liquid, not an enzyme.", "Bile contains no enzymes. It emulsifies lipids, breaking large droplets into small ones ➔ larger surface area for lipase.", "Writing 'bile digests fat' scores zero."],
[3, "What is the job of hydrochloric acid in the stomach?", ["It gives pepsin its acidic optimum pH and kills bacteria", "It digests protein", "It emulsifies fat", "It absorbs water"], "HCl helps an enzyme.", "HCl does not digest protein itself: pepsin does. HCl provides the acidic pH for pepsin and kills bacteria in food."],
[3, "Why is pancreatic juice alkaline?", ["To neutralise the acidic chyme from the stomach", "To kill bacteria", "To digest cellulose", "To emulsify fat"], "The duodenum enzymes need a different pH.", "Pancreatic juice is alkaline: it neutralises the acidic chyme so pancreatic enzymes can work at their optimum pH."],
[4, "What is chemical digestion?", ["Breaking large, complex, insoluble molecules into small, simple, soluble molecules using enzymes", "Breaking food into smaller pieces by chewing", "Absorbing food into the blood", "Moving food along the gut"], "Chemical bonds are broken.", "Chemical digestion uses enzymes to break bonds: large, complex, insoluble ➔ small, simple, soluble. Chewing is physical digestion."],
[5, "A patient has the gall bladder removed. What is the likely effect?", ["Less bile reaches the duodenum at mealtimes, so lipid digestion becomes slower", "Protein cannot be digested", "Starch digestion stops", "No effect on digestion"], "Normal job ➔ what's missing ➔ effect.", "The gall bladder stores bile. Without it, less bile is released after a fatty meal ➔ less emulsification ➔ smaller surface area for lipase ➔ slower lipid digestion."]
]);
KB("t8s3", [
[2, "Which part of the villus is one cell thick?", ["The epithelium", "The villus wall", "The lacteal", "The capillary network"], "Name the layer.", "The epithelium covering the villus is one cell thick ➔ short diffusion distance ➔ rapid absorption.", "Write 'the epithelium is one cell thick', not 'the villus wall'."],
[3, "Where are fatty acids and glycerol absorbed?", ["Into the lacteal", "Into the blood capillaries", "Into the hepatic vein", "Into the large intestine"], "Two roads out of the villus.", "Water-soluble products enter the capillaries; fatty acids and glycerol enter the lacteal (lymph)."],
[3, "Which vessel carries absorbed glucose from the small intestine to the liver?", ["The hepatic portal vein", "The hepatic vein", "The hepatic artery", "The lacteal"], "Portal = gateway to the liver.", "The hepatic portal vein goes from the small intestine to the liver. The hepatic vein takes blood from the liver to the vena cava."],
[4, "What happens to excess amino acids?", ["They are deaminated in the liver to form urea", "They are stored in the liver", "They are stored as glycogen", "They are excreted unchanged"], "Amino acids cannot be stored.", "Excess amino acids cannot be stored: the liver removes the amino group (deamination), forming urea, which the kidneys excrete."],
[4, "Where is most water absorbed in the gut?", ["The small intestine", "The large intestine only", "The stomach", "The mouth"], "Most, not the rest.", "Most water is absorbed in the small intestine; the large intestine absorbs the rest."]
]);
KB("t6s1", [
[2, "Why do stomata open in the day?", ["To let CO₂ in for photosynthesis; water loss is a side effect", "To let water evaporate out", "To let oxygen in for respiration only", "To let light in"], "What does photosynthesis need?", "Stomata open to let carbon dioxide diffuse in for photosynthesis. Losing water by transpiration is an unavoidable consequence."],
[3, "Which leaf cells in the epidermis have chloroplasts?", ["Only the guard cells", "All epidermal cells", "None at all", "Only the cuticle"], "The epidermis lets light through.", "The epidermis has no chloroplasts except in the guard cells, so light passes through to the mesophyll."],
[3, "How is the spongy mesophyll adapted?", ["Loosely packed cells with large air spaces ➔ rapid diffusion of gases", "Closely packed cells with many chloroplasts ➔ maximum light absorption", "A waxy layer ➔ less water loss", "Dead lignified cells ➔ support"], "Spongy = holes.", "Air spaces between loosely packed spongy cells allow the rapid diffusion of gases."],
[4, "At the compensation point, what is true?", ["The rate of photosynthesis equals the rate of respiration, so there is no net gas exchange", "Photosynthesis stops", "Respiration stops", "The plant only photosynthesises"], "Both still run.", "Both processes still happen; their rates are equal, so there is no net uptake or release of CO₂ or O₂."],
[5, "In bright light, what is the best description of a leaf's gas exchange?", ["Net uptake of CO₂ and net release of O₂, because photosynthesis is faster than respiration", "It takes in CO₂ and gives out O₂ only; it doesn't respire in the day", "Net release of CO₂", "No gas exchange"], "The word that earns the mark.", "Plants respire all the time. In bright light the rate of photosynthesis is higher than respiration ➔ NET uptake of CO₂ and NET release of O₂.", "Always say 'net' and compare the two rates."]
]);
KB("t6s2", [
[2, "Which colours of light does chlorophyll absorb most?", ["Red and blue", "Green", "Yellow only", "All colours equally"], "Leaves look green for a reason.", "Chlorophyll absorbs mainly red and blue light and reflects green light."],
[3, "Why are thylakoids stacked into grana?", ["To give a large surface area for chlorophyll to absorb light", "To store starch", "To hold the Calvin cycle enzymes", "To make the chloroplast stronger"], "More membrane, more pigment.", "Stacks of thylakoid membranes (grana) give a large surface area for chlorophyll and the light stage enzymes."],
[3, "A plant lacks magnesium. What symptom appears?", ["Chlorosis (yellow leaves), because chlorophyll cannot be made", "Stunted growth, because proteins cannot be made", "Purple leaves", "Wilting"], "Magnesium is in chlorophyll.", "Lack of magnesium ➔ less chlorophyll ➔ chlorosis. Lack of nitrate ➔ fewer proteins ➔ stunted growth."]
]);
KB("t6s3", [
[2, "Where does the oxygen released in photosynthesis come from?", ["Water, split by photolysis", "Carbon dioxide", "Glucose", "The air spaces"], "Photo-lysis = light splitting.", "Light energy splits water (photolysis): hydrogen goes to NADP and oxygen is released as a by-product."],
[3, "What are the products of the photochemical reactions?", ["ATP, NADPH and oxygen", "Glucose and oxygen", "Triose phosphate", "CO₂ and water"], "The light stage makes the 'batteries'.", "On the thylakoid membranes, light makes ATP (photophosphorylation), NADPH and O₂."],
[4, "Where do the photochemical (light-dependent) reactions happen?", ["On the thylakoid membranes", "In the stroma", "In the cytoplasm", "In the mitochondria"], "Solar panels.", "The light stage is on the thylakoid membranes; the Calvin cycle is in the stroma."]
]);
KB("t6s4", [
[2, "In the Calvin cycle, what do ATP and NADPH each provide?", ["ATP provides energy; NADPH provides hydrogen (reducing power)", "ATP provides hydrogen; NADPH provides energy", "Both provide carbon", "Both provide oxygen"], "One is energy, one is hydrogen.", "ATP gives the energy and NADPH gives the hydrogen to reduce the 3-C compound to triose phosphate."],
[3, "What is the first sugar made in photosynthesis?", ["Triose phosphate", "Glucose", "Sucrose", "Starch"], "A 3-carbon sugar.", "Triose phosphate (3-C) is made first; two combine to make glucose."],
[4, "Does the Calvin cycle only happen at night?", ["No: it needs no light directly, but it needs ATP and NADPH from the light stage, so it runs in the light", "Yes: light stops it", "Yes: it needs darkness", "No: it happens only in roots"], "Where do its ATP and NADPH come from?", "The Calvin cycle is light-independent, not a night reaction. It stops soon after dark because ATP and NADPH run out."],
[5, "Why do plants store excess glucose as starch?", ["Starch is insoluble, so it does not change the water potential of the cell", "Starch is sweeter", "Starch can move in the phloem", "Starch dissolves easily in cell sap"], "Osmotically inactive.", "Starch is insoluble and osmotically inactive, so storing it does not lower the water potential and make cells take in too much water."]
]);
KB("t6s5", [
[3, "As light intensity increases, the rate of photosynthesis rises and then levels off. What does the levelling off mean?", ["Light is no longer the limiting factor; CO₂ concentration or temperature is", "Light intensity is still limiting", "Photosynthesis has stopped", "The enzymes are denatured"], "Rising part vs flat part.", "Where the curve rises, light is limiting. Where it levels off, another factor (CO₂ or temperature) limits the rate."],
[4, "Why does temperature affect the rate of photosynthesis?", ["It affects the enzymes of the Calvin cycle", "It changes the colour of chlorophyll", "It affects the amount of light", "It changes the size of the stomata only"], "Enzymes are involved.", "The Calvin cycle is catalysed by enzymes, so temperature affects their activity."]
]);
KB("t6s6", [
[2, "Why is a plant kept in the dark for 48 hours before a starch experiment?", ["To destarch it, so any starch found later was made during the experiment", "To kill the plant", "To make more chlorophyll", "To open the stomata"], "Destarching.", "In darkness the stored starch is used up or converted to sucrose and transported away. Any starch detected later is new."],
[3, "Why is a leaf put into hot alcohol in the starch test?", ["To remove the chlorophyll, so the iodine colour change is seen clearly", "To kill the cells", "To add starch", "To soften the leaf"], "Boiling water breaks membranes; alcohol does something else.", "Hot alcohol (in a water bath, as it is flammable) removes chlorophyll so the blue-black colour is easy to see."],
[4, "Why is potassium hydroxide put in a flask with a leaf in a photosynthesis experiment?", ["It absorbs CO₂, to show CO₂ is needed", "It supplies CO₂", "It removes oxygen", "It tests for starch"], "Remove one requirement.", "KOH absorbs carbon dioxide, so the leaf has no CO₂. No starch forms ➔ CO₂ is needed for photosynthesis."]
]);
KB("t7s1", [
[2, "Where does glycolysis happen?", ["In the cytoplasm", "In the mitochondrial matrix", "On the cristae", "In the nucleus"], "Before the mitochondrion.", "Glycolysis happens in the cytoplasm. Only pyruvate enters the mitochondrion; glucose does not."],
[3, "What is the role of oxygen in aerobic respiration?", ["It is the final electron acceptor, forming water", "It combines with carbon to form CO₂", "It splits glucose", "It makes pyruvate"], "Where does inhaled oxygen end up?", "Oxygen accepts electrons and H⁺ at the end of the electron transport chain, forming water. NAD is then regenerated."],
[3, "Why is the inner mitochondrial membrane folded into cristae?", ["To increase the surface area for enzymes of oxidative phosphorylation", "To store glucose", "To make the mitochondrion stronger", "To hold the DNA"], "More membrane, more enzymes.", "Cristae give a large surface area so more enzymes of the electron transport chain can be packed in."],
[4, "In which stages is CO₂ released?", ["The link reaction and the Krebs cycle", "Glycolysis", "Oxidative phosphorylation", "All stages"], "Not in the cytoplasm.", "CO₂ is released in the link reaction and the Krebs cycle (matrix). No CO₂ is released in glycolysis."],
[5, "A student says 'respiration produces energy'. Which is the best correction?", ["Respiration releases energy stored in food; energy cannot be produced", "Respiration uses up energy", "Respiration is breathing", "Correct as written"], "Energy can't be made from nothing.", "Energy cannot be created. Respiration releases the chemical energy stored in food; part is stored in ATP, the rest is lost as heat."]
]);
KB("t7s2", [
[2, "What does muscle make in anaerobic respiration?", ["Lactic acid only (no CO₂)", "Ethanol and CO₂", "Lactic acid and CO₂", "Water and CO₂"], "Muscle ≠ yeast.", "Muscle: glucose ➔ lactic acid + 2 ATP. No CO₂. Yeast makes ethanol + CO₂."],
[3, "How much ATP is made per glucose in anaerobic respiration?", ["2 ATP", "38 ATP", "34 ATP", "0 ATP"], "Only glycolysis runs.", "Only glycolysis happens, giving a net 2 ATP. Much energy remains locked in lactic acid or ethanol."],
[4, "What happens to lactic acid after exercise?", ["Extra oxygen is taken in (oxygen debt); lactic acid is converted back to pyruvate, mainly in the liver", "It is excreted in urine", "It is stored in muscles forever", "It turns into CO₂ straight away"], "Oxygen debt.", "After exercise we breathe in extra oxygen to oxidise lactic acid back to pyruvate, mainly in the liver."],
[4, "Why can glycolysis continue in anaerobic respiration?", ["Pyruvate accepts hydrogen from NADH, so NAD is regenerated", "Oxygen is still present", "The Krebs cycle keeps running", "ATP is not needed"], "NAD must be recycled.", "Pyruvate is reduced to lactic acid (or ethanol + CO₂), regenerating NAD so glycolysis can keep making a little ATP."]
]);
KB("t7s3", [
[3, "In a respirometer, why is soda lime (or KOH) added?", ["To absorb CO₂, so the liquid movement shows O₂ uptake only", "To test for CO₂", "To supply oxygen", "To kill the seeds"], "It absorbs, it doesn't test.", "Soda lime/KOH absorbs CO₂, so the volume change (liquid movement) is due to O₂ being taken in."],
[3, "Why are boiled seeds used in a respiration experiment?", ["As a control: boiled seeds do not respire", "Boiled seeds respire faster", "To kill microorganisms only", "To supply heat"], "Dead seeds.", "Boiled (dead) seeds do not respire, so any change in the experimental set-up is caused by respiration of the living seeds."],
[4, "Why are seeds surface-sterilised before a respiration experiment?", ["To kill microorganisms, so their respiration does not affect the results", "To make the seeds germinate faster", "To remove water", "To stop the seeds respiring"], "Other living things respire too.", "Microorganisms on the seed coat also respire; sterilising removes them so only the seeds' respiration is measured."]
]);
