
KB("t9s1", [
[2, "What is an allele?", ["An alternative form of a gene, at the same locus", "The same thing as a gene, just a different word", "A whole chromosome carrying many genes", "A type of cell that carries genes"], "Gene for height: T or t.", "A gene controls a characteristic; alleles are its different forms (e.g. T and t) at the same locus."],
[3, "A plant is Tt (T = tall, dominant). What is its phenotype?", ["Tall", "Half tall, half short", "Short", "Medium height"], "Dominant is expressed in the heterozygote.", "T is dominant, so a Tt plant is tall. It is not 'half and half'."],
[3, "How many alleles of each gene does a gamete carry?", ["One", "Two", "Four", "None"], "Law of Segregation.", "The two alleles separate at meiosis, so each haploid gamete gets only one allele of each gene."],
[4, "A tall plant of unknown genotype is crossed with a short (tt) plant. Some offspring are short. What was the tall parent's genotype?", ["Tt (heterozygous)", "TT (homozygous dominant)", "tt", "It cannot be known"], "Test cross logic.", "A short (tt) offspring must get a t from each parent, so the tall parent must be Tt."],
[5, "Two heterozygous parents have one child with the recessive condition. What is the chance their NEXT child also has it?", ["1/4", "0, because they already had one", "1/2", "1"], "Each birth is independent.", "Each birth is an independent event, so the chance is still 1/4 every time."]
]);
KB("t9s2", [
[2, "What is the genotype of blood group O?", ["ii", "IᴬIᴮ", "Iᴬi", "IᴮIᴮ"], "O has no antigen.", "Group O is homozygous recessive: ii."],
[3, "Which antibodies are in the plasma of a person with group AB?", ["No anti-A and no anti-B", "Anti-A and anti-B", "Anti-A only", "Anti-B only"], "AB has both antigens.", "Group AB has both A and B antigens, so it has neither antibody. That's why AB is the universal recipient."],
[3, "Why is red-green colour blindness more common in males?", ["Males have only one X chromosome, so one recessive allele is enough", "The allele is on the Y chromosome", "Males have two X chromosomes", "Females cannot inherit it"], "XY vs XX.", "The allele is on the X. Males (XY) show it with one copy; females (XX) need two copies."],
[4, "A colour-blind father (XᵇY) and a normal (XᴮXᴮ) mother. What about their sons?", ["No son will be colour-blind: sons get their X from their mother", "All sons will be colour-blind", "Half the sons will be colour-blind", "All daughters will be colour-blind"], "Where does a son's X come from?", "A father passes Y to his sons, so the sons get the normal X from the mother. All daughters will be carriers."],
[4, "In a pedigree, two unaffected parents have an affected child. What does this show?", ["The trait is recessive and both parents are heterozygous carriers", "The trait is dominant", "The trait is caused by the environment", "One parent must be affected"], "Hidden in the parents.", "The parents must each carry a hidden recessive allele, so the trait is recessive."],
[3, "Which statement about Iᴬ and Iᴮ is correct?", ["They are co-dominant: both are fully expressed in IᴬIᴮ", "Iᴬ is dominant over Iᴮ", "Iᴮ is recessive to i", "They are on the Y chromosome"], "Group AB.", "Iᴬ and Iᴮ are co-dominant, giving group AB; both are dominant to i."]
]);
KB("t9s3", [
[2, "Which is an example of continuous variation?", ["Height", "ABO blood group", "Tongue rolling", "Free or attached earlobes"], "A range with in-between values.", "Height has a continuous range, controlled by many genes plus the environment. The others fall into a few distinct groups."],
[3, "What is the ultimate source of new alleles?", ["Mutation", "Independent assortment", "Crossing over", "Random fertilisation"], "The others only shuffle existing alleles.", "Mutation makes new alleles. Crossing over, independent assortment and random fertilisation only recombine existing ones."],
[3, "What ratio do you expect from Aa × aa?", ["1 : 1", "3 : 1", "9 : 3 : 3 : 1", "All dominant"], "A test cross.", "Aa × aa gives Aa and aa in equal numbers: 1 : 1."],
[4, "Who decides the sex of a human baby?", ["The sperm: it can carry an X or a Y chromosome", "The mother", "The egg: it can carry X or Y", "The environment"], "All eggs carry X.", "All ova carry X; half the sperm carry X and half carry Y. So the sperm decides the sex, with a 50% chance each time."]
]);
KB("t10s1", [
[2, "Which bases pair in DNA?", ["A with T, and C with G", "A with U, and C with G", "A with C, and T with G", "A with G, and C with T"], "U is only in RNA.", "In DNA, A pairs with T and C pairs with G by hydrogen bonds. U replaces T in RNA."],
[3, "Which sugar is found in DNA?", ["Deoxyribose", "Ribose", "Glucose", "Sucrose"], "D for DNA.", "DNA has deoxyribose; RNA has ribose."],
[4, "How does DNA control a characteristic?", ["Base sequence ➔ amino acid sequence ➔ protein ➔ characteristic", "DNA becomes the protein itself", "DNA makes energy", "Each base is one characteristic"], "Follow the chain.", "The base sequence of a gene decides the amino acid sequence of a polypeptide, so the protein made, which decides the characteristic."]
]);
KB("t10s2", [
[2, "Where does transcription happen?", ["In the nucleus", "At the ribosomes", "In the mitochondria", "In the cell membrane"], "DNA can't leave the nucleus.", "Transcription (DNA ➔ mRNA) happens in the nucleus. Translation happens at the ribosomes."],
[3, "Where is a codon found?", ["On mRNA", "On tRNA", "On DNA only", "On a ribosome"], "Anticodon is on tRNA.", "A codon is three bases on mRNA. The anticodon (on tRNA) pairs with it."],
[3, "The DNA template strand reads TAC. What is the mRNA codon?", ["AUG", "ATG", "TAC", "UAC"], "Complementary, and use U not T.", "mRNA is complementary to the template strand: T➔A, A➔U, C➔G. So TAC ➔ AUG (the start codon)."],
[4, "One base is DELETED near the start of a gene. What is the usual effect?", ["A frameshift: all the amino acids after it may change", "Only one amino acid changes", "No effect at all", "The DNA doubles"], "Reading in threes.", "A deletion shifts the reading frame, so every codon after it changes ➔ the protein changes shape and usually stops working."],
[4, "A substitution changes one DNA base, but the protein is unchanged. Why?", ["The new codon codes for the same amino acid (the code is degenerate)", "Substitutions never change proteins", "The ribosome ignores the change", "The mRNA is not made"], "More than one codon per amino acid.", "The genetic code is degenerate: several codons code for the same amino acid, so some substitutions have no effect."],
[5, "What causes Down syndrome?", ["An extra chromosome 21", "A gene mutation in the haemoglobin gene, like sickle-cell anaemia", "An infection caught by the mother during pregnancy", "A deletion of a single base in one gene"], "47 chromosomes.", "Non-disjunction gives a gamete with an extra chromosome 21. After fertilisation the zygote has 47 chromosomes."]
]);
KB("t10s3", [
[2, "Which enzyme cuts DNA at a specific sequence?", ["Restriction enzyme", "DNA ligase", "RNA polymerase", "Amylase"], "Scissors.", "Restriction enzymes cut DNA at specific base sequences. DNA ligase is the 'glue' that joins fragments."],
[3, "Why are the gene and the plasmid cut with the SAME restriction enzyme?", ["So the cut ends are complementary and can be joined", "To make the plasmid bigger", "To kill the bacteria", "Different enzymes would work better"], "The ends must match.", "The same restriction enzyme gives matching (complementary) ends, so DNA ligase can join the gene into the plasmid."],
[3, "Why does a human gene work inside a bacterium?", ["The genetic code is universal", "Bacteria have a nucleus", "Bacteria are human cells", "The gene changes into bacterial DNA"], "Same codons everywhere.", "The genetic code is universal: the same codons code for the same amino acids, so bacteria make the same human protein."],
[4, "In gel electrophoresis, which DNA fragments travel furthest?", ["The shortest fragments", "The longest fragments", "They all travel the same distance", "Only the positive fragments"], "Small ones slip through the gel.", "DNA is negative, so it moves to the positive terminal. Shorter fragments move faster through the gel's pores, so they travel further."],
[5, "In a paternity test, how should the child's DNA fingerprint compare with the parents'?", ["Every band in the child matches a band in either the mother or the father", "The child's pattern is identical to the father's", "The child's pattern is identical to the mother's", "No bands match"], "Half from each parent.", "Half the genetic material comes from each parent, so each of the child's bands must be found in the mother or the father."],
[4, "Why is GM human insulin better than insulin from animals?", ["It is identical to human insulin, pure, and made in large amounts quickly", "It is stronger than human insulin", "It can be swallowed as a tablet", "It lasts forever"], "Compare yield, structure, safety.", "GM insulin has the same structure as human insulin (less rejection), is pure (low infection risk) and is made in large amounts in fermenters."]
]);
KB("t11s1", [
[2, "How is a scientific name written?", ["Homo sapiens (italic; capital H only)", "Homo Sapiens, with capitals for both words because both are names", "homo sapiens, all lower case because it is a Latin phrase", "HOMO SAPIENS, all capitals so the genus and species stand out"], "Binomial nomenclature.", "Genus starts with a capital letter, species is all small letters; italics in print, underlined by hand."],
[3, "Which pair is more closely related?", ["Two species in the same genus", "Two species only in the same family", "Two species only in the same order", "Two species only in the same kingdom"], "The lower the shared level…", "Species in the same genus share a more recent common ancestor than those only in the same family, order or kingdom."],
[3, "Why are fungi NOT put in Kingdom Plantae?", ["No chlorophyll; no cellulose walls", "They are too small to be plants, as they are only seen under microscopes", "They can move around, which plants are not able to do", "They have no cells, so they can't be put in any kingdom with plants"], "Two key features.", "Fungi cannot photosynthesise and their cell walls are not cellulose, so they are a separate kingdom."],
[4, "A whale lives in the sea and has fins. Why is it classified as a mammal?", ["Lungs, mammary glands, live young", "It has scales and gills like a fish, but is much larger", "It lays shelled eggs on beaches, like sea turtles do", "It is cold-blooded, so its body temperature matches the sea"], "Look at the defining features.", "Mammals have hair, mammary glands and lungs, and most give birth to live young. Whales have these features."],
[4, "Which feature is best for one step of a dichotomous key?", ["Has wings / has no wings", "Big / small", "Pretty / ugly", "Light brown / dark brown"], "Clear, observable, constant.", "Keys should use clear yes/no features that do not vary, not size or subtle colour."],
[5, "Why did scientists move from 5 kingdoms to 3 domains?", ["New evidence from rRNA sequences showed Archaea are closer to eukaryotes than to bacteria", "Bacteria were discovered to be plants", "There were too many kingdoms to remember", "Microscopes stopped working"], "Science is tentative.", "Woese compared rRNA sequences: Archaea are a separate domain. New technology gives new evidence, so classification changes."]
]);
KB("t11s2", [
[2, "In natural selection, what does 'fittest' mean?", ["Best adapted to that environment", "The strongest", "The fastest runner", "The biggest"], "Not about the gym.", "The fittest individuals are the best adapted to their environment, so they are more likely to survive and reproduce."],
[3, "Mosquitoes become resistant to an insecticide. What is the best explanation?", ["Some resistant mosquitoes already existed; the insecticide selected them", "The insecticide made the mosquitoes mutate", "The mosquitoes decided to become resistant", "Each mosquito learned to survive"], "Selection, not cause.", "Mutations are random and already there. The insecticide is a selection pressure: resistant ones survive and reproduce, so their proportion rises."],
[4, "Which statement about evolution is correct?", ["Populations evolve over many generations; individuals do not", "Each individual evolves during its life", "Acquired characters are passed on to offspring", "Animals change because they need to"], "Darwin, not Lamarck.", "Evolution is a change in the allele frequencies of a population over generations. Acquired characters are not inherited."],
[5, "Why is the sickle-cell allele common in places with malaria?", ["Heterozygotes are less likely to get malaria and do not suffer sickle-cell anaemia, so they have a selection advantage", "People with sickle-cell anaemia survive malaria best", "Malaria causes the mutation", "The allele protects against all diseases"], "Heterozygote advantage.", "Heterozygotes resist malaria and don't have sickle-cell anaemia, so they survive and reproduce more, keeping the allele common."]
]);
KB("t11s3", [
[2, "What are homologous structures?", ["Structures with the same basic plan but different functions, e.g. the pentadactyl limb", "Structures with the same function but different plans", "Structures that are identical in every way", "Fossils of the same animal"], "Same bones, different jobs.", "Human arms, bat wings and whale flippers have the same bone arrangement but different functions ➔ common ancestor."],
[3, "Which rock layer usually has the oldest fossils?", ["The lowest layer", "The top layer", "The middle layer", "All layers are the same age"], "Layers build up over time.", "Sedimentary rocks form layer by layer, so the lowest layer is the oldest."],
[3, "A fossil has 1/4 of its original ¹⁴C left. The half-life is 5730 years. How old is it?", ["About 11 460 years", "About 5730 years", "About 17 190 years", "About 22 920 years"], "1/2 then 1/4.", "1/4 left = two half-lives = 2 × 5730 = 11 460 years."],
[4, "Which statement about humans and chimpanzees is correct?", ["They share a recent common ancestor", "Humans evolved from chimpanzees", "Chimpanzees evolved from humans", "They are the same species"], "Cousins, not parents.", "Humans and chimpanzees share a common ancestor; both species are still evolving."],
[5, "What must happen for isolated populations to become new species?", ["Gene flow stops, different mutations and selection pressures act, until they cannot interbreed to give fertile offspring", "They only need to look different from each other to be separate species", "Isolation alone is enough; they become new species straight away", "They must live in the same place so that they can compete with each other"], "Isolation is only the start.", "After isolation, different mutations and selection change allele frequencies until the groups can no longer interbreed to produce fertile offspring."]
]);
KB("t12s1", [
[3, "How are most mineral ions absorbed by root hair cells?", ["Active transport", "Simple diffusion, because the ions are small and move down their gradient", "Osmosis, because ions are carried into the cell with the water", "Phagocytosis, as the root hair membrane engulfs the ions"], "Soil has fewer ions than the cell.", "Most ions are taken up by active transport, using ATP from root respiration."],
[3, "A plant lacks nitrate. What symptom appears?", ["Stunted growth, because too few proteins are made", "Yellow leaves only, because chlorophyll isn't made", "Bigger flowers", "Faster growth"], "Nitrate ➔ protein.", "Nitrate is used to make proteins; lack ➔ stunted growth. Lack of magnesium ➔ chlorosis."],
[4, "How is a root hair cell adapted for absorption?", ["It is long and thin, giving a large surface area", "It has many chloroplasts", "It has a thick waxy cuticle", "It is dead and hollow"], "Surface area.", "The long, thin extension increases the surface area for absorbing water (osmosis) and minerals (active transport)."]
]);
KB("t12s2", [
[2, "Where does water evaporate from in a leaf?", ["Mesophyll cell surfaces", "Directly from the stomata, where the guard cells release water vapour", "Through the waxy cuticle on the upper surface of the leaf", "From the xylem only, as water leaves the veins straight into the air"], "Two steps, two verbs.", "Water evaporates from mesophyll cell surfaces, then the water vapour diffuses out through the stomata."],
[3, "What does a potometer actually measure?", ["Water uptake", "The exact rate of transpiration from the leaves", "The rate of photosynthesis in the leaves", "The amount of water stored in the leaves"], "State the assumption.", "It measures water uptake. We assume this is about equal to transpiration because very little water is used in photosynthesis."],
[3, "Why is the shoot cut under water when setting up a potometer?", ["To keep the water column unbroken", "To keep the leaves cool so they don't wilt", "To kill bacteria living on the cut stem", "To make the stem longer so it fits the potometer"], "An air bubble blocks the xylem.", "Air would break the continuous water column in the xylem, so the shoot is cut under water."],
[4, "Does the transpiration pull need ATP from the plant?", ["No: it is passive; the energy comes from the sun, which evaporates the water", "Yes: xylem cells use ATP to pump water", "Yes: root cells push the water up", "Only at night"], "Xylem is dead.", "Evaporation (powered by the sun's heat) creates the transpiration pull. Xylem is dead and uses no ATP."],
[4, "Which condition INCREASES the rate of transpiration?", ["Low humidity", "High humidity", "No wind", "Low temperature"], "Water vapour gradient.", "In dry (low-humidity) air, the gradient of water vapour between leaf and air is steeper, so water vapour diffuses out faster."]
]);
KB("t12s3", [
[2, "Which statement about phloem is correct?", ["Living sieve tubes carrying sucrose both ways", "It is dead and hollow like xylem, with lignified walls", "It carries water upwards only, like xylem", "It carries starch from the leaves to the roots"], "Living vs dead.", "Phloem is living and carries sucrose by translocation in both directions. Xylem is dead and carries water up."],
[3, "Why is sugar transported as sucrose, not glucose?", ["Sucrose is soluble but non-reactive, so it isn't used up on the journey", "Sucrose is insoluble, so it can't leak out of the phloem", "Glucose is too big to fit through the sieve plates", "Sucrose is a protein, which is carried more easily"], "Soluble but non-reactive.", "Glucose is reactive and would be respired along the way. Sucrose is soluble but non-reactive, so it is a good transport form."],
[4, "A ring of bark is removed from a tree. The stem swells just ABOVE the ring. Why?", ["Sugars build up above the ring ➔ lower water potential ➔ water enters by osmosis ➔ swelling", "Water piles up because xylem is removed", "Sugars physically pile up like sand", "The tree grows a new branch"], "Ring-barking removes phloem.", "Phloem is removed, so sucrose collects above the ring. This lowers the water potential, so water enters by osmosis and the tissue swells."],
[4, "How is a woody plant supported?", ["Thick lignified walls of xylem stop it collapsing", "Turgidity of dead xylem cells", "Its roots push it up", "The phloem is hard"], "Lignin.", "Lignified xylem walls give mechanical support. Non-woody plants rely on the turgidity of living cells (e.g. the cortex)."]
]);
KB("t13s1", [
[2, "What is the job of cilia in the trachea?", ["They sweep mucus to the throat", "They trap dust and bacteria in the air as it enters the lungs", "They absorb oxygen from the air passing through the trachea", "They keep the trachea open by pushing against its walls"], "Cilia sweep; mucus traps.", "Mucus traps dust and bacteria; cilia sweep the mucus up to the throat. C-shaped cartilage keeps the trachea open."],
[3, "What is the order of events when oxygen enters the blood in an air sac?", ["It dissolves in the water film, then diffuses across the epithelium and capillary endothelium", "It diffuses into the capillary first, then dissolves", "It is pumped by active transport", "It passes through the cilia"], "Dissolve first.", "Oxygen dissolves in the moist lining first, then diffuses across the one-cell-thick epithelium and endothelium, then binds to haemoglobin."],
[4, "How is a steep concentration gradient of oxygen kept at the air sacs?", ["Continuous ventilation AND continuous blood flow", "Continuous blood flow only", "Thick air sac walls", "Mucus on the air sac"], "Two things keep moving.", "Ventilation brings in fresh air; blood flow carries oxygen away. Both keep the gradient steep."],
[3, "Which is correct?", ["Respiration happens in the mitochondria of every cell; the lungs carry out ventilation and gas exchange", "The lungs carry out respiration to take in oxygen", "Breathing and respiration mean the same", "Respiration only happens in the lungs"], "Breathing ≠ respiration.", "Respiration is a chemical process in all cells. The lungs ventilate and exchange gases."]
]);
KB("t13s2", [
[2, "What happens to the diaphragm during inhalation?", ["The diaphragm muscle contracts and the diaphragm flattens", "The diaphragm relaxes and flattens", "The diaphragm contracts and domes upwards", "Nothing happens"], "Muscles contract to act.", "The diaphragm muscle contracts, pulling the diaphragm down so it flattens."],
[3, "Which is the correct order in inhalation?", ["Muscles contract ➔ thoracic volume increases ➔ pressure falls below atmospheric ➔ air is drawn in", "Air rushes in ➔ the chest gets bigger ➔ muscles contract", "Pressure rises ➔ air is drawn in", "The rib cage expands like a balloon ➔ air is pushed in"], "Volume changes first.", "The volume change comes first; the pressure change is the result; then air moves in."],
[3, "How does the rib cage move during inhalation?", ["Upwards and outwards", "It expands in size", "Downwards and inwards", "It does not move"], "Bone can't stretch.", "External intercostal muscles contract and pull the rib cage upwards and outwards. Bone cannot 'expand'.", "Write 'upwards and outwards', never 'the rib cage expands'."],
[5, "A knife punctures the chest wall. Why does the lung collapse?", ["Air enters the pleural cavity, so its low pressure is lost and the lung recoils by its own elasticity", "Air leaks out of the lung through the hole", "The diaphragm stops working", "The trachea closes"], "Pleural cavity.", "The pleural cavity is below atmospheric pressure. Air rushes into it, the pressure difference is lost, and the elastic lung collapses."]
]);
KB("t13s3", [
[3, "How does tar in cigarette smoke lead to lung infections?", ["Tar paralyses the cilia, so mucus and bacteria build up", "Tar kills all the cilia instantly", "Tar blocks the stomata", "Tar is a virus"], "Cilia stop sweeping.", "Tar paralyses the cilia, so they can't sweep mucus away. Mucus and bacteria accumulate ➔ infections."],
[4, "In emphysema, why do patients become breathless?", ["Less surface area", "The trachea gets wider, so too much air rushes in", "More air sacs are made, but they are too small", "The blood carries more oxygen, which slows breathing down"], "Surface area.", "Damaged air sac walls ➔ smaller surface area ➔ slower diffusion of O₂ into the blood."],
[4, "Which substance in cigarette smoke reduces the oxygen carried by the blood?", ["Carbon monoxide", "Nicotine", "Tar", "Water vapour"], "It binds haemoglobin.", "Carbon monoxide binds to haemoglobin, reducing oxygen transport. Nicotine raises heart rate; tar is a carcinogen."]
]);
KB("t14s1", [
[2, "Which vessel carries deoxygenated blood away from the heart?", ["The pulmonary artery", "The aorta", "The pulmonary vein", "The vena cava"], "The odd artery.", "The pulmonary artery is the only artery carrying deoxygenated blood (to the lungs)."],
[3, "Which statement about veins is correct?", ["Veins have a thinner muscular wall than arteries, a large lumen and valves", "Veins have no muscular wall", "Veins carry blood away from the heart", "Veins have thick elastic walls for high pressure"], "Thinner, not none.", "Veins have a thinner wall than arteries (not no muscle), a large lumen and valves to prevent backflow.", "'Veins have no muscular wall' scores zero."],
[3, "Why do capillaries slow blood down?", ["They are highly branched, so the total cross-sectional area is large", "They have valves", "Their walls are thick", "The heart pumps weakly into them"], "Many branches.", "Huge total cross-sectional area ➔ lower flow rate ➔ more time for exchange."],
[4, "What carries oxygen in the blood, and how is most CO₂ carried?", ["O₂ as oxyhaemoglobin in red blood cells; CO₂ mostly as hydrogencarbonate ions in the plasma", "Both are mainly dissolved in the plasma, which is mostly water", "O₂ is carried in the plasma; CO₂ in the red blood cells", "Both as oxyhaemoglobin"], "Oxygen is poorly soluble.", "Haemoglobin carries O₂ as oxyhaemoglobin; most CO₂ travels as hydrogencarbonate ions in plasma."]
]);
KB("t14s2", [
[2, "What do heart valves do?", ["They prevent the backflow of blood", "They push blood forward", "They make the heart beat", "They carry oxygen"], "One-way doors.", "Valves only prevent backflow. The heart muscle pumps the blood."],
[3, "Why is the wall of the left ventricle thicker than the right?", ["To generate a higher pressure to pump blood all round the body", "To withstand the high pressure", "Because it holds more blood", "To pump blood to the lungs"], "Create, not withstand.", "The thicker muscle contracts to generate a higher pressure, pumping blood a longer distance to the whole body."],
[4, "The ventricles contract. Why does the bicuspid valve close?", ["Pressure in the ventricle rises above pressure in the atrium", "The ventricle muscle pulls it shut", "The valve contracts", "Pressure in the atrium rises above the ventricle"], "Name the two places.", "When ventricular pressure is higher than atrial pressure, the bicuspid (and tricuspid) valve closes, preventing backflow into the atria."],
[4, "Which vessel supplies the heart muscle itself?", ["The coronary artery", "The aorta directly through the ventricle", "The pulmonary vein", "The vena cava"], "The heart feeds itself separately.", "Cardiac muscle gets oxygen and nutrients only from the coronary arteries, not from the blood inside its chambers."]
]);
KB("t14s3", [
[3, "How do nutrients reach body cells from the blood?", ["They pass from the capillary into tissue fluid, then into the cells", "Directly from the capillary into the cells", "Through the lymph first", "Through the veins"], "Never skip tissue fluid.", "Nutrients diffuse from capillaries into the tissue fluid that bathes the cells, then into the cells."],
[4, "Why is tissue fluid formed at the arteriole end of a capillary?", ["High hydrostatic (blood) pressure forces plasma out", "Red blood cells squeeze out", "Osmosis draws water out", "The heart pumps it out directly"], "Pressure pushes.", "High hydrostatic pressure forces some plasma out. Red blood cells, platelets and large plasma proteins stay in."],
[4, "What moves lymph along the lymph vessels?", ["Contraction of skeletal muscles squeezing the vessels, with valves preventing backflow", "The heart, which pumps lymph round the body together with the blood", "Gravity only, as lymph drains downwards towards the feet", "Cilia lining the lymph vessels, which beat to sweep the lymph along"], "Not the heart.", "Lymph moves when skeletal muscles squeeze the lymph vessels; valves stop it flowing backwards."],
[5, "A coronary artery is blocked by a plaque. What happens?", ["Less oxygen and nutrients reach the cardiac muscle; the cells can't respire aerobically and may die (heart attack)", "Blood in the ventricle can't reach the heart muscle", "The valves stop working", "The lungs stop working"], "Coronary = heart's own supply.", "Plaque narrows the coronary artery ➔ less blood flow ➔ cardiac muscle lacks O₂ ➔ cells die."]
]);
KB("t15s1", [
[2, "What is pollination?", ["Transfer of pollen grains from the anther to the stigma", "Fusion of male and female gametes", "Growth of the pollen tube", "Spreading of seeds"], "Transfer, not fusion.", "Pollination is only the transfer of pollen. Fertilisation is the fusion of gamete nuclei."],
[3, "Is a pollen grain a male gamete?", ["No: it carries / produces the male gamete", "Yes: it is the male gamete", "It is the female gamete", "It is a seed"], "Spacecraft and astronaut.", "The pollen grain carries the male gamete; the gamete travels down the pollen tube."],
[3, "What does the ovary become after fertilisation?", ["The fruit", "The seed", "The testa", "The embryo"], "Ovary ➔ fruit; ovule ➔ seed.", "The ovary becomes the fruit and each ovule becomes a seed."],
[4, "Whose genes are in the fruit wall of an apple?", ["Only the mother plant's", "Both parents', because the fruit forms after fertilisation", "Only the pollen's, because the pollen grain fertilises the ovary", "None at all, because the fruit wall is not made of living cells"], "Mother's own tissue.", "The fruit wall comes from the ovary wall, which is the mother's tissue. The seeds contain genes from both parents."],
[4, "How does a pollen tube reach the ovule?", ["It grows down the style by secreting enzymes, then enters through the micropyle", "The pollen grain swims down the style", "Wind carries it", "It needs water to reach the ovule"], "The grain stays on the stigma.", "The grain germinates on the stigma; the tube grows down the style (digesting it with enzymes) and enters the micropyle. No water is needed."]
]);
KB("t15s2", [
[2, "Where does fertilisation usually happen in humans?", ["In the oviduct", "In the uterus", "In the vagina", "In the ovary"], "Before implantation.", "Fertilisation happens in the oviduct; the embryo then implants in the uterus lining."],
[3, "Where do sperm mature and get stored?", ["In the epididymis", "In the testis", "In the vas deferens", "In the prostate"], "Made in one place, matured in another.", "Sperm are made in the testis but mature and are stored in the epididymis."],
[3, "What does amniotic fluid do?", ["It is a shock absorber that protects the foetus", "It gives the foetus nutrients and oxygen", "It carries blood", "It makes hormones"], "Cushion only.", "Amniotic fluid protects against mechanical injury. Nutrients and oxygen come via the placenta."],
[4, "Why must maternal and foetal blood never mix?", ["The mother's high blood pressure could damage foetal vessels, and different blood groups could clump", "Mixing would make the baby grow too fast", "Blood cannot move in the placenta, so mixing isn't possible", "Fetal blood has no oxygen to share with the mother"], "Two reasons.", "Separate blood protects the foetus from the mother's high pressure and prevents clumping of incompatible blood."],
[4, "How do contraceptive pills work?", ["Synthetic hormones inhibit ovulation", "They kill sperm", "They block the oviduct", "They stop menstruation only"], "The pill never kills sperm.", "The pill contains hormones that stop ovulation, so no ovum is released."],
[3, "How many chromosomes are in a human sperm?", ["23 single chromosomes (haploid)", "23 pairs", "46 single chromosomes", "46 pairs"], "One set.", "A gamete has 23 individual chromosomes (one set). Fertilisation restores 46 (23 pairs)."]
]);
KB("t15s3", [
[2, "Why is dry mass better than fresh mass for measuring plant growth?", ["Fresh mass changes with water content, so it is unreliable", "Dry mass is easier to measure", "Fresh mass is always zero", "Dry mass keeps the plant alive"], "Water comes and goes.", "Fresh mass fluctuates with water content. Dry mass measures the organic matter, so it is more reliable (but the plant is killed)."],
[3, "Why does the dry mass of a germinating seed fall at first?", ["Stored food is respired; no leaves yet", "The seed loses water as it swells, so its dry mass falls", "The seed photosynthesises underground, which uses up its dry mass", "The cotyledons grow bigger, which uses up the seed's dry mass"], "Respiration uses stored food.", "Enzymes hydrolyse stored food, which is respired to release energy. Dry mass rises only once leaves photosynthesise faster than respiration."],
[3, "What does primary growth increase?", ["Length only", "Thickness only", "Both length and thickness", "Leaf number only"], "Apical meristem.", "Primary growth (apical meristems) increases length. Secondary growth (vascular cambium) increases thickness."],
[4, "Which is NOT growth?", ["A raisin swelling in water", "A baby getting heavier over months", "A seedling getting taller", "A tree trunk getting thicker"], "Growth is irreversible.", "Growth is an irreversible increase in size and dry mass. Swelling by taking in water is reversible, so it is not growth."]
]);
KB("t16s1", [
[2, "Which part of the eye does MOST of the refraction?", ["The cornea", "The lens", "The pupil", "The retina"], "The lens does fine focusing.", "The cornea refracts most of the light; the lens fine-tunes the focus."],
[3, "Looking at a near object, what happens?", ["Ciliary muscles contract, suspensory ligaments slacken, the lens becomes thicker", "Suspensory ligaments contract and the lens gets thinner", "Ciliary muscles relax and the lens gets thicker", "The pupil contracts"], "Only muscles contract.", "Ciliary muscles contract ➔ tension in the ligaments decreases ➔ the elastic lens becomes thicker ➔ more refraction.", "Ligaments slacken or tighten; they never contract."],
[3, "In bright light, what happens to the iris?", ["Circular muscles contract, radial muscles relax, the pupil constricts", "The pupil itself contracts like a muscle to let in less light", "Radial muscles contract, making the pupil smaller", "Both sets of muscles relax, so the pupil returns to its normal size"], "Name the two muscles.", "Circular muscles contract and radial muscles relax, so the pupil constricts and less light enters."],
[3, "Which cells are found at the yellow spot?", ["Cone cells only", "Rod cells only", "Both equally", "No photoreceptors"], "Sharpest, colour vision.", "The yellow spot has many cone cells and no rods, giving the sharpest colour vision."],
[4, "Does an image form on the blind spot?", ["Yes, but nothing detects it", "No image forms there, because light can't reach that part of the eye", "Only in dim light, when the rods near the blind spot are active", "Only in colour, because the blind spot is full of cones"], "Where the optic nerve leaves.", "Light still falls there, but with no rods or cones no impulses are produced, so it isn't seen."],
[4, "What is the job of the semicircular canals?", ["Detecting head movement for balance", "Hearing sound", "Amplifying vibrations", "Equalising air pressure"], "Not for sound.", "Semicircular canals detect head movement. The cochlea detects sound; the Eustachian tube equalises pressure."],
[4, "Which part changes sound vibrations into nerve impulses?", ["Sensory hair cells in the cochlea", "The eardrum", "The ear bones", "The oval window"], "The receptors.", "The eardrum vibrates and the ossicles amplify, but sensory hair cells in the cochlea generate the nerve impulses."]
]);
KB("t16s2", [
[2, "How does a message cross a synapse?", ["A neurotransmitter diffuses across", "Electricity jumps across the gap from one neurone to the next", "The two neurones touch, so the impulse passes straight through", "Blood carries the signal across the gap between neurones"], "Chemical across the gap.", "Neurotransmitter is released from vesicles, diffuses across the cleft, binds to receptors, and a new impulse starts."],
[3, "Why do impulses travel in one direction only across a synapse?", ["Neurotransmitter is only released from the axon ending", "The myelin sheath blocks one side", "Impulses are too weak to go back", "Dendrons have no membrane"], "Vesicles are only on one side.", "Only the synaptic knob has vesicles of neurotransmitter, so transmission is one-way."],
[3, "Which reflex has only TWO neurones (no interneurone)?", ["The knee jerk reflex", "The withdrawal reflex", "The pupil reflex", "Every reflex"], "Stretch receptor straight to motor.", "The knee jerk: sensory ➔ motor, with no interneurone."],
[4, "Which part of the brain controls breathing and heart beat?", ["The medulla oblongata", "The cerebellum", "The cerebrum", "The spinal cord"], "The Breather.", "The medulla controls breathing and heart beat. The cerebellum controls balance and smooth movement."],
[4, "Do reflex actions involve the brain?", ["Not the cerebrum (some use the medulla)", "Never: no part of the brain is ever involved in a reflex", "Always: the cerebrum decides each reflex response", "Only the cerebellum, which controls balance and coordination"], "Reflex = no cerebrum.", "Spinal reflexes use the spinal cord; cranial reflexes (blinking, swallowing, pupil) use the medulla. The cerebrum isn't needed."],
[4, "Where are the cell bodies of sensory neurones found?", ["In the dorsal root ganglion", "In the grey matter of the spinal cord", "In the ventral root", "In the muscle"], "The swelling on the dorsal root.", "Sensory cell bodies are in the dorsal root ganglion. Motor and interneurone cell bodies are in the grey matter."]
]);
KB("t16s3", [
[2, "How do hormones travel to their target organs?", ["In the blood", "Through ducts that lead from the glands to each organ", "Along neurones, like nerve impulses but more slowly", "In the lymph only, which carries them to the organs"], "Endocrine = ductless.", "Endocrine glands secrete hormones directly into the blood."],
[3, "Why does a hormone act only on certain organs?", ["Only target organs have specific receptors for it", "It only reaches those organs", "Other organs destroy it", "It is too big for other cells"], "Receptors.", "Hormones reach the whole body in the blood, but only cells with specific receptors respond."],
[3, "A shoot is lit from one side. Where do the auxins go?", ["To the shaded side, which elongates more, so the shoot bends towards light", "They are destroyed on the lit side", "To the lit side", "They stay at the tip"], "Light moves auxins.", "Unilateral light makes auxins move to the shaded side; those cells elongate more, so the shoot bends towards the light."],
[4, "What does a clinostat do in a tropism experiment?", ["Rotates the plant so the stimulus acts evenly", "Measures how fast the shoot grows towards the light each hour", "Produces auxin and adds it to the shoot tip to speed up growth", "Kills the shoot tip so that the plant cannot detect the light"], "It removes the one-sided effect.", "Rotation removes the unilateral effect, so auxin is evenly spread and the plant grows straight."],
[4, "Compare nervous and hormonal coordination.", ["Nervous: fast, localised, short-lived. Hormonal: slow, widespread, long-lasting", "Both are fast and short-lived, but hormones reach more organs", "Hormonal coordination is faster, because blood moves quickly", "Nervous coordination uses the blood to carry its signals"], "Text message vs radio broadcast.", "Nerves send fast, local, brief impulses. Hormones travel in the blood: slower, widespread and longer-lasting."]
]);
KB("t16s4", [
[2, "What joins muscle to bone?", ["A tendon, which is inelastic", "A ligament, which is elastic", "Cartilage", "Synovial fluid"], "TM / LB.", "Tendons join muscle to bone and are inelastic, so the whole pull reaches the bone. Ligaments join bone to bone."],
[3, "When you bend your arm, what do the biceps and triceps do?", ["Biceps contracts, triceps relaxes", "Both contract", "Triceps contracts, biceps relaxes", "Both relax"], "Opposing muscles.", "The biceps (flexor) contracts and the triceps (extensor) relaxes to bend the arm."],
[3, "Which joint moves in only one plane?", ["The elbow (hinge joint)", "The shoulder", "The hip", "The ball-and-socket joint"], "Like a door.", "The elbow and knee are hinge joints; the shoulder and hip are ball-and-socket joints."],
[4, "What secretes synovial fluid?", ["The synovial membrane", "The cartilage", "The ligament", "The bone marrow"], "The oil factory.", "The synovial membrane secretes synovial fluid, which lubricates the joint and nourishes the cartilage."],
[4, "Can a muscle push?", ["No: muscles only pull by contracting, so they work in opposing pairs", "Yes: the triceps pushes the arm straight", "Only the biceps pushes", "Only the heart pushes"], "Pull only.", "Muscles can only contract (pull). The triceps contracts to straighten the arm."]
]);
KB("t17s1", [
[2, "What does 'negative' mean in negative feedback?", ["The response reverses the change", "The body responds badly to the change, making the person feel unwell", "The level always falls, whether it was too high or too low", "Nothing happens, because the body ignores small changes"], "Opposite.", "A change from the set point triggers a response that reverses it."],
[3, "What does insulin do?", ["It stimulates liver and muscle cells to take up glucose and convert it into glycogen", "It converts glucose into glycogen itself", "It raises blood glucose", "It digests glucose"], "Hormones are messengers.", "Insulin is a messenger: it stimulates liver cells to convert glucose to glycogen. It doesn't do the converting.", "Write 'insulin stimulates liver cells to…'."],
[3, "Which organ detects a change in blood glucose?", ["The pancreas", "The liver", "The kidney", "The stomach"], "The control centre.", "Cells in the pancreas (islets) detect glucose level and release insulin or glucagon. The liver is an effector."],
[4, "In type 2 diabetes, what is wrong?", ["Insulin is made but body cells are insensitive to it", "No insulin is made", "Too much glucagon is made", "The liver has no glycogen"], "Type 1 vs type 2.", "Type 1: too little or no insulin. Type 2: cells don't respond properly to insulin."],
[4, "Why can't insulin be taken as a tablet?", ["It would be digested", "It is too sweet, so the tablet would taste unpleasant", "It dissolves in water, so it would wash out of the body", "Tablets act too slowly to control blood glucose"], "What is insulin made of?", "Insulin is a protein; swallowing it would let proteases digest it, so it is injected."],
[3, "Which is correct?", ["Glucagon is a hormone; glycogen is a stored carbohydrate", "Glucagon and glycogen are the same", "Glycogen is a hormone", "Glucagon is stored in the liver"], "Similar names, different things.", "Glucagon (hormone) stimulates liver cells to break down glycogen (storage carbohydrate) into glucose."]
]);
KB("t17s2", [
[3, "Why is body temperature kept near 37 °C?", ["To keep enzymes working steadily", "To keep the skin soft and moist", "To make more sweat for cooling", "To store energy as fat under the skin"], "Enzymes.", "Enzymes work best near 37 °C, so a steady temperature keeps metabolism steady."],
[4, "Does homeostasis keep the body EXACTLY constant?", ["No: levels fluctuate within a narrow range around the set point", "Yes, exactly constant", "It keeps levels always rising", "It only works at night"], "A narrow range.", "Negative feedback keeps levels close to the set point, fluctuating within a narrow range."]
]);
KB("t18s1", [
[2, "What is a population?", ["All the organisms of one species living in an area", "All the species in an area", "The place where an organism lives", "The non-living factors"], "One species.", "A population is one species; a community is all the populations in an area."],
[3, "Two species need the same limited food. Which relationship is this?", ["Competition (− / −)", "Mutualism (+ / +)", "Commensalism (+ / 0)", "Predation (+ / −)"], "Both lose out.", "Competition harms both species because the resource is limited."],
[3, "Which relationship is shown by barnacles living on a whale?", ["Commensalism", "Parasitism: the barnacles feed on the whale's blood and harm it", "Mutualism: both the barnacles and the whale benefit from living together", "Competition: the barnacles and the whale compete for the same food"], "+ / 0.", "The barnacles get a home and food; the whale is not harmed."],
[4, "Why does a predator population rise AFTER the prey population rises?", ["More food becomes available, so more predators survive and reproduce, which takes time", "Predators eat more when there are fewer prey", "Prey attract predators with smells", "Both rise at exactly the same time"], "The lag.", "More prey ➔ more food ➔ more predator offspring survive. Reproduction takes time, so there is a lag."]
]);
KB("t18s2", [
[2, "Where does a food chain start?", ["With a producer", "With the sun", "With a decomposer", "With a herbivore"], "The sun is the energy source.", "Food chains start with a producer. The sun is the energy source, not part of the chain."],
[3, "Why is less energy available at each higher trophic level?", ["Energy is lost as heat in respiration, and in faeces, excretory products and uneaten parts", "Energy is used up by each organism, so there is none left over", "Energy is destroyed in respiration, so less passes to the next level", "Energy is recycled by decomposers back to the producers instead"], "Name the loss routes.", "Energy is lost as heat, and in faeces, excretory products and uneaten parts. Only a small fraction passes on.", "Never write 'energy is used up'."],
[3, "Which bacteria convert ammonium compounds into nitrates?", ["Nitrifying bacteria", "Nitrogen-fixing bacteria", "Denitrifying bacteria", "Decomposers"], "Nitr-ify ➔ nitr-ate.", "Nitrifying bacteria: ammonium ➔ nitrite ➔ nitrate. Nitrogen-fixing bacteria change N₂ into ammonium."],
[4, "Which process makes the soil POORER in nitrates?", ["Denitrification, in poorly aerated soil", "Nitrification", "Nitrogen fixation", "Decomposition"], "N₂ gas escapes.", "Denitrifying bacteria turn nitrates into nitrogen gas, removing nitrogen from the soil."],
[4, "Why can a pyramid of biomass in the sea be inverted?", ["Phytoplankton reproduce very fast (high turnover), so a small biomass supports more zooplankton", "Energy is gained at each level, so higher levels can have more biomass", "Zooplankton are producers, so they belong at the bottom of the pyramid", "Phytoplankton are very large, so a few of them weigh a lot"], "Turnover rate.", "At any moment phytoplankton biomass is small, but they reproduce so fast that they can support a larger zooplankton biomass."],
[3, "Is energy recycled in an ecosystem?", ["No: energy flows one way", "Yes, just like carbon, energy goes round and round the ecosystem", "Yes, decomposers recycle the energy back to the plants in the soil", "Only in the sea, where energy is recycled by plankton and fish"], "Energy flows, materials cycle.", "Energy enters as light and leaves as heat. Carbon and nitrogen are recycled."]
]);
KB("t18s3", [
[3, "Which method is best for estimating a population of grasshoppers?", ["Mark-and-recapture", "Quadrat", "Line transect", "Counting every individual"], "They move fast.", "Mark-and-recapture is used for mobile animals: population = x × y ÷ z."],
[4, "30 snails were marked and released. Later, 40 were caught and 10 of them were marked. Estimate the population.", ["120", "70", "30", "400"], "x × y ÷ z.", "Population = 30 × 40 ÷ 10 = 120."],
[3, "Why are quadrats placed randomly and many times?", ["So the sample is representative and the result reliable", "To save time", "To find the biggest plant", "Because one throw is enough"], "Avoid bias.", "Random, repeated quadrats avoid bias; taking a mean gives a more reliable result."],
[4, "What are the pioneer organisms in PRIMARY succession on bare rock?", ["Lichens", "Grasses", "Trees", "Shrubs"], "No soil yet.", "Lichens colonise bare rock, help break it down and add organic matter, so soil forms for mosses, then grasses."]
]);
KB("t19s1", [
[2, "In malaria, what is the mosquito?", ["The vector that carries the pathogen", "The pathogen", "The host that becomes ill", "The antibiotic"], "The driver, not the culprit.", "The mosquito is the vector. The pathogen is the protist Plasmodium."],
[3, "Why don't antibiotics work against viruses?", ["Viruses have no cell wall and no metabolism of their own for antibiotics to attack", "Viruses are too big", "Viruses are killed by the immune system first", "Antibiotics only work in the lungs"], "What do antibiotics target?", "Antibiotics attack bacterial cell walls, membranes or enzymes. Viruses have none of these."],
[4, "How does antibiotic resistance spread?", ["Resistant bacteria survive and multiply", "Antibiotics cause the bacteria to mutate into resistant forms", "The patient's body becomes resistant to the antibiotic over time", "Each bacterium learns to resist the antibiotic after a few doses"], "Selection pressure.", "Resistant bacteria already exist. The antibiotic selects them, so their proportion increases. Bacteria, not people, become resistant."],
[3, "Why does penicillin not harm human cells?", ["Human cells have no cell wall", "Human cells are too big", "Penicillin can't enter the blood", "Human cells make penicillin"], "What does penicillin stop being made?", "Penicillin stops bacterial cell walls forming, so bacteria burst by osmosis. Human cells have no cell wall."],
[4, "Clearing stagnant water in flowerpots helps prevent dengue. Why?", ["It removes mosquito breeding places, so fewer vectors spread the virus", "It kills the dengue virus in people", "It is a vaccine", "It stops bacteria growing"], "Break the transmission route.", "Aedes mosquitoes breed in stagnant water. Fewer mosquitoes (vectors) ➔ less transmission."]
]);
KB("t19s2", [
[2, "Which cells release antibodies?", ["Plasma cells, formed from B cells", "Phagocytes", "Killer T cells", "Red blood cells"], "B cells change first.", "Activated B cells become plasma cells, which release antibodies."],
[3, "How do antibodies help destroy bacteria?", ["They cause agglutination (clumping) so phagocytes engulf them, cause lysis or neutralise toxins", "They kill bacteria directly like a weapon", "They eat the bacteria", "They are a type of white blood cell"], "Handcuffs and labels.", "Antibodies bind to antigens: agglutination helps phagocytosis; they also cause lysis and act as antitoxins.", "Never write 'antibodies kill bacteria'."],
[4, "Why is the secondary immune response faster and stronger?", ["Memory cells recognise the antigen and quickly divide into plasma cells", "Antibodies from the first infection are still at a high level", "The pathogen is weaker the second time", "Phagocytes learn the pathogen"], "Memory cells.", "Memory cells recognise the same antigen, divide and differentiate quickly: shorter lag, more antibodies, longer-lasting."],
[4, "Why does an antivenom (serum) give only short-term protection?", ["Ready-made antibodies, no memory cells", "It contains weakened venom, so the body makes its own antibodies slowly", "It makes memory cells that die after a few weeks", "It only works in children, whose immune systems are still developing"], "Vaccine vs serum.", "Serum = passive immunity: immediate but short, because no memory cells form."],
[3, "Which is a non-specific defence?", ["The skin", "Antibodies", "Memory B cells", "Killer T cells"], "Works against everything.", "Skin, mucus, lysozyme and phagocytosis act against all pathogens. Lymphocytes give specific defence."],
[4, "What does HIV attack, and why does this cause AIDS?", ["Helper T cells", "Red blood cells, so less oxygen reaches the immune system", "Phagocytes only, so bacteria can no longer be engulfed", "The skin, so pathogens can enter the body more easily"], "Helpers activate the others.", "HIV destroys helper T cells, which normally activate B and killer T cells, so the immune system fails."]
]);
KB("t19s3", [
[2, "What is cancer?", ["Uncontrolled division after mutations", "Uncontrolled meiosis, which makes too many gametes in the body", "An infection caught from other people, like a cold", "A lack of vitamins, which stops cells dividing normally"], "Mitosis out of control.", "Mutations in genes controlling cell division ➔ uncontrolled mitosis ➔ tumour. Malignant tumours invade and metastasise."],
[3, "Is cancer infectious?", ["No", "Yes, because it spreads around the body, it can spread between people", "Only lung cancer is infectious, as it spreads in coughs", "Yes, by droplets, like the common cold"], "Spread within vs between.", "Metastasis spreads cancer inside one body. Cancer itself is non-infectious."],
[3, "How does tar in cigarette smoke increase the risk of lung cancer?", ["Tar is a carcinogen that induces mutations in airway cells", "Tar blocks the air sacs", "Tar raises the heart rate", "Tar lowers oxygen in the blood"], "Carcinogen ➔ mutation.", "Tar causes mutations in the DNA of airway cells, which can lead to uncontrolled cell division."],
[4, "Which statement about a benign tumour is correct?", ["It is enclosed and does not invade or spread", "It always spreads to other organs", "It is cancer", "It is caused by bacteria"], "Benign = kind.", "Benign tumours stay enclosed. Only malignant tumours invade nearby tissue and metastasise."],
[5, "Data show that smokers have more heart disease. Why is this alone not enough to prove smoking causes it?", ["Correlation is not cause", "Graphs of this kind are always wrong, because they leave out too many people", "Heart disease is infectious, so smokers might just catch it from each other", "Smokers are usually younger, so they are more likely to have heart disease"], "Correlation vs cause.", "Other factors (diet, exercise, genes) may differ. We need a mechanism, e.g. carbon monoxide lowers O₂ transport; nicotine causes clots."]
]);
