
/* 🎬 Media questions, part 1: Topics 1–5. Object entries for KH() (see khMedia() in q_h0.js):
   case files, virtual labs (scenes / animations), pick-the-graph, graph detective, sort it, tap it. */

/* ---------- Topic 1: Molecules of Life ---------- */
KH("t1s1", [
{ f: "G", k: "d", b: 5, q: "Energy is added at a steady rate to a block of ice at −10 °C until it has all boiled away. Which graph shows its temperature?", gch: [{ pts: [[0, -10], [1, 0], [3, 0], [5, 100], [8, 100]], smooth: false }, { pts: [[0, -10], [8, 120]], smooth: false }, { pts: [[0, -10], [1, 0], [5, 100], [8, 100]], smooth: false }, { pts: [[0, -10], [1, 0], [2, -5], [5, 100], [8, 100]], smooth: false }], gax: ["energy added", "temperature"], choices: ["Rises, stays flat while melting at 0 °C, rises, then stays flat while boiling at 100 °C", "A straight line all the way up", "No pause at 0 °C, only at 100 °C", "Dips below 0 °C again after melting starts"], why: ["Ignores the energy used to break hydrogen bonds when melting and boiling.", "Melting ice also absorbs energy without warming.", "Temperature never falls while energy is being added."], hint: "Where is energy used to break bonds instead of raising temperature?", explain: "While ice melts and while water boils, the energy breaks hydrogen bonds instead of raising the temperature, so the graph has two flat sections. The long flat section at 100 °C shows water's high latent heat of vaporisation, which is why sweating cools us so well." },
{ f: "S", k: "c", b: 5, q: "Sort each fact by the property of water that best explains it.", bins: ["Good solvent", "High specific heat capacity", "High latent heat of vaporisation"], items: [["Blood plasma carries glucose and urea", 0], ["Sweating cools you down", 2], ["A lake's temperature hardly changes between day and night", 1], ["Minerals reach the leaves in xylem sap", 0], ["A dog pants to cool down on a hot day", 2], ["Your body temperature stays steady when a room warms up quickly", 1]], hint: "Dissolving, warming up, or evaporating?", explain: "Solvent: substances dissolve and are carried (plasma, sap). Specific heat capacity: a lot of energy is needed to warm water, so temperature stays stable. Latent heat of vaporisation: evaporating water removes a lot of heat (sweating, panting)." }
]);
KH("t1s2", [
{ f: "D", k: "d", b: 5, q: "A student made a calibration graph by testing known glucose solutions with Benedict's solution. Juice Q, tested in the same way, gave 0.6 g of precipitate. What is its glucose concentration?", chart: { x: [0, 2, 0.5, "glucose concentration / %"], y: [0, 1, 0.2, "precipitate / g"], series: [{ pts: [[0, 0], [0.5, 0.25], [1, 0.5], [1.5, 0.75], [2, 1]], smooth: false, dots: true }] }, choices: ["1.2%", "0.6%", "3.0%", "It can't be found without heating for longer"], why: ["0.6 is the precipitate mass (y). Go across to the line, then down to the x-axis.", "That's off the scale; 0.6 g is inside the calibrated range.", "The calibration graph gives the answer, as long as the method was the same."], hint: "Find 0.6 g on the y-axis, go across to the line, then down.", explain: "Reading across from 0.6 g meets the line at 1.2% glucose. A calibration graph turns a measurement (mass of precipitate) into the value you want (concentration)." },
{ f: "K", k: "i", b: 6, q: "An 'energy drink' says 'no added sugar' on its label. A food lab tests it. What does the evidence show?", case: [["🧪", "Benedict's test", "Stays blue."], ["🧪", "Boiled with acid, neutralised, then Benedict's", "Brick-red."], ["🧪", "Iodine test", "Stays yellow-brown."], ["📋", "Ingredients", "Includes 'sugar cane extract'."]], choices: ["It contains a non-reducing sugar, such as sucrose, which the acid broke down into reducing sugars", "It contains no sugar at all", "It contains starch", "The acid itself turns Benedict's brick-red"], why: ["The acid-boiled test turned brick-red, so sugar was there, just not reducing sugar.", "Iodine stayed yellow-brown: no starch.", "The acid was neutralised; a control with acid alone would stay blue."], hint: "Why would boiling with acid change the result?", explain: "Sucrose (from sugar cane) is not a reducing sugar, so the first test is blue. Boiling with acid hydrolyses it into glucose and fructose, which are reducing sugars. 'No ADDED sugar' can still mean plenty of sugar!" }
]);
KH("t1s3", [
{ f: "S", k: "c", b: 5, q: "Sort each statement: is it true of DNA only, RNA only, or both?", bins: ["DNA only", "RNA only", "Both"], items: [["Contains the base uracil", 1], ["Two strands held together by base pairs", 0], ["Contains adenine, guanine and cytosine", 2], ["Contains the sugar deoxyribose", 0], ["Made of nucleotides", 2], ["Carries a copy of one gene to a ribosome", 1]], hint: "Think T vs U, one strand vs two.", explain: "DNA: double-stranded, deoxyribose, thymine. RNA: single-stranded, ribose, uracil; mRNA carries a gene's code to the ribosome. Both are made of nucleotides with A, G and C." },
{ f: "K", k: "c", b: 6, q: "A boy is allergic to raw egg but can safely eat cake made with egg. Which explanation fits ALL the evidence?", case: [["👦", "Patient", "Rash and swelling after eating raw or lightly cooked egg."], ["🔬", "Lab finding", "His antibodies bind to one specific 3D shape on an egg protein."], ["🍰", "Cake", "Baked at 180 °C for 30 minutes. No reaction."]], choices: ["Baking denatures the egg protein, changing the 3D shape his antibodies recognise", "Baking breaks the egg protein down into amino acids", "The sugar in the cake neutralises the allergy", "He has grown out of his allergy"], why: ["Heat breaks the bonds that hold the shape, not the peptide bonds.", "There's no evidence for this; shape is the key.", "Raw egg still triggers it."], hint: "Antibodies recognise SHAPE.", explain: "Antibodies bind to a specific shape. Long, hot baking unfolds (denatures) the protein, so the shape is lost. (Doctors test this carefully: never try it at home!)" }
]);

/* ---------- Topic 2: Cellular Organisation ---------- */
KH("t2s1", [
{ f: "V", k: "d", b: 5, q: "At ×400, one eyepiece graticule unit equals 2.5 µm. Use the picture: how long is this cell?", scene: { kind: "graticule", from: 22, to: 68 }, choices: ["115 µm", "46 µm", "170 µm", "18.4 µm"], why: ["That's the number of graticule units. Multiply by 2.5 µm.", "That used the right-hand reading (68) instead of the difference (68 − 22).", "That divided by 2.5 instead of multiplying."], hint: "Units covered = right edge − left edge.", explain: "The cell spans 68 − 22 = 46 units. 46 × 2.5 µm = 115 µm." },
{ f: "G", k: "d", b: 5, q: "The same slide is viewed at higher and higher magnification. Which graph shows the number of cells visible in the field of view?", gch: [{ pts: [[40, 120], [100, 48], [200, 12], [400, 3]] }, { pts: [[40, 3], [400, 120]] }, { pts: [[40, 60], [400, 60]], smooth: false }, { pts: [[40, 120], [400, 0]], smooth: false }], gax: ["magnification", "cells seen"], choices: ["Falls steeply at first, then levels off near zero", "Rises", "Stays the same", "Falls in a straight line to zero"], why: ["Higher magnification shows a SMALLER area, so fewer cells fit.", "The area you see shrinks as you zoom in.", "The visible area falls with the square of the magnification, so the drop is steep at first, not straight."], hint: "Double the magnification: what happens to the AREA you can see?", explain: "Doubling magnification halves the width AND the height of the field, so you see a quarter of the area. Cell numbers fall steeply at first." }
]);
KH("t2s2", [
{ f: "D", k: "d", b: 6, q: "Pancreas cells were given radioactive amino acids for a few minutes, and the radioactivity in different parts of the cell was tracked. What route do the secreted enzymes take?", chart: { x: [0, 60, 10, "time after label / min"], y: [0, 100, 20, "radioactivity / %"], series: [{ pts: [[0, 0], [5, 90], [15, 40], [30, 10], [60, 2]], c: G_BLUE, lbl: "rough ER", lx: 7, ly: 95 }, { pts: [[0, 0], [5, 10], [20, 70], [35, 30], [60, 5]], c: G_GREEN, lbl: "Golgi", lx: 22, ly: 78 }, { pts: [[0, 0], [15, 5], [30, 40], [45, 75], [60, 60]], c: PINK, lbl: "vesicles", lx: 46, ly: 86 }] }, choices: ["Rough ER → Golgi apparatus → secretory vesicles", "Golgi apparatus → rough ER → vesicles", "Vesicles → Golgi apparatus → rough ER", "The enzymes are made in the Golgi apparatus"], why: ["The Golgi peak comes AFTER the rough ER peak.", "That reverses the order of the peaks.", "The label appears in the rough ER first, where ribosomes make protein."], hint: "Follow the order of the peaks.", explain: "The label peaks first in the rough ER (protein made on ribosomes), then the Golgi (modified and packaged), then vesicles (carried to the membrane and secreted). This is how scientists worked out the secretory pathway." },
{ f: "S", k: "c", b: 5, q: "Sort each job to the organelle that does it.", bins: ["Mitochondrion", "Rough ER", "Golgi apparatus", "Chloroplast"], items: [["Releases energy by aerobic respiration", 0], ["Makes proteins on its ribosomes", 1], ["Packages proteins into vesicles for secretion", 2], ["Traps light energy to make glucose", 3], ["Found in large numbers in muscle and sperm cells", 0], ["Modifies proteins before they leave the cell", 2]], hint: "Energy, make, package, light.", explain: "Mitochondria release energy (so they're plentiful in active cells); rough ER makes proteins; the Golgi modifies and packages them; chloroplasts photosynthesise." }
]);
KH("t2s3", [
{ f: "K", k: "c", b: 6, q: "A new drug is being tested. Will it treat flu, which is caused by a virus?", case: [["💊", "Drug X", "Blocks the enzyme that builds bacterial cell walls."], ["🧪", "Test 1", "Kills Staphylococcus bacteria."], ["🧪", "Test 2", "No effect on yeast or on human cells."], ["🦠", "Flu virus", "A protein coat around genetic material; reproduces inside human cells."]], choices: ["No: viruses have no cell wall and use the host's cells, so drug X has nothing to target", "Yes, because it kills microbes", "No, because viruses have thicker cell walls", "Yes, but only at a higher dose"], why: ["It targets bacterial cell walls specifically; viruses aren't cells.", "Viruses have no cell walls at all.", "There is no target at any dose."], hint: "What does drug X attack, and does a virus have it?", explain: "Drug X works like penicillin. Viruses have no cell wall (or cell machinery of their own), which is why antibiotics don't treat viral infections." },
{ f: "S", k: "c", b: 5, q: "Sort each feature: prokaryotic cells, eukaryotic cells, or both?", bins: ["Prokaryotic only", "Eukaryotic only", "Both"], items: [["A nucleus surrounded by a membrane", 1], ["Ribosomes", 2], ["DNA as a circular loop free in the cytoplasm", 0], ["Mitochondria", 1], ["A cell membrane", 2], ["Small extra rings of DNA called plasmids", 0]], hint: "Prokaryotes have no membrane-bound organelles.", explain: "All cells have a membrane, cytoplasm, DNA and ribosomes. Only eukaryotes have a nucleus and membrane-bound organelles; prokaryotes have a circular chromosome and often plasmids." }
]);

/* ---------- Topic 3: Movement Across Membranes ---------- */
KH("t3s1", [
{ f: "P", k: "d", b: 5, q: "Agar cubes model cells. Suppose a cell survives only if oxygen reaches its centre within 20 minutes. Tap the SMALLEST cube that would NOT survive.", tap: { chart: { x: [1, 4, 1, "side of cube / cm"], y: [0, 60, 15, "time to reach centre / min"], series: [{ pts: [[1, 4], [2, 15], [3, 34], [4, 60]], dots: true }] }, want: 2 }, hint: "Find where the time first goes above 20 minutes.", explain: "The 2 cm cube takes 15 min (fine); the 3 cm cube takes 34 min (too slow). As size increases, SA:V falls and diffusion distance rises, so large organisms need transport systems." },
{ f: "K", k: "c", b: 6, q: "Two patients both have low blood oxygen. Which pair of explanations is correct?", case: [["👤", "Patient A", "Pneumonia: some alveoli are filled with fluid."], ["👤", "Patient B", "Emphysema: alveolar walls have broken down into a few large air sacs."], ["🩸", "Both", "Blood oxygen below normal; breathing rate raised."]], choices: ["A: a longer diffusion distance through the fluid. B: a much smaller surface area", "A: a smaller surface area. B: thicker alveolar walls", "Both: no air can enter their lungs", "A: less oxygen in the air. B: breathing too fast"], why: ["Emphysema doesn't thicken the walls; it destroys them, cutting the surface area.", "Air still enters; it's the exchange that fails.", "The air is normal; the lungs are the problem."], hint: "Use the factors that affect diffusion rate.", explain: "Fluid adds distance for oxygen to diffuse through; broken alveoli leave less surface. Both reduce the rate of diffusion into the blood." }
]);
KH("t3s2", [
{ f: "V", k: "d", b: 5, q: "Onion cells were left in 0.45 M sucrose for 30 minutes. Count the plasmolysed cells (contents pulled away from the wall). What does the result suggest?", scene: { kind: "plasmo", cells: "tptpptttpptpttpptp" }, choices: ["The cell sap has about the same water potential as 0.45 M sucrose", "The cell sap is far more concentrated than 0.45 M", "The sucrose entered the cells", "Half the cells are dead"], why: ["If so, no cells would be plasmolysed.", "Membranes are partially permeable; water left the cells instead.", "Plasmolysis is reversible: it shows water loss, not death."], hint: "Count, then work out the percentage.", explain: "9 of 18 cells (50%) are plasmolysed. When about half the cells are plasmolysed, the solution's water potential roughly equals the average cell sap's." },
{ f: "G", k: "d", b: 6, q: "Red blood cells are placed in salt solutions of increasing concentration. Which graph shows the percentage of cells that burst?", gch: [{ pts: [[0, 100], [0.3, 95], [0.45, 50], [0.6, 5], [0.9, 0], [1.2, 0]] }, { pts: [[0, 0], [0.6, 50], [1.2, 100]] }, { pts: [[0, 50], [1.2, 50]], smooth: false }, { pts: [[0, 100], [0.6, 0], [1.2, 100]] }], gax: ["salt concentration", "cells burst"], choices: ["High in very dilute solutions, falling to zero", "Rises as the solution gets saltier", "Stays the same", "High at both ends, low in the middle"], why: ["Cells burst in DILUTE solutions, where water enters by osmosis.", "Concentration changes the direction of water movement.", "In concentrated solutions cells shrink; they don't burst."], hint: "When does water rush IN?", explain: "In dilute solutions water enters by osmosis and the cells (with no wall) burst. Above about 0.9% salt (like blood plasma), they don't; in stronger solutions they shrink." }
]);
KH("t3s3", [
{ f: "S", k: "c", b: 5, q: "Sort each example by how the substance moves.", bins: ["Diffusion", "Osmosis", "Active transport", "Phagocytosis"], items: [["Oxygen entering red blood cells in the lungs", 0], ["Water entering a root hair cell", 1], ["Glucose taken up from the gut against its gradient", 2], ["A white blood cell engulfing a bacterium", 3], ["Nitrate ions taken into roots from dilute soil water", 2], ["Carbon dioxide leaving a leaf at night", 0]], hint: "Water only? Against a gradient? Whole particles?", explain: "Diffusion: down a gradient, no energy. Osmosis: water across a partially permeable membrane. Active transport: against a gradient, using ATP. Phagocytosis: engulfing large particles." },
{ f: "K", k: "c", b: 6, q: "Seabirds drink seawater but don't dehydrate. Which explanation fits ALL the evidence?", case: [["🐦", "Seabird", "Drinks seawater (about 3.5% salt)."], ["👃", "Salt glands", "Release fluid TWICE as salty as seawater out of the nostrils."], ["⚡", "Gland cells", "Packed with mitochondria."]], choices: ["The gland cells actively transport salt against its concentration gradient, using lots of ATP from respiration", "Salt diffuses out because seawater is saltier than blood", "Osmosis moves the salt out of the glands", "The mitochondria store the extra salt"], why: ["The fluid is SALTIER than seawater, so salt moves against the gradient.", "Osmosis moves water, not salt.", "Mitochondria release energy; they don't store salt."], hint: "Which direction does the salt move compared with its gradient?", explain: "Making fluid saltier than seawater means moving salt against its gradient: active transport, powered by ATP from the many mitochondria." }
]);

/* ---------- Topic 4: Cell Cycle and Division ---------- */
KH("t4s1", [
{ f: "V", k: "d", b: 5, q: "This root-tip view shows 30 cells. Count the cells that are dividing (any stage of mitosis). What is the mitotic index?", scene: { kind: "mitosis", counts: { I: 22, P: 3, M: 2, A: 2, T: 1 }, seed: 7 }, choices: ["About 27%", "About 73%", "8%", "About 7%"], why: ["That's the percentage NOT dividing (in interphase).", "8 is the number of cells; divide by 30 to get a percentage.", "That counts only one stage. Every stage of division counts."], hint: "Dividing cells ÷ total cells × 100.", explain: "Dividing: 3 prophase + 2 metaphase + 2 anaphase + 1 telophase = 8. 8 ÷ 30 × 100 ≈ 27%. Most cells are in interphase because it is the longest stage." },
{ f: "P", k: "s", b: 5, q: "Tap a cell in ANAPHASE.", tap: { scene: { kind: "mitosis", counts: { I: 20, P: 3, M: 3, A: 2, T: 2 }, seed: 4 }, want: "A" }, hint: "Chromatids are being pulled to opposite ends.", explain: "In anaphase, the chromatids separate and move to opposite poles, so you see two groups of V-shapes at the ends. Metaphase has them lined up in the middle; telophase has two new nuclei." }
]);
KH("t4s2", [
{ f: "D", k: "d", b: 6, q: "Down syndrome is caused by an extra chromosome 21, which comes from a gamete. Which conclusion is best supported?", chart: { x: [20, 45, 5, "mother's age / years"], y: [0, 3, 0.5, "chance of Down syndrome / %"], series: [{ pts: [[20, 0.07], [25, 0.08], [30, 0.1], [35, 0.3], [40, 1], [45, 3]], dots: true }] }, choices: ["The chance rises steeply after about 35, which fits more errors in chromosome separation in meiosis in older eggs", "Mothers under 30 can't have a baby with Down syndrome", "Down syndrome is caused by errors in mitosis in the baby", "At 45 the chance is about 3%"], why: ["The chance is low, not zero.", "The extra chromosome comes from a gamete, made by meiosis.", "A true reading, but it doesn't explain the pattern."], hint: "Describe the shape, then link it to how gametes are made.", explain: "If homologous chromosomes or chromatids fail to separate in meiosis, a gamete gets an extra chromosome 21. The data show this happens more often as eggs age." },
{ f: "T", k: "d", b: 6, q: "Twin study. Which trait is MOST affected by the environment?", table: [["Trait", "Identical twins alike (%)", "Non-identical twins alike (%)"], ["Blood group", "100", "64"], ["Height (within 3 cm)", "92", "48"], ["Body mass (within 3 kg)", "68", "46"]], choices: ["Body mass, because identical twins (same genes) still differ most often", "Blood group, because non-identical twins differ", "Height, because it shows continuous variation", "Non-identical twins match 46% for body mass"], why: ["Identical twins always match (100%), so the environment has no effect.", "Identical twins match 92%: mostly genetic.", "A true reading, but not an answer."], hint: "Identical twins share all their genes. Where do THEY differ?", explain: "Differences between identical twins must come from the environment. They differ most for body mass (only 68% alike), so diet and exercise matter most there." }
]);
KH("t4s3", [
{ f: "S", k: "c", b: 5, q: "Sort each statement: mitosis, meiosis, or both?", bins: ["Mitosis", "Meiosis", "Both"], items: [["Produces genetically identical cells", 0], ["Halves the chromosome number", 1], ["Involves crossing over", 1], ["DNA is copied beforehand", 2], ["Used to grow and repair tissues", 0], ["Spindle fibres pull chromosomes apart", 2]], hint: "Identical vs different; same number vs half.", explain: "Mitosis: identical diploid cells for growth and repair. Meiosis: crossing over and halving to make varied gametes. Both copy DNA first and use spindles." },
{ f: "G", k: "d", b: 6, q: "Which graph shows the DNA content of a cell during MEIOSIS?", gch: [{ pts: [[0, 2], [1, 2], [2, 4], [3, 4], [3.01, 2], [4, 2], [4.01, 1], [5, 1]], smooth: false }, { pts: [[0, 2], [1, 2], [2, 4], [3, 4], [3.01, 2], [5, 2]], smooth: false }, { pts: [[0, 2], [2, 4], [4, 8], [5, 8]], smooth: false }, { pts: [[0, 2], [1, 2], [1.01, 1], [3, 1], [3.01, 0.5], [5, 0.5]], smooth: false }], gax: ["time", "DNA per cell"], choices: ["Doubles, then halves twice, ending at half the start", "Doubles, then halves once, back to the start", "Keeps doubling", "Halves twice without doubling first"], why: ["That's mitosis: one division, back to the starting amount.", "DNA is copied only once before meiosis.", "DNA must be copied first, before the two divisions."], hint: "One copy, two divisions.", explain: "DNA is copied once (2 → 4), then meiosis I halves it (4 → 2) and meiosis II halves it again (2 → 1): gametes have half the DNA of body cells." }
]);

/* ---------- Topic 5: Enzymes and Metabolism ---------- */
KH("t5s1", [
{ f: "K", k: "c", b: 6, q: "A cheese maker uses the enzyme rennet to curdle milk. Which explanation fits all three days?", case: [["🧪", "Rennet", "An enzyme with an optimum of about 40 °C."], ["📅", "Day 1", "Vat at 40 °C: curds form in 30 minutes."], ["📅", "Day 2", "Heater broke; vat at 20 °C: curds take 2 hours."], ["📅", "Day 3", "Vat overheated to 70 °C, then cooled to 40 °C: no curds at all."]], choices: ["Cold slowed it; 70 °C denatured it for good", "At 20 °C the enzyme was denatured, which is why the curds took so long to form", "On day 3 the enzyme was used up by the extra heat, so none was left to work", "Rennet works best at 70 °C, so day 3 should have been the fastest day"], why: ["It still worked on day 2, just slowly.", "Enzymes aren't used up; the heat changed its shape permanently.", "Its optimum is about 40 °C."], hint: "Which change can be reversed, and which can't?", explain: "Cold slows enzymes reversibly (less kinetic energy, fewer collisions). Heat above the optimum denatures them permanently, so cooling doesn't restore activity." },
{ f: "P", k: "d", b: 5, q: "Tap the FIRST point where adding more substrate no longer increases the rate.", tap: { chart: { x: [0, 6, 1, "substrate concentration"], y: [0, 60, 10, "rate"], series: [{ pts: [[0, 0], [1, 25], [2, 42], [3, 50], [4, 50], [6, 50]], dots: true }] }, want: 3 }, hint: "Where does the line become flat?", explain: "From 3 units onwards the rate stays at 50: all active sites are busy, so enzyme concentration is now the limiting factor." }
]);
KH("t5s2", [
{ f: "V", k: "d", b: 5, q: "Pieces of liver were put in hydrogen peroxide at three temperatures. The liver's catalase releases oxygen bubbles. Watch for one loop of the clock: which conclusion fits?", scene: { kind: "bubbles", item: "liver", tubes: [{ lbl: "10 °C", every: 2.5 }, { lbl: "35 °C", every: 1 }, { lbl: "70 °C", every: 10 }] }, choices: ["Catalase works fastest near 35 °C; at 70 °C it is mostly denatured", "The rate rises with temperature all the way", "At 10 °C the enzyme is denatured", "Tube A gives 10 bubbles every 10 s"], why: ["Tube C (70 °C) is the slowest.", "It still works at 10 °C, just slowly.", "Misreading: tube A gives about 4; tube B gives 10."], hint: "Count bubbles per 10 s for each tube.", explain: "About 4, 10 and 1 bubbles per 10 s. The rate rises from 10 to 35 °C (more collisions), then falls at 70 °C as the enzyme denatures." },
{ f: "G", k: "d", b: 5, q: "Which graph shows the effect of pH on pepsin, a stomach protease?", gch: [{ pts: [[1, 40], [2, 100], [3, 70], [4, 30], [6, 5], [8, 0], [10, 0]] }, { pts: [[1, 0], [4, 20], [7, 100], [10, 20]] }, { pts: [[1, 0], [10, 100]], smooth: false }, { pts: [[1, 0], [6, 10], [8.5, 100], [10, 50]] }], gax: ["pH", "rate"], choices: ["A peak at about pH 2", "A peak at pH 7", "Rising steadily with pH", "A peak at about pH 8–9"], why: ["pH 7 suits many enzymes, but not those in the acidic stomach.", "Enzymes have an optimum, not a steady rise.", "That's trypsin, which works in the alkaline small intestine."], hint: "Where does pepsin work?", explain: "Pepsin works in stomach acid, so its optimum is about pH 2. Away from its optimum, the active site's shape changes." }
]);
KH("t5s3", [
{ f: "K", k: "c", b: 6, q: "A customer complains about a biological washing powder. Which explanation covers BOTH complaints?", case: [["😤", "Complaint 1", "Egg stains weren't removed on a 90 °C wash."], ["📦", "Label", "Contains proteases and lipases. Best at 30–40 °C."], ["🧪", "Lab test", "At 40 °C the powder removed 95% of an egg stain."], ["🧶", "Complaint 2", "A wool jumper was damaged after a 40 °C wash with the powder."]], choices: ["At 90 °C the proteases were denatured, so egg protein wasn't digested; at 40 °C working proteases digested the wool, which is also protein", "The powder was out of date, so the enzymes had all stopped working", "The lipases in the powder digested the wool, because wool is made of fat", "Wool always shrinks in warm water, so the enzymes had nothing to do with it"], why: ["The lab test at 40 °C worked fine.", "Wool is protein (keratin); lipases digest fats.", "That ignores why the enzymes matter, and ignores the egg stain."], hint: "What is wool made of?", explain: "Proteases digest any protein they fit, including wool and silk. That's why such labels warn against washing wool, and why very hot washes waste the enzymes." },
{ f: "S", k: "c", b: 5, q: "Sort each description: competitive or non-competitive inhibitor?", bins: ["Competitive", "Non-competitive"], items: [["Has a shape similar to the substrate", 0], ["Binds away from the active site", 1], ["Its effect shrinks when lots of substrate is added", 0], ["Changes the shape of the active site", 1], ["Ethanol given to treat methanol poisoning", 0], ["Heavy metal ions such as mercury", 1]], hint: "Same active site, or somewhere else?", explain: "Competitive inhibitors compete for the active site, so more substrate reduces their effect. Non-competitive inhibitors bind elsewhere and change the active site, so more substrate doesn't help." }
]);
