
/* 🎬 Media questions, part 2: Photosynthesis, Respiration, Genetics, Molecular Genetics (see q_m1.js). */

/* ---------- Topic 6: Photosynthesis ---------- */
KH("t6s1", [
{ f: "G", k: "d", b: 5, q: "Which graph shows how wide the stomata of a typical leaf open over 24 hours on a sunny day?", gch: [{ pts: [[0, 0], [5, 1], [8, 7], [12, 9], [16, 7], [19, 2], [22, 0], [24, 0]] }, { pts: [[0, 9], [6, 9], [12, 9], [18, 9], [24, 9]], smooth: false }, { pts: [[0, 4], [24, 4]], smooth: false }, { pts: [[0, 9], [6, 3], [12, 0], [18, 3], [24, 9]] }], gax: ["time of day (0–24 h)", "stomatal opening"], choices: ["Closed at night, opening in the morning, widest around midday, closing in the evening", "Wide open all day and all night", "Half open all the time", "Widest at midnight, closed at noon"], why: ["Stomata close in the dark, when there's no light for photosynthesis, which saves water.", "Guard cells respond to light, so the opening changes over the day.", "That's the reverse of a typical plant (only some desert plants open at night)."], hint: "Guard cells respond to light.", explain: "In light, guard cells take up solutes and water and open the stomata for CO₂; in the dark they close, reducing water loss when photosynthesis can't happen." },
{ f: "K", k: "c", b: 6, q: "Some desert plants (like pineapple) work differently. Why is this an advantage in a desert?", case: [["🌵", "Stomata", "Open at NIGHT, closed during the day."], ["🌙", "At night", "Takes in CO₂ and stores it as an acid in its vacuoles."], ["☀️", "In the day", "Releases the stored CO₂ inside the leaf for photosynthesis."]], choices: ["Opening stomata in the cool night loses far less water, while CO₂ is still stored for daytime photosynthesis", "It photosynthesises at night instead of the day", "It doesn't need CO₂", "It respires only at night"], why: ["Photosynthesis needs light: only CO₂ uptake happens at night.", "It still needs CO₂; it just takes it in at a different time.", "Respiration happens all the time."], hint: "When is evaporation lowest?", explain: "Night air is cooler and more humid, so open stomata lose much less water. Storing CO₂ separates 'taking in CO₂' from 'using light', a clever adaptation." }
]);
KH("t6s2", [
{ f: "G", k: "d", b: 5, q: "Which graph shows the rate of photosynthesis of a green plant in light of different colours (equal intensity)?", gch: [{ pts: [[400, 60], [450, 90], [500, 40], [550, 15], [600, 40], [650, 85], [700, 20]] }, { pts: [[400, 15], [550, 95], [700, 15]] }, { pts: [[400, 50], [700, 50]], smooth: false }, { pts: [[400, 10], [550, 40], [700, 95]] }], gax: ["colour: blue → green → red", "rate"], choices: ["High in blue and red light, low in green", "Highest in green light", "The same for every colour", "Rising from blue to red"], why: ["Green is mostly reflected, which is why leaves look green.", "Chlorophyll absorbs some colours far better than others.", "Blue light is also strongly absorbed."], hint: "Which colours does chlorophyll absorb?", explain: "The rate follows chlorophyll's absorption: high in blue and red, low in green. This graph is called an action spectrum." },
{ f: "K", k: "c", b: 6, q: "Sun leaves and shade leaves from the same tree were tested. Which explanation of the DIM-light result is best?", case: [["☀️", "Sun leaf", "Small and thick, with several palisade layers."], ["🌳", "Shade leaf", "Large and thin, with more chlorophyll per chloroplast."], ["💡", "Results", "In dim light the shade leaf photosynthesises faster; in bright light the sun leaf is faster."]], choices: ["More chlorophyll and a larger area let the shade leaf trap more of the scarce light", "Shade leaves don't need light", "Sun leaves are damaged by dim light", "Shade leaves have more stomata, so they take in more CO₂"], why: ["All leaves need light to photosynthesise.", "Sun leaves still work in dim light, just more slowly.", "In dim light, LIGHT is the limiting factor, not CO₂."], hint: "What limits photosynthesis in dim light?", explain: "In dim light, light is limiting, so trapping more of it matters. In bright light, the sun leaf's extra palisade cells (and Calvin cycle enzymes) can use more." }
]);
KH("t6s3", [
{ f: "S", k: "c", b: 5, q: "Sort each event: light-dependent reactions or Calvin cycle (light-independent)?", bins: ["Light-dependent", "Calvin cycle"], items: [["Water is split", 0], ["Carbon dioxide is fixed", 1], ["ATP and NADPH are made", 0], ["ATP and NADPH are used", 1], ["Happens on thylakoid membranes", 0], ["Happens in the stroma", 1], ["Oxygen is released", 0]], hint: "Light energy captured vs sugar built.", explain: "The light-dependent reactions (thylakoids) split water, release O₂ and make ATP and NADPH. The Calvin cycle (stroma) uses them to fix CO₂ into sugar." },
{ f: "G", k: "d", b: 6, q: "Dashed line: blue DCPIP being decolourised by chloroplasts in bright light. The experiment is repeated in DIM light. Which pink line shows the new result?", gch: [{ ref: [[0, 100], [2, 50], [4, 20], [6, 5], [8, 0], [10, 0]], pts: [[0, 100], [2, 75], [4, 52], [6, 34], [8, 20], [10, 10]] }, { ref: [[0, 100], [2, 50], [4, 20], [6, 5], [8, 0], [10, 0]], pts: [[0, 100], [1, 40], [2, 10], [4, 0], [10, 0]] }, { ref: [[0, 100], [2, 50], [4, 20], [6, 5], [8, 0], [10, 0]], pts: [[0, 100], [10, 100]], smooth: false }, { ref: [[0, 100], [2, 50], [4, 20], [6, 5], [8, 0], [10, 0]], pts: [[0, 100], [2, 70], [4, 55], [6, 50], [10, 50]] }], gax: ["time", "blue colour left"], choices: ["Falls more slowly", "Falls faster", "Doesn't change at all", "Falls to half, then stops"], why: ["Less light means fewer electrons released per second.", "Dim light still drives some reactions.", "Given time, all the DCPIP would be reduced; dim light only slows it."], hint: "Less light, fewer electrons per second.", explain: "DCPIP accepts electrons released by the light-dependent reactions. In dim light, fewer are released per second, so the blue fades more slowly." }
]);
KH("t6s4", [
{ f: "K", k: "c", b: 6, q: "Rice was grown at today's CO₂ level and at a possible future level. Which explanation fits ALL the results?", case: [["🌍", "Experiment", "Rice grown at 400 ppm and 600 ppm CO₂."], ["🌾", "Result", "Grain yield +15% at 600 ppm, but protein in the grain −8%."], ["🧪", "Note", "The same amount of nitrogen fertiliser was given to both."]], choices: ["More CO₂ was fixed, so more carbohydrate was made, but nitrogen didn't increase, so protein became a smaller share", "Extra CO₂ destroys proteins", "Higher CO₂ closed the stomata, so less photosynthesis happened", "The rice made protein directly from CO₂"], why: ["There's no evidence of this; protein falls as a SHARE of the grain.", "The yield went UP, so photosynthesis increased.", "Protein needs nitrogen as well as carbon."], hint: "What's needed to make carbohydrate vs protein?", explain: "The Calvin cycle fixes more CO₂ into sugars when CO₂ is less limiting. Proteins also need nitrogen, which didn't change, so the grain is 'diluted' in protein. A real concern for future nutrition." },
{ f: "P", k: "d", b: 6, q: "GP (pink line) and RuBP (dots shown below it) were measured in a chloroplast. Tap the FIRST GP measurement taken after the light was switched off.", tap: { chart: { x: [0, 4, 1, "time / min"], y: [0, 20, 5, "amount (units)"], series: [{ pts: [[0, 10], [1, 10], [2, 10], [3, 16], [4, 18]], dots: true, c: PINK, lbl: "GP", lx: 3.3, ly: 19 }, { pts: [[0, 8], [1, 8], [2, 8], [3, 4], [4, 3]], dots: true, c: G_BLUE, lbl: "RuBP", lx: 3.3, ly: 5 }] }, want: 3 }, hint: "When does GP start to build up?", explain: "In the dark, GP can't be turned into sugar (no ATP or NADPH), so it builds up, while RuBP is used but not regenerated. The first sign is at 3 minutes." }
]);
KH("t6s5", [
{ f: "P", k: "d", b: 6, q: "The lower line is at 0.04% CO₂ and the upper line at 0.1% CO₂. On the LOWER line, tap the first point where CO₂ has become the limiting factor.", tap: { chart: { x: [0, 8, 2, "light intensity"], y: [0, 60, 10, "rate of photosynthesis"], series: [{ pts: [[0, 0], [2, 20], [4, 30], [6, 30], [8, 30]], dots: true, c: G_BLUE, lbl: "0.04% CO₂", lx: 5.2, ly: 25 }, { pts: [[0, 0], [2, 20], [4, 38], [6, 50], [8, 54]], dots: true, c: PINK, lbl: "0.1% CO₂", lx: 5.2, ly: 57 }] }, want: 2 }, hint: "Where does more light stop helping on the lower line?", explain: "From light 4 onwards, the lower line is flat: more light gives no gain, but more CO₂ (upper line) does. So CO₂ is limiting from that point." },
{ f: "K", k: "c", b: 6, q: "A tomato grower tests ways to raise winter yield. What do the trial results suggest?", case: [["🍅", "Winter greenhouse", "12 °C, 0.04% CO₂, light at 30% of summer levels."], ["💰", "Options", "Heater (+8 °C), CO₂ burner (to 0.1%), or LED lamps."], ["📊", "Trial", "Each option alone raised yield by about 5%. Heater + lamps together raised it by 30%."]], choices: ["Several factors are limiting at once in winter, so raising only one gives little gain", "CO₂ is the only limiting factor", "The lamps are useless", "Yield can't be increased in winter"], why: ["CO₂ alone gave only 5%.", "The lamps helped a lot when combined with heat.", "It rose by 30% with two changes."], hint: "Why would two together beat each alone?", explain: "When light and temperature are both low, raising one just makes the other limiting. Raising both together lifts the rate much more: limiting factors interact." }
]);
KH("t6s6", [
{ f: "K", k: "i", b: 6, q: "Leaf discs sink in sodium hydrogencarbonate solution, then float as oxygen from photosynthesis collects inside them. What is the best evaluation of this experiment?", case: [["🍃", "Method", "10 leaf discs per cup; time for each to float is recorded."], ["💡", "Lamp at 10 cm", "Mean time to float: 6 min."], ["💡", "Lamp at 30 cm", "Mean time to float: 21 min."], ["🌡️", "Note", "The lamp warmed the water to 31 °C at 10 cm; it stayed at 24 °C at 30 cm."]], choices: ["Light and temperature both changed, so the faster floating can't be put down to light alone", "It proves light is the only limiting factor", "The discs float faster because warm water is less dense", "A hotter lamp should be used"], why: ["Two variables changed at once.", "Floating comes from oxygen inside the discs, not water density.", "That would make the temperature problem worse."], hint: "Did only one variable change?", explain: "Use a heat shield (a beaker of water) or an LED so only light intensity changes. Then the difference can be linked to light." },
{ f: "P", k: "d", b: 5, q: "Hydrogencarbonate indicator measured the CO₂ change around a leaf at different light intensities (positive = CO₂ rising). Tap the compensation point.", tap: { chart: { x: [0, 5, 1, "light intensity"], y: [-10, 10, 5, "CO₂ change"], series: [{ pts: [[0, 8], [1, 4], [2, 0], [3, -4], [4, -7], [5, -8]], dots: true }] }, want: 2 }, hint: "Where is there no net change?", explain: "At the compensation point, photosynthesis uses CO₂ exactly as fast as respiration makes it, so there is no net change (zero)." }
]);

/* ---------- Topic 7: Cellular Respiration ---------- */
KH("t7s1", [
{ f: "V", k: "d", b: 6, q: "Respirometers with germinating seeds and with glass beads (control) ran for 10 minutes. The capillary is 1 mm² in cross-section. Watch where each bead ends. What is the seeds' rate of oxygen uptake?", scene: { kind: "bead", tubes: [{ lbl: "Seeds", mm: 36 }, { lbl: "Glass beads", mm: 4 }], max: 50, mins: 10 }, choices: ["3.2 mm³ per minute", "3.6 mm³ per minute", "32 mm³ per minute", "0.4 mm³ per minute"], why: ["That forgets to subtract the control's movement.", "That's the total in 10 minutes; divide by 10.", "That's only the control's movement."], hint: "Correct for the control, then divide by time.", explain: "36 − 4 = 32 mm moved because of respiration. 32 mm × 1 mm² = 32 mm³ in 10 min, so 3.2 mm³ per minute. The control corrects for temperature and pressure changes." },
{ f: "K", k: "c", b: 6, q: "A dormouse hibernates for 5 months. Which explanation of its mass loss is best?", case: [["❄️", "Body temperature", "Falls from 37 °C to about 5 °C."], ["❤️", "Heart rate", "Falls from about 300 to 10 beats per minute."], ["⚖️", "Over winter", "Loses 40% of its body mass, mostly fat."]], choices: ["It respires stored fat slowly all winter for energy, losing the carbon as CO₂ and some water", "It stops respiring completely", "The cold makes its cells shrink", "Its fat turns into muscle"], why: ["It's alive, so respiration continues, just very slowly.", "Cells don't shrink like that from cold.", "There's no evidence of this; it's using the fat up."], hint: "Where does the mass of the fat go?", explain: "Respiration breaks fat down into CO₂ (breathed out) and water. The cold body slows respiration so the fat store lasts all winter." }
]);
KH("t7s2", [
{ f: "G", k: "d", b: 6, q: "A runner exercises hard from the 2nd to the 8th minute. Which graph shows their oxygen use?", gch: [{ pts: [[0, 1], [2, 1], [3, 4], [8, 4], [9, 2.6], [12, 1.5], [15, 1]] }, { pts: [[0, 1], [2, 1], [3, 4], [8, 4], [8.2, 1], [15, 1]], smooth: false }, { pts: [[0, 2], [15, 2]], smooth: false }, { pts: [[0, 3], [2, 3], [5, 1], [8, 1], [15, 3]] }], gax: ["time (exercise 2–8 min)", "oxygen used"], choices: ["Rises during exercise and stays above resting for a while afterwards", "Drops straight back to resting the moment exercise stops", "Stays the same throughout", "Falls during exercise"], why: ["Extra oxygen is still needed after exercise to break down lactic acid (the oxygen debt).", "Working muscles need more oxygen.", "Muscles use MORE oxygen when working."], hint: "What is repaid after exercise?", explain: "During hard exercise some energy comes from anaerobic respiration, building lactic acid. Afterwards, extra oxygen is used to break it down: the oxygen debt." },
{ f: "S", k: "c", b: 5, q: "Sort each statement: aerobic respiration, anaerobic respiration in muscle, or anaerobic respiration in yeast?", bins: ["Aerobic", "Anaerobic (muscle)", "Anaerobic (yeast)"], items: [["Produces lactic acid", 1], ["Produces ethanol and carbon dioxide", 2], ["Produces carbon dioxide and water", 0], ["Releases the most energy per glucose", 0], ["Used to make bread rise", 2], ["Leads to an oxygen debt", 1]], hint: "Check the products of each.", explain: "Aerobic: CO₂ + water, most energy. Anaerobic in muscle: lactic acid (oxygen debt). Anaerobic in yeast: ethanol + CO₂ (bread, brewing)." }
]);
KH("t7s3", [
{ f: "P", k: "d", b: 6, q: "CO₂ was measured in a sealed greenhouse over 24 hours. Tap the time when photosynthesis FIRST became faster than respiration.", tap: { chart: { x: [0, 24, 6, "time of day / h"], y: [300, 650, 50, "CO₂ / ppm"], series: [{ pts: [[0, 500], [3, 560], [6, 600], [9, 520], [12, 400], [15, 360], [18, 420], [21, 470], [24, 510]], dots: true }] }, want: 2 }, hint: "When does CO₂ stop rising and start falling?", explain: "CO₂ rises all night (respiration only). After about 6 am it falls, which means photosynthesis is using CO₂ faster than respiration makes it." },
{ f: "K", k: "c", b: 6, q: "A bottle garden was sealed in 1972 and watered only once, yet it is still alive. Why does it keep going?", case: [["🫙", "Bottle", "Sealed glass; sits by a sunny window."], ["🌿", "Inside", "Plants, soil and microbes. No animals."], ["⏳", "Age", "Over 50 years with no new air or food added."]], choices: ["Photosynthesis and respiration recycle O₂ and CO₂, decomposers recycle minerals, and light brings in energy from outside", "Grown plants don't need CO₂", "It needs no energy input", "Photosynthesis makes all the water it needs"], why: ["Plants need CO₂ to photosynthesise all their lives.", "Light energy enters through the glass; energy is not recycled.", "Photosynthesis uses water, it doesn't make it overall; water is recycled by transpiration and condensation."], hint: "What is recycled, and what must come in?", explain: "Matter (carbon, oxygen, water, minerals) cycles inside the bottle, but energy flows through: light in, heat out. A mini ecosystem!" }
]);

/* ---------- Basic Genetics ---------- */
KH("t9s1", [
{ f: "G", k: "d", b: 5, q: "A heterozygous tall pea plant (Tt) is crossed with a short plant (tt). Which bar chart shows the expected 100 offspring (tall, short)?", gch: [{ bars: [50, 50] }, { bars: [75, 25] }, { bars: [100, 0] }, { bars: [25, 75] }], gax: ["tall | short", "offspring"], choices: ["50 tall, 50 short", "75 tall, 25 short", "100 tall, 0 short", "25 tall, 75 short"], why: ["That's Tt × Tt.", "That's TT × tt.", "That reverses the ratio."], hint: "Tt gives T or t; tt gives only t.", explain: "Half the offspring are Tt (tall) and half tt (short): a 1 : 1 ratio, typical of a test cross with a heterozygote." },
{ f: "K", k: "c", b: 6, q: "A breeder wants to know if a black cat is BB or Bb (black is dominant to brown). What's the best conclusion?", case: [["🐈‍⬛", "Black cat", "Genotype unknown."], ["🐈", "Mate", "A brown cat."], ["🐾", "Litter", "4 kittens, all black."]], choices: ["Probably BB, but not certain: a Bb cat would have all-black kittens 1 time in 16", "Definitely BB", "Definitely Bb", "The brown cat must be Bb"], why: ["(1/2)⁴ = 1/16, so a Bb parent could still give 4 black kittens.", "No brown kittens appeared, so there's no proof of b.", "Brown is recessive, so a brown cat must be bb."], hint: "What's the chance of 4 black kittens if the cat is Bb?", explain: "Each kitten from Bb × bb has a 1/2 chance of being black, so 4 in a row is 1/16. More kittens would make the conclusion more certain." }
]);
KH("t9s2", [
{ f: "P", k: "s", b: 6, q: "This condition is caused by a DOMINANT allele. Tap a person who MUST be heterozygous.", tap: { scene: { kind: "pedigree", people: [["1", "m", 1, 0, 0], ["2", "f", 0, 0, 1], ["3", "f", 1, 1, 0], ["4", "m", 0, 1, 1], ["5", "m", 0, 1, 2]], pairs: [["1", "2"]], kids: [[0, ["3", "4", "5"]]] }, want: ["1", "3"] }, hint: "Unaffected people are aa. Who passed an a to someone, or got an a from someone?", explain: "Unaffected 4 and 5 are aa, so they each got an a from father 1, who is affected: 1 is Aa. Person 3 is affected but got an a from unaffected mother 2 (aa), so 3 is Aa too." },
{ f: "K", k: "c", b: 6, q: "Two babies may have been mixed up in hospital. Which pairing must be right?", case: [["👶", "Baby X", "Blood group O."], ["👶", "Baby Y", "Blood group AB."], ["👫", "Couple 1", "Both group AB."], ["👫", "Couple 2", "One group A, one group B."]], choices: ["Baby X belongs to couple 2 and baby Y to couple 1", "Baby X belongs to couple 1 and baby Y to couple 2", "Either way is possible", "Neither baby fits either couple"], why: ["AB × AB parents have no i allele, so they can't have a group O child.", "Couple 1 can't have an O baby, so only one way works.", "Couple 2 (Iᴬi × Iᴮi) can have an O baby, and couple 1 can have an AB baby."], hint: "Which couple CAN'T have a group O child?", explain: "An O baby is ii, so both parents need an i allele. AB parents (IᴬIᴮ) have none, so baby X must be couple 2's. Couple 1 can have an AB child (baby Y)." }
]);
KH("t9s3", [
{ f: "D", k: "d", b: 6, q: "The percentage of people carrying the sickle-cell allele was surveyed in three regions. Which conclusion is best supported?", chart: { y: [0, 25, 5, "carriers / %"], bars: { cats: ["None", "Low", "High"], vals: [1, 5, 20], c: "#F2A3A3", xl: "malaria in the region" } }, choices: ["Carriers are most common where malaria is common, consistent with carriers surviving malaria better", "Malaria causes the sickle-cell mutation", "Carriers can't catch malaria at all", "20% are carriers where malaria is high"], why: ["Mutations arise randomly; malaria SELECTS for carriers.", "Carriers are more resistant, not immune.", "A true reading, but not a conclusion."], hint: "Link the pattern to natural selection.", explain: "Where malaria kills many people, carriers survive and reproduce more often, so the allele stays common. Where there's no malaria, it gives no advantage." },
{ f: "S", k: "c", b: 5, q: "Sort each feature: caused by genes only, the environment only, or both?", bins: ["Genes only", "Environment only", "Both"], items: [["ABO blood group", 0], ["Height", 2], ["A scar from an accident", 1], ["Body mass", 2], ["Tongue-rolling ability (as usually taught)", 0], ["The language you speak", 1]], hint: "Could identical twins differ in it?", explain: "Discontinuous features like blood group are genetic. Height and mass depend on genes AND diet and health. Scars and language come only from the environment." }
]);

/* ---------- Molecular Genetics and Biotechnology ---------- */
KH("t10s1", [
{ f: "S", k: "c", b: 5, q: "Sort each description: a nucleotide, a gene, or a chromosome?", bins: ["Nucleotide", "Gene", "Chromosome"], items: [["A sugar, a phosphate and a base", 0], ["A length of DNA coding for one polypeptide", 1], ["A long DNA molecule coiled around proteins", 2], ["There are 46 of these in a human body cell", 2], ["The unit that joins to make a DNA strand", 0], ["Has two alleles in a body cell", 1]], hint: "Smallest to largest: nucleotide → gene → chromosome.", explain: "Nucleotides join into DNA strands. A gene is one section of DNA; a chromosome is one long DNA molecule carrying hundreds of genes." },
{ f: "K", k: "c", b: 6, q: "A nerve cell and a developing red blood cell come from the same person. Which explanation fits ALL the evidence?", case: [["🧠", "Nerve cell", "Makes neurotransmitters; no haemoglobin."], ["🩸", "Developing red blood cell", "Makes lots of haemoglobin."], ["🔬", "DNA test", "Both cells contain the haemoglobin gene."]], choices: ["Every body cell has the same genes, but each cell type switches on (uses) only some of them", "Nerve cells lost the haemoglobin gene", "The haemoglobin gene is mutated in nerve cells", "Red blood cells have extra chromosomes"], why: ["The DNA test found the gene in the nerve cell.", "There's no evidence of a mutation.", "Body cells have the same chromosomes."], hint: "Having a gene ≠ using it.", explain: "Cells copy their DNA exactly by mitosis, so all body cells have the same genes. Different cell types express different genes, so they make different proteins." }
]);
KH("t10s2", [
{ f: "T", k: "d", b: 6, q: "A DNA template strand reads TAC AAA CCG ATT. Using the codon table, what does it code for?", table: [["mRNA codon", "AUG", "UUU", "GGC", "UAA", "GCA"], ["Meaning", "Met (start)", "Phe", "Gly", "STOP", "Ala"]], choices: ["Met – Phe – Gly, then stop", "Met – Phe – Gly – Ala", "Phe – Gly – Met", "It can't be translated"], why: ["UAA is a stop codon: no amino acid is added.", "The order of codons gives the order of amino acids.", "Complementary pairing gives AUG UUU GGC UAA, all in the table."], hint: "First make the mRNA: T→A, A→U, C→G, G→C.", explain: "TAC AAA CCG ATT → mRNA AUG UUU GGC UAA → Met, Phe, Gly, STOP." },
{ f: "K", k: "c", b: 6, q: "Which chain of events best explains sickle-cell anaemia?", case: [["🧬", "DNA", "One base changes: CTC → CAC in the haemoglobin gene."], ["🔤", "Protein", "Glutamic acid is replaced by valine at position 6."], ["🩸", "In low oxygen", "Haemoglobin molecules stick together into long fibres; red cells become sickle-shaped and block capillaries."]], choices: ["A base substitution changes one codon, so one amino acid changes, which alters how the protein behaves and deforms the cells", "A deletion shifts the reading frame", "The sickle shape of the cell changes the DNA", "Valine is poisonous to red blood cells"], why: ["It's a substitution: one base swapped, and the length is unchanged.", "That reverses cause and effect.", "There's no evidence; the effect comes from the protein's changed behaviour."], hint: "Follow DNA → mRNA → protein → cell.", explain: "A single base substitution changes one amino acid. That small change makes haemoglobin molecules clump in low oxygen, distorting the red blood cells." }
]);
KH("t10s3", [
{ f: "P", k: "s", b: 5, q: "DNA from a crime scene was compared with three suspects. Tap the suspect whose profile matches.", tap: { scene: { kind: "gel", lanes: [{ lbl: "Scene", bands: [2, 5, 7, 10] }, { lbl: "S1", bands: [2, 5, 8, 10] }, { lbl: "S2", bands: [2, 5, 7, 10] }, { lbl: "S3", bands: [3, 5, 7, 11] }] }, want: "S2" }, hint: "Every band must line up.", explain: "Only S2 has bands at exactly 2, 5, 7 and 10 kb. S1 and S3 each share some bands but not all, so they are excluded." },
{ f: "S", k: "c", b: 5, q: "Sort each point about genetic engineering: a benefit or a concern?", bins: ["Benefit", "Concern"], items: [["Pest-resistant crops need less insecticide", 0], ["Genes could spread to wild relatives", 1], ["Golden Rice could reduce vitamin A deficiency", 0], ["Fewer crop varieties could reduce genetic diversity", 1], ["Insulin made by bacteria is cheap and identical to human insulin", 0], ["Long-term effects need careful testing", 1]], hint: "Who gains, and what could go wrong?", explain: "A balanced view weighs real benefits (less pesticide, better nutrition, medicines) against real risks (gene flow, less diversity, the need for long-term testing)." }
]);
