
/* 🎬 Media questions, part 3: Evolution, Plants, Nutrition, Gas Exchange, Transport (see q_m1.js). */

/* ---------- Biodiversity and Evolution ---------- */
KH("t11s1", [
{ f: "S", k: "c", b: 5, q: "Sort each animal or feature into its vertebrate class.", bins: ["Mammal", "Bird", "Reptile", "Amphibian"], items: [["Whale", 0], ["Penguin", 1], ["Sea turtle", 2], ["Newt", 3], ["Has hair and feeds its young on milk", 0], ["Moist skin; lays jelly-covered eggs in water", 3]], hint: "Ignore where it lives; look at its body features.", explain: "Whales are mammals (lungs, milk), penguins are birds (feathers), sea turtles are reptiles (dry scales, eggs on land), and newts are amphibians (moist skin, eggs in water)." },
{ f: "K", k: "c", b: 6, q: "Are these two finch populations separate species?", case: [["🏝️", "Island finches", "Two populations look almost identical."], ["🎵", "Songs", "Each population only responds to its own song."], ["🧪", "Lab test", "Hybrids hatch, but all of them are infertile."]], choices: ["Yes: they can't produce fertile offspring, and their different songs stop them mating anyway", "No, because they look identical", "No, because hybrids can hatch", "It can't be decided without counting them"], why: ["Appearance doesn't define a species.", "The offspring must be FERTILE to count as one species.", "Numbers don't decide species status."], hint: "Use the definition of a species.", explain: "A species is a group that can interbreed to produce fertile offspring. Different songs keep them apart, and infertile hybrids show they've already split." }
]);
KH("t11s2", [
{ f: "P", k: "d", b: 5, q: "Peppered moths near an industrial city. Tap the year when dark moths first made up MORE than half the population.", tap: { chart: { x: [1840, 1920, 20, "year"], y: [0, 100, 20, "dark moths / %"], series: [{ pts: [[1840, 2], [1860, 10], [1880, 45], [1900, 85], [1920, 95]], dots: true }] }, want: 3 }, hint: "Find where the line first goes above 50%.", explain: "At 1880 only 45% were dark; by 1900, 85%. Soot made dark moths better camouflaged, so they survived and bred more: natural selection over just a few decades." },
{ f: "S", k: "c", b: 5, q: "Sort each statement: is it part of natural selection, or a common misunderstanding?", bins: ["Natural selection", "Misunderstanding"], items: [["Individuals in a population vary", 0], ["Giraffes stretched their necks and passed on longer necks", 1], ["Better-adapted individuals leave more offspring", 0], ["Bacteria decide to become resistant", 1], ["New variation can come from random mutation", 0], ["An individual evolves during its lifetime", 1]], hint: "Populations evolve; individuals don't.", explain: "Natural selection works on inherited variation in a population over generations. Individuals can't choose or acquire new inherited traits." }
]);
KH("t11s3", [
{ f: "T", k: "d", b: 6, q: "Differences in the protein cytochrome c compared with humans. Which conclusion is best supported?", table: [["Species", "Chimpanzee", "Rhesus monkey", "Horse", "Chicken", "Tuna", "Yeast"], ["Differences", "0", "1", "12", "13", "21", "44"]], choices: ["Humans share the most recent common ancestor with chimpanzees, then monkeys; yeast is the most distant relative", "Humans evolved from chimpanzees", "Horses are more closely related to us than monkeys are", "Yeast has 44 differences"], why: ["Humans and chimps share a common ancestor; neither evolved from the other.", "Horses have 12 differences; monkeys have only 1.", "A true reading, but not a conclusion."], hint: "Fewer differences = more recent common ancestor.", explain: "Molecular differences build up over time after two lineages split. The pattern matches what fossils and anatomy suggest." },
{ f: "G", k: "d", b: 5, q: "Which graph shows the number of toes per foot in horse ancestors from 55 million years ago to now?", gch: [{ pts: [[0, 4], [15, 4], [20, 3], [45, 3], [50, 1], [55, 1]], smooth: false }, { pts: [[0, 1], [25, 3], [55, 4]], smooth: false }, { pts: [[0, 3], [55, 3]], smooth: false }, { pts: [[0, 4], [54, 4], [55, 1]], smooth: false }], gax: ["55 million years ago → now", "toes per foot"], choices: ["Falls in steps, from 4 to 3 to 1", "Rises over time", "Stays the same", "Stays at 4, then suddenly drops to 1 recently"], why: ["Modern horses have one toe per foot.", "Fossils show change.", "Fossils show gradual change through in-between forms."], hint: "Modern horses stand on a single toe (the hoof).", explain: "Horse fossils show a series of in-between forms: 4 toes, then 3, then 1, as horse ancestors adapted to running on open grassland." }
]);

/* ---------- Life Processes in Plants ---------- */
KH("t12s1", [
{ f: "K", k: "c", b: 6, q: "A vertical farm in Hong Kong grows lettuces with their roots in flowing nutrient solution. Why do they wilt after the air pump breaks?", case: [["🏢", "Vertical farm", "No soil: roots hang in nutrient solution."], ["🫧", "Air pump", "Normally bubbles air through the solution."], ["⚠️", "Pump failure", "After 2 days without bubbles, the leaves wilt, even though the roots are in water."]], choices: ["Without oxygen, root cells can't respire aerobically, so active uptake fails and the roots are damaged, cutting water uptake", "There's no water for the roots", "The bubbles carry water up to the leaves", "The solution became too dilute"], why: ["The roots are surrounded by water.", "Bubbles supply oxygen, not water to the leaves.", "Nothing changed the solution's concentration."], hint: "What do the bubbles supply to root cells?", explain: "Roots need oxygen for aerobic respiration. Without it, they can't make enough ATP, root cells are damaged, and water and ion uptake drop, so the plant wilts. The same happens in waterlogged soil." },
{ f: "S", k: "c", b: 5, q: "Sort each statement: true of nitrate, magnesium, or both?", bins: ["Nitrate", "Magnesium", "Both"], items: [["Needed to make amino acids and proteins", 0], ["Part of the chlorophyll molecule", 1], ["A shortage causes yellow leaves", 2], ["A shortage causes very stunted growth", 0], ["Taken up by root hairs by active transport", 2]], hint: "Proteins vs chlorophyll.", explain: "Nitrate supplies nitrogen for amino acids (and chlorophyll); magnesium is at the centre of chlorophyll. Lack of either causes yellowing; both are taken up actively." }
]);
KH("t12s2", [
{ f: "V", k: "d", b: 5, q: "A potometer shoot was tested for 5 minutes in each of three conditions. Watch the bead. Which explanation fits all three?", scene: { kind: "bead", tubes: [{ lbl: "Still air", mm: 15 }, { lbl: "Fan", mm: 35 }, { lbl: "Bag on shoot", mm: 4 }], max: 40, mins: 5 }, choices: ["Wind removes humid air, steepening the water vapour gradient; a bag traps humid air, making the gradient shallow", "Wind closes the stomata, so transpiration stops", "The bag stops all water uptake", "The fan cools the leaf, so less water evaporates"], why: ["The fan gives the BIGGEST reading.", "The bead still moved 4 mm.", "The fan raised the reading, so evaporation increased."], hint: "Think about the air right next to the leaf.", explain: "Moving air keeps the air around the stomata dry, so water vapour diffuses out faster. A bag fills with humid air, so diffusion slows almost to a stop." },
{ f: "G", k: "d", b: 6, q: "Water LOSS (dashed) and water UPTAKE (pink) of a tree over 24 hours. Which graph is right?", gch: [{ ref: [[0, 1], [6, 2], [10, 7], [13, 10], [17, 6], [21, 2], [24, 1]], pts: [[0, 2], [6, 2], [11, 5], [15, 9], [19, 6], [24, 2]] }, { ref: [[0, 1], [6, 2], [10, 7], [13, 10], [17, 6], [21, 2], [24, 1]], pts: [[0, 2], [6, 5], [9, 9], [13, 6], [18, 2], [24, 2]] }, { ref: [[0, 1], [6, 2], [10, 7], [13, 10], [17, 6], [21, 2], [24, 1]], pts: [[0, 5], [24, 5]], smooth: false }, { ref: [[0, 1], [6, 2], [10, 7], [13, 10], [17, 6], [21, 2], [24, 1]], pts: [[0, 10], [6, 9], [12, 2], [18, 9], [24, 10]] }], gax: ["time of day", "water"], choices: ["Uptake rises and falls like loss, but peaks a little LATER", "Uptake peaks BEFORE loss", "Uptake stays the same all day", "Uptake is highest at night"], why: ["Loss creates the tension that pulls water up, so uptake follows loss.", "Uptake changes as transpiration pulls on the water column.", "Transpiration (and the pull) is weakest at night."], hint: "What drives water up the xylem?", explain: "Transpiration from the leaves pulls the water column up. Uptake by the roots responds to this pull, so it lags behind loss; the trunk even shrinks slightly at midday." }
]);
KH("t12s3", [
{ f: "P", k: "d", b: 5, q: "Radioactive CO₂ was given to one mature leaf. After an hour, the radioactivity in other parts was measured. Tap the biggest sink.", tap: { chart: { y: [0, 50, 10, "radioactivity (% of total)"], bars: { cats: ["Young leaves", "Old leaves", "Stem", "Fruits", "Roots"], vals: [25, 3, 10, 45, 17], c: "#B9F3C9", xl: "plant part" } }, want: 3 }, hint: "Where did most of the labelled sugar go?", explain: "Developing fruits are the strongest sinks, receiving the most sucrose through the phloem. Mature leaves are sources, so they receive almost none." },
{ f: "S", k: "c", b: 5, q: "Sort each description: xylem, phloem, or both?", bins: ["Xylem", "Phloem", "Both"], items: [["Carries sucrose", 1], ["Made of dead, hollow cells with lignin", 0], ["Carries water and mineral ions", 0], ["Can carry substances up and down", 1], ["Found in vascular bundles", 2], ["Its lignin helps support the plant", 0]], hint: "Dead pipes vs living tubes.", explain: "Xylem: dead, lignified vessels carrying water and ions upwards, also giving support. Phloem: living sieve tubes carrying sugars both ways. Both are in vascular bundles." }
]);

/* ---------- Nutrition in Humans ---------- */
KH("t8s1", [
{ f: "K", k: "d", b: 6, q: "Here is a student's food for one day. What is the best advice?", case: [["📋", "Daily guide", "Energy about 9500 kJ; protein about 50 g; fat under 70 g; plenty of fruit and vegetables."]], table: [["Meal", "Energy (kJ)", "Protein (g)", "Fat (g)"], ["Pineapple bun", "1400", "7", "18"], ["Char siu rice", "3200", "30", "35"], ["Bubble tea", "1500", "2", "12"], ["Instant noodles", "1900", "9", "20"], ["Total", "8000", "48", "85"]], choices: ["Energy and protein are about right, but fat is too high and there's no fruit or veg; swap the noodles or bubble tea for lower-fat choices plus vegetables", "Eat more food, because the energy is far too low", "Cut down on protein", "The diet is balanced"], why: ["8000 kJ is close to the guide.", "48 g is about right.", "Fat is over 70 g and there's almost no fibre, fruit or vegetables."], hint: "Compare each total with the guide.", explain: "Total fat (85 g) is above the guide, and nothing provides fibre or vitamins from fruit and vegetables. Small swaps fix it without cutting energy." },
{ f: "S", k: "c", b: 5, q: "Sort each cause and symptom to the deficiency disease it matches.", bins: ["Scurvy", "Rickets", "Anaemia", "Constipation"], items: [["Too little vitamin C", 0], ["Too little vitamin D", 1], ["Too little iron", 2], ["Too little dietary fibre", 3], ["Bleeding gums", 0], ["Soft, bent leg bones", 1], ["Pale skin and always tired", 2]], hint: "Match each nutrient to what it's used for.", explain: "Vitamin C → collagen (scurvy); vitamin D → calcium uptake for bones (rickets); iron → haemoglobin (anaemia); fibre → gut movement (constipation)." }
]);
KH("t8s2", [
{ f: "G", k: "d", b: 5, q: "Which graph shows the pH in the mouth, the stomach and the small intestine?", gch: [{ pts: [[0, 7], [1, 7], [2, 2], [3, 2], [4, 8], [5, 8]], smooth: false }, { pts: [[0, 7], [5, 7]], smooth: false }, { pts: [[0, 2], [5, 8]], smooth: false }, { pts: [[0, 2], [1, 2], [2, 7], [3, 7], [4, 2], [5, 2]], smooth: false }], gax: ["mouth → stomach → small intestine", "pH"], choices: ["About 7, then about 2, then about 8", "About 7 all the way", "Rising steadily from 2 to 8", "About 2, then about 7, then about 2"], why: ["The stomach is strongly acidic.", "The mouth is about neutral, not acidic.", "That's backwards: the stomach is the acidic part."], hint: "Where is the acid made, and what neutralises it?", explain: "Saliva is about neutral; stomach acid gives about pH 2 for pepsin; bile and pancreatic juice make the small intestine slightly alkaline for its enzymes." },
{ f: "K", k: "c", b: 6, q: "Why are adults in some populations much more likely to digest milk than others?", case: [["🌍", "Survey", "Adults who can't digest lactose: about 90% in East Asia, about 10% in Northern Europe."], ["🐄", "History", "Northern Europeans have kept dairy cattle for thousands of years."], ["🧬", "Gene", "An allele keeps the lactase gene switched on into adulthood."]], choices: ["In dairy-farming populations, adults with the allele could use milk and survived better, so natural selection made the allele common", "Adults who drank milk made lactase and passed this on", "East Asians have no lactase gene", "Cold climates make the body produce lactase"], why: ["Changes acquired during life aren't inherited.", "Everyone has the gene; in most people it switches off after childhood.", "Climate doesn't switch the gene on directly."], hint: "Which kind of change is passed on to children?", explain: "Where milk was an important food, adults who kept making lactase had an advantage. Over many generations the allele became common: natural selection in human populations." }
]);
KH("t8s3", [
{ f: "G", k: "d", b: 6, q: "Dashed line: glucose in the hepatic portal vein (from gut to liver) after a meal. Which pink line shows glucose in the hepatic vein (leaving the liver)?", gch: [{ ref: [[0, 5], [1, 12], [2, 9], [3, 6], [4, 5]], pts: [[0, 5], [1, 7], [2, 6.5], [3, 5.5], [4, 5]] }, { ref: [[0, 5], [1, 12], [2, 9], [3, 6], [4, 5]], pts: [[0, 5], [1, 12], [2, 9], [3, 6], [4, 5]] }, { ref: [[0, 5], [1, 12], [2, 9], [3, 6], [4, 5]], pts: [[0, 5], [1, 15], [2, 13], [3, 9], [4, 7]] }, { ref: [[0, 5], [1, 12], [2, 9], [3, 6], [4, 5]], pts: [[0, 0], [4, 0]], smooth: false }], gax: ["time after a meal", "blood glucose"], choices: ["A much smaller, smoother rise", "Exactly the same as the portal vein", "Even higher than the portal vein", "Zero glucose"], why: ["The liver removes extra glucose before it reaches the body.", "The liver doesn't add more after a meal.", "Blood always carries some glucose."], hint: "What does the liver do with extra glucose?", explain: "Insulin makes the liver store extra glucose as glycogen, so blood leaving the liver has a much steadier glucose level." },
{ f: "S", k: "c", b: 5, q: "Sort each product of digestion: absorbed into blood capillaries or into lacteals?", bins: ["Blood capillaries", "Lacteals"], items: [["Glucose", 0], ["Amino acids", 0], ["Fatty acids and glycerol", 1], ["Vitamins B and C (water-soluble)", 0], ["Vitamins A and D (fat-soluble)", 1], ["Mineral ions", 0]], hint: "Fats and things that dissolve in fat go one way.", explain: "Water-soluble products enter the blood capillaries in each villus. Fats re-form inside villus cells and enter the lacteals (lymph), taking fat-soluble vitamins with them." }
]);

/* ---------- Gas Exchange in Humans ---------- */
KH("t13s1", [
{ f: "P", k: "d", b: 5, q: "Oxygen in blood moving along a capillary past an alveolus (alveolar air = 13 kPa). Tap the FIRST point where the blood is fully loaded.", tap: { chart: { x: [0, 5, 1, "distance along capillary"], y: [0, 15, 5, "oxygen in blood / kPa"], series: [{ pts: [[0, 5], [1, 10], [2, 12.5], [3, 13], [4, 13], [5, 13]], dots: true }] }, want: 3 }, hint: "Where does the blood reach 13 kPa?", explain: "Blood is fully loaded only part of the way along. The spare length is a safety margin: in exercise, blood flows faster and still has time to load fully." },
{ f: "K", k: "c", b: 6, q: "Why does extra oxygen help this premature baby?", case: [["👶", "Baby", "Born at 28 weeks."], ["🔬", "Lungs", "Few alveoli; they tend to collapse because they lack surfactant."], ["🩺", "Treatment", "Surfactant sprayed into the lungs; air with extra oxygen given."]], choices: ["A higher oxygen concentration in the alveoli steepens the gradient, so more oxygen diffuses into the blood across the small surface area", "Babies need more oxygen than adults", "Oxygen makes the alveoli grow", "It reduces the CO₂ in the air"], why: ["That's not the main point; the problem is the small exchange surface.", "Oxygen doesn't build alveoli.", "Air has very little CO₂ anyway; the aim is more oxygen."], hint: "Which factor in diffusion can doctors change quickly?", explain: "Surface area can't be increased quickly, but the concentration gradient can. Steeper gradient → faster diffusion, making up for the small surface." }
]);
KH("t13s2", [
{ f: "S", k: "c", b: 5, q: "Sort each event: breathing in, or breathing out at rest?", bins: ["Breathing in", "Breathing out"], items: [["Diaphragm contracts and flattens", 0], ["External intercostal muscles relax", 1], ["Ribs move up and out", 0], ["Volume of the thorax decreases", 1], ["Pressure in the lungs falls below atmospheric", 0], ["Elastic lungs recoil", 1]], hint: "In: muscles contract, volume up, pressure down.", explain: "Breathing in is active (muscles contract, volume up, pressure down). At rest, breathing out is passive (muscles relax, lungs recoil, volume down, pressure up)." },
{ f: "G", k: "d", b: 5, q: "Dashed line = atmospheric pressure. Which pink line shows the pressure inside the lungs during one breath IN and then OUT?", gch: [{ ref: [[0, 0], [4, 0]], pts: [[0, 0], [1, -1], [2, 0], [3, 1], [4, 0]] }, { ref: [[0, 0], [4, 0]], pts: [[0, 0], [1, 1], [2, 0], [3, -1], [4, 0]] }, { ref: [[0, 0.02], [4, 0.02]], pts: [[0, 0], [4, 0]], smooth: false }, { ref: [[0, 0], [4, 0]], pts: [[0, 0], [1, -1], [2, -0.5], [3, -1], [4, 0]] }], gax: ["time: in, then out", "lung pressure"], choices: ["Below atmospheric while breathing in, above it while breathing out", "Above atmospheric while breathing in", "Always equal to atmospheric", "Below atmospheric the whole time"], why: ["That's reversed: air flows in when lung pressure is LOWER.", "Air only moves when there's a pressure difference.", "Air flows out only when lung pressure is HIGHER than outside."], hint: "Air moves from high to low pressure.", explain: "Expanding the thorax lowers lung pressure below atmospheric, so air flows in; recoil raises it above atmospheric, so air flows out." }
]);
KH("t13s3", [
{ f: "D", k: "d", b: 6, q: "A country's cigarette sales and lung cancer deaths over a century (each scaled so its peak = 100). What does the gap between the two peaks suggest?", chart: { x: [1900, 2000, 20, "year"], y: [0, 100, 20, "relative level (peak = 100)"], series: [{ pts: [[1900, 5], [1920, 40], [1940, 80], [1960, 100], [1980, 80], [2000, 50]], c: G_BLUE, lbl: "cigarettes", lx: 1925, ly: 62 }, { pts: [[1900, 2], [1920, 10], [1940, 35], [1960, 70], [1980, 100], [2000, 85]], c: PINK, lbl: "lung cancer", lx: 1962, ly: 92 }] }, choices: ["Lung cancer takes about 20 years to develop after exposure, so the effects of smoking appear decades later", "Lung cancer makes people stop smoking", "Smoking has no link with lung cancer", "Lung cancer deaths peaked in 1980"], why: ["Smoking peaked FIRST; cancer followed.", "The two curves follow each other with a delay.", "A true reading, but not an explanation."], hint: "Which peak came first, and by how much?", explain: "Cancers develop slowly as mutations build up. The 20-year lag is one reason the link took so long to prove, and why quitting early matters." },
{ f: "S", k: "c", b: 5, q: "Sort each effect to the substance in cigarette smoke that causes it.", bins: ["Nicotine", "Tar", "Carbon monoxide"], items: [["An addictive drug", 0], ["Contains carcinogens", 1], ["Binds to haemoglobin", 2], ["Paralyses cilia and causes coughing", 1], ["Raises heart rate and blood pressure", 0], ["Reduces the oxygen reaching a fetus", 2]], hint: "Addiction, cancer, oxygen.", explain: "Nicotine: addiction, raised heart rate. Tar: carcinogens and damaged cilia. Carbon monoxide: binds haemoglobin, so less oxygen is carried." }
]);

/* ---------- Transport in Humans ---------- */
KH("t14s1", [
{ f: "S", k: "c", b: 5, q: "Sort each feature: artery, vein or capillary?", bins: ["Artery", "Vein", "Capillary"], items: [["Wall only one cell thick", 2], ["Thick, muscular and elastic wall", 0], ["Has valves", 1], ["Carries blood away from the heart", 0], ["Lowest blood pressure", 1], ["Where substances are exchanged with tissue cells", 2]], hint: "Pressure, direction, exchange.", explain: "Arteries: thick walls for high pressure, away from the heart. Veins: valves, lowest pressure, back to the heart. Capillaries: one cell thick for exchange." },
{ f: "K", k: "c", b: 6, q: "Why does it take much longer to replace red blood cells than plasma after donating blood?", case: [["🩸", "Donation", "470 mL of blood given."], ["⏱️", "Next 2 days", "Plasma volume back to normal."], ["⏱️", "Next 6–8 weeks", "Red blood cell count back to normal."], ["🍳", "Advice", "Eat iron-rich foods."]], choices: ["Plasma is mostly water and dissolved substances, replaced quickly from drinks; new red cells must be made in bone marrow, which needs iron for haemoglobin and takes weeks", "Red blood cells are made in the heart", "Plasma contains the red blood cells", "Red blood cells divide slowly in the blood"], why: ["They're made in the bone marrow.", "Plasma is the liquid part; red cells are carried in it.", "Mature red cells have no nucleus, so they can't divide."], hint: "Where are red blood cells made, and what do they need?", explain: "Fluid is replaced from what you drink within a day or two. New red cells take weeks to make in the bone marrow, and each needs iron for haemoglobin." }
]);
KH("t14s2", [
{ f: "V", k: "d", b: 5, q: "This 6-second heart trace was recorded straight after a sprint. Count the tall spikes. What is the heart rate?", scene: { kind: "ecg", bpm: 140, lbl: "After a sprint" }, choices: ["About 140 beats per minute", "About 14 beats per minute", "About 70 beats per minute", "About 280 beats per minute"], why: ["That's the beats in 6 s; multiply by 10.", "That's about a resting rate; count again.", "That counts each small bump as a beat. Count only the tall spikes."], hint: "Beats in 6 s × 10.", explain: "There are 14 tall spikes in 6 seconds, so 14 × 10 = 140 beats per minute. During exercise, heart rate rises to deliver more oxygen and glucose to the muscles." },
{ f: "S", k: "c", b: 5, q: "Sort each part: does it carry oxygenated or deoxygenated blood?", bins: ["Oxygenated", "Deoxygenated"], items: [["Pulmonary vein", 0], ["Aorta", 0], ["Left ventricle", 0], ["Pulmonary artery", 1], ["Vena cava", 1], ["Right atrium", 1]], hint: "The pulmonary vessels are the exceptions to the 'arteries = oxygenated' idea.", explain: "The left side of the heart handles oxygenated blood from the lungs. The pulmonary ARTERY carries deoxygenated blood to the lungs, and the pulmonary VEIN brings oxygenated blood back." }
]);
KH("t14s3", [
{ f: "G", k: "d", b: 6, q: "Pink = blood pressure along a capillary; dashed = the pull of plasma proteins drawing water back in. Which graph shows fluid pushed OUT at the artery end and drawn back IN at the vein end?", gch: [{ ref: [[0, 3], [4, 3]], pts: [[0, 4.5], [4, 1.5]], smooth: false }, { ref: [[0, 3], [4, 3]], pts: [[0, 5], [4, 4]], smooth: false }, { ref: [[0, 3], [4, 3]], pts: [[0, 2], [4, 1]], smooth: false }, { ref: [[0, 3], [4, 3]], pts: [[0, 1.5], [4, 4.5]], smooth: false }], gax: ["artery end → vein end", "pressure"], choices: ["Pink starts above the dashed line and ends below it", "Pink stays above the dashed line", "Pink stays below the dashed line", "Pink rises along the capillary"], why: ["Then fluid would leave all along the capillary and none would return.", "Then no tissue fluid would form at all.", "Blood pressure FALLS along a capillary."], hint: "Out when pushing beats pulling; in when pulling wins.", explain: "At the artery end, blood pressure is higher than the protein pull, so fluid is pushed out. Pressure falls along the capillary until the pull wins, and most fluid returns." },
{ f: "K", k: "c", b: 6, q: "Why does this patient feel chest pain only when climbing stairs?", case: [["👨", "Patient", "55, smoker, chest pain when climbing stairs, none at rest."], ["🩻", "Angiogram", "One coronary artery is 70% narrowed."], ["📈", "Resting heart trace", "Normal."]], choices: ["At rest, the narrowed artery still supplies enough blood; during exercise the heart muscle needs more oxygen than it can deliver", "Exercise blocks the artery completely", "A normal heart trace proves the pain is from his chest muscles", "Smoking only causes pain during exercise"], why: ["The narrowing stays the same; the DEMAND changes.", "A normal resting trace doesn't rule out narrowing that only matters in exercise.", "Smoking damages the arteries; the pain comes from the heart muscle lacking oxygen."], hint: "Supply vs demand.", explain: "Exercise raises heart rate and the heart muscle's need for oxygen. A narrowed coronary artery can't increase supply enough, so the muscle is short of oxygen and hurts (angina)." }
]);
