
/* 🎬 Media questions, part 4: Reproduction, Coordination, Homeostasis, Ecosystems, Health (see q_m1.js). */

/* ---------- Reproduction, Growth and Development ---------- */
KH("t15s1", [
{ f: "P", k: "d", b: 5, q: "Pollen grains were grown on agar with different sugar concentrations. Tap the concentration that gave the longest pollen tubes.", tap: { chart: { x: [0, 20, 5, "sucrose / %"], y: [0, 350, 50, "pollen tube length / µm"], series: [{ pts: [[0, 0], [5, 120], [10, 300], [15, 260], [20, 150]], dots: true }] }, want: 2 }, hint: "Highest point.", explain: "Tubes grew longest at 10% sucrose. Too little sugar gives too little energy; too much draws water out of the pollen by osmosis." },
{ f: "K", k: "c", b: 6, q: "An orchard has fewer bees than it used to. Why are many apples misshapen?", case: [["🍎", "Orchard", "Apple flowers are pollinated by insects."], ["🐝", "Bee decline", "Wild bee numbers halved in 10 years."], ["📉", "Harvest", "Fewer apples, and many are lopsided."], ["🔪", "Cut open", "Lopsided apples have seeds on one side only."]], choices: ["Less pollen reached the stigmas, so fewer ovules were fertilised, and the fruit grows less where there are no seeds", "Bees eat parts of the apples", "Apples are wind-pollinated, so bees don't matter", "Seeds make apples smaller"], why: ["The bees visit the flowers, not the fruit.", "The flowers are insect-pollinated; that's why bees matter.", "Developing seeds actually stimulate fruit growth around them."], hint: "Where are the seeds, and where is the apple small?", explain: "Each seed comes from a fertilised ovule. Developing seeds make the fruit grow around them, so sides without seeds stay small. Fewer pollinators means fewer fertilised ovules." }
]);
KH("t15s2", [
{ f: "S", k: "c", b: 6, q: "Sort each job to the hormone that does it.", bins: ["FSH", "LH", "Oestrogen", "Progesterone"], items: [["Stimulates a follicle to develop in the ovary", 0], ["A surge of it triggers ovulation", 1], ["Repairs and thickens the uterus lining after menstruation", 2], ["Keeps the uterus lining ready after ovulation", 3], ["Its fall at the end of the cycle leads to menstruation", 3]], hint: "Two from the pituitary, two from the ovary.", explain: "FSH (pituitary) starts a follicle growing; oestrogen (ovary) rebuilds the lining; an LH surge (pituitary) triggers ovulation; progesterone (ovary) keeps the lining, and its fall starts menstruation." },
{ f: "T", k: "d", b: 6, q: "Mean birth mass of babies, by the mother's smoking habits. Which conclusion is best supported?", table: [["Mother", "Never smoked", "1–10 a day", "More than 10 a day", "Quit early in pregnancy"], ["Mean birth mass (kg)", "3.40", "3.20", "3.00", "3.35"]], choices: ["Birth mass falls as smoking increases, and quitting early largely prevents the effect", "Smoking only matters above 10 a day", "Quitting has no benefit", "Babies of heavy smokers average 3.00 kg"], why: ["1–10 a day also lowered birth mass.", "Quitters' babies were almost as heavy as non-smokers'.", "A true reading, but not a conclusion."], hint: "Compare every group with 'never smoked'.", explain: "A dose-response pattern (more smoking, lighter babies), plus recovery after quitting, strongly suggests smoking slows fetal growth (CO and nicotine reduce oxygen supply)." }
]);
KH("t15s3", [
{ f: "P", k: "d", b: 6, q: "Mean dry mass of seedlings after germination. Tap the day when photosynthesis first matched respiration.", tap: { chart: { x: [0, 10, 2, "days after sowing"], y: [60, 140, 20, "dry mass / mg"], series: [{ pts: [[0, 100], [2, 90], [4, 80], [6, 85], [8, 100], [10, 130]], dots: true }] }, want: 2 }, hint: "Where does dry mass stop falling?", explain: "Dry mass falls while stored food is respired; it stops falling (the minimum, day 4) when photosynthesis makes as much as respiration uses, then rises." },
{ f: "G", k: "d", b: 5, q: "Which graph shows a person's height from birth to 20 years?", gch: [{ pts: [[0, 50], [2, 88], [10, 139], [12, 151], [14, 165], [16, 172], [18, 175], [20, 175]] }, { pts: [[0, 50], [20, 175]], smooth: false }, { pts: [[0, 50], [10, 60], [15, 90], [20, 175]] }, { pts: [[0, 50], [5, 140], [10, 175], [20, 175]] }], gax: ["age 0 → 20 years", "height"], choices: ["Fast in infancy, slower in childhood, a spurt at puberty, then levelling off", "A straight line", "Slow at first, then faster and faster", "Fully grown by about 10"], why: ["Growth rate changes a lot with age.", "Babies grow fastest of all.", "Growth continues through puberty."], hint: "When do people grow fastest?", explain: "Human growth has two fast phases (infancy and the adolescent growth spurt) and stops in early adulthood." }
]);

/* ---------- Coordination and Response ---------- */
KH("t16s1", [
{ f: "G", k: "d", b: 5, q: "Someone walks out of a dark cinema into bright sunlight halfway along the time axis. Which graph shows their pupil diameter?", gch: [{ pts: [[0, 7], [5, 7], [5.4, 3], [6, 2.5], [10, 2.5]], smooth: false }, { pts: [[0, 7], [10, 2.5]], smooth: false }, { pts: [[0, 2.5], [5, 2.5], [5.4, 7], [10, 7]], smooth: false }, { pts: [[0, 5], [10, 5]], smooth: false }], gax: ["time (sunlight at the middle)", "pupil diameter"], choices: ["Wide, then shrinks within about a second, then stays small", "Shrinks slowly and steadily the whole time", "Small, then widens", "Stays the same"], why: ["The pupil reflex is fast, and it only starts when the light changes.", "Bright light makes the pupil SMALLER.", "This is a reflex: it must change."], hint: "Reflexes are fast.", explain: "Bright light triggers the pupil reflex: the circular iris muscles contract within a second, protecting the retina." },
{ f: "K", k: "c", b: 6, q: "Grandpa can't read the menu. Which explanation fits ALL the evidence?", case: [["👴", "Grandpa, 65", "Holds the menu at arm's length to read it."], ["🔭", "Distance", "Sees far objects clearly."], ["🔬", "Optician", "The lens has become stiff and less elastic."]], choices: ["The stiff lens can't become thick enough to focus light from near objects, so he needs convex reading glasses", "His retina has lost its rods, so he can't see the small print", "His ciliary muscles can't relax, so his lens is stuck too thick", "He needs concave lenses to spread the light out before it reaches the eye"], why: ["Rods are for dim light; he can see, just not up close.", "His far vision is fine; the problem is the lens rounding up for near objects.", "Concave lenses correct short sight."], hint: "Near vision needs a fat lens.", explain: "With age, the lens loses elasticity and can't round up for near objects. Convex lenses do some of the bending for it." }
]);
KH("t16s2", [
{ f: "S", k: "c", b: 5, q: "You touch a hot pan. Sort each structure to its role in the reflex arc.", bins: ["Receptor", "Sensory neurone", "Relay neurone", "Motor neurone", "Effector"], items: [["Heat-sensitive nerve endings in the skin", 0], ["Carries impulses into the spinal cord", 1], ["Lies entirely inside the spinal cord", 2], ["Carries impulses out to the arm", 3], ["The biceps, which pulls the hand away", 4]], hint: "Follow the impulse from skin to muscle.", explain: "Receptor → sensory neurone → relay neurone (spinal cord) → motor neurone → effector (muscle). The brain is told afterwards, which is why you feel pain after you've moved." },
{ f: "K", k: "d", b: 6, q: "How much further does a texting driver travel before starting to brake, compared with an alert driver?", case: [["🚗", "Speed", "At 50 km/h, a car travels about 14 m every second."]], table: [["Driver", "Mean reaction time (s)"], ["Alert", "0.7"], ["On a hands-free call", "0.9"], ["Texting", "1.4"]], choices: ["About 10 m further", "About 0.7 m further", "About 20 m further", "No further: braking is an automatic reflex"], why: ["0.7 is the extra TIME in seconds; multiply by 14 m per second.", "That's the texting driver's whole distance (1.4 × 14).", "Braking is a voluntary response through the brain, so distraction slows it."], hint: "Extra time × distance per second.", explain: "(1.4 − 0.7) s × 14 m/s ≈ 10 m: about two car lengths further before the brakes even start working." }
]);
KH("t16s3", [
{ f: "G", k: "d", b: 5, q: "A shoot tip is lit from the LEFT. Which bar chart shows the auxin on its left (lit) and right (shaded) sides?", gch: [{ bars: [35, 65] }, { bars: [65, 35] }, { bars: [50, 50] }, { bars: [0, 100] }], gax: ["lit side | shaded side", "auxin"], choices: ["More auxin on the shaded side", "More auxin on the lit side", "Equal on both sides", "All the auxin on the shaded side"], why: ["Auxin moves AWAY from the light.", "Then the shoot would grow straight up.", "Some auxin stays on the lit side."], hint: "Which side grows faster when a shoot bends towards light?", explain: "More auxin on the shaded side makes those cells elongate more, so the shoot curves towards the light." },
{ f: "K", k: "c", b: 6, q: "A student rides a huge roller coaster. Which explanation fits ALL the evidence?", case: [["🎢", "Ride", "A steep drop at 100 km/h."], ["❤️", "Within seconds", "Heart rate 70 → 130; faster breathing; wide pupils."], ["🩸", "Blood test", "Blood glucose up; adrenaline high."], ["⏱️", "10 min later", "Most effects are still there."]], choices: ["Adrenaline acts on many organs and lingers", "Only nerves are involved, so the effects stop instantly", "Insulin raised the blood glucose", "Adrenaline acts only on the heart"], why: ["The effects lasted 10 minutes: that's hormonal.", "Insulin LOWERS blood glucose; adrenaline raises it.", "Pupils, breathing and glucose all changed too."], hint: "Fast start, long-lasting, many organs.", explain: "Nerves trigger adrenaline release in seconds, but adrenaline travels in the blood to many targets and lingers, so the 'fight or flight' effects last for minutes." }
]);
KH("t16s4", [
{ f: "S", k: "c", b: 5, q: "Sort each muscle: contracting or relaxing?", bins: ["Contracts", "Relaxes"], items: [["Triceps, when straightening the arm", 0], ["Biceps, when straightening the arm", 1], ["Biceps, when bending the arm", 0], ["Triceps, when bending the arm", 1]], hint: "Muscles only pull.", explain: "Antagonistic pairs: the muscle on the side the bone moves towards contracts and pulls, while its partner relaxes." },
{ f: "P", k: "d", b: 5, q: "Clothes-peg squeezes per minute over 5 minutes. Tap the minute that shows the biggest DROP from the minute before.", tap: { chart: { y: [0, 70, 10, "squeezes per minute"], bars: { cats: ["1", "2", "3", "4", "5"], vals: [60, 52, 40, 34, 30], c: "#C9C3F0", xl: "minute" } }, want: 2 }, hint: "Work out each drop: 60→52, 52→40, …", explain: "The biggest drop (12) is in minute 3. Fatigue builds as lactic acid accumulates and the oxygen supply can't keep up." }
]);

/* ---------- Homeostasis ---------- */
KH("t17s1", [
{ f: "G", k: "d", b: 6, q: "Dashed line: blood glucose after a meal. Which pink line shows insulin?", gch: [{ ref: [[0, 5], [30, 9], [60, 7], [90, 5.5], [120, 5]], pts: [[0, 1], [30, 6], [45, 8], [60, 6], [90, 2], [120, 1]] }, { ref: [[0, 5], [30, 9], [60, 7], [90, 5.5], [120, 5]], pts: [[0, 8], [30, 2], [60, 3], [90, 6], [120, 8]] }, { ref: [[0, 5], [30, 9], [60, 7], [90, 5.5], [120, 5]], pts: [[0, 4], [120, 4]], smooth: false }, { ref: [[0, 5], [30, 9], [60, 7], [90, 5.5], [120, 5]], pts: [[0, 1], [90, 1], [120, 8]] }], gax: ["time after a meal", "level"], choices: ["Rises soon after glucose rises, peaks a little later, then falls", "Falls when glucose rises", "Stays the same", "Rises only after 2 hours"], why: ["That's how GLUCAGON behaves.", "Insulin responds to blood glucose.", "Insulin responds within minutes."], hint: "Insulin answers a rise in glucose.", explain: "The pancreas detects the rise and releases insulin, which brings glucose back down; as glucose falls, insulin falls too: negative feedback." },
{ f: "K", k: "c", b: 6, q: "A footballer with type 1 diabetes feels shaky near the end of training. Which explanation fits ALL the evidence?", case: [["👧", "Athlete", "Has type 1 diabetes; injects insulin before meals."], ["⚽", "Training", "90 minutes of football after lunch."], ["⚠️", "Problem", "Shaky and confused near the end."], ["🍬", "Fix", "A sugary drink helps within minutes."]], choices: ["Her muscles used lots of glucose while the injected insulin kept removing it from the blood, so her blood glucose fell too low", "Her blood glucose was too high", "Her pancreas released too much glucagon", "Insulin gives the muscles energy directly"], why: ["The sugary drink helped, so glucose was too LOW.", "Glucagon raises glucose; it would help, not cause this.", "Insulin helps cells take up glucose; it isn't a fuel."], hint: "Two things were lowering her blood glucose at once.", explain: "Exercise uses glucose fast, and injected insulin can't be switched off like natural insulin. Athletes with diabetes adjust insulin and snacks around training." }
]);
KH("t17s2", [
{ f: "P", k: "d", b: 5, q: "Breathing rate of a resting person breathing air with different amounts of CO₂. Resting rate = 12. Tap the lowest CO₂ level that at least DOUBLES the breathing rate.", tap: { chart: { x: [0, 5, 1, "CO₂ in inhaled air / %"], y: [0, 35, 5, "breaths per minute"], series: [{ pts: [[0, 12], [1, 13], [2, 15], [3, 18], [4, 24], [5, 32]], dots: true }] }, want: 4 }, hint: "Double 12 is 24.", explain: "At 4% CO₂ the rate reaches 24, double the resting rate. Even small rises in CO₂ are detected by chemoreceptors, which speed up breathing." },
{ f: "S", k: "c", b: 5, q: "Sort each quantity: does it rise or fall during hard exercise?", bins: ["Rises", "Falls"], items: [["CO₂ concentration in the blood", 0], ["Blood pH", 1], ["Breathing rate", 0], ["Oxygen in the blood leaving the muscles", 1], ["Heart rate", 0]], hint: "Muscles use O₂ and make CO₂.", explain: "Working muscles use more O₂ and release more CO₂ (which lowers blood pH). Chemoreceptors detect this, and breathing and heart rate rise." }
]);

/* ---------- Ecosystems ---------- */
KH("t18s1", [
{ f: "S", k: "c", b: 5, q: "Sort each example by the type of interaction.", bins: ["Competition", "Predation", "Parasitism", "Mutualism"], items: [["Two bird species eat the same seeds", 0], ["A heron catches fish", 1], ["A tapeworm lives in a pig's gut", 2], ["Bees get nectar and pollinate flowers", 3], ["Barnacles crowd each other on a rock", 0], ["Head lice feed on blood from the scalp", 2]], hint: "Who gains, and who loses?", explain: "Competition: both lose some resources. Predation: one kills and eats the other. Parasitism: one lives on or in another, harming it. Mutualism: both gain." },
{ f: "K", k: "c", b: 6, q: "An island experiment. Which explanation fits ALL the results?", case: [["🏝️", "Island", "Rabbits eat grass; foxes eat rabbits."], ["🦊", "Year 1", "All the foxes are removed."], ["🐇", "Years 2–3", "Rabbit numbers boom."], ["🌾", "Year 4", "The grass is eaten bare; many rabbits starve."]], choices: ["Without predators, rabbits increased until food (grass) became the limiting factor, so many starved", "Foxes were needed to fertilise the grass", "The rabbits died of old age", "Removing predators always increases prey forever"], why: ["The grass was eaten, not unfertilised.", "The crash followed the grass running out.", "Food becomes limiting."], hint: "What limits the rabbits once the foxes are gone?", explain: "Predators help keep prey below the level their food supply can support. Without them, the prey overshoot, destroy their food, and crash." }
]);
KH("t18s2", [
{ f: "G", k: "d", b: 5, q: "Which bar chart shows the energy at four trophic levels (producers → top carnivores)?", gch: [{ bars: [100, 10, 1, 0.1] }, { bars: [100, 50, 25, 12] }, { bars: [25, 25, 25, 25] }, { bars: [10, 30, 60, 100] }], gax: ["producers → top carnivores", "energy"], choices: ["Each level has about one tenth of the level below", "Each level has half of the level below", "All levels have the same energy", "Energy increases up the food chain"], why: ["Usually only about 10% passes on, not 50%.", "Energy is lost at every level.", "That's upside down: energy is lost, not gained."], hint: "About 90% is lost at each step.", explain: "Most energy is used in respiration (lost as heat) or not eaten or digested, so roughly 10% passes to the next level." },
{ f: "S", k: "c", b: 5, q: "Sort each process: does it release CO₂ into the air or remove it?", bins: ["Releases CO₂", "Removes CO₂"], items: [["Photosynthesis", 1], ["Respiration by animals", 0], ["Burning fossil fuels", 0], ["Decomposers breaking down dead leaves", 0], ["A new forest growing", 1]], hint: "Only one process takes carbon out of the air.", explain: "Photosynthesis removes CO₂ (so growing forests store carbon). Respiration, decomposition and combustion return it." }
]);
KH("t18s3", [
{ f: "K", k: "i", b: 6, q: "Ecologists marked 60 snails with bright paint and released them. Later they caught 50, of which 12 were marked: estimate (60 × 50) ÷ 12 = 250. Birds found the painted snails more easily. How does this affect the estimate?", case: [["🐌", "First catch", "60 snails marked with bright paint and released."], ["🐌", "Second catch", "50 snails caught; 12 of them marked."], ["🐦", "Problem", "Birds spotted and ate painted snails more often."]], choices: ["An overestimate", "An underestimate: there must be fewer snails than the calculation shows", "No effect on the estimate, because predation affects every snail equally", "The estimate is exactly right, because bright paint makes recapture easier"], why: ["Fewer marked snails recaptured makes the estimate BIGGER.", "The method assumes marked and unmarked snails survive equally.", "One of the method's assumptions was broken."], hint: "What happens to the 12 if marked snails disappear?", explain: "N = (first catch × second catch) ÷ marked recaptured. If marks make animals more likely to die, fewer are recaptured, so N comes out too high. Marks must be harmless and hidden." },
{ f: "G", k: "i", b: 6, q: "Which graph shows the number of plant species found as more and more quadrats are sampled?", gch: [{ pts: [[0, 0], [2, 8], [4, 12], [6, 14], [10, 15], [14, 15]] }, { pts: [[0, 0], [14, 28]], smooth: false }, { pts: [[0, 10], [14, 10]], smooth: false }, { pts: [[0, 15], [14, 5]] }], gax: ["number of quadrats", "species found"], choices: ["Rises quickly, then levels off", "Rises in a straight line forever", "Stays the same", "Falls"], why: ["The habitat has a limited number of species, so new ones become rare.", "More quadrats find more species at first.", "You can't 'unfind' species you've already recorded."], hint: "How many new species does each extra quadrat add?", explain: "Early quadrats find many new species; later ones mostly find species already recorded. Where the curve levels off tells you that you have sampled enough." }
]);

/* ---------- Health and Diseases ---------- */
KH("t19s1", [
{ f: "V", k: "d", b: 5, q: "Antiseptic discs A, B and C, and a disc soaked in water (W), on a plate covered with bacteria. Which conclusion is best supported?", scene: { kind: "plate", discs: [{ lbl: "A", zone: 8 }, { lbl: "B", zone: 24 }, { lbl: "C", zone: 14 }, { lbl: "W", zone: 6 }] }, choices: ["B stopped bacterial growth over the widest area; the water disc had no effect, so it is a valid control", "A kills all the bacteria, as it has the smallest clear zone", "C is the most effective, as its zone is in the middle of the range", "B's clear zone is about 12 mm across, which shows it works well"], why: ["A has the smallest clear zone of the antiseptics.", "C's clear zone (about 14 mm) is smaller than B's (about 24 mm).", "Read the ruler: B's clear zone is about 24 mm across."], hint: "Compare the clear zones using the ruler.", explain: "B ≈ 24 mm, C ≈ 14 mm, A ≈ 8 mm, and W shows no clear zone beyond the disc itself. The control shows the effect comes from the antiseptics, not the disc." },
{ f: "S", k: "c", b: 5, q: "Sort each disease by how it usually spreads.", bins: ["Water or food", "Air (droplets)", "Animal vector", "Body fluids"], items: [["Cholera", 0], ["Influenza", 1], ["Dengue fever", 2], ["HIV", 3], ["Tuberculosis", 1], ["Malaria", 2]], hint: "Think about how each pathogen gets from person to person.", explain: "Cholera: contaminated water. Flu and TB: droplets. Dengue and malaria: mosquitoes. HIV: blood and other body fluids. Knowing the route tells you how to block it." }
]);
KH("t19s2", [
{ f: "S", k: "c", b: 5, q: "Sort each example: active or passive immunity?", bins: ["Active immunity", "Passive immunity"], items: [["Vaccination", 0], ["Antibodies passed across the placenta", 1], ["Recovering from chickenpox", 0], ["Antibodies in breast milk", 1], ["An injection of ready-made antibodies", 1], ["Memory cells are made", 0]], hint: "Who makes the antibodies?", explain: "Active: your own lymphocytes make antibodies and memory cells (long-lasting). Passive: you receive ready-made antibodies (fast, but short-lived)." },
{ f: "K", k: "d", b: 6, q: "A parent reads about a measles outbreak at a school. What is the best response?", case: [["🏫", "School", "1000 students; 92% vaccinated."], ["🦠", "Outbreak", "30 cases: 26 unvaccinated, 4 vaccinated."], ["💬", "Parent says", "'4 vaccinated children got measles, so the vaccine doesn't work.'"]], choices: ["Only 80 students were unvaccinated but they had 26 cases (about 1 in 3); the 920 vaccinated had 4 (under 1 in 200), so the vaccine greatly reduces risk", "The parent is right: if the vaccine worked, no vaccinated child would get measles", "The vaccine only works in some years, depending on the weather", "The unvaccinated children were just unlucky; the vaccine made little difference"], why: ["Compare RATES, not raw numbers.", "There's no evidence of that.", "1 in 3 vs 1 in 230 is far too big a difference for luck."], hint: "Work out the rate in each group.", explain: "Unvaccinated: 26 ÷ 80 ≈ 33%. Vaccinated: 4 ÷ 920 ≈ 0.4%. No vaccine is 100% effective, but it cuts the risk about 75 times." }
]);
KH("t19s3", [
{ f: "D", k: "d", b: 6, q: "Risk of type 2 diabetes at different body mass index (BMI) values (BMI 20 = 1). Which statement is best supported?", chart: { x: [20, 40, 5, "BMI"], y: [0, 20, 5, "relative risk"], series: [{ pts: [[20, 1], [25, 2], [30, 5], [35, 10], [40, 20]], dots: true }] }, choices: ["Risk rises steeply with BMI, roughly doubling with each 5-unit rise above 25", "A BMI below 25 removes all risk", "Risk rises in a straight line", "At BMI 40 the relative risk is 20"], why: ["A relative risk of 1 is the baseline, not zero.", "The curve gets steeper as BMI rises.", "A true reading, but not a conclusion."], hint: "Compare each step: 2 → 5 → 10 → 20.", explain: "The risk roughly doubles with each step above BMI 25, a steep, accelerating rise. Even modest weight loss in this range can cut the risk a lot." },
{ f: "S", k: "c", b: 5, q: "Sort each disease by its main cause.", bins: ["Mainly lifestyle", "Mainly genetic", "Infectious"], items: [["Type 2 diabetes", 0], ["Haemophilia", 1], ["Lung cancer from smoking", 0], ["Thalassaemia", 1], ["Tuberculosis", 2], ["Influenza", 2]], hint: "Can it spread? Is it inherited?", explain: "Infectious diseases are caused by pathogens. Genetic disorders are inherited. Many non-communicable diseases are strongly linked to lifestyle (genes can add some risk too)." }
]);
