
/* ============================================================
   5. Question bank. 15 questions per stage, Bloom levels 1–6.
   Array format: [bloom, question, choices (correct FIRST; shown shuffled), hint, explanation, exam tip?]
   Object format: dial locks, or questions with a diagram (svg) and fixed choice order (fix).
   ============================================================ */
const QB = {};
QB.t1s1 = [
[1, "Which ion is needed to make chlorophyll?", ["Magnesium (Mg²⁺)", "Iron (Fe²⁺)", "Calcium (Ca²⁺)", "Sodium (Na⁺)"], "Think of the green pigment in leaves.", "Magnesium is part of the chlorophyll molecule. Without it, leaves turn yellow."],
[1, "Which ion is part of haemoglobin?", ["Iron", "Magnesium", "Calcium", "Phosphate"], "Haemoglobin carries oxygen in red blood cells.", "Iron (Fe²⁺) is part of haemoglobin, which carries oxygen."],
[2, "Why is water called a good solvent in living things?", ["Many substances dissolve in it, so reactions can take place in solution", "It has no taste or smell", "It freezes at 0 °C", "It is found only inside cells"], "Where do most chemical reactions in cells happen?", "Many substances dissolve in water, so cell reactions happen in solution and dissolved substances can be transported."],
[2, "Why does sweating cool us down?", ["Evaporation of water from sweat takes heat away from the skin", "Sweat is colder than blood", "Sweat reflects sunlight", "Sweat stops the body from making heat"], "Water needs a lot of energy to change into vapour.", "When sweat evaporates, it absorbs a lot of heat energy from the skin, so the body cools.", "Say 'evaporation of sweat REMOVES heat', not just 'sweat is cold'."],
[2, "A farmer's crop has yellow leaves and grows poorly. Which ion might the soil lack?", ["Magnesium", "Calcium", "Iron", "Sodium"], "Yellow = not enough of the green pigment.", "Lack of magnesium means the plant cannot make enough chlorophyll, so leaves turn yellow (chlorosis). Lack of nitrate can do this too."],
[3, "Bao feels tired and looks pale. A doctor says Bao is anaemic. Which food would help most?", ["Red meat and green leafy vegetables (rich in iron)", "Milk (rich in calcium)", "Potato chips (rich in salt)", "Butter (rich in fat)"], "Anaemia = not enough haemoglobin.", "Iron is needed to make haemoglobin. Red meat and green leafy vegetables are good sources of iron."],
[3, "Which process in a cell needs water as a reactant?", ["Hydrolysis of starch into maltose", "Condensation of glucose into starch", "Diffusion of oxygen", "Absorption of light by chlorophyll"], "Hydro- means water, -lysis means splitting.", "In hydrolysis, water is added to break a large molecule into smaller ones, e.g. digestion of starch."],
{ b: 3, type: "dial", q: "Match each ion to its main job. Set each dial.", labels: ["Calcium", "Phosphate", "Nitrate"], dials: [["Bones & teeth", "Making DNA & ATP", "Making proteins"], ["Bones & teeth", "Making DNA & ATP", "Making proteins"], ["Bones & teeth", "Making DNA & ATP", "Making proteins"]], answer: [0, 1, 2],
  hint: "Nitrate contains nitrogen, which is in every amino acid.", explain: "Calcium builds bones and teeth (and helps blood clot). Phosphate is in DNA, ATP and phospholipids. Nitrate provides nitrogen to make amino acids and proteins." },
[4, "Water has a high specific heat capacity. What is the best explanation of why this matters to organisms?", ["Body temperature does not change quickly when the surroundings get hot or cold", "Water can dissolve many substances", "Water is easily pumped around the body", "Water can freeze from the top down"], "Specific heat capacity is about heating up or cooling down.", "A large amount of heat is needed to change the temperature of water, so the temperature of cells and bodies stays steady."],
[4, "A plant stem becomes soft and droops on a hot day. Which role of water does this show?", ["Water gives support by keeping cells turgid", "Water is a reactant in photosynthesis", "Water lubricates joints", "Water is a transport medium in blood"], "Firm plant cells are full of water.", "When cells lose water they are no longer turgid, so soft stems lose support and droop (wilt)."],
[4, "Blood plasma is about 90% water. What does this tell us about one role of water?", ["It is a transport medium for dissolved substances like glucose and urea", "It is used to make proteins", "It stores energy", "It makes blood red"], "What does plasma carry around the body?", "Plasma carries dissolved nutrients, wastes, hormones and ions. Water acts as the transport medium."],
[5, "Pom says: 'Iron and calcium are needed in large amounts, so they are not really important.' Which is the best judgement?", ["Wrong: minerals are needed in small amounts but their lack causes diseases such as anaemia and rickets", "Right: only carbohydrates and proteins matter", "Right: the body makes its own minerals", "Wrong: minerals give us most of our energy"], "Do minerals give energy? What happens if we lack them?", "Minerals are needed in small amounts and give no energy, but lacking them causes deficiency diseases (e.g. iron → anaemia; calcium → rickets / weak bones)."],
[5, "Two plants grow in solutions: A has all minerals; B has all minerals except magnesium. Which conclusion is best supported if only B has yellow leaves?", ["Magnesium is needed for healthy green leaves", "Magnesium is needed for roots only", "Magnesium is poisonous to plants", "Yellow leaves are caused by too much water"], "Only one factor was different between A and B.", "Since the only difference was magnesium, the yellow leaves in B show that magnesium is needed to make chlorophyll.", "In experiment questions, name the ONE variable that differs and link it to the result."],
[6, "You design an experiment to show that plants need nitrate. Which plan is best?", ["Grow identical seedlings in a complete mineral solution and in the same solution without nitrate; compare growth after some weeks", "Grow one seedling in soil and one in sand", "Grow seedlings in nitrate solution only", "Grow seedlings in the dark and in the light"], "A fair test changes only ONE thing.", "Use a complete solution as a control and remove only nitrate from the other. Keep all other conditions the same and compare growth (e.g. height, leaf colour)."],
[6, "You make a poster: 'Why we need water'. Which set of points is correct and complete?", ["Solvent, transport medium, reactant in hydrolysis and photosynthesis, temperature control, support, lubrication", "Gives energy, builds muscles, makes bones", "Stores fat, makes hormones, carries oxygen", "Only for quenching thirst"], "Water gives no energy. List its jobs.", "Water is a solvent, a transport medium, a reactant, helps control temperature, supports plant cells and lubricates (e.g. mucus, joints)."]
];
QB.t1s2 = [
[1, "Which of these is a monosaccharide?", ["Glucose", "Starch", "Sucrose", "Cellulose"], "Mono = one sugar unit.", "Glucose is a single sugar unit (monosaccharide). Sucrose is a disaccharide; starch and cellulose are polysaccharides."],
[1, "Which reagent is used to test for starch?", ["Iodine solution", "Benedict's solution", "Biuret reagent", "DCPIP"], "The positive result is blue-black.", "Iodine solution turns from brown to blue-black when starch is present."],
[2, "Maltose is made of which two sugar units?", ["Glucose + glucose", "Glucose + fructose", "Glucose + galactose", "Fructose + fructose"], "Maltose is made when starch is digested.", "Maltose = glucose + glucose. Sucrose = glucose + fructose. Lactose = glucose + galactose."],
[2, "What happens in a condensation reaction?", ["Two molecules join and a water molecule is released", "A molecule is split by adding water", "A sugar is heated with Benedict's", "Water vapour turns into liquid"], "Condensation → water comes OUT.", "In condensation, two molecules are joined and water is released. Hydrolysis is the reverse."],
[2, "Why is glycogen a good energy store in animals?", ["It is insoluble and compact, and can be quickly hydrolysed to glucose", "It dissolves easily in blood", "It is a protein that makes muscles", "It cannot be broken down"], "Stores should stay put and be easy to use.", "Glycogen is insoluble (does not affect osmosis), compact, and can be broken down into glucose quickly when needed."],
[3, "Bao heats a food sample with Benedict's solution. It turns brick-red. What does this show?", ["A reducing sugar is present", "Starch is present", "Protein is present", "Fat is present"], "Benedict's test: blue → green → yellow → brick-red.", "A brick-red precipitate shows a reducing sugar (e.g. glucose or maltose) is present."],
[3, "A peanut is rubbed on paper. After drying, a translucent spot remains. What does the peanut contain?", ["Lipid", "Starch", "Protein", "Vitamin C"], "Which food leaves a see-through mark?", "Lipids leave a translucent (grease) spot on paper that does not dry out. Water would dry away."],
{ b: 3, type: "dial", q: "Set each dial to the correct storage or structural carbohydrate.", labels: ["Energy store in plants", "Energy store in animals", "Plant cell walls"], dials: [["Starch", "Glycogen", "Cellulose"], ["Starch", "Glycogen", "Cellulose"], ["Starch", "Glycogen", "Cellulose"]], answer: [0, 1, 2],
  hint: "Animals store glycogen in the liver and muscles.", explain: "Plants store starch; animals store glycogen; cellulose forms plant cell walls (and is dietary fibre for us)." },
[4, "A triglyceride is broken down in digestion. What are the products?", ["Glycerol and three fatty acids", "Glucose and fructose", "Amino acids", "Glycerol and three glucose"], "Tri- = three.", "A triglyceride is made of one glycerol and three fatty acids joined by condensation. Hydrolysis releases them again."],
[4, "Why do hibernating bears store fat rather than carbohydrate?", ["Fat stores about twice as much energy per gram and also insulates the body", "Fat dissolves in blood more easily", "Fat is easier to digest than sugar", "Carbohydrates cannot be stored"], "Compare energy per gram and other jobs of fat.", "Lipids release about twice as much energy per gram as carbohydrates, so they are a light, compact store. A fat layer also insulates against cold."],
{ b: 4, q: "Four food tests were done (see diagram). Which tube shows starch is present?", svg: "tubes", fix: true, choices: ["Tube A", "Tube B", "Tube C", "Tube D"], answer: 0,
  hint: "Iodine + starch gives a very dark colour.", explain: "Tube A is blue-black: iodine + starch. B (brick-red) shows reducing sugar, C (purple) shows protein, D (blue) is a negative Benedict's result." },
[5, "Pom says: 'Sucrose must be a reducing sugar because it is sweet.' Which is the best response?", ["Not correct: sucrose is a non-reducing sugar; it gives a negative Benedict's test unless it is hydrolysed first", "Correct: all sweet sugars are reducing sugars", "Correct: sucrose turns iodine blue-black", "Not correct: sucrose is a protein"], "Is taste a scientific test?", "Sweetness is not evidence. Sucrose is a non-reducing sugar. It must first be hydrolysed (boiled with acid, then neutralised) before Benedict's gives a positive result."],
[5, "A student concludes 'this food has no sugar' because the Benedict's test stayed blue. What is the weakness?", ["It only shows there is no reducing sugar; a non-reducing sugar like sucrose could still be present", "Benedict's always stays blue", "The student should have used iodine", "Blue means a lot of sugar"], "Which sugars does Benedict's detect directly?", "Benedict's detects reducing sugars only. Sucrose would need hydrolysis first, so the conclusion is too strong."],
[6, "You want to find out which of three drinks contains the most reducing sugar. Which plan is best?", ["Add the same volume of each drink to the same volume of Benedict's, heat for the same time, and compare the colour or amount of precipitate", "Taste each drink", "Add iodine to each drink", "Heat the drinks without any reagent"], "Keep the test fair and semi-quantitative.", "Use equal volumes and heating times so only the drink differs. The colour (green → yellow → orange → brick-red) shows which has more reducing sugar."],
[6, "Bao wants to design a snack for a long hike. Which combination is most sensible?", ["Starchy food for steady energy, some fat for a compact energy store, and water", "Only sweets for instant sugar", "Only water, since it gives energy", "Only protein, since it is the main energy source"], "Which nutrient is the main energy source, and which is the most compact store?", "Carbohydrates (especially starch) give steady energy; fat stores a lot of energy per gram; water is needed but gives no energy."]
];
QB.t1s3 = [
[1, "What are the building units of proteins?", ["Amino acids", "Glucose", "Fatty acids", "Nucleotides"], "There are about 20 kinds of them.", "Proteins are made of amino acids joined by peptide bonds."],
[1, "Which test shows a purple colour when protein is present?", ["Biuret test", "Iodine test", "Benedict's test", "Grease spot test"], "Blue reagent → purple/violet.", "In the Biuret test, the blue solution turns purple when protein is present."],
[2, "What bond joins two amino acids together?", ["Peptide bond", "Glycosidic bond", "Hydrogen bond only", "Ester bond"], "A chain of amino acids is called a polypeptide.", "Amino acids are joined by peptide bonds in condensation reactions, forming polypeptides."],
[2, "Why does cooking an egg turn its clear egg white solid and white?", ["Heat denatures the proteins, changing their shape permanently", "Heat turns protein into fat", "Heat adds more amino acids", "Heat makes the protein dissolve"], "Can you uncook an egg?", "High temperature breaks the bonds that hold the 3-D shape. The proteins denature and cannot return to their original shape."],
[2, "Which statement about DNA is correct?", ["It is a nucleic acid made of nucleotides that stores genetic information", "It is a protein made of amino acids", "It is a lipid in the cell membrane", "It is a carbohydrate energy store"], "DNA's building units are nucleotides.", "DNA is a nucleic acid. Its sequence of bases stores the genetic code for making proteins."],
[3, "Insulin controls blood sugar. What type of molecule is it?", ["A protein (hormone)", "A carbohydrate", "A lipid", "A nucleic acid"], "Many hormones and all enzymes (nearly) are made of the same molecule type.", "Insulin is a protein hormone made of amino acids."],
[3, "Maron adds orange juice drop by drop to blue DCPIP solution. The blue colour disappears. What does this show?", ["Vitamin C is present", "Starch is present", "Protein is present", "Fat is present"], "DCPIP is decolourised by one vitamin.", "Vitamin C decolourises blue DCPIP. The fewer drops of juice needed, the more vitamin C it has."],
{ b: 3, type: "dial", q: "Match each protein to its job.", labels: ["Keratin", "Antibody", "Haemoglobin"], dials: [["Structure (hair, nails)", "Defence against germs", "Carrying oxygen"], ["Structure (hair, nails)", "Defence against germs", "Carrying oxygen"], ["Structure (hair, nails)", "Defence against germs", "Carrying oxygen"]], answer: [0, 1, 2],
  hint: "Antibodies are made by white blood cells.", explain: "Keratin is a structural protein in hair and nails; antibodies defend the body; haemoglobin carries oxygen in red blood cells." },
[4, "Two proteins both have 100 amino acids, but different functions. What is the most likely reason?", ["Their amino acid sequences are different, so they fold into different shapes", "One is made of glucose", "They have a different number of peptide bonds", "One is a lipid"], "Sequence → shape → function.", "The order of amino acids decides how the chain folds into a 3-D shape, and the shape decides its function."],
[4, "Which feature is found in proteins but NOT in carbohydrates?", ["Nitrogen atoms", "Carbon atoms", "Hydrogen atoms", "Oxygen atoms"], "Amino acids contain an amino group.", "Carbohydrates contain only C, H and O. Proteins also contain nitrogen (and often sulphur)."],
[4, "Why does a high fever (e.g. 42 °C) become dangerous?", ["Body proteins such as enzymes may start to denature and stop working", "Proteins turn into sugar", "The body makes too much DNA", "Water in cells begins to boil"], "What does heat do to protein shape?", "At high temperature, enzymes and other proteins change shape (denature), so metabolism is disturbed."],
[5, "Lulu says: 'A food that gives a negative Biuret test must contain no nitrogen at all.' Which is the best judgement?", ["Too strong: it shows no protein was detected, but other nitrogen compounds (e.g. DNA) might be present, or protein may be too little to detect", "Correct: all nitrogen is in proteins", "Correct: Biuret tests for nitrogen", "Wrong: Biuret tests for starch"], "What exactly does the Biuret test detect?", "The Biuret test detects peptide bonds in proteins. A negative result does not rule out other nitrogen compounds or very small amounts of protein."],
[5, "Which explanation of why protein is important for teenagers is best?", ["Proteins provide amino acids to build new cells and tissues for growth and repair, and to make enzymes and antibodies", "Proteins are the main source of quick energy", "Proteins store vitamins", "Proteins make bones hard by themselves"], "Teenagers are still growing.", "Growth needs new cells, which need proteins. Proteins also form enzymes, hormones and antibodies."],
[6, "You are given an unknown white powder. Which set of tests would identify whether it has starch, reducing sugar and protein?", ["Iodine (blue-black), Benedict's with heating (brick-red), Biuret (purple), each on a separate sample", "Only Benedict's", "Only iodine, repeated three times", "Heat the powder and smell it"], "Each food substance needs its own test.", "Use separate samples: iodine for starch, Benedict's + heat for reducing sugar, Biuret for protein. Record colour changes."],
[6, "You want to compare vitamin C in fresh and boiled orange juice. Which plan is best?", ["Add each juice drop by drop to the same volume of DCPIP; count drops needed to decolourise it; repeat and compare", "Add iodine to each juice", "Taste both juices", "Heat both with Benedict's"], "Fewer drops = more vitamin C.", "Measure the number of drops needed to decolourise a fixed volume of DCPIP. Repeat for reliability. Boiled juice usually needs more drops, because heat destroys vitamin C."]
];
