
/* ============================================================
   Extra question bank (Study mode levels + the See/Data/Investigate locks).
   These files load AFTER every older bank, so KB() appends and no saved question id ever moves.
   KX(stage, [[skill, bloom, question, [correct, ...3 wrong], hint, explain, tip?], ...])
   skill letters as in SKILL_TAGS: c concept · s see · d data · i invest (the `skill` field is set directly).
   Each stage gets about 8: Easy (Bloom 1–2), Medium (3–4) and Hard (5–6), across concept, data and investigate.
   ============================================================ */
const KX_SKILL = { c: "concept", s: "see", d: "data", i: "invest" };
const KX = (id, list) => KB(id, list.map(([k, b, q, choices, hint, explain, tip]) => Object.assign({ skill: KX_SKILL[k], b, q, choices, hint, explain }, tip ? { tip } : {})));

/* ---------- Topic 1: Molecules of Life ---------- */
KX("t1s1", [
["c", 2, "Which property of water lets blood plasma carry glucose, ions and urea around the body?", ["Water is a good solvent", "Water has a low specific heat capacity", "Water is non-polar", "Water cannot form hydrogen bonds"], "Think about what plasma does to glucose and salts.", "Water is polar, so many substances dissolve in it. Dissolved substances can then be transported in plasma, xylem and phloem."],
["d", 2, "A sports-drink label lists per 100 mL: sodium 40 mg, potassium 20 mg, calcium 10 mg, magnesium 5 mg. Which ion is present in the greatest amount?", ["Sodium", "Potassium", "Calcium", "Magnesium"], "Find the biggest number.", "Sodium is 40 mg per 100 mL, the largest value. It replaces the sodium lost in sweat."],
["c", 4, "Why do we feel cooler when sweat evaporates from our skin?", ["Evaporating water takes a lot of heat energy from the skin", "Sweat is colder than blood", "Sweat blocks heat from entering the body", "The salt in sweat absorbs heat"], "Changing liquid water into vapour needs energy.", "Water has a high latent heat of vaporisation. Each gram that evaporates removes a lot of heat from the skin, so the body cools."],
["d", 4, "Over one sunny day the air temperature changed from 10 °C to 30 °C, but a pond's water only changed from 18 °C to 21 °C. What best explains this?", ["Water has a high specific heat capacity", "Water is a good solvent", "Water is less dense as ice", "The pond had no sunlight"], "A lot of energy is needed to warm water up.", "Water must absorb a lot of heat energy to rise in temperature, so ponds and cells stay at a stable temperature. This protects aquatic life."],
["i", 4, "A student tests whether seedlings need magnesium ions for healthy leaves. Which set-up is the control?", ["Seedlings in a complete mineral solution", "Seedlings in a solution lacking only magnesium", "Seedlings in distilled water", "Seedlings kept in the dark"], "The control has everything, so it can be compared.", "The control has all the minerals. Any difference in the magnesium-free set can then be put down to the missing magnesium alone."],
["c", 5, "A plant grown without nitrate has yellow older leaves and very little growth. Which explanation is best?", ["Nitrogen is needed for proteins and chlorophyll", "Nitrate is needed only to make cellulose for new cell walls", "Nitrate is the plant's energy source, so without it growth stops", "Nitrate is needed to make starch, which stores energy"], "Which molecules contain nitrogen?", "Amino acids (so proteins) and chlorophyll contain nitrogen. Without nitrate the plant cannot make new proteins for growth. Cellulose and starch contain no nitrogen."],
["d", 5, "Survey of women: Group A eats 8 mg iron a day, 30% are anaemic; Group B eats 15 mg, 10% anaemic; Group C eats 18 mg, 9% anaemic. Which conclusion is best supported?", ["Anaemia falls as iron intake rises, but the benefit levels off above about 15 mg a day", "Iron intake has no link with anaemia", "Eating 18 mg a day removes anaemia completely", "Anaemia is caused only by low iron"], "Compare the drop from A to B with the drop from B to C.", "From 8 to 15 mg anaemia drops by 20 percentage points; from 15 to 18 mg it drops by only 1. Some women in C are still anaemic, so other causes exist too.", "Describe the trend, then any change in the trend, and quote numbers."],
["i", 5, "Magnesium-free seedlings had yellow leaves after a week. A classmate says this proves magnesium is part of the chlorophyll molecule. What is the best evaluation?", ["It shows magnesium is needed for green leaves, but not that magnesium is inside chlorophyll", "It fully proves it", "It shows magnesium is not needed", "It proves magnesium is part of every protein"], "What exactly did the experiment measure?", "The experiment shows that magnesium is needed for leaves to stay green. Knowing it is part of chlorophyll needs other evidence, such as the molecule's structure.", "A conclusion must not claim more than the results show."]
]);
KX("t1s2", [
["c", 2, "Which carbohydrate is the main energy store in plant cells?", ["Starch", "Glycogen", "Cellulose", "Sucrose"], "Iodine turns it blue-black.", "Plants store glucose as starch. Animals and fungi store it as glycogen; cellulose is structural, in cell walls."],
["d", 2, "Energy released per gram: carbohydrate 17 kJ, protein 17 kJ, lipid 39 kJ. About how many times more energy does 1 g of lipid release than 1 g of carbohydrate?", ["About 2 times", "About 4 times", "About the same", "About 22 times"], "Divide 39 by 17.", "39 ÷ 17 ≈ 2.3, so lipid releases a little over twice as much energy per gram. This makes fat a compact long-term store."],
["c", 4, "Why is glycogen well suited to storing energy in liver and muscle cells?", ["It is compact and insoluble, and its many branches let glucose be released quickly", "It dissolves easily so it moves in the blood", "It holds more energy per gram than fat", "It is made of amino acids"], "Think about shape and solubility.", "Glycogen is insoluble, so it does not affect osmosis, and it is compact. Its many branch ends let enzymes remove glucose fast when energy is needed."],
["d", 4, "Four drinks were boiled with Benedict's solution. Colours: A blue, B green, C orange, D brick-red. Which order goes from LEAST to MOST reducing sugar?", ["A, B, C, D", "D, C, B, A", "B, A, D, C", "A, C, B, D"], "Blue means none; brick-red means a lot.", "The colour goes blue → green → yellow → orange → brick-red as reducing sugar increases, so A < B < C < D."],
["i", 3, "Which is the correct method for the ethanol emulsion test for lipids?", ["Shake the food with ethanol, pour the ethanol into water, look for a cloudy white emulsion", "Add iodine, heat, look for blue-black", "Add Benedict's solution, boil, look for brick-red", "Add water first, then ethanol, look for a clear solution"], "Lipids dissolve in ethanol but not in water.", "The lipid dissolves in ethanol. Poured into water, it comes out as tiny droplets, giving a cloudy white emulsion."],
["c", 5, "Sucrose gives a negative Benedict's test. After boiling with dilute acid and neutralising, it turns brick-red. Why?", ["The acid hydrolyses sucrose into glucose and fructose, which are reducing sugars", "The acid turns sucrose into starch", "The acid makes Benedict's solution more sensitive", "Boiling destroys the sucrose"], "Sucrose is a disaccharide.", "Acid breaks the glycosidic bond, giving glucose and fructose. Both are reducing sugars, so the test is now positive. This is the test for non-reducing sugars."],
["d", 5, "After a Benedict's test on equal volumes, juice X gave 0.8 g of precipitate and juice Y gave 0.4 g. A student says X contains twice as much sugar as Y. What is the best comment?", ["It is only fair for reducing sugars; any sucrose in the juices was not detected", "Wrong: Y has more sugar", "Precipitate mass is not linked to sugar", "Correct for every kind of sugar"], "Which sugars does Benedict's detect without acid?", "More precipitate means more reducing sugar, so X has about twice the reducing sugar. Sucrose is not detected unless it is hydrolysed first."],
["i", 5, "Why is filtering, drying and weighing the Benedict's precipitate better than judging its colour by eye?", ["It gives a number", "It removes the sugar, so the test can be repeated", "It makes the test faster, as no colour needs to be judged", "The colour never changes, so it can't be used to compare samples"], "Different people judge colours differently.", "Colour judgments are subjective. A mass is a quantitative measurement that can be compared, repeated and averaged."]
]);
KX("t1s3", [
["c", 2, "What are the monomers that join to make proteins?", ["Amino acids", "Glucose", "Nucleotides", "Fatty acids and glycerol"], "They are joined by peptide bonds.", "Proteins are polypeptides: chains of amino acids joined by peptide bonds."],
["d", 2, "Biuret test results: egg white purple, glucose solution blue, milk purple, water blue. Which contain protein?", ["Egg white and milk", "Glucose solution and water", "All four", "Only egg white"], "Purple is positive.", "Biuret solution turns purple (lilac) with protein and stays blue without it."],
["c", 4, "Why does boiling an egg change the egg white for good?", ["Heat breaks the bonds holding the protein's 3D shape, so it denatures and cannot refold", "Heat breaks proteins into amino acids", "Heat turns protein into fat", "Heat adds water to the protein"], "Shape is everything for a protein.", "Heat breaks the weak bonds that hold the folded shape. The protein unfolds (denatures). The peptide bonds stay intact, so it is not broken into amino acids."],
["d", 4, "A DNA sample is 30% adenine. What percentage is guanine?", ["20%", "30%", "40%", "70%"], "A pairs with T; G pairs with C.", "A = T = 30%, so A + T = 60%. That leaves 40% for G + C, and G = C, so G = 20%."],
["i", 3, "What is the best control for a biuret test on a food sample?", ["Distilled water with biuret solution, to show the colour without protein", "Glucose heated with Benedict's solution", "Starch with iodine", "The food sample with no reagent"], "The control shows the 'negative' colour.", "Water plus biuret solution shows the colour you get with no protein (blue), so a lilac test result can be compared fairly."],
["c", 5, "Two proteins contain exactly the same number and types of amino acids but have different functions. What best explains this?", ["Different sequences fold differently", "One has more peptide bonds holding the chain together", "One contains glucose joined to the amino acids", "This is impossible: the same amino acids always make the same protein"], "Order matters.", "The sequence of amino acids decides how the chain folds, and the shape decides the function. Same amino acids in a different order give a different protein."],
["d", 5, "Sample 1: A 20%, T 20%, G 30%, C 30%. Sample 2: A 25%, U 25%, G 30%, C 20%. Which conclusion is best?", ["Sample 1 is double-stranded DNA; Sample 2 is single-stranded RNA", "Both are DNA", "Sample 2 is double-stranded DNA", "Sample 1 is RNA because G = C"], "Look for uracil, and check whether the bases pair up.", "Sample 1 has T and A = T, G = C, so it is double-stranded DNA. Sample 2 has U (RNA) and G ≠ C, so its bases are not paired: single-stranded."],
["i", 5, "A biuret test gives a very pale lilac that is hard to judge. What is the best improvement?", ["Use side-by-side controls on white", "Boil the mixture with the biuret reagent until the colour gets darker", "Add iodine as well, so that the protein turns a stronger purple colour", "Use less food, so the colour of the food itself doesn't hide the result"], "Give the eye something to compare with.", "Side-by-side controls on a white background make a faint colour change much easier to judge fairly."]
]);

/* ---------- Topic 2: Cellular Organisation ---------- */
KX("t2s1", [
["c", 2, "Which statement is part of the cell theory?", ["All living things are made of one or more cells", "All cells have a nucleus", "Cells can form from non-living matter", "Only animals are made of cells"], "It applies to all life.", "The cell theory says all organisms are made of cells, the cell is the basic unit of life, and new cells come only from existing cells."],
["d", 2, "A microscope has a ×10 eyepiece and a ×40 objective lens. What is the total magnification?", ["×400", "×50", "×4", "×4000"], "Multiply the two lenses.", "Total magnification = eyepiece × objective = 10 × 40 = ×400."],
["c", 4, "Why can an electron microscope show ribosomes when a light microscope cannot?", ["Higher resolution (shorter wavelength)", "It has a much brighter lamp, so the small ribosomes can be lit up clearly", "It stains the ribosomes with special dyes that a light microscope can't use", "It uses living cells, so the ribosomes are moving and easier to spot"], "Resolution is about telling two close points apart.", "Resolution is limited by wavelength. Electrons have a far shorter wavelength than light, so tiny structures like ribosomes can be seen as separate."],
["d", 4, "A cell's image is 30 mm long at ×600 magnification. What is its actual length?", ["50 µm", "18 000 mm", "5 µm", "0.5 mm"], "Actual = image ÷ magnification.", "30 mm ÷ 600 = 0.05 mm = 50 µm (1 mm = 1000 µm).", "Convert to µm at the end and show the formula."],
["i", 4, "Why is only a thin layer of onion epidermis used to make a slide?", ["So light can pass through and the cells do not overlap", "So it dries out faster", "So it does not need a stain", "So it is magnified more"], "Light microscopes shine light through the specimen.", "Light must pass through the specimen. A single thin layer of cells lets you see each cell clearly without overlap."],
["c", 5, "A student says, 'An electron microscope is always better than a light microscope.' What is the best evaluation?", ["Not always: it can't show living cells or colour", "Yes, it can see everything", "No, light microscopes have higher resolution", "Yes, it is cheaper and smaller"], "Think about living cells and cost.", "Electron microscopes resolve far more detail, but they are expensive, specimens must be dead, and colours are added later. Light microscopes can watch living cells."],
["d", 5, "At ×400, one eyepiece-graticule unit equals 2.5 µm. A cell spans 16 units. How long is the cell?", ["40 µm", "6.4 µm", "18.5 µm", "400 µm"], "Multiply units by the calibration.", "16 × 2.5 µm = 40 µm."],
["i", 5, "Why must the eyepiece graticule be calibrated again after switching from the ×10 to the ×40 objective?", ["Each division now covers a smaller real length", "The graticule gets bigger at higher magnification, so it must be measured again", "Calibration is only needed once, as long as the same microscope is used", "The stage micrometer changes size when the objective is changed"], "The graticule is in the eyepiece, not on the slide.", "The graticule does not change size, but the specimen is magnified 4× more, so each graticule unit covers a quarter of the real length. A new calibration with a stage micrometer is needed."]
]);
KX("t2s2", [
["c", 2, "Which organelle is the site of aerobic respiration?", ["Mitochondrion", "Ribosome", "Chloroplast", "Vacuole"], "The 'powerhouse' of the cell.", "Aerobic respiration (after glycolysis) happens in mitochondria and releases most of the cell's ATP."],
["d", 2, "Average mitochondria per cell: skin 200, liver 2000, muscle 3000. Which cell type probably uses the most energy?", ["Muscle cell", "Skin cell", "Liver cell", "They all use the same"], "More mitochondria, more respiration.", "Muscle cells have the most mitochondria, so they can release the most energy by aerobic respiration for contraction."],
["c", 4, "A cell has a cell wall, chloroplasts and a large permanent vacuole. Where did it most likely come from?", ["A plant leaf", "A human liver", "A bacterium", "A root deep in the soil"], "Chloroplasts need light.", "Cell wall plus large vacuole means a plant cell; chloroplasts mean a part exposed to light, such as a leaf. Root cells underground have no chloroplasts."],
["d", 4, "In pancreas cells that secrete enzymes, rough endoplasmic reticulum fills 35% of the cell area; in fat-storing cells it fills 3%. What best explains this?", ["They make lots of protein for secretion", "Fat cells need more protein than pancreas cells, so they make more ER", "Rough ER stores fat, so the pancreas needs less of it", "Rough ER makes glucose, which pancreas cells release into the blood"], "Enzymes are proteins.", "Rough ER is covered in ribosomes and makes proteins for secretion. Enzyme-secreting cells need a lot of it."],
["i", 3, "Why is iodine solution added when looking at onion cells?", ["To stain the cells", "To kill bacteria on the slide that might hide the cells", "To test the cells for protein, which turns them purple", "To make the cells swell so they are easier to see"], "Most cell parts are almost colourless.", "Stains add contrast. Iodine stains the nucleus and cell outline yellow-brown so they are easier to see."],
["c", 5, "Mature red blood cells have no nucleus and no mitochondria. What is a benefit AND a cost of this?", ["More room for haemoglobin, but they cannot divide or repair themselves and live about 120 days", "They respire faster, but carry less oxygen", "They live longer, but carry less oxygen", "They make more protein, but cannot carry carbon dioxide"], "Space vs maintenance.", "Without a nucleus there is more room for haemoglobin. But with no nucleus they cannot make new proteins, so they wear out and are replaced after about 120 days."],
["d", 5, "Muscle cells of trained athletes have about 40% more mitochondria than those of untrained people. Which conclusion is best supported?", ["Training is linked to more mitochondria, allowing more aerobic respiration for contraction", "Athletes have bigger nuclei", "Untrained muscles do not respire", "More mitochondria means less oxygen is used"], "This is a link (correlation) between training and mitochondria.", "More mitochondria allow more ATP from aerobic respiration. The data show a link with training; they do not show training is the only cause."],
["i", 5, "A student sees no chloroplasts in onion bulb cells and concludes that onion is not a plant. What is the best evaluation?", ["Wrong: the bulb grows underground with no light, so it lacks chloroplasts; it still has cell walls and a vacuole", "Correct", "Wrong, chloroplasts are too small to see under a light microscope", "Correct, every plant cell has chloroplasts"], "Not every plant cell photosynthesises.", "Only plant cells exposed to light have chloroplasts. The cell wall and large vacuole still show onion cells are plant cells."]
]);
KX("t2s3", [
["c", 2, "Which structure is found in BOTH prokaryotic and eukaryotic cells?", ["Ribosomes", "A nucleus", "Mitochondria", "Chloroplasts"], "Every cell must make proteins.", "All cells have a cell membrane, cytoplasm, DNA and ribosomes. Prokaryotes lack a nucleus and membrane-bound organelles."],
["d", 2, "A bacterium is 2 µm long and a liver cell is 20 µm long. How many times longer is the liver cell?", ["10 times", "100 times", "18 times", "2 times"], "Divide.", "20 ÷ 2 = 10. Eukaryotic cells are usually about 10–100 times bigger than prokaryotes."],
["c", 3, "Why is the cell membrane called 'partially permeable'?", ["Lets some substances through, not others", "It lets everything through, but slowly", "It is only partly made of lipid; the rest is protein", "It covers only part of the cell, leaving gaps"], "Some, not all.", "Small or lipid-soluble molecules cross easily; large or charged ones need proteins or cannot cross."],
["d", 4, "Beetroot cubes were left in ethanol. Colour of the liquid (absorbance): 0% 0.05, 20% 0.15, 40% 0.60, 60% 0.95. What does this show?", ["Higher ethanol concentrations damage the membrane more, so more red pigment leaks out", "Ethanol makes beetroot produce more pigment", "Membranes become less permeable in ethanol", "Ethanol has no effect below 60%"], "Pigment leaking out means the membrane is damaged.", "The red pigment is held inside the vacuole by membranes. Ethanol dissolves lipids, so the more ethanol, the more the membranes leak and the darker the liquid."],
["i", 4, "In the beetroot experiment, why are the cubes rinsed before being put into the test liquids?", ["To wash off pigment from cells cut open, so only pigment leaking through membranes is measured", "To cool them down, so the membranes are not damaged by heat", "To fill the cells with water, so they release pigment more easily", "To make them softer, so the pigment can leak out faster"], "Cutting bursts some cells.", "Cut surfaces release pigment from damaged cells. Rinsing removes it so it does not add to the reading."],
["c", 5, "Penicillin damages bacterial cell walls but does not harm human cells. Why?", ["Human cells have no cell wall, so there is nothing for penicillin to attack", "Human cells have thicker walls", "Penicillin cannot enter the blood", "Human cells are prokaryotic"], "What do bacteria have that we do not?", "Penicillin stops bacteria building their cell walls. Animal cells have no cell wall, so they are not affected."],
["d", 5, "Beetroot cubes in water at: 20 °C 0.10, 40 °C 0.12, 60 °C 0.70, 80 °C 0.95 (absorbance). Best explanation for the big jump between 40 and 60 °C?", ["Membrane proteins denature and the lipid layer becomes more fluid, so pigment leaks out", "More pigment is made at 60 °C, so more leaks out", "The cell wall melts at 60 °C, letting the pigment escape", "Water evaporates from the cubes, making the solution more concentrated"], "Membranes contain proteins.", "Above about 40 °C, membrane proteins denature and the bilayer becomes more fluid, leaving gaps. Pigment leaks out, so absorbance rises sharply."],
["i", 5, "At 30 °C one beetroot cube gave a very high reading while the other two were low. What should the student do?", ["Treat it as an anomaly and repeat", "Use only the high reading", "Change to a different temperature", "Throw away the whole experiment"], "One odd result among repeats...", "A result that does not fit the pattern of repeats is an anomaly. Repeat it, then leave it out of the mean if it is still odd and explain why."]
]);

/* ---------- Topic 3: Movement Across Membranes ---------- */
KX("t3s1", [
["c", 2, "Diffusion is the net movement of particles...", ["from a higher to a lower concentration, down a concentration gradient", "from a lower to a higher concentration, using energy", "of water only, across a membrane", "only inside living cells"], "Down the gradient.", "Diffusion is passive: particles spread from where they are more concentrated to where they are less concentrated."],
["d", 2, "Surface area : volume ratio is 6:1 for a 1 cm cube and 3:1 for a 2 cm cube. Which statement is correct?", ["The smaller cube has the larger surface area to volume ratio", "The bigger cube has the larger ratio", "Both ratios are the same", "Ratio does not depend on size"], "Compare 6 and 3.", "6:1 is bigger than 3:1. Small objects have more surface for each unit of volume."],
["c", 4, "Why does diffusion happen faster at a higher temperature?", ["Particles have more kinetic energy and move faster", "Membranes get thicker", "The concentration gradient reverses", "Particles get smaller"], "Heat = movement.", "At higher temperatures particles move faster, so they spread out more quickly."],
["d", 4, "Agar cubes of 1, 2 and 3 cm sides were left in acid for 5 minutes. Volume coloured: 100%, 78%, 52%. Which conclusion is best?", ["As cube size increases, SA:V falls, so a smaller fraction is reached by diffusion in the same time", "Bigger cubes take in acid faster, so more of each cube changes colour", "Diffusion only works in small cubes, so the largest cube shows no change", "Size has no effect: the differences are due to errors in timing"], "Look at the percentage, not the total.", "Bigger cubes have a lower SA:V and longer distances to the centre, so in 5 minutes diffusion colours a smaller fraction of them."],
["i", 3, "In the agar-cube experiment, which variables must be kept the same?", ["Acid concentration, temperature and time", "Cube size", "Percentage coloured", "Nothing needs to be controlled"], "Only cube size should change.", "Cube size is the independent variable and % coloured is measured. Everything else, such as acid strength, temperature and time, must stay the same."],
["c", 5, "Why do large multicellular organisms need transport systems when single-celled organisms do not?", ["Their SA:V is small and diffusion distances are long, so diffusion alone is too slow", "They have no cell membranes", "Diffusion does not happen in large organisms", "They need less oxygen"], "Think distance and ratio.", "In a large body, most cells are far from the surface. Diffusion over long distances is far too slow, so blood or xylem/phloem carry substances instead."],
["d", 5, "Rates of diffusion: concentration difference 10 → rate 4; 20 → 8; 40 → 16. With a membrane twice as thick at difference 20 → rate 4. Which statement fits?", ["Rate is proportional to the concentration difference and halves when the distance doubles", "Thickness has no effect", "Rate falls as concentration difference rises", "A thicker membrane doubles the rate"], "Check each doubling.", "Doubling the difference doubles the rate. Doubling the thickness (distance) halves it. This is why thin alveolus walls and steep gradients matter."],
["i", 5, "A student times how long dye takes to colour agar cubes fully, judging 'fully coloured' by eye. How could the method be made more accurate?", ["Measure the uncoloured centre at fixed times", "Use bigger cubes, so the colour takes longer and is easier to judge", "Do it in a hotter room, so the dye spreads faster and evenly", "Use only one cube, so there is less to watch at the same time"], "Replace a judgment with a measurement.", "Measuring the uncoloured centre at set times gives numbers instead of a subjective judgment, so results are more accurate and repeatable."]
]);
KX("t3s2", [
["c", 2, "Osmosis is the net movement of...", ["water across a partially permeable membrane, dilute to concentrated", "solute molecules moving down their concentration gradient through any membrane", "water molecules moving from a concentrated to a dilute solution using ATP", "any kind of particle moving through any membrane from high to low pressure"], "It is only about water.", "Osmosis is a special case of diffusion: water moves across a partially permeable membrane from a high water potential (dilute) to a low water potential (concentrated)."],
["d", 2, "A potato strip was 50 mm long before and 46 mm after soaking in a solution. What happened?", ["It lost water", "It gained water, because the solution was more dilute than the cell sap", "No osmosis happened; potato strips always shrink when cut", "It grew, because the cells divided while in the solution"], "Shorter means it shrank.", "The strip got shorter, so its cells lost water by osmosis to a more concentrated solution."],
["c", 4, "Why do red blood cells burst in pure water while plant cells do not?", ["Plant cells have a strong cell wall that stops them bursting; red blood cells have no wall", "Plant cells have no vacuole", "Red blood cell membranes are fully permeable", "Plant cells pump water out"], "What surrounds a plant cell?", "Both take in water by osmosis. The plant cell wall pushes back (turgor), so the cell becomes firm, not burst. Red blood cells swell until they burst (haemolysis)."],
["d", 4, "Potato mass change: 0 M +12%, 0.2 M +4%, 0.4 M −5%, 0.6 M −14%. Estimate the concentration giving no change in mass.", ["About 0.3 M", "0 M", "0.6 M", "Exactly 0.4 M"], "Where does the change cross zero?", "The change goes from +4% at 0.2 M to −5% at 0.4 M, so it crosses 0 at about 0.3 M. At that concentration, the solution matches the cell sap.", "Read the x-intercept from your line of best fit."],
["i", 4, "Why calculate the percentage change in mass rather than just the change in mass?", ["Starting masses differ", "It gives a bigger number that is easier to plot on the graph", "It removes the effect of water on the surface of the pieces", "It is quicker to calculate than the actual change in mass"], "Losing 1 g from 2 g is not the same as from 10 g.", "Pieces never start at exactly the same mass. Percentage change compares them fairly."],
["c", 5, "A gardener puts far too much fertiliser on a lawn and the grass wilts. Why?", ["Soil water becomes more concentrated than root cell sap, so water leaves root cells by osmosis", "Fertiliser blocks the xylem, so water can't reach the leaves", "Fertiliser burns the leaves with heat from the chemical reaction", "Roots take in too much water from the fertiliser and burst"], "Which way does water move now?", "Extra dissolved minerals lower the soil's water potential below that of root cells. Water leaves the roots by osmosis, so the plant loses turgor and wilts."],
["d", 5, "Onion cells plasmolysed: sucrose 0.3 M 0%, 0.4 M 10%, 0.5 M 50%, 0.6 M 90%. What is the best estimate of the concentration equal to the cell sap?", ["About 0.5 M", "0.3 M, the highest concentration where no cells are plasmolysed", "0.6 M, where most of the cells are clearly plasmolysed", "0 M, because the cell sap is mostly water"], "Use the 50% point.", "Incipient plasmolysis is taken where 50% of cells are plasmolysed. At about 0.5 M, the external solution balances the average cell sap."],
["i", 5, "In a potato experiment, some pieces were weighed 1 minute after removal and others 10 minutes after. What is the problem?", ["Blot and weigh all pieces the same way", "There is no effect, because water on the surface has no mass", "It makes the results more accurate, as some pieces dry a little", "It speeds up osmosis in the pieces that are weighed later"], "Water evaporates from the surface.", "Waiting lets surface water evaporate by different amounts. Blotting in the same way and weighing at once keeps this variable controlled."]
]);
KX("t3s3", [
["c", 2, "Active transport needs...", ["energy from respiration (ATP) and carrier proteins", "only a concentration gradient", "no membrane", "light energy"], "It goes against the gradient.", "Active transport moves substances against their concentration gradient through carrier proteins, using ATP from respiration."],
["d", 2, "Nitrate concentration: root hair cell 20 units, soil water 2 units. Which way does nitrate move by active transport?", ["Into the root cell, against the concentration gradient", "Out of the cell into the soil", "No movement", "Into the cell by diffusion"], "Which side is more concentrated?", "The cell already has more nitrate than the soil, so taking in more is against the gradient. That needs active transport."],
["c", 4, "Why do root hair cells contain many mitochondria?", ["To release energy for the active uptake of mineral ions", "To photosynthesise using light that reaches the soil", "To store water for times of drought", "To make the cellulose cell wall stronger"], "Active transport needs ATP.", "Mineral ions are often more concentrated in the root than in the soil, so they are taken in by active transport, which needs ATP from respiration in mitochondria."],
["d", 4, "Potassium uptake by roots: with oxygen 100 units per hour; without oxygen 15 units per hour. What best explains this?", ["Most uptake is active and needs aerobic respiration; a little happens by diffusion", "Oxygen blocks uptake, so it falls when oxygen is present", "All uptake is by diffusion, which oxygen speeds up", "Potassium needs light, so the plants were kept in the dark"], "What does oxygen allow cells to do?", "Without oxygen, aerobic respiration stops and little ATP is made, so active uptake falls. The small remaining uptake can be by diffusion."],
["i", 4, "To show ion uptake is active, a student adds a respiratory poison to one set of roots. What is the control?", ["Same roots and solution, no poison", "Roots in a solution with no ions, to show uptake needs ions", "Roots kept in the dark, to show uptake needs light", "Dead roots given the poison, to show the poison kills roots"], "Change only one thing.", "The control is identical except for the poison, so any difference in uptake is caused by stopping respiration."],
["c", 5, "Phagocytosis and active transport both use energy. Which describes the difference?", ["Phagocytosis engulfs large particles in a vesicle made from the membrane; active transport moves single ions or molecules through carrier proteins", "Phagocytosis moves water into the cell by osmosis through the membrane", "Active transport engulfs whole bacteria by wrapping the membrane around them", "They are the same process, just with different names for different cells"], "Size of what is moved.", "Phagocytosis takes in whole bacteria or debris by wrapping the membrane around them. Active transport pumps individual ions or molecules through carrier proteins."],
["d", 5, "Glucose uptake by gut cells: 10 °C 5, 20 °C 10, 37 °C 20, 50 °C 3 (units). Why does uptake drop at 50 °C?", ["Carrier proteins and respiratory enzymes denature, so active transport fails", "Glucose evaporates", "Diffusion stops at high temperature", "The cells grow larger"], "Proteins and heat.", "Up to 37 °C, faster respiration and movement raise uptake. At 50 °C the carrier proteins and enzymes denature, so active uptake falls sharply."],
["i", 5, "A student says an ion is taken up actively because it is more concentrated inside the cell. Which extra evidence would most strengthen this claim?", ["Uptake stops when respiration is blocked, even though the gradient is still there", "The ion is a mineral, and minerals are always taken up actively", "The cell is large, so it needs active transport to fill it", "Uptake only happens in the light, when the plant has more energy"], "Link uptake to energy.", "Showing that uptake depends on respiration (ATP) rules out diffusion. Concentration alone is only part of the evidence."]
]);

/* ---------- Topic 4: Cell Cycle and Division ---------- */
KX("t4s1", [
["c", 2, "In which stage of the cell cycle is DNA copied?", ["Interphase", "Metaphase", "Anaphase", "Telophase"], "Before division starts.", "DNA replicates during interphase, so each chromosome has two identical chromatids before mitosis begins."],
["d", 2, "In a root tip, 80 cells were in interphase and 20 were in mitosis. What percentage were dividing?", ["20%", "80%", "25%", "100%"], "20 out of 100.", "20 ÷ (80 + 20) × 100 = 20%. This is the mitotic index."],
["c", 4, "Why are the two daughter cells from mitosis genetically identical?", ["DNA is copied exactly and the chromatids are shared equally between them", "They swap genes", "One cell gets all the chromosomes", "They come from two parents"], "Copy, then split evenly.", "Each chromosome is copied exactly, and the two identical chromatids are pulled to opposite poles, so each new cell gets an identical set."],
["d", 4, "A cell cycle takes 24 hours. Of 200 cells, 10 are in mitosis. Estimate how long mitosis lasts.", ["1.2 hours", "10 hours", "12 hours", "0.5 hours"], "Fraction of cells × total time.", "10 ÷ 200 = 0.05 of cells are in mitosis, so mitosis takes about 0.05 × 24 = 1.2 hours."],
["i", 4, "Why is a root tip squashed and stained when making a slide to see mitosis?", ["To spread the cells and stain chromosomes", "To kill bacteria on the root tip so the slide stays clean", "To start mitosis in the root cells so stages can be seen", "To stop chromosomes forming, so the nucleus is clearer"], "Thin + coloured = visible.", "Squashing separates cells into one layer, and the stain colours chromosomes so the stages can be seen."],
["c", 5, "Many anti-cancer drugs stop cell division. Why do they often cause hair loss too?", ["They hit all fast-dividing cells", "They dissolve the hair along with the tumour cells", "Hair cells are actually cancer cells, so they are destroyed too", "The drugs stop meiosis, which is how hair grows"], "Which normal cells divide fast?", "The drugs cannot tell cancer cells from other fast-dividing cells, such as hair follicles and the gut lining, so these are damaged too."],
["d", 5, "The DNA content of a cell goes 2 units → rises to 4 → stays at 4 → drops to 2. When does the drop happen?", ["At the end of mitosis, when the cell divides into two", "During interphase, when the cell grows larger", "At prophase, when the chromosomes first become visible", "When DNA is copied, as the old strands are broken down"], "Rising is copying; falling is splitting.", "DNA doubles in interphase, stays doubled through mitosis, then halves when the cell splits into two daughter cells (cytokinesis)."],
["i", 5, "A student counts dividing cells in only one field of view at the very tip of a root and concludes that 30% of all root cells divide. What is the best criticism?", ["One field from the fastest-dividing area", "The method is fine, because the tip is where cells divide", "They should count only interphase cells to find the answer", "They should use a leaf instead"], "Is one field representative?", "Cell division is concentrated just behind the tip. One field there overestimates division in the whole root. More fields give a representative result."]
]);
KX("t4s2", [
["c", 2, "Meiosis produces...", ["four genetically different haploid cells", "two identical diploid cells", "four identical diploid cells", "two identical haploid cells"], "Two divisions, half the chromosomes.", "Meiosis has two divisions, giving four haploid cells. Crossing over and independent assortment make them all genetically different."],
["d", 2, "A human body cell has 46 chromosomes. How many are in a sperm cell?", ["23", "46", "92", "12"], "Gametes are haploid.", "Gametes carry one set of chromosomes: 46 ÷ 2 = 23."],
["c", 4, "Why is meiosis needed for sexual reproduction?", ["It halves the chromosome number, so fertilisation restores the diploid number", "It doubles the chromosome number", "It makes clones", "It repairs tissues"], "What happens at fertilisation?", "Two gametes fuse at fertilisation. If each had the full 46, the zygote would have 92. Meiosis halves the number so the zygote has 46."],
["d", 4, "An organism has 2n = 8 (4 pairs). How many chromosome combinations can its gametes have from independent assortment alone?", ["16", "8", "4", "64"], "2 to the power of the number of pairs.", "Each pair can line up two ways, so there are 2⁴ = 16 combinations. For humans it is 2²³, over 8 million."],
["i", 3, "A student measures the hand spans of 5 classmates to study variation. What is the best improvement?", ["Measure a much larger random sample", "Measure only the tallest students", "Measure each hand once more", "Use a longer ruler"], "Is 5 enough?", "Five people cannot show the pattern of variation. A large random sample shows the true distribution."],
["c", 5, "Identical twins raised apart differ in body mass by 8 kg. What does this show?", ["Body mass is affected by the environment as well as genes", "Body mass depends only on genes", "They are not really identical", "A mutation happened"], "Same genes, different results.", "Identical twins have the same genes, so differences between them must come from the environment, such as diet and exercise."],
["d", 5, "Heights of 100 students form a bell-shaped spread from 150 to 185 cm; their blood groups fall into 4 separate groups. Which conclusion is best?", ["Height continuous; blood group discontinuous", "Height is discontinuous and blood group is continuous", "Both are continuous", "Both are discontinuous"], "Range vs categories.", "A smooth range with a peak is continuous variation, usually polygenic and affected by the environment. Distinct categories are discontinuous, usually controlled by one gene."],
["i", 5, "A student wants to know whether fertiliser affects bean pod length. Which method is best?", ["Grow many plants from one seed batch with and without fertiliser, other conditions the same, and compare mean pod lengths", "Measure one pod from each plant, so every plant is included in the study", "Grow different bean varieties with and without fertiliser, to see more variation", "Compare pods bought from two shops, where one uses fertilised beans"], "Large samples, one variable.", "Pod length varies continuously, so many plants are needed, and only fertiliser should differ. Comparing means (and spread) shows any effect."]
]);
KX("t4s3", [
["c", 2, "Which type of cell division is used for growth and repair?", ["Mitosis", "Meiosis", "Fertilisation", "Pollination"], "Identical cells are needed.", "Mitosis makes genetically identical cells, which is what growth and repair need."],
["d", 2, "A cell with 20 chromosomes divides by mitosis. How many chromosomes does each daughter cell have?", ["20", "10", "40", "5"], "Mitosis keeps the number.", "Mitosis keeps the chromosome number the same: each daughter cell has 20."],
["c", 4, "Which happens in meiosis but NOT in mitosis?", ["Homologous chromosomes pair up and cross over", "Chromatids separate", "A spindle forms", "DNA is copied beforehand"], "Pairs swapping pieces.", "Only in meiosis I do homologous chromosomes pair up and exchange sections (crossing over). Spindles and chromatid separation happen in both."],
["d", 4, "DNA per cell: 6 pg at the start, 12 pg after copying, 6 pg after the first division, 3 pg after the second. Which process is this?", ["Meiosis", "Mitosis", "Fertilisation", "Binary fission"], "Two divisions, ending with half.", "Two divisions after one copy, ending at half the original DNA, is meiosis. Mitosis ends back at 6 pg after one division."],
["i", 4, "Why are anthers used to observe meiosis but root tips to observe mitosis?", ["Anthers make pollen (gametes) by meiosis; root tips grow by mitosis", "Root tips are bigger", "Anthers grow by mitosis only", "Anthers contain no DNA"], "Where are gametes made?", "Choose tissue where the process happens: pollen forms by meiosis in anthers, and root tips grow quickly by mitosis."],
["c", 5, "Asexual reproduction by mitosis is quick, but risky when the environment changes. Why?", ["Identical offspring: one disease could kill all", "It is very slow, so the population can't grow fast enough", "The offspring are all different, so some may not survive", "It needs two parents, which can be hard to find in a changing environment"], "No variation...", "Without variation, if one individual is not adapted to a new disease or condition, none are. Sexual reproduction gives variation for natural selection."],
["d", 5, "In a cell where 2n = 14, how many chromosomes (separated chromatids) are moving to the poles in total during anaphase of mitosis?", ["28", "14", "7", "56"], "Each chromosome has two chromatids.", "Each of the 14 chromosomes splits into 2 chromatids, so 28 are moving: 14 to each pole."],
["i", 5, "Onion root tips were grown in water or in a chemical. Which result best supports that the chemical inhibits mitosis?", ["Fewer dividing cells in treated tips (many fields, repeats)", "Bigger cells in the treated root tips, because they stop dividing and keep growing", "A darker stain in the treated roots, showing more chromosomes are present", "The same percentage in both, showing the chemical works only after a delay"], "Reliable, repeated, compared.", "A clearly lower mitotic index in the treated roots, from many fields and repeats, is good evidence that mitosis has been slowed."]
]);

/* ---------- Topic 5: Enzymes and Metabolism ---------- */
KX("t5s1", [
["c", 2, "What is an enzyme?", ["A protein that acts as a biological catalyst", "A carbohydrate that stores energy", "A hormone carried in the blood", "A fat"], "It speeds up reactions.", "Enzymes are proteins that speed up chemical reactions without being used up."],
["d", 2, "Starch was digested in 2 minutes with amylase and in 60 minutes without it. How many times faster was it with the enzyme?", ["30 times", "58 times", "2 times", "120 times"], "Divide 60 by 2.", "60 ÷ 2 = 30, so the enzyme made the reaction 30 times faster."],
["c", 4, "Why does an enzyme act on only one kind of substrate?", ["Its active site has a shape complementary to that substrate only", "It is too big", "It is used up", "It is made from the substrate"], "Lock and key.", "The active site has a specific shape. Only a substrate with a complementary shape can fit and form an enzyme-substrate complex."],
["d", 4, "Product formed: 1 min 10 mg, 2 min 18 mg, 3 min 23 mg, 4 min 25 mg, 5 min 25 mg. Why does it level off?", ["The substrate has run out", "The enzyme has been used up", "The enzyme was denatured by cold", "The enzyme changed into product"], "Enzymes are not used up.", "Enzymes are reused, so the reaction stops only when all the substrate has been turned into product."],
["i", 3, "To show amylase digests starch, a student tests a starch-amylase mixture with iodine every minute. What is the best control?", ["Starch with boiled amylase (or water) instead of active amylase", "Amylase with no iodine", "The starch at 0 minutes only", "Glucose with iodine"], "Remove only the active enzyme.", "Boiled amylase is denatured. If starch remains there but disappears with active amylase, the enzyme caused the change."],
["c", 5, "A student says catalase 'gives energy' to the reaction it speeds up. What is the best evaluation?", ["Wrong: enzymes lower the activation energy; they do not add energy", "Correct", "Wrong: enzymes raise the activation energy", "Correct: enzymes act as a fuel"], "What hill do enzymes lower?", "Enzymes provide a pathway with lower activation energy, so more molecules can react. They add no energy and are not used up."],
["d", 5, "With substrate in excess, initial rates were: enzyme concentration 1 → 5, 2 → 10, 4 → 20 units. Which conclusion is best?", ["Rate is proportional to enzyme concentration while substrate is in excess", "Rate falls as enzyme concentration rises", "Enzyme concentration has no effect", "Rate depends only on temperature"], "Double the enzyme, and...?", "Each doubling of enzyme doubles the rate, because there are twice as many active sites and plenty of substrate to fill them."],
["i", 5, "Why measure the initial rate instead of total product after 30 minutes when comparing enzyme concentrations?", ["Later, all tubes level off", "The initial rate is lower, so it's easier to measure", "Enzymes stop working after 30 minutes", "The total product is always the same, so it can't be measured"], "Every tube ends with the same product.", "Given time, every tube converts all its substrate. The initial rate is measured before substrate becomes limiting, so it shows the enzyme effect."]
]);
KX("t5s2", [
["c", 2, "What does 'optimum temperature' of an enzyme mean?", ["The temperature at which it works fastest", "The lowest temperature it works at", "The temperature at which it denatures", "Always 37 °C"], "Best = optimum.", "The optimum is the temperature giving the highest rate. For many human enzymes it is about 37 °C, but not for all enzymes."],
["d", 2, "Rate of pepsin: pH 1 → 6, pH 2 → 10, pH 4 → 4, pH 7 → 0. What is the optimum pH?", ["About pH 2", "pH 7, which is neutral and suits most enzymes in the body", "pH 1, the most acidic value tested", "pH 4, where the stomach becomes less acidic after a meal"], "Find the highest rate.", "The rate is highest at pH 2, which suits the acidic stomach where pepsin works."],
["c", 4, "Why does the rate of an enzyme reaction fall above the optimum temperature?", ["The active site changes shape", "Molecules move more slowly at high temperatures, so fewer collide", "The substrate denatures, so it can no longer bind to the enzyme", "The enzyme is used up faster at high temperatures"], "Heat breaks bonds in proteins.", "High temperatures break the bonds holding the enzyme's shape. The active site no longer fits the substrate."],
["d", 4, "Rates: 10 °C 4, 20 °C 8, 30 °C 16, 40 °C 22, 50 °C 6. What happens from 10 to 30 °C?", ["The rate doubles for each 10 °C rise", "The rate halves for each 10 °C rise", "The rate stays constant", "The rate triples for each 10 °C rise"], "4 → 8 → 16.", "4 to 8 to 16 is a doubling every 10 °C, because molecules move faster and collide more often."],
["i", 4, "When testing temperature on amylase, why are the starch and amylase kept in separate tubes in the water bath for 5 minutes before mixing?", ["So both reach the test temperature before the reaction starts", "To let the starch dissolve", "To denature the amylase", "To save time"], "Start at the right temperature.", "If they were mixed at room temperature, the reaction would start at the wrong temperature. Pre-warming both makes the test fair."],
["c", 5, "Enzymes from bacteria in hot springs have an optimum of 80 °C. What best explains this?", ["More bonds hold their shape", "They are not made of protein, so heat can't denature them", "Heat does not affect them at all, at any temperature", "They have no active site"], "Shape held by bonds.", "These enzymes are held together by extra bonds, so their active sites keep their shape at high temperatures. They still denature at even higher temperatures."],
["d", 5, "Substrate concentration vs rate: 0.1 → 5, 0.2 → 10, 0.4 → 16, 0.8 → 18, 1.6 → 18. What limits the rate above 0.8?", ["Enzyme concentration: all the active sites are occupied", "Substrate concentration", "A low temperature", "The enzyme has denatured"], "Adding more substrate does nothing.", "When more substrate no longer raises the rate, every active site is busy. Only more enzyme would raise the rate further."],
["i", 6, "A student found the optimum of an enzyme was 40 °C, but tested only 20, 40 and 60 °C. What is the best improvement?", ["Test more temperatures around 40 °C", "Repeat the test several times at 40 °C only, to make that result more reliable", "Test at 0 °C and 100 °C as well, so the full range of temperatures is covered", "Test the effect of pH instead, because temperature has already been tested"], "The true optimum could be anywhere from 21 to 59 °C.", "With only three temperatures, the real peak could be anywhere between 20 and 60 °C. Smaller intervals around 40 °C find it more precisely."]
]);
KX("t5s3", [
["c", 2, "Which enzymes are added to biological washing powders to remove food stains?", ["Proteases and lipases", "Amylase to dissolve clothing", "DNA polymerase", "Insulin"], "Stains contain protein and fat.", "Proteases digest protein stains (egg, blood) and lipases digest fat stains, so they wash out at lower temperatures."],
["d", 2, "A washing powder removes 90% of an egg stain at 40 °C but 20% at 90 °C. Which temperature should be used?", ["40 °C", "90 °C", "Both work the same", "Neither"], "Higher removal is better.", "At 40 °C the enzymes work well; at 90 °C they denature and remove much less stain."],
["c", 4, "How does a competitive inhibitor slow an enzyme?", ["It has a similar shape to the substrate and occupies the active site", "It binds elsewhere and changes the active site", "It destroys the enzyme", "It speeds up the reaction"], "It competes for the same place.", "A competitive inhibitor fits the active site, so fewer substrate molecules can bind. More substrate can outcompete it."],
["d", 4, "With inhibitor X, rate at low substrate is 20% of normal, but at very high substrate it is 95% of normal. What type of inhibitor is X?", ["Competitive: lots of substrate outcompetes it", "Non-competitive", "It is not an inhibitor", "It is another enzyme"], "Extra substrate rescues the rate.", "If more substrate restores the rate, the inhibitor must be competing for the active site."],
["i", 4, "Testing a biological washing powder on stained cloth, which is the best control?", ["Boiled powder, same cloth and stain", "No cloth at all, just powder and water, to see if the powder changes colour", "A different stain on the same cloth, washed with the same powder", "Hotter water with the same powder, to see if the enzymes work faster"], "Remove only the active enzymes.", "Boiling denatures the enzymes but keeps everything else in the powder, so any difference is due to the enzymes."],
["c", 5, "Mercury ions are non-competitive inhibitors. Why does adding more substrate not restore the rate?", ["They bind elsewhere and change the active site", "They compete with the substrate for the active site, so more substrate wins", "They add more enzyme to the reaction, which uses up the substrate", "They are a second substrate, which the enzyme prefers to break down"], "They do not compete.", "Non-competitive inhibitors bind elsewhere on the enzyme and distort the active site. Extra substrate cannot fix the changed shape."],
["d", 5, "Fruit-juice yield: no pectinase 40 mL; pectinase 10 min 60 mL; 20 min 70 mL; 40 min 72 mL. What is the best advice for a factory?", ["About 20 minutes is enough", "40 minutes doubles the yield, so it is always worth waiting", "Pectinase reduces the yield, as it breaks down the juice", "Time makes no difference once pectinase has been added"], "Compare 20 → 40 min with 0 → 20 min.", "Yield rises quickly to 70 mL by 20 min, then only 2 mL more in the next 20 min. Running longer costs time and energy for little gain."],
["i", 4, "A student compares lactase trapped in beads with free lactase by measuring glucose in milk after 5 minutes. Which variables must be controlled?", ["The amount of lactase, the volume of milk and the temperature", "The colour of the beads", "The final glucose reading", "The result of the glucose test strip"], "Only the enzyme form should differ.", "To compare fairly, only free vs immobilised should change. Glucose produced is what is measured."]
]);
