
/* Extra bank, part 2 (format: see q_x1.js). */

/* ---------- Topic 6: Photosynthesis ---------- */
KX("t6s1", [
["c", 2, "Through which pores do gases enter and leave a leaf?", ["Stomata", "Xylem vessels", "The cuticle", "Palisade cells"], "Guard cells open and close them.", "Carbon dioxide diffuses in and oxygen and water vapour diffuse out through stomata, mostly on the lower surface."],
["d", 2, "A leaf has 20 stomata per mm² on its upper surface and 250 per mm² on its lower surface. About how many times more are on the lower surface?", ["About 12 times", "About 2 times", "About 230 times", "About 25 times"], "Divide 250 by 20.", "250 ÷ 20 = 12.5. Most stomata are on the shaded lower surface, which reduces water loss."],
["c", 4, "Why are palisade mesophyll cells packed tightly just below the upper surface?", ["To absorb as much light as possible for photosynthesis", "To lose water quickly", "To store starch underground", "To protect the leaf from insects"], "Where does light hit first?", "Palisade cells are full of chloroplasts and sit where light is strongest, so they trap the most light."],
["d", 4, "A leaf takes in 10 units of CO₂ per hour in the light but gives out 2 units per hour in the dark. Why does it give out CO₂ in the dark?", ["Respiration continues but photosynthesis stops", "Photosynthesis releases CO₂", "The stomata are closed", "The leaf has died"], "Which process never stops?", "Leaves respire all the time. In the light, photosynthesis uses more CO₂ than respiration makes; in the dark only respiration happens, so CO₂ is released."],
["i", 4, "A student counts stomata from nail-varnish peels. Why count several fields of view on each peel?", ["Stomata are unevenly spread", "One field of view is too bright to count the stomata accurately", "Counting several fields makes the stomata open wider", "It is quicker than counting all the stomata in just one field"], "One field could be unusual.", "Counting several fields and taking a mean reduces the effect of an unusual patch, so the estimate is more reliable."],
["c", 5, "Many desert plants have stomata sunk in pits and surrounded by hairs. Why?", ["They trap moist air near each stoma", "They take in more CO₂ by trapping it in the hairs around each stoma", "They keep insects out, which would otherwise damage the guard cells", "They absorb more light, so the leaf can photosynthesise faster"], "Think about the air right outside the stoma.", "Still, humid air collects in the pit and among the hairs. The gradient for water vapour diffusion is smaller, so less water is lost by transpiration."],
["d", 5, "Leaves were greased with petroleum jelly and weighed after a day. Mass lost: no grease 20%; upper surface greased 18%; lower surface greased 4%; both greased 1%. Which conclusion is best?", ["Most water is lost through stomata, mainly on the lower surface", "The upper surface loses the most water", "Water is lost only through the cuticle", "Grease increases water loss"], "Grease blocks stomata.", "Blocking the lower surface cuts loss from 20% to 4%, so most water leaves through lower-surface stomata. Blocking the upper surface changes little."],
["i", 5, "In that experiment, the leaf greased on both surfaces still lost 1% of its mass. How should this result be used?", ["As a baseline", "Ignore it, the experiment failed", "It shows grease evaporates", "It shows the leaf respired all its mass"], "Not all water loss is through stomata.", "Some water escapes through the waxy cuticle and the cut petiole. The both-greased leaf shows this background loss, which helps interpret the others."]
]);
KX("t6s2", [
["c", 2, "Which pigment absorbs most of the light energy used in photosynthesis?", ["Chlorophyll", "Haemoglobin", "Melanin", "Keratin"], "It makes leaves green.", "Chlorophyll in the chloroplasts absorbs mainly red and blue light. Carotenoids help as accessory pigments."],
["d", 2, "On a chromatogram, a pigment moved 8 cm and the solvent front moved 10 cm. What is its Rf value?", ["0.8", "1.25", "2", "80"], "Rf = pigment distance ÷ solvent distance.", "Rf = 8 ÷ 10 = 0.8. Rf is always between 0 and 1."],
["c", 4, "Why do most leaves look green?", ["Chlorophyll absorbs red and blue light and reflects green light", "Chlorophyll absorbs mostly green light", "Leaves give out green light", "Green light passes through the stomata"], "We see the colour that is not absorbed.", "Green light is mostly reflected or transmitted, so it reaches our eyes. Red and blue light are absorbed for photosynthesis."],
["d", 4, "Rate of photosynthesis under different colours of light (same intensity): red 90, blue 100, green 15. Which conclusion is best?", ["Red and blue light are absorbed and used most; green is mostly reflected", "Green light is used most, because leaves are green", "Colour makes no difference, only light intensity matters", "Only blue light works, as red light is too weak"], "Compare green with the others.", "Rates are high in red and blue light, matching chlorophyll's absorption peaks. Green light gives a low rate because little is absorbed."],
["i", 4, "In paper chromatography of leaf pigments, why is the start line drawn in pencil, not ink?", ["Pencil graphite does not dissolve and run in the solvent", "Pencil is easier to see", "Ink makes pigments move faster", "Pencil absorbs the pigments"], "Ink is a mixture of dyes too.", "Ink would dissolve and separate along with the pigments, mixing up the results. Graphite stays put."],
["c", 5, "A variegated leaf (green and white parts) was kept in light and tested for starch. Only the green parts turned blue-black. What does this show?", ["Chlorophyll is needed for photosynthesis", "Light is needed for photosynthesis", "Carbon dioxide is needed", "White parts photosynthesise faster"], "What do the white parts lack?", "Both parts had the same light, CO₂ and water. Only the green (chlorophyll-containing) parts made starch, so chlorophyll is needed."],
["d", 5, "Solvent front 12 cm; spots at 11.4, 8.4, 7.2 and 6.0 cm. Reference Rf: carotene 0.95, xanthophyll 0.70, chlorophyll a 0.60, chlorophyll b 0.50. Which spot is chlorophyll a?", ["The spot at 7.2 cm", "The spot at 11.4 cm", "The spot at 8.4 cm", "The spot at 6.0 cm"], "Work out each Rf.", "7.2 ÷ 12 = 0.60, matching chlorophyll a. The others are 0.95 (carotene), 0.70 (xanthophyll) and 0.50 (chlorophyll b)."],
["i", 5, "A student's chromatogram shows one big green smear instead of separate spots. What is the most likely cause and fix?", ["The spot was too large or too dilute; apply a small, concentrated spot, drying between applications", "The solvent ran too long; stop it earlier", "The paper was too long; cut it shorter", "The leaf was too green; use a paler leaf"], "Good separation starts with a tiny spot.", "A wide or wet spot spreads out, so pigments overlap. Many tiny applications, dried each time, give a small concentrated spot that separates cleanly."]
]);
KX("t6s3", [
["c", 2, "Where do the light-dependent reactions happen?", ["Thylakoid membranes", "In the stroma, where carbon dioxide is fixed", "In the mitochondria, where energy is released", "In the nucleus, where the genes are kept"], "Stacks of membranes.", "Chlorophyll sits in the thylakoid membranes, where light energy is trapped to make ATP and NADPH and to split water."],
["d", 2, "A pondweed gave off 40 bubbles per minute with a lamp 10 cm away, 22 at 20 cm and 6 at 40 cm. At which distance was photosynthesis fastest?", ["10 cm", "20 cm", "40 cm", "All the same"], "Most bubbles = fastest.", "The most oxygen bubbles were produced at 10 cm, where light is most intense."],
["c", 4, "Where does the oxygen released by photosynthesis come from?", ["Water (photolysis)", "Carbon dioxide, which is split to release its oxygen", "Glucose, which gives off oxygen as it is made", "Chlorophyll, which releases oxygen when it absorbs light"], "Which reactant is split in the light?", "In the light-dependent reactions, water is split into hydrogen (electrons) and oxygen. The oxygen is released as a by-product."],
["d", 4, "Isolated chloroplasts were mixed with blue DCPIP dye. In light the dye turned colourless in 5 minutes; in the dark it stayed blue. What does this show?", ["The light-dependent reactions release electrons (reducing power) only in light", "DCPIP makes oxygen", "Chloroplasts work better in the dark", "Light destroys the dye"], "DCPIP loses its colour when it gains electrons.", "DCPIP is reduced (turns colourless) by electrons released in the light-dependent reactions. No light, no electrons, so it stays blue."],
["i", 4, "Why are isolated chloroplasts kept in ice-cold buffer solution before a DCPIP experiment?", ["To slow enzyme activity and prevent damage until the test starts", "To make them photosynthesise faster", "To kill them", "To dissolve the chlorophyll"], "Cold slows reactions.", "Low temperature slows enzymes that would damage the chloroplasts, and the buffer keeps the pH steady, so they stay working."],
["c", 5, "A plant is given water containing a heavy oxygen isotope (¹⁸O). Where does the label appear?", ["In the oxygen gas released", "In the glucose made", "In the carbon dioxide taken in", "Nowhere"], "Oxygen gas comes from which reactant?", "The O₂ released comes from splitting water, so the heavy oxygen appears in the oxygen gas. This experiment proved O₂ comes from water, not CO₂."],
["d", 5, "Time for DCPIP to go colourless: full light 3 min, half light 6 min, quarter light 12 min. Which conclusion is best?", ["The rate is proportional to light intensity in this range", "Light has no effect", "Rate is highest at quarter light", "Rate doubles when light halves"], "Rate is 1 ÷ time.", "Rates are 1/3, 1/6 and 1/12 per min. Halving the light halves the rate, so the rate is proportional to light intensity here."],
["i", 5, "Boiled chloroplasts in light left DCPIP blue. What does this control show?", ["The reaction needs working (non-denatured) proteins in the chloroplast, not just light and pigment", "Boiling adds oxygen to the chloroplasts, which stops the DCPIP changing colour", "Light is not needed for the reaction, only the green pigment", "Heat breaks down the DCPIP itself, so it can no longer change colour"], "What does boiling destroy?", "Boiling denatures the proteins and enzymes in the thylakoids. Even with light and pigment present, no electrons reach the DCPIP."]
]);
KX("t6s4", [
["c", 2, "Where does the Calvin cycle (light-independent reactions) happen?", ["In the stroma of the chloroplast", "On the thylakoid membranes", "In the cytoplasm", "In the mitochondrion"], "The fluid around the thylakoids.", "The enzymes of the Calvin cycle, including rubisco, are in the stroma."],
["d", 2, "A plant made 10 mg of glucose per hour at 20 °C and 18 mg per hour at 30 °C. How much more did it make at 30 °C?", ["8 mg per hour", "28 mg per hour", "1.8 mg per hour", "18 mg per hour"], "Subtract.", "18 − 10 = 8 mg per hour more. The Calvin cycle is enzyme-controlled, so it speeds up with temperature (up to a point)."],
["c", 4, "Why does the Calvin cycle stop soon after the light is switched off?", ["The ATP and NADPH from the light-dependent reactions run out", "Carbon dioxide runs out", "The enzymes are destroyed by darkness", "Oxygen builds up"], "What does it need from the light reactions?", "The Calvin cycle is not directly driven by light, but it needs ATP and NADPH made in the light. Once these run out, it stops."],
["d", 4, "When the light is switched off, the level of the CO₂ acceptor (RuBP) in the chloroplast falls. Why?", ["RuBP is still used to fix CO₂, but it cannot be regenerated without ATP and NADPH", "RuBP is broken down by light, so it falls once the light is switched off", "RuBP leaves the chloroplast through the stomata when photosynthesis stops", "More RuBP is made in the dark, but it is then used up even faster"], "Used up vs made again.", "Fixing CO₂ uses RuBP without needing light. Making RuBP again needs ATP, so in the dark RuBP is used but not replaced."],
["i", 4, "To trace carbon in photosynthesis, algae were given radioactive ¹⁴CO₂ and samples were killed after very short times. Why short times?", ["To find the first compounds made, before the label spreads into others", "To stop the algae dying", "Because ¹⁴C disappears quickly", "To save radioactive material"], "First in line...", "The earliest labelled compound is the first product of CO₂ fixation. Longer times let the label spread through the whole cycle and beyond."],
["c", 5, "Rubisco is the most abundant enzyme on Earth. Why do plants make so much of it?", ["Rubisco works very slowly, so a lot is needed to fix enough CO₂", "It is used up in each reaction", "It also absorbs light", "It is a storage protein only"], "Slow worker, big team.", "Rubisco fixes only a few CO₂ molecules per second, so leaves pack in huge amounts of it to fix enough carbon."],
["d", 5, "Radioactive carbon was found mostly in GP after 2 s, in sugars after 10 s, and in amino acids and lipids after 60 s. Which conclusion is best?", ["GP is the first product; sugars made from it are then turned into other molecules", "Amino acids are the first product", "Sugars are made directly from CO₂ without GP", "Lipids are made before sugars"], "Follow the order of time.", "The label appears first in GP, then sugars, then amino acids and lipids. This shows the order of the pathway."],
["i", 5, "Two destarched plants are kept in bright light in sealed flasks, one containing soda lime (absorbs CO₂). Only the leaf without soda lime contains starch. What can be concluded?", ["CO₂ is needed to make starch, as only CO₂ differed between the flasks", "Light is needed to make starch", "Soda lime makes starch", "Starch is made from oxygen"], "What was different?", "Both had light, water and chlorophyll. Only the CO₂ supply differed, so CO₂ is needed for photosynthesis to make starch."]
]);
KX("t6s5", [
["c", 2, "What is a limiting factor?", ["The factor in shortest supply that holds back the rate of a process", "The factor that is always light", "Any factor that speeds up a process", "A factor that has no effect"], "The weakest link.", "The rate of photosynthesis is held back by whichever factor (light, CO₂ or temperature) is in shortest supply."],
["d", 2, "Rate of photosynthesis: light 1 unit → 5, 2 → 10, 3 → 15, 4 → 15. From what light intensity does light stop being the limiting factor?", ["About 3 units", "1 unit", "2 units", "4 units"], "Where does the rate stop rising?", "The rate rises up to 3 units, then stays at 15. Beyond that, something else (CO₂ or temperature) limits the rate."],
["c", 4, "Why do some greenhouse growers burn paraffin heaters in winter?", ["Raises CO₂ and temperature", "It adds oxygen, which the plants need for photosynthesis in winter", "It adds light only, because the flames make the greenhouse brighter", "It kills all the pests in the greenhouse with smoke"], "Burning releases heat and CO₂.", "Burning paraffin releases heat and CO₂. In winter both may limit photosynthesis, so raising them can increase crop yield."],
["d", 4, "Rates: 0.04% CO₂ at 20 °C → 10; 0.1% CO₂ at 20 °C → 18; 0.1% CO₂ at 30 °C → 28. What was limiting at 0.04% CO₂ and 20 °C?", ["CO₂ concentration", "Light intensity", "Water", "Chlorophyll"], "What change raised the rate first?", "Raising CO₂ alone raised the rate from 10 to 18, so CO₂ was limiting. Once CO₂ was higher, temperature became limiting."],
["i", 4, "When testing the effect of light on pondweed, why is extra sodium hydrogencarbonate added to the water?", ["So CO₂ is plentiful and does not limit or change the rate", "To change the light intensity", "To kill bacteria", "To warm the water"], "It releases CO₂.", "Sodium hydrogencarbonate provides plenty of CO₂, so only light intensity affects the rate."],
["c", 5, "On a bright summer midday, adding extra CO₂ to a greenhouse raises the rate of photosynthesis but adding more light does not. Why?", ["Light is already saturating, so CO₂ is the limiting factor", "Light slows photosynthesis", "CO₂ absorbs light", "The plants stop respiring"], "Which change helped?", "Extra light gives no gain, so light is not limiting. Extra CO₂ gives a gain, so CO₂ is the limiting factor."],
["d", 5, "Adding CO₂ to a greenhouse raises the crop's value by $40 a day but costs $50 a day. What is the best advice?", ["Do not add CO₂ unless the extra yield is worth more; another factor may be limiting too", "Add more CO₂ to make more money, since yield always rises with CO₂", "CO₂ always pays for itself, so the cost doesn't matter", "Switch off the lights instead, to save money for the CO₂"], "Compare gain with cost.", "Spending $50 to earn $40 loses money. Growers balance the extra yield from raising a limiting factor against its cost."],
["i", 6, "In a pondweed experiment, the lamp is moved closer to increase light, but it also warms the water. What is the best improvement?", ["Use a heat shield or an LED", "Use a brighter lamp so that light, not temperature, becomes the main factor", "Count the bubbles for less time, so the water has less time to warm up", "Move the lamp further away from the plant for every reading instead"], "Two variables are changing.", "Moving a hot lamp changes temperature as well as light. A heat shield or LED keeps temperature constant, so only light intensity changes."]
]);
KX("t6s6", [
["c", 2, "Which test shows that a leaf contains starch?", ["Iodine solution turns blue-black", "Benedict's solution turns brick-red", "Biuret solution turns purple", "Limewater turns milky"], "The starch test.", "Iodine solution turns from yellow-brown to blue-black when starch is present."],
["d", 2, "A student counted oxygen bubbles in three 1-minute periods: 12, 13 and 11. What is the mean?", ["12 bubbles per minute", "36 bubbles per minute", "13 bubbles per minute", "11 bubbles per minute"], "Add and divide by 3.", "(12 + 13 + 11) ÷ 3 = 12 bubbles per minute."],
["c", 3, "Why does a pondweed give off bubbles of gas in the light?", ["Oxygen is made as a by-product of photosynthesis", "Carbon dioxide is released by photosynthesis", "Water is boiling", "The plant is respiring only"], "Which gas does photosynthesis release?", "In photosynthesis water is split and oxygen is released. In the light, it collects as bubbles."],
["d", 4, "A pondweed released 2.0 cm³ of gas in 5 minutes at 10 cm from a lamp and 0.5 cm³ at 20 cm. Light intensity is proportional to 1/distance². Which statement is correct?", ["At 10 cm, light intensity is 4 times higher and the rate is 4 times higher", "At 10 cm, light is 2 times higher and the rate is 4 times higher", "Light intensity is the same at both distances", "The rate is 2 times higher at 20 cm"], "Halve the distance: 2² = 4.", "Halving the distance makes light 4× as intense (1/d²). The gas volume is also 4× (2.0 vs 0.5), so the rate is proportional to light intensity here."],
["i", 4, "Why is collecting the gas in a syringe or capillary tube better than counting bubbles?", ["Bubbles vary in size, so measuring volume is more accurate", "It is faster", "Bubbles contain no oxygen", "Syringes make more gas"], "Are all bubbles the same?", "Bubbles can be big or small, so counting them is not accurate. Measuring the volume of gas gives a better measure of rate."],
["c", 5, "Hydrogencarbonate indicator is red at normal CO₂, yellow at higher CO₂ and purple at lower CO₂. A leaf in bright light turns it purple. Why?", ["The rate of photosynthesis is greater than respiration, so CO₂ is removed", "The leaf only respires", "The leaf releases CO₂", "Light changes the indicator's colour directly"], "Purple = less CO₂.", "In bright light photosynthesis uses CO₂ faster than respiration makes it, so CO₂ falls and the indicator turns purple."],
["d", 5, "After 2 hours: tube A (leaf, bright light) purple; B (leaf, dark) yellow; C (leaf, dim light) red; D (no leaf, bright light) red. What does tube C show?", ["The compensation point", "The leaf has died, so it no longer exchanges gases with the indicator", "Only photosynthesis happens, so the CO₂ concentration stays the same", "Only respiration happens, so the indicator should slowly turn yellow"], "No change in colour means no net change in CO₂.", "In C, CO₂ used by photosynthesis equals CO₂ made by respiration, so there is no net change and the indicator stays red."],
["i", 4, "In that experiment, what is tube D (no leaf, in bright light) for?", ["It is a control showing that light alone does not change the indicator colour", "It measures respiration", "It gives the leaf more CO₂", "It is spare in case a tube breaks"], "Rule out other causes.", "If D stays red, the colour changes in A and B must be caused by the leaf, not by light or the tube itself."]
]);

/* ---------- Topic 7: Cellular Respiration ---------- */
KX("t7s1", [
["c", 2, "What are the products of aerobic respiration?", ["Carbon dioxide and water (with energy as ATP)", "Oxygen and glucose", "Lactic acid", "Ethanol and carbon dioxide"], "Glucose is fully broken down.", "Glucose + oxygen → carbon dioxide + water, releasing energy that is used to make ATP."],
["d", 2, "A person breathed 12 times a minute at rest and 30 times a minute after running. By how many breaths per minute did the rate increase?", ["18", "42", "2.5", "12"], "Subtract.", "30 − 12 = 18 more breaths per minute, to supply more oxygen and remove more CO₂."],
["c", 4, "Why do muscles respire faster during exercise?", ["Contraction uses ATP, so more ATP must be made by respiration", "Muscles need to make more glucose", "Exercise produces oxygen", "Respiration cools the muscles"], "Muscle contraction needs energy.", "Contracting muscles use ATP quickly. Respiration speeds up to remake it, so muscles need more oxygen and glucose."],
["d", 4, "Germinating seeds released 30 units of CO₂ per hour; boiled seeds released 0. Which conclusion is best?", ["Living, germinating seeds respire; dead seeds do not", "Boiled seeds respire faster", "Seeds absorb CO₂", "Germination uses CO₂"], "Boiling kills the seeds.", "Only living cells respire. The boiled seeds act as a control, showing the CO₂ comes from living seeds."],
["i", 4, "In a respirometer with germinating seeds, why is soda lime included?", ["To absorb CO₂", "To give the seeds oxygen for aerobic respiration", "To keep the seeds warm so they germinate faster", "To make the seeds germinate by providing minerals"], "Remove one gas to measure the other.", "Soda lime absorbs the CO₂ released, so the volume of air falls as oxygen is used, and the liquid moves towards the seeds."],
["c", 5, "A poison stops cells using oxygen in mitochondria. Why can a person die quickly, even with plenty of glucose?", ["Cells cannot make enough ATP by anaerobic respiration alone to keep vital organs working", "Glucose turns into a poison when it can't be respired", "The blood stops carrying glucose to the organs", "The lungs stop taking in air when the poison is present"], "Most ATP comes from where?", "Most ATP is made using oxygen in mitochondria. Anaerobic respiration makes too little for the heart and brain, so they fail quickly."],
["d", 5, "In a respirometer, the liquid moved 30 mm in 10 minutes along a tube with a cross-section of 1 mm². What is the rate of oxygen uptake?", ["3 mm³ per minute", "30 mm³ per minute", "300 mm³ per minute", "0.3 mm³ per minute"], "Volume = distance × area, then divide by time.", "Volume = 30 mm × 1 mm² = 30 mm³ in 10 min, so the rate is 3 mm³ per minute."],
["i", 5, "Why is a control respirometer with glass beads instead of seeds set up alongside?", ["It corrects for temperature and pressure", "To find out how fast glass beads respire compared with seeds", "To give the seeds more room, so they don't run out of oxygen", "To absorb CO₂ from the seed respirometer as well"], "Air volume changes with temperature too.", "If the liquid moves in the control, temperature or pressure changed. That movement can be subtracted from the seed respirometer reading."]
]);
KX("t7s2", [
["c", 2, "What does anaerobic respiration in human muscle produce?", ["Lactic acid", "Ethanol", "Carbon dioxide and water", "Oxygen"], "It builds up in hard-working muscles.", "With too little oxygen, muscles break glucose down to lactic acid, releasing a small amount of energy."],
["d", 2, "Yeast gave 8 bubbles of CO₂ per minute at 20 °C and 25 per minute at 35 °C. At which temperature was respiration faster?", ["35 °C", "20 °C", "Same at both", "Cannot tell"], "More bubbles, more CO₂.", "More CO₂ per minute means faster respiration, because yeast enzymes work faster at the warmer temperature."],
["c", 4, "Why do we keep breathing hard for a while after exercise?", ["To repay the oxygen debt", "To cool down the lungs, which heat up during exercise", "To get rid of the extra glucose made in the muscles", "To make more lactic acid for the muscles to use"], "Oxygen debt.", "Extra oxygen is needed after exercise to break down the lactic acid made by anaerobic respiration."],
["d", 4, "Blood lactate: 1 unit at rest, 12 straight after a sprint, 2 after 30 minutes' rest. Why does it fall?", ["Lactic acid is broken down using oxygen, mainly in the liver", "Lactic acid is breathed out", "Lactic acid turns into oxygen", "The muscles keep making more"], "Where does lactic acid go?", "During recovery, lactic acid is carried to the liver and broken down using oxygen, so blood levels return to normal."],
["i", 4, "Before adding yeast, a glucose solution is boiled and then cooled. Why?", ["Remove oxygen and microbes, without killing yeast", "To make more glucose by breaking down any starch in the solution", "To add oxygen so that the yeast respires aerobically at first", "To speed up the yeast's enzymes so fermentation starts faster"], "Anaerobic means no oxygen.", "Boiling drives out oxygen and kills other microbes. Cooling is needed because hot liquid would kill the yeast."],
["c", 5, "Why does anaerobic respiration release much less energy from each glucose molecule than aerobic respiration?", ["Glucose is only partly broken down; much energy stays in lactic acid or ethanol", "Anaerobic respiration uses more glucose", "Oxygen contains the energy", "It happens in mitochondria"], "Where is the leftover energy?", "Without oxygen, glucose is not fully broken down to CO₂ and water. A lot of chemical energy is still locked in lactic acid or ethanol."],
["d", 5, "Yeast CO₂ output in different sugars (same concentration): glucose 30, sucrose 25, lactose 0. Which conclusion is best?", ["No enzyme for lactose", "Lactose is poisonous to yeast, so it kills the cells", "Yeast prefers lactose but can't reach it", "Sucrose can't be used at all, so the bubbles came from glucose"], "Enzymes are specific.", "Yeast respires glucose and can break sucrose into glucose and fructose. It produces no CO₂ with lactose, so it cannot use it."],
["i", 5, "A student counts bubbles from yeast at different temperatures, but the bubbles differ in size. What is a better method?", ["Collect the gas in a gas syringe and measure its volume over a fixed time", "Count for a shorter time", "Use more yeast at higher temperatures only", "Guess the bubble sizes"], "Measure volume, not number.", "A gas syringe measures the actual volume of CO₂, which is more accurate than counting bubbles of different sizes."]
]);
KX("t7s3", [
["c", 2, "Which process releases oxygen?", ["Photosynthesis", "Aerobic respiration", "Anaerobic respiration", "Fermentation"], "Plants in light.", "Photosynthesis releases oxygen. Respiration uses oxygen (aerobic) or none (anaerobic)."],
["d", 2, "Ethanol made by yeast: 0 h 0%, 24 h 4%, 48 h 8%, 72 h 10%. How much ethanol was made in the first 24 hours?", ["4%", "8%", "10%", "24%"], "Read the 24 h value.", "It rose from 0% to 4% in the first 24 hours. The rate slows later as sugar runs out and ethanol builds up."],
["c", 4, "Which statement correctly compares photosynthesis with aerobic respiration?", ["Photosynthesis stores energy in glucose; respiration releases energy from glucose", "Both release oxygen", "Both happen only in light", "Respiration happens only in animals"], "Store vs release.", "Photosynthesis uses light to build glucose; respiration breaks glucose down to release energy. Plants do both; animals only respire."],
["d", 4, "In a closed greenhouse, CO₂ is highest at dawn and lowest in the early afternoon. Why?", ["Night: respiration only; afternoon: photosynthesis wins", "Plants release CO₂ in the light, so it should be highest in the afternoon", "CO₂ is made only at midday, when the plants are hottest", "Respiration stops at night, so the CO₂ must come from outside"], "Which processes run at night?", "At night, respiration adds CO₂ with no photosynthesis. During the day photosynthesis is faster than respiration, so CO₂ falls."],
["i", 4, "To show that germinating peas release heat, why are they put in a vacuum flask?", ["To cut heat loss", "To give them oxygen through the vacuum", "To keep them in the dark so they don't photosynthesise", "To stop them respiring until the experiment starts"], "Keep the heat in.", "The vacuum flask insulates the peas, so the small amount of heat released by respiration builds up and can be measured."],
["c", 5, "Plants respire all day and night. Why do they still gain mass over a year?", ["Over each day, total photosynthesis is greater than total respiration", "They stop respiring in summer", "They take mass from the soil only", "Respiration adds mass"], "Compare the totals.", "As long as photosynthesis makes more glucose than respiration uses, the extra is used to build new tissue, so the plant grows."],
["d", 5, "Temperature rise in vacuum flasks over 2 days: germinating peas 4 °C, dormant peas 1 °C, boiled peas 0 °C. Which conclusion is best?", ["Germinating peas respire fastest and release the most heat", "Dormant peas respire fastest", "Boiled peas respire slowly", "Peas do not respire"], "Bigger rise, more respiration.", "Germinating seeds need lots of energy for growth, so they respire fastest. Dormant seeds respire slowly; boiled (dead) seeds not at all."],
["i", 5, "Why is disinfectant added to the boiled peas in that experiment?", ["To kill microbes that would warm the flask", "To make the peas germinate faster than the others", "To add oxygen, so the peas can respire aerobically", "To keep the peas moist, so they don't dry out in the flask"], "Something else could respire on dead peas.", "Bacteria and fungi grow on dead peas and release heat as they respire. Disinfectant stops this, so the boiled peas are a true control."]
]);

/* ---------- Basic Genetics ---------- */
KX("t9s1", [
["c", 2, "What does 'phenotype' mean?", ["The observable characteristics of an organism", "The pair of alleles it has", "Its DNA sequence", "Its parents' genes"], "What you can see or measure.", "Phenotype is the observable feature, like tall or short. Genotype is the alleles, like Tt."],
["d", 2, "Two Tt plants are crossed and 300 offspring grow. About how many are short (tt)?", ["75", "150", "225", "300"], "Expected ratio 3 tall : 1 short.", "A Tt × Tt cross gives 1/4 tt, so about 300 ÷ 4 = 75 short plants."],
["c", 4, "What is a test cross used for?", ["To find whether an organism with the dominant phenotype is homozygous or heterozygous", "To make new alleles", "To find the recessive phenotype", "To check whether a plant is male or female"], "Cross with a homozygous recessive.", "Crossing with a homozygous recessive shows the hidden allele: if any recessive offspring appear, the parent must be heterozygous."],
["d", 4, "Mendel's second generation contained 787 tall and 277 dwarf pea plants. Which ratio is this closest to?", ["3 : 1", "1 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1"], "Divide 787 by 277.", "787 ÷ 277 ≈ 2.84, close to 3 : 1, as expected for a cross between two heterozygotes."],
["i", 4, "Why did Mendel grow very large numbers of pea plants?", ["So chance effects even out and the ratios are closer to the true ones", "To sell the peas", "Because pea plants grow slowly", "To make the plants taller"], "Coin tosses: 4 vs 1000.", "Inheritance involves chance. With large numbers, random variations cancel out and the true ratio shows."],
["c", 5, "A black guinea pig (B dominant) is crossed with a white one (bb). All 10 offspring are black. Can we be sure the black parent is BB?", ["Very likely, but not certain", "Yes, completely certain, because no white offspring appeared at all", "No: it must be Bb, because a cross with bb always gives some white", "No: it must be bb, because black offspring can come from two recessive alleles"], "Each offspring is a 1/2 chance if Bb.", "If the parent were Bb, each offspring has a 1/2 chance of being black, so 10 black in a row is (1/2)¹⁰ ≈ 1/1024. Possible but very unlikely."],
["d", 5, "Purple-flowered × white-flowered plants gave 52 purple and 48 white offspring. What were the parents' genotypes (P = purple, dominant)?", ["Pp × pp", "PP × pp", "Pp × Pp", "PP × PP"], "52 : 48 is about 1 : 1.", "A 1 : 1 ratio comes from a heterozygote crossed with a homozygous recessive: Pp × pp."],
["i", 5, "Mendel started his crosses with pure-breeding plants. Why was this important?", ["Their genotypes were known", "Pure-breeding plants grow faster, so the results come sooner", "Pure-breeding plants have no alleles, so there's nothing to confuse the results", "Pure-breeding plants cannot be crossed, so they can't be contaminated"], "Known starting point.", "Pure-breeding plants are homozygous, so Mendel knew exactly which alleles they could pass on. This let him explain the ratios he saw."]
]);
KX("t9s2", [
["c", 2, "What does 'codominance' mean?", ["Both alleles are fully expressed in the heterozygote", "One allele hides the other", "Neither allele is expressed", "The alleles blend into a new allele"], "Both show.", "In codominance, both alleles show in the phenotype, e.g. blood group AB has both A and B antigens."],
["d", 2, "In a class of 40, blood groups are O 18, A 12, B 8, AB 2. What percentage are group O?", ["45%", "18%", "30%", "50%"], "18 out of 40.", "18 ÷ 40 × 100 = 45%."],
["c", 4, "Red (CᴿCᴿ) cattle crossed with white (CᵂCᵂ) give roan (CᴿCᵂ). What ratio comes from roan × roan?", ["1 red : 2 roan : 1 white", "3 red : 1 white", "All roan", "1 red : 1 white"], "Draw a Punnett square.", "CᴿCᵂ × CᴿCᵂ gives 1 CᴿCᴿ : 2 CᴿCᵂ : 1 CᵂCᵂ, so 1 red : 2 roan : 1 white."],
["d", 4, "Among 400 children of parents who are both carriers of a recessive condition, 96 are affected. How does this compare with the expected number?", ["Close to the expected 100 (1 in 4)", "Much higher than expected", "Much lower than expected", "Expected number is 200"], "Carrier × carrier = 1/4 affected.", "1/4 of 400 is 100. 96 is close, so the data fit recessive inheritance."],
["i", 4, "Why do scientists use family pedigrees instead of planned crosses to study human inheritance?", ["It would be unethical to control human breeding, and humans have few children and long generations", "Pedigrees are always more accurate", "Humans have no alleles", "Planned crosses are illegal for plants too"], "Think ethics and time.", "We cannot choose human partners or wait many generations, so geneticists study patterns in existing families instead."],
["c", 5, "A baby has blood group O. Couple 1 is AB and O; couple 2 is A and B. Which couple could be the parents?", ["Couple 2 only", "Couple 1 only", "Both couples", "Neither couple"], "An O baby needs ii.", "The baby is ii, so each parent must carry i. An AB parent (IᴬIᴮ) has no i. A (Iᴬi) × B (Iᴮi) parents can have an ii child."],
["d", 5, "Parents are IᴬIᴮ × Iᴬi. What are the expected proportions of their children's blood groups?", ["A 50%, AB 25%, B 25%, O 0%", "A 25%, B 25%, AB 25%, O 25%", "A 75%, B 25%", "AB 100%"], "Draw the Punnett square.", "Gametes Iᴬ, Iᴮ × Iᴬ, i give IᴬIᴬ (A), Iᴬi (A), IᴬIᴮ (AB), Iᴮi (B): A 50%, AB 25%, B 25%, no O."],
["i", 5, "A student says a trait 'skips generations' in their family, so it cannot be genetic. How could they test this claim?", ["Draw a pedigree over several generations", "Ask one relative whether they think the trait runs in the family", "Look at one generation only, since the trait skips the others", "Count how many people in the family are tall, as height is linked to it"], "Recessive traits often skip generations.", "A recessive trait can be hidden in carriers and reappear later. A pedigree over several generations shows whether the pattern fits."]
]);
KX("t9s3", [
["c", 2, "Which is an example of discontinuous variation?", ["Blood group", "Height", "Body mass", "Hand span"], "Separate categories.", "Blood group has distinct groups with no in-betweens; height, mass and hand span vary continuously."],
["d", 2, "In a survey, 30 students can roll their tongue and 10 cannot. What percentage can?", ["75%", "30%", "25%", "66%"], "30 out of 40.", "30 ÷ 40 × 100 = 75%."],
["c", 4, "Why is human height an example of continuous variation?", ["It is controlled by many genes and affected by the environment", "It is controlled by one gene", "It has only two forms", "It is not inherited"], "Many factors add up.", "Many genes each add a little, and diet and health also matter, giving a smooth range of heights."],
["d", 4, "A cross gives 68 round and 22 wrinkled seeds. Which ratio and parents does this fit?", ["About 3 : 1, from two heterozygous parents", "About 1 : 1, from heterozygous × homozygous recessive", "All round, from homozygous parents", "About 9 : 3 : 3 : 1"], "68 ÷ 22 ≈ ?", "68 ÷ 22 ≈ 3.1, so about 3 : 1, from Rr × Rr."],
["i", 4, "A student compares leaf length in sun and shade. How should leaves be chosen?", ["Measure many randomly chosen leaves (for example 30) from each area", "Choose the biggest leaf from each area", "Measure one leaf from each area", "Choose leaves that look different"], "Avoid bias and small samples.", "Random sampling avoids bias, and large samples make the means more reliable."],
["c", 5, "Carriers of the sickle-cell allele (HbᴬHbˢ) are common where malaria is common. Why?", ["Carriers are more resistant to malaria, so they survive and pass on the allele more often", "Malaria causes the sickle-cell mutation in people it infects", "Carriers can't catch any disease at all", "The allele helps carry more oxygen in the blood"], "Natural selection at work.", "Carriers have mild or no anaemia but resist malaria. In malaria areas they survive to reproduce more, so the allele stays common."],
["d", 5, "Sun leaves: mean 6.2 cm, range 5–7 cm. Shade leaves: mean 8.5 cm, range 7.5–9.5 cm. Which conclusion is best?", ["Shade leaves are longer on average, and the ranges hardly overlap, so the difference is likely real", "There is no difference, because the two ranges overlap slightly", "Sun leaves are longer, because they get more light for growth", "The difference must be genetic, because the leaves come from different trees"], "Compare means AND ranges.", "The means differ by 2.3 cm and the ranges barely overlap, so the difference is unlikely to be chance. The data do not show whether the cause is genetic or environmental."],
["i", 5, "How could you show that the shade-leaf difference is caused by the environment, not genes?", ["Grow cuttings (clones) from one plant in sun and in shade", "Measure more leaves from different species", "Grow seeds from many plants in the sun", "Measure leaf colour instead"], "Keep genes the same.", "Cuttings from one plant have identical genes. Any difference between them in sun and shade must come from the environment."]
]);

/* ---------- Molecular Genetics and Biotechnology ---------- */
KX("t10s1", [
["c", 2, "What is a gene?", ["A section of DNA that codes for a protein", "A whole chromosome", "A type of cell", "A protein"], "A recipe within the DNA.", "A gene is a length of DNA with a base sequence that codes for one protein (polypeptide)."],
["d", 2, "Each amino acid is coded by three bases. How many amino acids can a DNA sequence of 300 bases code for?", ["100", "300", "900", "30"], "Divide by 3.", "300 ÷ 3 = 100 amino acids."],
["c", 4, "Why is complementary base pairing important when DNA is copied?", ["Each strand acts as a template, so the new strands are exact copies", "It makes DNA single-stranded", "It changes the genes", "It stops DNA from being copied"], "A pairs with T, C with G.", "Because A only pairs with T and C with G, each old strand fixes the order of bases on the new strand, giving identical copies."],
["d", 4, "A human body cell nucleus contains 6.4 pg of DNA. How much DNA does a sperm nucleus contain?", ["3.2 pg", "6.4 pg", "12.8 pg", "1.6 pg"], "Gametes are haploid.", "Sperm have one set of chromosomes, so half the DNA: 3.2 pg."],
["i", 4, "When extracting DNA from strawberries, why is detergent added?", ["To break down membranes", "To make the DNA visible by staining it white", "To cut the DNA into small pieces so it dissolves", "To add colour to the DNA so it shows up in the ethanol"], "Membranes are made of lipids.", "Detergent breaks up the lipids in membranes, releasing DNA from the cells and nuclei."],
["c", 5, "There are only 4 bases. How can they code for about 20 amino acids?", ["A triplet of bases gives 4³ = 64 combinations, more than enough for 20", "Each base codes for 5 amino acids", "Pairs of bases give 64 combinations", "Each amino acid has its own base"], "4 × 4 × 4.", "Single bases give only 4 codes and pairs only 16. Triplets give 64, enough for 20 amino acids plus stop signals."],
["d", 5, "A DNA molecule has 1000 base pairs, and 22% of its bases are thymine. How many guanine bases does it have?", ["560", "220", "280", "440"], "2000 bases in total.", "T = A = 22%, so G + C = 56% and G = 28%. 28% of 2000 bases = 560."],
["i", 5, "In DNA extraction, why is ice-cold ethanol poured on top of the strawberry extract?", ["DNA comes out of solution in cold ethanol", "It dissolves the DNA so that it can be poured off the top", "It kills the strawberry cells so they release their DNA", "It stains the DNA red so that it can be seen clearly"], "DNA precipitates.", "DNA comes out of solution where the ethanol meets the extract and can be spooled out. Cold temperatures help it precipitate and protect it from enzymes."]
]);
KX("t10s2", [
["c", 2, "Where does translation (making a protein from mRNA) happen?", ["At a ribosome", "In the nucleus", "In the vacuole", "On the cell membrane"], "Protein factories.", "mRNA travels to ribosomes in the cytoplasm, where amino acids are joined in the order of its codons."],
["d", 2, "How many codons are in the mRNA sequence AUG GCA UUU?", ["3", "9", "1", "6"], "A codon is three bases.", "9 bases ÷ 3 = 3 codons, coding for 3 amino acids."],
["c", 4, "Why does a cell send mRNA to the ribosomes instead of the DNA itself?", ["DNA stays protected; mRNA is a small copy", "Ribosomes cannot read RNA, so DNA must stay in the nucleus", "DNA is single-stranded, so it would break if it left the nucleus", "mRNA is bigger than DNA, so it carries more information"], "The master copy stays safe.", "The DNA stays safely in the nucleus. A small mRNA copy of one gene can leave through the nuclear pores."],
["d", 4, "A DNA template strand reads TAC GGT. What is the mRNA made from it?", ["AUG CCA", "ATG CCA", "TAC GGT", "UAC GGU"], "Pair the bases; RNA uses U instead of T.", "T→A, A→U, C→G, G→C: TAC GGT becomes AUG CCA."],
["i", 4, "Bacteria plates were exposed to UV for 0, 10 and 20 seconds, then mutant colonies were counted. What is the control?", ["The plate with 0 seconds of UV, treated the same way otherwise", "A plate with no bacteria", "The plate with 20 seconds of UV", "A plate kept in the fridge"], "No UV.", "The 0 s plate shows how many mutants appear naturally, so any increase can be linked to UV."],
["c", 5, "Why may a single base substitution have no effect on the protein?", ["The code is degenerate: the new triplet may code for the same amino acid", "Substitutions always delete genes", "Proteins do not use DNA", "The ribosome repairs it"], "Several codons per amino acid.", "Most amino acids have more than one codon. If the changed triplet still codes for the same amino acid, the protein is unchanged (a silent mutation)."],
["d", 5, "Mutant colonies after UV: 0 s 2, 10 s 15, 20 s 40, 30 s 12 (very few bacteria survived). What best explains the drop at 30 s?", ["High UV kills most bacteria, so fewer survive to form any colonies, including mutants", "UV stops causing mutations after 20 s", "Mutants turn back to normal", "The plate was not exposed"], "Look at the note about survival.", "Mutations rise with UV dose, but a big dose kills most cells. With few survivors, there are fewer mutant colonies to count."],
["i", 5, "Total survivors differed a lot between UV plates. How could the results be compared more fairly?", ["Express mutants as a percentage of surviving colonies", "Count only the plate with most colonies", "Ignore the survivors", "Add more UV to every plate"], "Mutant number depends on survivors.", "Percentage of survivors that are mutants allows fair comparison when survival is very different."],
["c", 6, "Why is a deletion of one base usually more harmful than a substitution of one base?", ["It shifts the reading frame, so every codon after it changes", "Deletions are always at the start", "Substitutions change all the codons", "Deletions add extra amino acids"], "Frameshift.", "Removing one base moves the reading of every later triplet (frameshift), so many amino acids change and the protein usually does not work."]
]);
KX("t10s3", [
["c", 2, "Which enzyme cuts DNA at a specific base sequence?", ["Restriction enzyme", "DNA ligase", "Amylase", "Lipase"], "Molecular scissors.", "Restriction enzymes cut DNA at particular sequences, often leaving sticky ends. Ligase joins DNA pieces."],
["d", 2, "PCR doubles the DNA in each cycle. Starting with 1 molecule, how many are there after 5 cycles?", ["32", "10", "25", "64"], "2 × 2 × 2 × 2 × 2.", "2⁵ = 32 molecules."],
["c", 4, "Why are bacteria useful for making human insulin?", ["They reproduce quickly and accept plasmids carrying the human gene, which they read using the same genetic code", "They already make human insulin naturally, so no change is needed", "They have a nucleus like ours, so the human gene fits in easily", "They never mutate, so the insulin is always exactly the same"], "Fast, simple, universal code.", "Bacteria multiply fast and can take up plasmids. Because the genetic code is universal, they make the same insulin protein."],
["d", 4, "DNA profiles: crime scene bands at 3, 5 and 8 kb; suspect A at 3, 5 and 8 kb; suspect B at 2, 5 and 9 kb. Which conclusion is best?", ["Suspect A's profile matches the crime scene sample", "Suspect B's profile matches", "Both match", "Neither matches"], "Compare every band.", "All of suspect A's bands match. Suspect B shares only one band, so B is excluded."],
["i", 4, "After adding plasmids with an antibiotic-resistance gene, why are bacteria grown on agar containing that antibiotic?", ["To select the transformed bacteria", "To kill all the bacteria, so that only the plasmids remain", "To make the plasmids grow faster inside the bacteria", "To feed the bacteria, as antibiotics are a source of energy"], "A survival test.", "Most bacteria do not take up the plasmid. The antibiotic kills those, leaving only transformed bacteria."],
["c", 5, "Which is a fair benefit AND concern of a pest-resistant GM crop?", ["Less pesticide is needed, but the gene might spread to wild relatives", "It needs more pesticide, and is completely safe", "It cannot be eaten, but grows faster", "It has no benefits"], "Balance both sides.", "GM pest resistance can cut pesticide use and raise yields. Concerns include gene flow to wild plants and effects on other insects."],
["d", 5, "PCR starts with 10 DNA molecules. Roughly how many are there after 20 cycles?", ["About 10 million", "About 200", "About 20 000", "About 1 billion"], "2²⁰ ≈ 1 million.", "2²⁰ ≈ 1 048 576, so 10 × ~1 million ≈ 10 million. This is why tiny samples can be analysed."],
["i", 5, "A company says its GM fish is safe to eat, based on a 2-week trial with 10 rats. What is the best evaluation?", ["Too short and too small", "This proves it is safe, as none of the rats became ill", "This proves it is dangerous, as only 10 rats were used", "Rats are always the same as humans, so the trial is enough"], "Size, length, independence.", "Ten rats for two weeks cannot show long-term or rare effects. Larger, longer, repeated studies by independent scientists are needed."]
]);
