
/* Extra bank, part 3 (format: see q_x1.js). */

/* ---------- Biodiversity and Evolution ---------- */
KX("t11s1", [
["c", 2, "In the scientific name Homo sapiens, which word is the genus?", ["Homo", "sapiens", "Both words", "Neither word"], "The first word, with a capital letter.", "Binomial names give the genus first (capital letter) and the species second (lower case)."],
["d", 2, "A pond survey found 12 snails, 30 water fleas, 3 fish and 5 beetles. What percentage were arthropods (water fleas and beetles)?", ["70%", "35%", "60%", "10%"], "35 out of 50.", "Arthropods = 30 + 5 = 35 out of 50 animals, which is 70%."],
["c", 4, "Why do scientists use scientific names instead of common names?", ["Each species has one name used worldwide, so there is no confusion", "Scientific names are shorter", "Common names are always wrong", "Only scientists can say them"], "One species, many local names.", "Common names change between languages and places. One agreed scientific name avoids confusion."],
["d", 4, "DNA differences from humans: chimpanzee 1.2%, gorilla 1.6%, orangutan 3.1%. Which is our closest living relative?", ["Chimpanzee", "Gorilla", "Orangutan", "They are equally related"], "Fewest differences.", "The fewer the DNA differences, the more recently two species shared a common ancestor. Chimpanzees differ least."],
["i", 4, "When writing a dichotomous key, what should each step do?", ["Use one clear feature with two contrasting choices", "Ask about several features at once", "Use features that change with season", "Give three or more choices"], "Dichotomous = splitting in two.", "Each step should split the organisms into two groups using one clear, observable feature."],
["c", 5, "Whales and sharks both have streamlined bodies and fins. Why are whales classified as mammals?", ["Lungs, hair and milk", "They live in the sea, so they must be fish", "They are bigger than sharks, and size decides the group", "They have fins and a tail, like all fish"], "Look past features shaped by the same habitat.", "Fins and streamlining are adaptations to water, not signs of close relationship. Lungs, hair and milk show whales are mammals."],
["d", 5, "Base differences in one gene: species A–B 2, A–C 10, B–C 10, A–D 25. Which statement is best?", ["A and B are most closely related; A and D are least closely related", "A and D are most closely related", "C is the ancestor of all", "All are equally related"], "Smallest number = closest.", "Only 2 differences between A and B means a recent common ancestor. 25 differences between A and D means a distant one."],
["i", 5, "A key asks 'Is the leaf large or small?' What is the problem, and the fix?", ["'Large' is subjective: use a measurement", "There is no problem, because everyone agrees on what large means", "Ask about the colour instead, as it is easier to see", "Use more pictures instead of words, so no measuring is needed"], "Would two people always agree?", "Different users judge size differently. A measurable feature gives the same answer for everyone."]
]);
KX("t11s2", [
["c", 2, "Who proposed the theory of evolution by natural selection?", ["Charles Darwin (and Alfred Russel Wallace)", "Gregor Mendel, who bred pea plants in his monastery garden", "Louis Pasteur, who disproved spontaneous generation", "Robert Hooke, who first described cells under a microscope"], "He sailed on HMS Beagle.", "Darwin and Wallace proposed natural selection. Mendel discovered the patterns of inheritance."],
["d", 2, "Before industry, 2% of peppered moths near a city were dark. After industry, 95% were dark. By how many percentage points did the dark form increase?", ["93", "97", "47", "2"], "Subtract.", "95 − 2 = 93 percentage points. Dark moths were better camouflaged on sooty trees, so more survived."],
["c", 4, "How do bacteria become resistant to an antibiotic?", ["A random mutation makes some resistant; the antibiotic kills the others, so resistant ones survive and reproduce", "The antibiotic teaches the bacteria how to resist it", "The bacteria choose to change once they meet the antibiotic", "The patients become resistant, not the bacteria"], "The mutation comes first.", "Resistance comes from random mutation. The antibiotic selects for it by killing non-resistant bacteria, so the resistant ones multiply."],
["d", 4, "Rabbits exposed to a deadly virus: in year 1, 99% of infected rabbits died; in year 7, 25% died. What best explains this?", ["Rabbits with resistance survived and passed on their alleles, so resistance became common", "The rabbits learned to avoid the virus", "The virus stopped existing", "Rabbits made antibodies they inherited"], "Survivors breed.", "A few rabbits had alleles giving resistance. They survived and reproduced, so over generations a larger fraction were resistant."],
["i", 4, "Students model natural selection by scattering coloured paper 'moths' on newspaper and letting a 'predator' pick them up for 30 seconds. Which result is expected?", ["More of the newsprint-coloured moths survive", "More of the brightly coloured moths survive", "Equal numbers of each survive", "No moths survive"], "Camouflage.", "The predator finds the bright moths more easily, so camouflaged moths survive, modelling selection by predators."],
["c", 5, "A student says giraffes stretched their necks, so their offspring were born with longer necks. What is the best evaluation?", ["Wrong: changes during life are not inherited; giraffes already varied, and longer-necked ones survived and bred more", "Correct: stretching makes the neck longer, and this is passed on", "Wrong: giraffes' necks did not change at all over time", "Correct: stretching changes the genes in the neck cells"], "Acquired vs inherited.", "Stretching does not change the DNA in gametes. Evolution acts on existing genetic variation: longer-necked giraffes reached more food and passed on their alleles."],
["d", 5, "Percentage of resistant bacteria in a hospital: month 0 1%, month 6 10%, month 12 40%. The antibiotic was then stopped; at month 24 it was 25%. Why did it fall?", ["Without the antibiotic, resistance gave no edge", "The bacteria forgot their resistance once the antibiotic stopped", "All the resistant bacteria died at the same time", "The antibiotic is still being used in secret"], "Selection pressure removed.", "Resistance is favoured only when the antibiotic is present. Without it, resistant bacteria may grow slower and are out-competed."],
["i", 5, "In the paper-moth model, why should several different students act as the 'predator'?", ["To reduce one person's bias", "To make the experiment faster by sharing the work", "To use fewer moths in each round of the game", "So everyone in the class gets a turn at being a predator"], "One person might have a habit.", "Different predators give repeated trials. If the same pattern appears each time, the result is more reliable."]
]);
KX("t11s3", [
["c", 2, "What are fossils?", ["Preserved remains or traces of organisms from long ago", "Living organisms in rocks", "Rocks shaped like animals by chance", "Bones of animals alive today only"], "Ancient evidence.", "Fossils are the remains or traces (bones, shells, footprints, imprints) of organisms preserved in rock."],
["d", 2, "Rock layers from deepest to top contain: A fish, B amphibians, C reptiles, D mammals. Which fossils are the oldest?", ["The fish in layer A", "The mammals in layer D", "The reptiles in layer C", "All the same age"], "Lower layers formed first.", "In undisturbed rock, deeper layers are older, so the fish in A are oldest."],
["c", 4, "Why are homologous structures, like the five-fingered limbs of humans, bats and whales, evidence for evolution?", ["They have the same basic bone plan, suggesting a common ancestor", "They do the same job", "They are all used for swimming", "They evolved separately by chance"], "Same plan, different uses.", "The same set of bones adapted for different jobs shows these animals inherited the plan from a shared ancestor."],
["d", 4, "Differences in a protein (cytochrome c) from humans: chimpanzee 0, rhesus monkey 1, dog 11, yeast 44. Which conclusion is best?", ["Humans are most closely related to chimpanzees and least to yeast, supporting common descent", "Yeast is our closest relative", "Dogs are more closely related to us than monkeys", "Proteins tell us nothing about relationships"], "Fewer differences = closer relative.", "The number of differences rises with how distant the relationship is, matching what fossils and anatomy suggest."],
["i", 4, "How could scientists test whether two frog populations are separate species?", ["Test if they produce fertile offspring", "Compare their colours carefully under the same light", "Count how many frogs there are in each population", "Measure their size and compare the averages"], "The species definition.", "A species is a group that can interbreed to produce fertile offspring. If the two cannot, they are separate species."],
["c", 5, "Squirrels split by a deep canyon become two species. Which order of events is correct?", ["Isolation → no gene flow → different mutations and selection on each side → can no longer interbreed", "Can no longer interbreed → isolation → mutations", "Mutations → isolation → same species", "Selection → gene flow → isolation"], "Separate first, then change.", "Geographical isolation stops gene flow. Each population gains different mutations and adapts to its side, until they can no longer interbreed."],
["d", 5, "Finch beak depth averaged 9.2 mm before a drought. During the drought only large, hard seeds were left. Offspring of the survivors averaged 9.7 mm. What best explains this?", ["Deeper-beaked birds survived and bred", "Beaks grew deeper from cracking hard seeds, and this was passed on", "The drought caused mutations that made beaks deeper", "All finches grew bigger beaks because they ate more"], "Who survived?", "Deeper-beaked finches could eat the remaining seeds, survived and bred. Their offspring inherited deeper beaks: natural selection in action."],
["i", 5, "Why do scientists need beak measurements over several generations to show that finches have evolved?", ["To show the change is inherited and lasting, not just random variation in one year", "Because finches grow slowly", "To count more seeds", "Because one measurement is always wrong"], "Evolution = inherited change over generations.", "A change seen in one year could be chance or caused by diet. Showing it in offspring over generations shows it is genetic."]
]);

/* ---------- Life Processes in Plants ---------- */
KX("t12s1", [
["c", 2, "How do root hair cells take in water from the soil?", ["By osmosis", "By active transport", "By photosynthesis", "By phagocytosis"], "Water moves into the more concentrated cell sap.", "Cell sap is more concentrated than soil water, so water enters root hair cells by osmosis."],
["d", 2, "After 4 weeks, seedlings in a complete solution had a mass of 12 g; seedlings with no nitrate had 3 g. How many times heavier were the complete-solution seedlings?", ["4 times", "9 times", "3 times", "15 times"], "Divide 12 by 3.", "12 ÷ 3 = 4. Without nitrate, plants cannot make enough protein to grow."],
["c", 4, "How do root hairs increase water uptake?", ["They greatly increase the surface area for absorption", "They make water", "They pump water out", "They close the stomata"], "More surface, more uptake.", "Thousands of long, thin root hairs give a huge surface area for water and mineral uptake."],
["d", 4, "Nitrate uptake by roots: in aerated solution 50 units; in unaerated solution 10 units. Which conclusion is best?", ["Uptake depends on aerobic respiration, as it is mainly active transport", "Air blocks nitrate uptake", "Nitrate moves only by diffusion", "Roots photosynthesise"], "What does air supply to roots?", "Oxygen allows aerobic respiration, which makes ATP for active transport. With little oxygen, uptake falls sharply."],
["i", 4, "Why are seedlings grown in solution culture, not soil, when testing which minerals they need?", ["Solutions let you control the minerals", "Soil is too heavy for young seedlings to push through", "Seedlings grow faster in water, so results come sooner", "Soil has no water in it, so plants can't take up minerals"], "Control the variable.", "In solution culture, one mineral can be left out while all others are supplied, which is impossible to control in soil."],
["c", 5, "Plants in waterlogged soil often wilt, even though there is plenty of water. Why?", ["No oxygen for root respiration", "There is too much oxygen in the waterlogged soil, which poisons the roots", "The water blocks the stomata on the leaves, so they can't take in CO₂", "The leaves absorb too much water from the wet air and burst their cells"], "Roots need oxygen too.", "Water fills the air spaces in soil. Without oxygen, roots cannot respire aerobically, so active uptake fails and roots die, reducing water uptake."],
["d", 5, "After 4 weeks: complete solution, green leaves, 12 g; no nitrate, yellow, 3 g; no magnesium, yellow between veins, 8 g; no phosphate, purple tinge, 5 g. Which statement is fully supported by these results?", ["Lacking nitrate reduced growth more than lacking magnesium or phosphate", "Magnesium is not needed", "Phosphate is needed only for leaf colour", "Nitrate is part of chlorophyll"], "Use only what the data show.", "The no-nitrate plants had the lowest mass. The data do not show which molecules each mineral is part of, so the last option goes beyond the results."],
["i", 5, "In solution culture, the solutions are aerated and the containers are covered with black paper. Why?", ["Aeration gives roots oxygen for respiration; black paper stops algae growing in the light", "Both keep the solution warm", "Aeration adds minerals; paper adds darkness to the leaves", "To stop the plants growing"], "Roots need oxygen; algae need light.", "Air bubbles keep roots respiring. Covering the containers stops algae, which would use minerals and change the solutions."]
]);
KX("t12s2", [
["c", 2, "What is transpiration?", ["The loss of water vapour from leaves, mainly through stomata", "The uptake of water by roots", "The transport of sugar in phloem", "Making food in the leaves"], "Evaporation from leaves.", "Water evaporates from mesophyll cells and diffuses out of the stomata as vapour. This pulls water up the xylem."],
["d", 2, "In a potometer, the air bubble moved 24 mm in 4 minutes. What is the rate of water uptake?", ["6 mm per minute", "96 mm per minute", "20 mm per minute", "28 mm per minute"], "Distance ÷ time.", "24 ÷ 4 = 6 mm per minute."],
["c", 4, "Why does transpiration increase on a windy day?", ["Wind removes water vapour near the leaf, keeping the diffusion gradient steep", "Wind adds water to the leaf", "Wind closes the stomata", "Wind cools the leaf so it loses more water"], "What builds up near the leaf in still air?", "In still air, humid air collects round the leaf and slows diffusion. Wind blows it away, keeping the gradient steep."],
["d", 4, "Transpiration rates: 20 °C → 5, 25 °C → 8, 30 °C → 12 (dry air). At 30 °C: humidity 30% → 12, 60% → 7, 90% → 2. Which conclusion is best?", ["Transpiration rises with temperature and falls as humidity rises", "Transpiration falls with temperature", "Humidity has no effect", "Transpiration is fastest in humid air"], "Look at each variable separately.", "Higher temperature speeds evaporation and diffusion. Higher humidity reduces the water vapour gradient, so less water is lost."],
["i", 4, "Why is the leafy shoot cut under water when a potometer is set up?", ["To keep air out of the xylem", "To clean the shoot so the leaves transpire evenly", "To kill bacteria that would block the xylem", "To make the shoot heavier so it stays in the tube"], "Air bubbles break the water column.", "If air gets into the xylem, the continuous water column breaks and water cannot be drawn up properly."],
["c", 5, "A potometer measures water uptake, not exactly transpiration. Why?", ["Some water taken up is used in photosynthesis or kept in cells, so uptake is not quite the same as loss", "Potometers measure sugar moving in the phloem, not water in the xylem", "Plants do not lose water through the leaves, so uptake is all that happens", "All the water taken up is lost, so the two measurements are exactly the same"], "Not all water leaves.", "Most water taken up is lost by transpiration, but a little is used for photosynthesis and to keep cells turgid."],
["d", 5, "Over 24 hours, water loss from a tree peaked at 2 pm, but water uptake by its roots peaked at 4 pm. Why does uptake lag behind loss?", ["Loss from the leaves creates tension that pulls water up; uptake by the roots follows after this tension builds", "Roots take up water only in the dark, when transpiration has stopped", "The xylem is closed in the morning, so water can't move until the afternoon", "Water moves down from the leaves to the roots during the day"], "What drives the flow?", "Transpiration pulls water up the xylem. The trunk shrinks slightly as tension builds, and root uptake catches up later in the day."],
["i", 5, "Two plants have very different leaf areas. How can their transpiration rates be compared fairly?", ["Divide each rate by the plant's total leaf area", "Compare the rates directly", "Cut off leaves until they match", "Measure only the bigger plant"], "Rate per unit area.", "A larger plant loses more water just because it has more leaves. Rate per cm² of leaf allows a fair comparison."]
]);
KX("t12s3", [
["c", 2, "Which tissue carries sucrose from the leaves to other parts of a plant?", ["Phloem", "Xylem", "Epidermis", "Cuticle"], "Sugar goes in the...", "Phloem carries sucrose and amino acids (translocation). Xylem carries water and mineral ions."],
["d", 2, "Phloem sap collected by aphids contains 20% sucrose; xylem sap contains 0.01%. How many times more sucrose is in phloem sap?", ["2000 times", "20 times", "200 times", "0.01 times"], "Divide 20 by 0.01.", "20 ÷ 0.01 = 2000. Phloem carries sugars; xylem carries water and ions."],
["c", 4, "How are the stems and leaves of non-woody plants supported?", ["Turgid cells press against their cell walls, and lignified xylem gives strength", "By bones inside the stem, like the skeleton of an animal", "By air trapped in the stomata, which inflates the leaves", "By sugar in the phloem, which makes the stem stiff and heavy"], "Firm cells.", "Water makes cells turgid, which keeps soft tissues firm. Xylem walls with lignin also add strength."],
["d", 4, "Radioactive CO₂ was given to one leaf. After an hour, labelled sugar was found in the stem above and below the leaf, in the roots and in a fruit. Which conclusion is best?", ["Sugars move up and down in the phloem", "Sugar moves only downwards from the leaf to the roots, by gravity", "Roots and fruits make their own sugar, so the label came from elsewhere", "The xylem carries the sugar, along with water, from the leaf"], "Up AND down.", "Translocation carries sugars from sources (leaves) to sinks (roots, fruits, growing tips) in both directions."],
["i", 4, "In a ringing experiment, a ring of bark (including phloem) is removed from a branch. What is the best control?", ["A similar branch on the same tree with no ring removed", "A branch with all the leaves removed", "A branch from a different species", "A dead branch"], "Change one thing only.", "The control branch is the same except for the ring, so any difference is due to removing the phloem."],
["c", 5, "Removing a complete ring of bark eventually kills a tree, but not at once. Why?", ["Phloem is removed, so roots receive no sugar; they use stored food and die later, while xylem still carries water for a while", "The xylem is removed with the bark, so water stops flowing at once", "The leaves stop photosynthesising at once, because they lose their sugar", "The bark contains the chlorophyll, so the tree can't make food any more"], "Which tissue is in the bark?", "The phloem is in the bark, the xylem deeper. Roots slowly run out of stored sugar and die, then water uptake fails."],
["d", 5, "Sucrose concentration in phloem: leaf 20%, stem 15%, root 5%. What does this suggest?", ["Sucrose moves from a source (leaf) to a sink (root), down a concentration gradient", "Sucrose moves from roots to leaves", "Roots make the most sucrose", "Sucrose is the same everywhere"], "High to low.", "Sucrose is loaded into phloem in the leaves and removed in the roots, so concentration falls along the path from source to sink."],
["i", 5, "Why are aphids used to collect phloem sap?", ["Their stylet taps one sieve tube", "Aphids make phloem sap themselves inside their own bodies", "Aphids dissolve the xylem walls so the sap can flow out", "Aphids are easy to colour, so the sap can be traced through the plant"], "Nature's needle.", "Cutting the stem would mix contents of many cells. An aphid's stylet taps one sieve tube; cut off the aphid, and pure sap flows out of the stylet."]
]);

/* ---------- Nutrition in Humans ---------- */
KX("t8s1", [
["c", 2, "Which nutrient is the body's main source of energy?", ["Carbohydrates", "Vitamins", "Minerals", "Water"], "Bread, rice, noodles.", "Carbohydrates such as starch and sugars are the main energy source. Fats are a compact energy store."],
["d", 2, "Per 100 g, a cereal contains: protein 8 g, fat 3 g, carbohydrate 60 g, fibre 5 g. Which nutrient is in the largest amount?", ["Carbohydrate", "Protein", "Fat", "Fibre"], "Biggest number.", "Carbohydrate is 60 g per 100 g, the largest amount."],
["c", 4, "Why does a pregnant woman need more iron in her diet?", ["To make more haemoglobin for her extra blood and for the fetus", "To make her bones stronger", "To digest more food", "To make more insulin"], "Iron is in haemoglobin.", "Her blood volume increases and the fetus needs to build its own blood, so more iron is needed for haemoglobin."],
["d", 4, "Daily energy needs: 10-year-old 8000 kJ, office worker 10 000 kJ, teenage boy 12 000 kJ, builder 14 000 kJ. Why does the builder need the most?", ["More physical activity", "They are the oldest adults, and older people need more energy", "They eat more protein, which needs extra energy to digest", "They grow the fastest, as building workers are still growing"], "Activity uses energy.", "Physical work needs more energy for muscle contraction. Age, sex and growth also change energy needs."],
["i", 4, "To compare the energy in two foods by burning each under a tube of water, which should be kept the same?", ["Mass of food, volume of water and distance between flame and tube", "The type of food, because it is the variable that should be kept the same", "The final temperature of the water, so the results can be compared", "The colour of the flame, because it shows how much energy is released"], "Only the food type should change.", "Food type is the independent variable. Mass, water volume and set-up must be the same for a fair test."],
["c", 5, "A child eats enough energy but too little protein and develops a swollen belly (kwashiorkor). Why can't extra carbohydrate fix this?", ["The body needs amino acids for growth and blood proteins; carbohydrates cannot provide them", "Carbohydrates make swelling worse", "The child needs more fat", "Carbohydrates contain too much nitrogen"], "What do amino acids contain that sugars don't?", "Amino acids contain nitrogen and are needed to build proteins. Carbohydrates cannot be turned into all the amino acids the body needs."],
["d", 5, "Energy (J) = mass of water (g) × 4.2 × temperature rise (°C). 1 g of peanut heated 20 g of water by 30 °C. What is the energy per gram?", ["2520 J (about 2.5 kJ)", "600 J (just 20 × 30, forgetting the 4.2)", "84 J (just 20 × 4.2, forgetting the temperature rise)", "25 200 J (ten times too big from a slip in the units)"], "20 × 4.2 × 30.", "20 × 4.2 × 30 = 2520 J per gram."],
["i", 5, "That value is much lower than the food label (about 24 kJ per gram). What is the main reason, and the best improvement?", ["Much heat is lost to the air and the tube; use an insulated calorimeter close to the flame", "The peanut had no energy; use a new one", "The thermometer was wrong; use two", "The water was too cold; heat it first"], "Where else does the heat go?", "Most heat escapes to the surroundings, and burning may be incomplete. A calorimeter that traps the heat gives a value closer to the label."]
]);
KX("t8s2", [
["c", 2, "Where does protein digestion begin?", ["In the stomach", "In the mouth", "In the large intestine", "In the oesophagus"], "Pepsin works in acid.", "Pepsin in the stomach starts breaking proteins into polypeptides. Trypsin and other proteases continue in the small intestine."],
["d", 2, "Approximate time food spends: mouth 1 minute, stomach 3 hours, small intestine 5 hours, large intestine 30 hours. Where does it stay longest?", ["Large intestine", "Stomach", "Small intestine", "Mouth"], "Biggest number.", "Food residue spends longest in the large intestine, where water is absorbed."],
["c", 4, "Why does the stomach make hydrochloric acid?", ["Right pH for pepsin; kills bacteria", "It digests fats into fatty acids before they reach the intestine", "It neutralises bile, which would otherwise damage the stomach", "It absorbs glucose from food into the blood"], "Two jobs.", "The acid gives pepsin its optimum pH (about 2) and kills many microbes swallowed with food."],
["d", 4, "Visking tubing containing starch and amylase was placed in water. After 30 minutes the water tested positive for reducing sugar but not for starch. Why?", ["Starch was digested into maltose", "Starch passed through the tubing, then turned into sugar outside", "The amylase turned into sugar and leaked out of the tubing", "Water entered the tubing and carried sugar out with it"], "Big vs small molecules.", "Starch is too big to cross the tubing. Amylase digests it into maltose, which is small enough to diffuse out."],
["i", 4, "Why is the outside of the Visking tubing rinsed before it is placed in the water?", ["To remove any starch or sugar spilled on the outside", "To make the tubing stronger", "To start digestion", "To add water to the tubing"], "False positives.", "Spilled starch or sugar on the outside would give a false result in the water tests."],
["c", 5, "Bile contains no enzymes. How does it help fat digestion?", ["It emulsifies fats into small droplets, increasing the surface area for lipase, and neutralises stomach acid", "It digests fats into fatty acids and glycerol, like lipase does", "It absorbs fats through the gut wall into the lacteals", "It makes fat droplets bigger, so they are easier for lipase to find"], "Physical, not chemical.", "Bile salts break large fat globules into tiny droplets, giving lipase more surface to work on. Its alkali also gives a suitable pH."],
["d", 5, "Protein digested in 1 hour: pepsin at pH 2 90%, at pH 7 5%; trypsin at pH 2 5%, at pH 8 85%. Which conclusion is best?", ["Pepsin works best in acid (stomach); trypsin works best in alkaline conditions (small intestine)", "Both enzymes work best at pH 7, which is neutral", "Trypsin works only in the stomach, where pepsin also works", "pH has no effect on these enzymes, only temperature does"], "Compare the two enzymes' best pH.", "Each enzyme works best at the pH of where it acts: pepsin in the acidic stomach and trypsin in the alkaline small intestine."],
["i", 5, "To test whether bile speeds up fat digestion, tubes of milk and lipase with or without bile contain an indicator that turns from pink to colourless as fatty acids form. What should be measured and controlled?", ["Measure the time for the colour change; keep volumes, temperature and lipase concentration the same", "Measure the final colour only; change the temperature", "Measure the volume of milk; change the lipase", "Measure nothing; just watch"], "Independent: bile. Dependent: time.", "The time to lose the pink colour shows how fast fatty acids form. Everything except bile must be kept the same."]
]);
KX("t8s3", [
["c", 2, "Where are most digested food molecules absorbed?", ["The small intestine (ileum)", "The stomach", "The large intestine", "The mouth"], "Lined with villi.", "The ileum is long and covered in villi, giving a huge surface for absorption."],
["d", 2, "Villi increase the inner surface area of the small intestine from about 0.5 m² to about 30 m². By how many times?", ["60 times", "30 times", "15 times", "6 times"], "Divide 30 by 0.5.", "30 ÷ 0.5 = 60 times bigger."],
["c", 4, "Why are the walls of villi only one cell thick?", ["To make the diffusion distance short", "To make them strong", "To store fat", "To make enzymes"], "Short distance, fast diffusion.", "A thin wall means digested food has only a short distance to travel to the blood capillaries."],
["d", 4, "Glucose concentration: inside the ileum 10 units, in the blood of the villus 15 units. Glucose is still absorbed. How?", ["Active transport", "Diffusion, because glucose molecules are small enough to pass through", "Osmosis, because glucose moves in with the water from the gut", "Phagocytosis, as the villus cells engulf the glucose molecules"], "Low to high.", "Glucose moves from lower to higher concentration, which needs active transport using ATP."],
["i", 4, "In a model gut made of Visking tubing containing starch and glucose, why is the surrounding water tested at intervals?", ["To see which substance passes through, and when", "To keep the water warm, so the enzymes in the tubing work at 37 °C", "To digest the starch outside the tubing, as it leaks out slowly", "To add more glucose to the water, so the gradient stays steep"], "Timeline of results.", "Testing at intervals shows that glucose appears outside while starch does not, modelling which molecules can be absorbed."],
["c", 5, "Why do fatty acids and glycerol enter the lacteals rather than the blood capillaries in a villus?", ["They form fat particles too big for capillaries", "Lacteals contain enzymes that digest the fats into smaller molecules", "The blood capillaries are already full of glucose and amino acids", "Fats are water-soluble, so they are carried away in the lymph"], "Lacteals are lymph vessels.", "Inside villus cells, fatty acids and glycerol rejoin into fats coated with protein. These particles enter the lacteal and travel in lymph."],
["d", 5, "After a meal, blood glucose is 12 units in the hepatic portal vein (gut to liver) but 7 units in the hepatic vein (liver to body). What best explains the difference?", ["The liver stores excess glucose as glycogen", "The liver makes glucose", "Glucose is lost in the urine", "The gut uses all the glucose"], "In vs out of the liver.", "The liver removes extra glucose and stores it as glycogen, keeping blood glucose steady for the rest of the body."],
["i", 5, "How could you test whether a drug reduces glucose absorption?", ["Give two similar groups the same glucose drink, one with the drug, and measure blood glucose over time", "Give one person the drug and see how they feel", "Measure glucose in the drug", "Give the drug without glucose"], "Two groups, one difference.", "A control group without the drug shows the normal rise in blood glucose. A smaller rise with the drug suggests less absorption."]
]);

/* ---------- Gas Exchange in Humans ---------- */
KX("t13s1", [
["c", 2, "Where does gas exchange happen in the lungs?", ["In the alveoli", "In the trachea", "In the bronchi", "In the larynx"], "Tiny air sacs.", "Oxygen and CO₂ diffuse across the walls of the alveoli and the capillaries around them."],
["d", 2, "Inhaled air is 21% oxygen and exhaled air is 16% oxygen. How much oxygen (percentage points) is taken in by the body?", ["5", "16", "21", "37"], "Subtract.", "21 − 16 = 5 percentage points of oxygen are absorbed into the blood."],
["c", 4, "Why is each alveolus surrounded by many blood capillaries?", ["Blood constantly carries oxygen away, keeping a steep concentration gradient", "To make the alveolus stronger, so it doesn't burst", "To keep the alveolus warm, so oxygen dissolves faster", "To carry air into the alveolus from the bronchioles"], "Keep the gradient.", "Flowing blood takes oxygen away and brings CO₂, so the gradient stays steep and diffusion stays fast."],
["d", 4, "Oxygen partial pressure: in alveolar air 13 kPa; in blood arriving at the lungs 5 kPa; in blood leaving 13 kPa. What does this show?", ["Oxygen diffuses from the alveoli into the blood until the levels are equal", "Oxygen moves from blood into the alveoli", "No gas exchange happens", "Blood makes oxygen"], "High to low.", "Oxygen diffuses down its gradient from 13 kPa in the alveolus to 5 kPa in the blood, until the blood reaches 13 kPa."],
["i", 4, "When measuring lung volumes with a spirometer, why is a nose clip worn?", ["So all the air goes through the mouthpiece", "To stop the person smelling the chemicals inside the spirometer", "To keep the nose warm, as cold air would change the results", "To slow the breathing down, so it is easier to measure"], "Air could escape another way.", "Without a nose clip, some air would go in and out through the nose and not be recorded."],
["c", 5, "Why do people with emphysema become breathless easily?", ["The alveolar walls break down, reducing the surface area, so less oxygen diffuses into the blood", "Their lungs make too much mucus, which is the only problem", "Their diaphragm stops working, so they can't breathe in", "Their blood has too much oxygen, which slows breathing"], "Fewer, larger air spaces.", "Emphysema destroys alveolar walls, leaving fewer, larger air spaces with less total surface area for gas exchange."],
["d", 5, "Vital capacity (same age and height): athlete 6.0 L, non-smoker 4.8 L, smoker 4.0 L. Which conclusion is best supported?", ["Regular training is linked to a larger vital capacity, and smoking to a smaller one", "Smoking increases vital capacity", "Vital capacity depends only on height", "Training proves smokers can't exercise"], "Compare each with the non-smoker.", "The athlete's capacity is highest and the smoker's lowest. These are links in a small comparison; a larger study would be needed to show cause."],
["i", 5, "To compare the vital capacity of smokers and non-smokers fairly, which variables should be controlled?", ["Age, sex, height and fitness", "Hair colour and diet only", "The number of cigarettes", "Nothing, just compare them"], "What else affects lung size?", "Lung capacity depends on body size, sex, age and training. Matching these leaves smoking as the main difference."]
]);
KX("t13s2", [
["c", 2, "What does the diaphragm do when we breathe in?", ["It contracts and flattens", "It relaxes and domes upwards", "It pushes the ribs down", "It stays still"], "It moves down.", "The diaphragm contracts and flattens, increasing the volume of the chest so air moves in."],
["d", 2, "A person takes 15 breaths a minute, each of 0.5 L. What volume of air do they breathe per minute?", ["7.5 L", "15.5 L", "30 L", "0.5 L"], "Multiply.", "15 × 0.5 = 7.5 L per minute."],
["c", 4, "Why does air rush into the lungs when the chest volume increases?", ["The pressure inside the lungs falls below atmospheric pressure", "The lungs suck air in by contracting", "The pressure inside rises", "Air is pumped in by the trachea"], "Air moves from high to low pressure.", "A larger volume means lower pressure inside the lungs. Air flows in from the higher pressure outside."],
["d", 4, "At rest: tidal volume 0.5 L, 12 breaths/min. During exercise: 2.0 L, 30 breaths/min. What are the minute volumes?", ["6 L/min at rest, 60 L/min in exercise", "12 L/min at rest, 30 L/min in exercise", "0.5 L/min at rest, 2 L/min in exercise", "6 L/min at both"], "Tidal volume × rate.", "0.5 × 12 = 6 L/min; 2.0 × 30 = 60 L/min, ten times more air for the muscles."],
["i", 4, "In the bell-jar model of the chest, the rubber sheet represents the diaphragm. What is one limitation of the model?", ["The bell jar is rigid, but the real rib cage moves up and out", "The balloons are too small", "Rubber is not a muscle", "The model has no trachea"], "What can't the model do?", "Real breathing also uses the intercostal muscles to move the ribs. The rigid bell jar cannot show this."],
["c", 5, "A stab wound lets air into the space around one lung, and the lung collapses. Why?", ["The pressure around the lung equals atmospheric pressure, so the lung can no longer be kept inflated", "The lung fills with blood from the wound and can no longer hold air", "The diaphragm is cut by the wound, so the lung can't be pulled down", "Air pressure from outside crushes the ribs, which squeezes the lung flat"], "The seal around the lung.", "Normally the pleural cavity is sealed at low pressure, keeping the lung stretched. When air enters, the elastic lung recoils and collapses."],
["d", 5, "A spirometer contains soda lime. Its volume fell 0.6 L in 2 minutes while a person breathed from it. What was the rate of oxygen use?", ["0.3 L per minute", "1.2 L per minute", "0.6 L per minute", "2.6 L per minute"], "Volume ÷ time.", "0.6 L ÷ 2 min = 0.3 L per minute."],
["i", 5, "Why must soda lime be present in the spirometer when measuring oxygen use?", ["It absorbs the CO₂ breathed out, so the fall in volume equals the oxygen used", "It adds oxygen", "It keeps the air moist", "It stops the person breathing too fast"], "Otherwise CO₂ replaces the oxygen.", "Without soda lime, exhaled CO₂ would replace much of the used oxygen, and the volume would hardly fall."]
]);
KX("t13s3", [
["c", 2, "Which substance in tobacco smoke is addictive?", ["Nicotine", "Tar", "Carbon monoxide", "Oxygen"], "It makes quitting hard.", "Nicotine is the addictive drug. Tar contains carcinogens, and carbon monoxide reduces oxygen transport."],
["d", 2, "Inhaled air contains 0.04% CO₂ and exhaled air about 4%. About how many times more CO₂ is in exhaled air?", ["100 times", "10 times", "4 times", "1000 times"], "4 ÷ 0.04.", "4 ÷ 0.04 = 100 times more, because respiration releases CO₂."],
["c", 4, "Why does carbon monoxide reduce oxygen transport?", ["It binds to haemoglobin", "It destroys red blood cells, so fewer are left to carry oxygen", "It blocks the alveoli, so oxygen can't reach the blood", "It removes oxygen from the air before it is breathed in"], "Competition for haemoglobin.", "Carbon monoxide combines with haemoglobin almost irreversibly, leaving fewer sites to carry oxygen."],
["d", 4, "Lung cancer deaths per 100 000 per year: non-smokers 10; 1–14 cigarettes/day 80; 15–24 150; 25 or more 250. Which conclusion is best?", ["The risk rises as the number of cigarettes smoked rises", "Smoking a few cigarettes is safe", "Non-smokers never get lung cancer", "Risk is the same for all smokers"], "Look at the trend.", "More cigarettes per day means more deaths from lung cancer. This dose-response pattern is strong evidence of a link."],
["i", 4, "A smoking machine draws cigarette smoke through cotton wool and an indicator. What is the best control?", ["The same apparatus drawing air with no cigarette", "A cigarette with no cotton wool", "Two cigarettes at once", "A different indicator"], "Remove only the smoke.", "Drawing plain air shows how the cotton wool and indicator change without smoke, so any difference is caused by the smoke."],
["c", 5, "Smoking and lung cancer are linked. What evidence shows that smoking actually causes lung cancer, not just that they occur together?", ["More cigarettes give more risk, chemicals in tar cause mutations in experiments, and quitting lowers the risk", "Smokers are often older, and older people are more likely to get cancer", "Some smokers never get cancer, which shows that the risk is small", "Lung cancer is common, so it must be caused by smoking"], "Correlation plus mechanism.", "A dose-response pattern, a known mechanism (carcinogens damage DNA) and a falling risk after quitting together show cause, not just correlation."],
["d", 5, "Lung cancer risk compared with non-smokers (= 1): current smokers 15; 10 years after quitting 5; 20 years after quitting 2. Which conclusion is best?", ["Quitting lowers the risk, and it keeps falling over time, though it stays above a non-smoker's", "Quitting has no effect, because the damage is already done", "After quitting, the risk drops straight to zero", "The risk rises after quitting, as the lungs repair themselves"], "Compare with 1.", "The risk drops from 15 to 2, but even after 20 years it is still twice a non-smoker's. Quitting early helps most."],
["i", 5, "A one-year study finds e-cigarette users have fewer lung problems than smokers and concludes e-cigarettes are safe. What is the best evaluation?", ["It only compares them with smokers over a short time; comparison with non-smokers and long-term data are needed", "It proves e-cigarettes are completely safe", "It proves e-cigarettes are more harmful than cigarettes", "The study is perfect"], "Less harmful is not harmless.", "Being less harmful than cigarettes does not mean safe. Lung diseases take many years to develop, so long studies with non-smokers are needed."]
]);

/* ---------- Transport in Humans ---------- */
KX("t14s1", [
["c", 2, "Which blood cells carry oxygen?", ["Red blood cells", "White blood cells", "Platelets", "Plasma cells"], "They contain haemoglobin.", "Red blood cells are packed with haemoglobin, which combines with oxygen in the lungs."],
["d", 2, "Blood is 45% cells and 55% plasma. How much plasma is in 5 L of blood?", ["2.75 L", "2.25 L", "0.55 L", "5 L"], "55% of 5.", "0.55 × 5 = 2.75 L of plasma."],
["c", 4, "Why do arteries have thick, elastic walls?", ["To withstand high pressure and smooth out the surges as the heart beats", "To let substances diffuse through", "To slow the blood down", "To carry blood back to the heart"], "Pressure from the heart.", "Thick muscle and elastic tissue stand up to high pressure; the elastic fibres stretch and recoil to keep blood flowing smoothly."],
["d", 4, "Average blood pressure: aorta 120, arterioles 60, capillaries 25, veins 5 (mmHg). Why is the pressure so low in veins?", ["Pressure is lost as blood passes through many narrow vessels, far from the heart", "Veins pump blood backwards", "Veins have thicker walls", "The heart pumps blood into veins first"], "Resistance along the way.", "Friction in arterioles and capillaries uses up pressure. By the time blood reaches the veins, little is left, so valves and muscles help it return."],
["i", 4, "What is the best way to compare pulse rate before and after exercise?", ["A full minute, before and after, repeated", "Count for 5 seconds once, then multiply by 12", "Guess from how tired you feel before and after the exercise", "Measure only after exercise, as the resting rate is the same for everyone"], "Accurate and repeated.", "Counting for longer reduces counting errors, and repeats give a reliable mean. A resting value is needed for comparison."],
["c", 5, "People who live at high altitude have more red blood cells. Why?", ["Each breath contains less oxygen, so more red cells and haemoglobin are needed to carry enough", "Mountain air contains more oxygen, so more cells are needed to carry it", "Cold makes the body produce more cells of every kind", "Exercise makes more platelets, which carry oxygen"], "Thin air.", "At altitude there is less oxygen in each breath. Extra red blood cells let the blood still pick up and carry enough oxygen."],
["d", 5, "Red blood cell count (millions/mm³): at sea level 5.0; after 4 weeks at altitude 5.8; 6 weeks after returning to sea level 5.1. Which conclusion is best?", ["The body makes more red cells at altitude, and this change reverses after returning", "Altitude reduces red cells, because there is less oxygen to carry", "The change is permanent once the body has adapted", "Red cell count never changes, so the readings must be errors"], "Up then down.", "The count rose at altitude and fell back after returning. The body adjusts red cell production to oxygen levels."],
["i", 5, "A study of 5 athletes who trained at altitude found they ran faster afterwards. What is the best evaluation?", ["Too small, with no control group", "This proves altitude training works for every athlete", "This proves altitude training is harmful to the heart", "The study is fully reliable"], "What else could explain it?", "Without a control group training at sea level, we cannot tell if altitude made the difference. Five athletes is also too few."]
]);
KX("t14s2", [
["c", 2, "Which chamber of the heart pumps blood to the whole body?", ["The left ventricle", "The right ventricle", "The left atrium", "The right atrium"], "It has the thickest wall.", "The left ventricle pumps oxygenated blood into the aorta, which carries it to the body."],
["d", 2, "Heart rate is 70 beats per minute and each beat pumps 70 mL. What is the cardiac output?", ["4.9 L per minute", "140 mL per minute", "70 L per minute", "1 L per minute"], "70 × 70 mL.", "70 × 70 = 4900 mL = 4.9 L per minute."],
["c", 4, "Why is the wall of the left ventricle thicker than the right?", ["It pumps to the whole body", "It holds more blood, so it needs a thicker wall to stop it bursting", "It receives blood from the lungs, which is under very high pressure", "It has more valves, which need thick muscle to open and close them"], "Distance and pressure.", "The left ventricle must push blood through the whole body. The right ventricle pumps to the lungs at a lower pressure, which also protects the delicate capillaries there."],
["d", 4, "During a heartbeat, pressure in the left ventricle rises above the pressure in the aorta. What happens?", ["The semilunar valve opens and blood flows into the aorta", "The bicuspid valve opens", "Blood flows back into the atrium", "The heart stops"], "Valves open when pressure behind is higher.", "When ventricle pressure exceeds aortic pressure, the semilunar valve is pushed open and blood is ejected into the aorta."],
["i", 4, "During a heart dissection, how can you tell the left ventricle from the right?", ["The left ventricle has a much thicker muscular wall, which feels firmer when pressed", "The left ventricle is always on your left", "The right ventricle is bigger and thicker", "They look exactly the same"], "Feel the walls.", "Pressing both sides shows the left ventricle wall is firmer and thicker. Left and right are named from the heart's owner, not the viewer."],
["c", 5, "Why is a double circulation more efficient than the single circulation of a fish?", ["Blood is re-pumped after the lungs", "Blood visits the lungs twice, so it picks up twice as much oxygen", "The heart has fewer chambers, so it wastes less energy pumping", "Blood moves more slowly, so there's more time for exchange in the tissues"], "Two pumps in one.", "Pressure drops a lot in the lung capillaries. Returning to the heart lets blood be pumped again, so it reaches the body fast and at high pressure."],
["d", 5, "Cardiac output: at rest 5 L/min at 70 beats/min; in exercise 20 L/min at 160 beats/min. Which statement is correct?", ["Both heart rate and stroke volume increase (about 71 mL to 125 mL per beat)", "Only heart rate increases; the volume per beat stays the same", "Stroke volume falls, because the heart has less time to fill", "Only stroke volume increases; heart rate is not important"], "Stroke volume = output ÷ rate.", "5000 ÷ 70 ≈ 71 mL; 20 000 ÷ 160 = 125 mL. The heart beats faster AND pumps more per beat."],
["i", 5, "To test whether caffeine affects the heart rate of water fleas (Daphnia), why must they all be kept at the same temperature?", ["Heart rate changes with temperature", "Caffeine only works when it is cold, so the water must be cool", "Warm water breaks down caffeine, so it must be kept at room temperature", "Temperature doesn't matter, as long as the same Daphnia are used"], "Water fleas don't control body temperature.", "Daphnia's body temperature follows the water. A warmer flea has a faster heart, so temperature must be controlled."]
]);
KX("t14s3", [
["c", 2, "Tissue fluid is formed from...", ["plasma forced out of the capillaries", "lymph made by the liver", "red blood cells", "digested food"], "Leaks out of the thinnest vessels.", "High pressure at the artery end of capillaries pushes plasma out. It bathes the cells as tissue fluid."],
["d", 2, "About 20 L of fluid leaves the capillaries each day and 17 L returns to them. How much returns to the blood as lymph?", ["3 L", "37 L", "17 L", "20 L"], "Subtract.", "20 − 17 = 3 L is drained by lymph vessels and returned to the blood."],
["c", 4, "Why does tissue fluid contain no red blood cells?", ["Red blood cells are too big to pass through the capillary walls", "They are destroyed in the capillaries", "They dissolve in tissue fluid", "They are made in tissue fluid"], "Size filter.", "Only small molecules and water pass through the capillary walls. Cells and large proteins stay in the blood."],
["d", 4, "Relative risk of coronary heart disease: blood cholesterol below 5 mmol/L = 1; 6 mmol/L = 2; 7 mmol/L = 4. Which conclusion is best?", ["The risk rises steeply as cholesterol rises", "Cholesterol has no effect", "The risk falls as cholesterol rises", "Only cholesterol above 7 matters"], "1 → 2 → 4.", "Each extra 1 mmol/L doubles the risk, a steep rise, which is why high cholesterol is treated."],
["i", 4, "In a study of exercise and blood pressure, why are volunteers randomly assigned to the exercise or control group?", ["To avoid bias", "To make the study faster by splitting the work", "So everyone gets to exercise at least once", "To change their blood pressure before the study starts"], "Fair groups.", "Random allocation spreads other factors, like diet and age, evenly between the groups."],
["c", 5, "Why can severe protein deficiency cause swelling (oedema)?", ["Fewer plasma proteins: less water drawn back", "Proteins build up and block the lymph vessels, so fluid can't drain away", "The heart pumps more blood to make up for the missing protein", "Cells make extra water when they are short of protein"], "Proteins in plasma pull water back.", "Plasma proteins keep the water potential of blood low, drawing tissue fluid back in. With too few, fluid collects in the tissues."],
["d", 5, "Heart attacks per 1000 people per year: inactive 8, moderately active 5, very active 3. A newspaper says 'Exercise halves heart attacks.' What is the best evaluation?", ["The data show a lower rate (over 50% lower) in active people, but it is a correlation; other factors may differ", "The headline is exactly right: exercise halves the risk of a heart attack", "Exercise increases heart attacks, because it puts strain on the heart", "There is no link at all, because the numbers are too small to compare"], "Link ≠ cause.", "The very active rate is less than half the inactive rate. But active people may also eat better or smoke less, so the data alone cannot prove cause."],
["i", 5, "What is the best design to test whether a new diet lowers blood cholesterol?", ["Randomly assign many volunteers to the new diet or a control diet, and measure cholesterol before and after", "Ask a few people who already eat the diet how healthy they feel", "Measure one person's cholesterol before and after the diet", "Compare cholesterol levels in countries with different diets"], "Large, randomised, controlled.", "A large randomised trial with a control group and before-and-after measures shows whether the diet itself makes the difference."]
]);
