
/* Extra bank, part 4 (format: see q_x1.js). */

/* ---------- Reproduction, Growth and Development ---------- */
KX("t15s1", [
["c", 2, "Which part of a flower makes pollen?", ["The anther", "The stigma", "The ovary", "The petal"], "Top of the stamen.", "Anthers make pollen grains, which contain the male gametes. The stigma receives pollen."],
["d", 2, "A flower has 5 petals, 10 stamens and one carpel with 6 ovules. What is the largest number of seeds it can make?", ["6", "10", "5", "21"], "Each ovule can become one seed.", "Each fertilised ovule becomes one seed, so at most 6 seeds."],
["c", 4, "Why do wind-pollinated flowers make huge amounts of small, light pollen?", ["Most pollen is lost, so lots is needed for some to land on a stigma by chance", "To attract insects", "Because pollen is food for birds", "To make the flower heavier"], "Wind is not aimed.", "Wind carries pollen randomly. Light pollen travels far, and huge numbers raise the chance that a few grains reach a stigma."],
["d", 4, "Pollen tube length after 1 hour in sucrose solutions: 0% 0 µm, 5% 120 µm, 10% 300 µm, 20% 150 µm. Which concentration was best?", ["About 10%", "0%, because pollen tubes grow best without any sugar to slow them", "5%, because a little sugar gives energy without drawing out water", "20%, because the most sugar provides the most energy for growth"], "Find the longest tubes.", "Tubes grew longest at 10%. At 20% the solution may draw water out of the pollen by osmosis, slowing growth."],
["i", 4, "Pollen grains are germinated on sugar-agar slides. Why are the slides covered and kept at the same temperature?", ["To stop them drying out, and because temperature affects growth rate", "To keep them in the dark only", "To stop the pollen being eaten", "To make the tubes straight"], "Control other variables.", "Drying would stop growth, and temperature changes growth rate, so both must be controlled to compare sugar concentrations fairly."],
["c", 5, "In some plants the stamens ripen before the stigma of the same flower is ready. What is the effect?", ["Self-pollination is prevented, so cross-pollination and genetic variation are more likely", "The plant cannot reproduce at all, because pollen and stigma are never ready together", "Self-pollination is guaranteed, because the pollen waits for the stigma", "Seeds form without any pollination, because the stamens ripen early"], "Timing stops the flower pollinating itself.", "When the pollen is released before the stigma is ready, it must reach another flower's stigma. Cross-pollination gives more variation."],
["d", 5, "Seed germination: 5 °C 10%, 15 °C 60%, 25 °C 95%, 35 °C 70%, 45 °C 0%. Why did no seeds germinate at 45 °C?", ["Enzymes in the seeds were denatured, killing the embryos", "There was too much oxygen", "Seeds need cold to germinate", "The seeds had no water"], "Germination needs enzymes.", "Germination uses enzymes to break down food stores. At 45 °C they denature, so the embryos cannot grow."],
["i", 5, "To test whether light is needed for germination, a student sets up two dishes of 20 seeds, one in the dark. How can the test be improved?", ["Control other variables; repeat dishes", "Use only one seed in each dish, so it's easier to see", "Use different seed types in each dish, to test more species", "Water only the dark dish"], "Fair and repeated.", "Only light should differ. Repeat dishes show whether results are consistent, making the conclusion more reliable."]
]);
KX("t15s2", [
["c", 2, "Where does fertilisation usually happen in humans?", ["In the oviduct (fallopian tube)", "In the uterus", "In the ovary", "In the vagina"], "On the way to the uterus.", "Sperm meet the egg in the oviduct. The zygote then moves to the uterus and implants."],
["d", 2, "A 28-day menstrual cycle has ovulation at about day 14. If a period starts on 1 March, when is ovulation likely?", ["Around 14 March", "Around 1 March", "Around 28 March", "Around 7 March"], "Day 1 is the start of the period.", "Counting day 1 as 1 March, day 14 is about 14 March. Cycles vary, so this is an estimate."],
["c", 4, "Why is the placenta important?", ["It lets oxygen, nutrients and wastes pass between mother and fetus without their blood mixing", "It makes the fetus's blood and pumps it around its body", "It digests food for the fetus and passes on the products", "It stops all substances crossing, to protect the fetus"], "Exchange organ.", "The placenta has a large surface area and thin barrier, so substances diffuse between the two bloods without them mixing."],
["d", 4, "In a cycle, oestrogen rises from days 5–13, LH peaks on day 14, and progesterone is high from days 15–24 and then falls. What happens when progesterone falls?", ["The uterus lining breaks down and menstruation begins", "Ovulation happens", "The lining thickens", "A new egg is fertilised"], "Progesterone maintains the lining.", "Progesterone keeps the uterus lining ready. If no pregnancy happens, it falls, and the lining is shed."],
["i", 4, "Why is it difficult to test the effect of a medicine on human fetuses?", ["It would be unethical to risk harming a fetus in an experiment", "Fetuses do not react to medicines", "Medicines cannot reach the fetus", "There are no pregnant volunteers"], "Ethics.", "We cannot ethically give a possibly harmful drug to pregnant women to see what happens, so scientists rely on animal studies and records."],
["c", 5, "Why is it important that the mother's and fetus's blood do not mix?", ["Protects the fetus from high pressure and some antibodies", "The fetus has no blood of its own until it is born, so nothing could mix", "Mixing would speed up the exchange of food and oxygen too much for the fetus", "The bloods are identical, so mixing would make no difference at all"], "Pressure and protection.", "Separate circulations protect the fetus's delicate vessels from high pressure and keep out many harmful cells and substances."],
["d", 5, "Mean birth mass: babies of non-smoking mothers 3.4 kg; of smoking mothers 3.1 kg. Which explanation is best?", ["CO and nicotine cut oxygen to the fetus", "Smoking makes babies grow faster, so they are born earlier and lighter", "Nicotine is a food for the fetus, so it replaces some of its normal nutrients", "There is no link; the difference is due to chance alone"], "What does smoke do to oxygen supply?", "Less oxygen and nutrients reach the fetus, so it grows more slowly and is lighter at birth."],
["i", 5, "A study finds babies of mothers who drink a lot of coffee are lighter. Why can't we conclude that coffee causes this?", ["Heavy coffee drinkers may differ in other ways, such as smoking or stress, which could cause the effect", "Coffee has no chemicals in it, so it can't affect a baby", "The babies must be measured twice before any conclusion can be drawn", "Lighter babies drink coffee too, through their mother's milk"], "Confounding factors.", "A correlation may be caused by other factors linked to coffee drinking. These must be controlled before claiming cause."]
]);
KX("t15s3", [
["c", 2, "What does 'growth' mean in biology?", ["A permanent increase in size or dry mass", "Any change in mass", "Getting older", "A change in shape only"], "It must be permanent.", "Growth is a permanent increase in size and dry mass, usually from making new cells and materials."],
["d", 2, "A baby has a mass of 3.5 kg at birth and 10 kg at one year old. How much mass did it gain?", ["6.5 kg", "13.5 kg", "3 kg", "10 kg"], "Subtract.", "10 − 3.5 = 6.5 kg in the first year."],
["c", 4, "Why is dry mass the best measure of growth?", ["Water content changes; dry mass doesn't", "Dry mass is quicker to measure, as no drying is needed", "Plants contain no water, so wet and dry mass are the same", "Wet mass is always smaller, so it underestimates growth"], "Water comes and goes.", "A plant can gain or lose water quickly, so wet mass changes without real growth. Dry mass shows permanent new material."],
["d", 4, "Height gain per year: age 2 8 cm; age 8 5 cm; age 13 (girls) 9 cm; age 18 1 cm. What does the rise at 13 show?", ["A growth spurt during puberty", "Growth has stopped", "Children grow fastest at 18", "Growth is constant"], "Faster again around puberty.", "Growth slows in childhood then speeds up during puberty (the adolescent growth spurt) before stopping in adulthood."],
["i", 4, "How is the dry mass of seedlings measured?", ["Heat them at about 100 °C and reweigh until the mass stops changing", "Weigh them straight from the soil", "Leave them in the fridge overnight", "Burn them completely"], "Remove all the water but nothing else.", "Heating at about 100 °C drives off water. When the mass is constant, all the water has gone."],
["c", 5, "Why does a germinating seed lose dry mass at first?", ["It respires its stored food before its leaves can photosynthesise", "It absorbs water, which is heavier than the food it uses up", "It makes new cells, which have less mass than the stored food", "It takes in minerals from the soil, which replace the stored food"], "Using up stores.", "The embryo uses stored starch for respiration, releasing CO₂. It gains dry mass only once leaves photosynthesise faster than it respires."],
["d", 5, "Seedling dry mass: day 0 100 mg, day 4 80 mg, day 8 90 mg, day 12 130 mg. When did photosynthesis begin to exceed respiration?", ["Between day 4 and day 8", "Between day 0 and day 4", "Only after day 12", "It never did"], "When does mass start rising?", "Dry mass falls until day 4, then rises. From then, photosynthesis is making more than respiration uses."],
["i", 5, "What is a problem with measuring the dry mass of seedlings over time, and how is it handled?", ["Measuring kills them, so a large sample of different seedlings is dried each day and the mean is used", "It is too quick to measure, so many seedlings are needed", "Dry mass is always the same, so nothing can be measured", "Seedlings can be dried and then regrown, so it isn't a problem"], "You can't dry the same seedling twice.", "Drying kills the seedlings. Many similar seedlings are grown, and a sample is dried on each day, so means can be compared."]
]);

/* ---------- Coordination and Response ---------- */
KX("t16s1", [
["c", 2, "Which part of the eye contains the light-sensitive receptor cells?", ["The retina", "The cornea", "The iris", "The lens"], "At the back of the eye.", "The retina contains rods and cones, which turn light into nerve impulses."],
["d", 2, "Pupil diameter is 7 mm in dim light and 2 mm in bright light. By how much does it shrink?", ["5 mm", "9 mm", "3.5 mm", "2 mm"], "Subtract.", "7 − 2 = 5 mm narrower in bright light."],
["c", 4, "Why does the pupil become smaller in bright light?", ["To protect the retina", "To let in more light, so the image is brighter", "To focus on near objects, by making the lens thicker", "Because the lens gets thinner, which pulls the iris inwards"], "A reflex protecting the retina.", "In bright light, the circular iris muscles contract and the radial muscles relax, narrowing the pupil to cut the light entering."],
["d", 4, "The nearest point a person can focus on: age 10 7 cm, age 40 20 cm, age 60 100 cm. What best explains this?", ["The lens loses elasticity", "The retina grows forwards with age, so near images fall behind it", "The pupil gets bigger with age, which lets in too much light", "The cornea gets thinner, so it bends light less than before"], "Focusing near needs a fat lens.", "With age, the lens stiffens and cannot round up as much, so near objects need to be held further away."],
["i", 4, "In a two-point touch test, why does the person being tested keep their eyes closed?", ["So they report only what they feel, not what they see", "To relax them", "To make the skin more sensitive", "To stop them blinking"], "Remove another source of information.", "If they could see the points, they might guess. Closing the eyes means only touch receptors are tested."],
["c", 5, "You look up from a distant view to read a book. What happens in your eyes?", ["Ciliary muscles contract, suspensory ligaments slacken, and the lens becomes fatter", "Ciliary muscles relax and the lens becomes thinner", "The pupil widens and the lens stays the same", "The retina moves forward"], "Near = fat lens.", "For near objects, the ciliary muscles contract, the ligaments loosen, and the elastic lens rounds up to bend light more."],
["d", 5, "Smallest distance at which two points feel separate: fingertip 2 mm, palm 10 mm, back 40 mm. Which conclusion is best?", ["Touch receptors are most densely packed in the fingertips", "The back has the most receptors", "All skin is equally sensitive", "The palm has no receptors"], "Smaller distance = more receptors.", "If two points 2 mm apart feel separate, each touches a different receptor, so receptors are close together in fingertips."],
["i", 5, "How could the two-point touch test be made more reliable?", ["Random single touches, repeats, more people", "Test only one person once, but very carefully", "Press as hard as possible so the points are easy to feel", "Tell the person how many points are being used each time"], "Avoid guessing and repeat.", "Random single touches catch guessing, repeats give consistent results, and testing several people shows the general pattern."]
]);
KX("t16s2", [
["c", 2, "Which neurone carries impulses from a receptor to the central nervous system?", ["Sensory neurone", "Motor neurone", "Relay neurone", "Effector neurone"], "It carries sensations in.", "Sensory neurones carry impulses from receptors to the CNS. Motor neurones carry them out to effectors."],
["d", 2, "In a ruler-drop test, catch distances were 12 cm, 10 cm and 14 cm. What is the mean?", ["12 cm", "36 cm", "10 cm", "14 cm"], "Add and divide by 3.", "(12 + 10 + 14) ÷ 3 = 12 cm."],
["c", 4, "Why are reflex actions so fast?", ["They involve few neurones and do not need conscious thought in the brain", "They use hormones", "They involve every neurone in the body", "Muscles react on their own"], "Short path.", "A reflex arc passes through the spinal cord or lower brain via a relay neurone, skipping slow conscious decisions."],
["d", 4, "A ruler-drop test gave a mean catch distance of 15 cm before drinking coffee and 10 cm after. Which conclusion is best?", ["Reaction time was shorter after the coffee", "Reaction time was longer after the coffee", "Coffee has no effect", "The ruler moved more slowly"], "Shorter distance = quicker catch.", "The ruler fell less far before being caught, so the reaction was faster. Caffeine is a stimulant."],
["i", 4, "In a ruler-drop test, why should the ruler be dropped without warning and caught with the same hand each time?", ["No anticipation; same hand each time", "To make the experiment more fun and keep the catcher alert", "To make the ruler fall faster, so the time is shorter", "So the ruler doesn't break when it is caught"], "Fair test.", "Warning lets the person anticipate, and dominant and non-dominant hands may differ. Controlling these keeps the test fair."],
["c", 5, "A spinal cord injury in the neck can cause loss of feeling and movement below the injury. Why?", ["Impulses can't cross the injury", "The muscles below the injury are destroyed by the damage", "The receptors in the skin below the injury stop working", "The brain stops working properly after a spinal injury"], "The spinal cord is the main pathway.", "Sensory impulses cannot reach the brain, and motor impulses cannot reach muscles below the damage."],
["d", 5, "Impulses travel at 100 m/s in myelinated neurones and 1 m/s in unmyelinated ones. How long does each take to travel 1 m?", ["0.01 s and 1 s", "100 s and 1 s", "1 s and 0.01 s", "0.1 s and 10 s"], "Time = distance ÷ speed.", "1 ÷ 100 = 0.01 s; 1 ÷ 1 = 1 s. Myelin makes impulses 100 times faster here."],
["i", 5, "Is the ruler-drop test a good way to measure a reflex?", ["No: catching is voluntary", "Yes, it is a perfect reflex test, because the catch happens very fast", "Yes, catching is automatic, so the brain is not involved at all", "No, because rulers are too short to give an accurate measurement"], "Do you decide to catch it?", "Catching involves seeing, deciding and acting, so it measures reaction time, not a reflex arc like the knee jerk."]
]);
KX("t16s3", [
["c", 2, "Which gland releases adrenaline?", ["The adrenal gland", "The pancreas", "The thyroid", "The pituitary"], "Named after it.", "The adrenal glands, above the kidneys, release adrenaline in 'fight or flight' situations."],
["d", 2, "A shoot lit from one side bent 0° at 0 h, 10° at 2 h and 25° at 4 h. How much did it bend in 4 hours?", ["25°", "35°", "10°", "15°"], "Read the 4 h value.", "It bent 25° towards the light in 4 hours."],
["c", 4, "How do hormones differ from nerve impulses?", ["They travel in the blood, act more slowly, last longer and can affect many organs", "They are faster and shorter-lasting", "They travel along neurones", "They only act on muscles"], "Blood vs neurones.", "Hormones are chemicals carried in the blood to target organs. Nerve impulses are electrical, fast and precise."],
["d", 4, "Coleoptiles lit from one side: tip removed → no bending; tip covered with a foil cap → no bending; base covered, tip uncovered → bends. Which conclusion is best?", ["The tip detects the light", "The base detects the light", "Light is not needed", "Foil makes shoots bend"], "Which treatment stops bending?", "Bending happens only when the tip can sense light, so the tip is the light-sensitive region."],
["i", 4, "Why are many seedlings used for each treatment in a phototropism experiment?", ["Individual seedlings vary, so using many gives a more reliable result", "To make the experiment faster", "So some can be eaten", "Because seedlings need company"], "Variation between individuals.", "One seedling could be unusual. A mean from many seedlings is more reliable."],
["c", 5, "Why does a shoot bend towards light?", ["Auxin moves to the shaded side, making those cells elongate more", "Auxin moves to the lit side and makes it grow faster", "Light kills cells on the lit side", "The shoot is pulled by light"], "Faster growth on the dark side.", "Light makes auxin collect on the shaded side, where cells elongate more, so the shoot curves towards the light."],
["d", 5, "Auxin collected from tips lit from one side: lit side 35%, shaded side 65%. Which conclusion is best?", ["One-sided light causes auxin to move to the shaded side", "Light destroys auxin", "Auxin is the same on both sides", "Auxin moves towards light"], "Compare the two sides.", "More auxin on the shaded side supports the idea that auxin is redistributed away from the light."],
["i", 5, "Seedlings on a slowly rotating clinostat, lit from one side, grow straight. What does this show?", ["It cancels the one-sided stimulus (a control)", "Rotation kills the auxin, so the shoot can't respond to light", "Clinostats make shoots bend towards the centre of rotation", "It shows that light is not needed for growth at all"], "Every side gets the same light.", "As each side faces the light equally, there is no one-sided stimulus, so the shoot grows straight. It shows bending needs one-sided light."]
]);
KX("t16s4", [
["c", 2, "What are muscles that work in opposite directions, like the biceps and triceps, called?", ["Antagonistic muscles", "Voluntary muscles", "Cardiac muscles", "Smooth muscles"], "Opposing pairs.", "Antagonistic muscles work in pairs: when one contracts, the other relaxes."],
["d", 2, "When the biceps shortens by 5 cm, the hand moves 35 cm. How many times further does the hand move?", ["7 times", "30 times", "40 times", "5 times"], "Divide 35 by 5.", "35 ÷ 5 = 7. The forearm acts as a lever that multiplies the movement."],
["c", 4, "Why must muscles work in antagonistic pairs?", ["Muscles only pull", "Muscles can only push, so another muscle is needed to pull the bone back", "One muscle on its own would be too strong and could break the bone", "So that each muscle can rest while the other works, and never gets tired"], "Pull, never push.", "A muscle can only contract and pull. To straighten the arm after the biceps bends it, the triceps must contract."],
["d", 4, "Bone density (age 30 = 100%): age 50 women 85%, men 95%; age 70 women 65%, men 85%. Which conclusion is best?", ["Women lose bone density faster than men, so they are at greater risk of osteoporosis", "Men lose bone density faster than women, especially after age 50", "Bone density rises with age, making older bones stronger", "There is no difference between men and women in bone loss"], "Compare each sex.", "Women's bone density falls further, especially after menopause when oestrogen falls, raising osteoporosis risk."],
["i", 4, "Students count clothes-peg squeezes each minute for 5 minutes to study muscle fatigue. What must be kept the same?", ["Same hand, same peg, full squeezes", "The number of squeezes, which should be the same each minute", "The time on the clock, which must be read accurately", "The colour of the peg, so each student uses the same one"], "Only time should change.", "Using the same hand and peg, and full squeezes, keeps the test fair as fatigue builds."],
["c", 5, "In osteoarthritis the cartilage at a joint wears away. Why is the joint painful and stiff?", ["Bone rubs on bone, causing friction, pain and damage", "The joint fills with blood", "Muscles stop working", "Ligaments grow too long"], "Cartilage is the smooth cushion.", "Cartilage reduces friction and absorbs shock. Without it, bones grind together, which is painful and limits movement."],
["d", 5, "Peg squeezes per minute: minute 1 60, minute 2 50, minute 3 40, minute 4 32. What best explains the drop?", ["Muscle fatigue (lactic acid)", "The peg got stiffer with use, so it was harder to squeeze", "The muscle grew stronger, so it squeezed more slowly but harder", "The person got bored, which is the only reason the count fell"], "Working muscles need oxygen.", "As the muscle works hard, anaerobic respiration increases and lactic acid builds up, causing fatigue."],
["i", 5, "To compare fatigue in the dominant and non-dominant hands, how could the method be improved?", ["Rest, alternate order, repeat", "Use only the dominant hand, as it is stronger", "Do both hands at once without rest, to save time", "Count for only 10 seconds"], "Fatigue from one trial affects the next.", "Rest stops fatigue carrying over, alternating the order removes order effects, and repeats increase reliability."]
]);

/* ---------- Homeostasis ---------- */
KX("t17s1", [
["c", 2, "Which hormone lowers blood glucose?", ["Insulin", "Glucagon", "Adrenaline", "Oestrogen"], "Made by the pancreas after meals.", "Insulin makes cells take up glucose and makes the liver store it as glycogen, lowering blood glucose."],
["d", 2, "Blood glucose was 5 mmol/L before a meal and 8 mmol/L 30 minutes after. By how much did it rise?", ["3 mmol/L", "13 mmol/L", "8 mmol/L", "1.6 mmol/L"], "Subtract.", "8 − 5 = 3 mmol/L, from glucose absorbed in the small intestine."],
["c", 4, "What is negative feedback?", ["A change from the set point triggers responses that reverse it, bringing it back", "A change is made bigger and bigger", "The body ignores any change", "A response that only happens once"], "Reverse the change.", "In negative feedback, a rise causes responses that lower it, and a fall causes responses that raise it, keeping conditions stable."],
["d", 4, "Glucose tolerance test (blood glucose in mmol/L at 0, 1 and 2 hours): person A 5, 9, 5; person B 7, 15, 13. Who may have diabetes?", ["Person B", "Person A", "Both", "Neither"], "Who returns to normal?", "Person A returns to normal within 2 hours. Person B starts high, rises far and stays high: a sign of diabetes."],
["i", 4, "When testing urine samples for glucose with test strips, what is a useful control?", ["Known glucose solution and distilled water", "A strip that is not used, kept in its packet as a comparison", "A different type of strip, to check the first type works", "A blood sample from the same person, tested at the same time"], "Positive and negative.", "Known positive and negative samples show the strips work and what each colour means."],
["c", 5, "Why do people with type 1 diabetes inject insulin rather than taking it as a tablet?", ["Insulin is a protein, so it would be digested in the gut", "Tablets are too big", "Insulin works only in muscles", "Injections are cheaper"], "What does the stomach do to protein?", "Insulin would be broken down by proteases in the gut before reaching the blood, so it is injected."],
["d", 5, "During long exercise, blood glucose fell from 5 to 4 mmol/L and glucagon levels rose. What best explains the glucagon rise?", ["Glucagon stimulates the liver to break glycogen into glucose, raising blood glucose", "Glucagon lowers blood glucose", "Glucagon makes muscles store glucose", "Glucagon is made by muscles"], "Opposite of insulin.", "Falling glucose triggers the pancreas to release glucagon, which makes the liver release glucose: negative feedback."],
["i", 5, "In a trial of a new diabetes drug, volunteers do not know if they get the drug or a placebo. Why?", ["To avoid bias", "To keep the drug a secret from other drug companies", "To make the trial shorter, as fewer tests are needed", "Because placebos are harmful if patients know about them"], "Expectation can change results.", "If volunteers knew, their behaviour or reports could change. A blind trial makes the comparison fair."]
]);
KX("t17s2", [
["c", 2, "Which part of the brain controls breathing rate?", ["The medulla (brainstem)", "The cerebrum", "The cerebellum", "The pituitary gland"], "Automatic control.", "The breathing centre in the medulla sends impulses to the diaphragm and intercostal muscles."],
["d", 2, "Breathing rate was 12 breaths per minute at rest and 24 during exercise. How many times faster was it in exercise?", ["2 times", "12 times", "24 times", "36 times"], "Divide 24 by 12.", "24 ÷ 12 = 2, twice as fast."],
["c", 4, "What mainly stimulates faster breathing during exercise?", ["A rise in blood CO₂ (lower pH), detected by chemoreceptors", "A rise in blood glucose", "A fall in body temperature", "A rise in oxygen"], "The breathing centre watches CO₂.", "Exercising muscles release CO₂, lowering blood pH. Chemoreceptors detect this, and the breathing centre increases rate and depth."],
["d", 4, "Breathing rate when a resting person breathes air containing 0%, 3% and 6% CO₂: 12, 18 and 30 breaths per minute. Which conclusion is best?", ["More CO₂ in the inhaled air makes breathing faster", "CO₂ slows breathing", "CO₂ has no effect", "Breathing depends only on oxygen"], "Look at the trend.", "Breathing rate rises as CO₂ rises, even with oxygen available, showing CO₂ is the main stimulus."],
["i", 4, "When measuring breathing rate before and after exercise, why wait for it to return to resting before each new trial?", ["So each trial starts from the same baseline", "To make the person tired", "To speed up recovery", "To save time"], "Same starting point.", "If breathing is still fast from the last trial, the next result would be wrong. A resting baseline keeps trials comparable."],
["c", 5, "Why does holding your breath become impossible after a while?", ["CO₂ builds up", "Oxygen builds up in the blood and forces you to breathe out", "The lungs burst if you don't breathe for too long", "The diaphragm gets tired and stops working"], "What rises when you don't breathe out?", "CO₂ keeps being made by respiration. As it builds up, blood pH falls and the urge to breathe becomes overwhelming."],
["d", 5, "Blood pH: at rest 7.40, during hard exercise 7.30, 10 minutes after 7.38. What best explains these changes?", ["CO₂ and lactic acid lower the pH in exercise; faster breathing removes CO₂ and helps restore it", "Exercise makes blood more alkaline, so the pH rises", "The pH does not change in exercise; the readings are within error", "Breathing adds acid to the blood, which is removed later by the kidneys"], "Acids from respiration.", "CO₂ forms an acid in blood, and lactic acid adds more. Deeper, faster breathing removes CO₂, so the pH returns towards 7.4."],
["i", 5, "A claim says we breathe faster in exercise only because oxygen runs out. Which experiment tests it best?", ["At rest, breathe air with extra CO₂ but normal oxygen, and see whether breathing rate rises", "Run faster and see if the breathing rate keeps rising", "Hold your breath and see how long it takes to feel the urge to breathe", "Breathe pure oxygen while asleep and see if the breathing stops"], "Change CO₂ but not oxygen.", "If breathing speeds up when only CO₂ rises, CO₂ (not lack of oxygen) is the main stimulus, which the claim ignores."]
]);

/* ---------- Ecosystems ---------- */
KX("t18s1", [
["c", 2, "What is a community?", ["All the populations of different species living in an area", "One species in an area", "The non-living parts of an area", "All the organisms of one species worldwide"], "Many species together.", "A population is one species in an area; a community is all the populations living and interacting there."],
["d", 2, "In the food chain grass → grasshopper → frog → snake, how many consumers are there?", ["3", "4", "1", "2"], "Everything that eats.", "The grasshopper, frog and snake are consumers. Grass is the producer."],
["c", 4, "Why do food chains rarely have more than five links?", ["Energy is lost at each level, so too little is left to support more levels", "There are not enough animals in most habitats", "Top predators eat plants, which shortens the chain", "Producers run out of light in long food chains"], "Energy loss adds up.", "Only about 10% of energy passes to each level. After a few levels, there is too little to support a population of predators."],
["d", 4, "Hare numbers peak in year 2 and lynx numbers peak in year 3; hares then fall in years 3–4. What best explains this?", ["More lynx eat more hares, and lynx numbers lag behind hare numbers", "Hares eat lynx", "Lynx and hares compete for food", "The numbers are random"], "Predator follows prey.", "Plenty of hares lets lynx breed. More lynx then eat more hares, so hares fall, and lynx fall after them."],
["i", 4, "To investigate competition, radish seeds are grown in pots at different densities. What should be measured?", ["The mean dry mass per plant after a fixed time", "The total number of seeds sown", "The colour of the pots", "The height of the tallest plant only"], "Fair measure of each plant's growth.", "Mean dry mass per plant shows how well each plant grew with more competitors."],
["c", 5, "If all the frogs were removed from a food web, what is most likely to happen?", ["Grasshoppers increase, and snakes decrease or switch to other prey", "Nothing changes, because other animals will quickly fill the gap", "Grasshoppers decrease, because frogs protect them from snakes", "Snakes increase, because they have less competition for food"], "Follow the arrows.", "Fewer frogs means fewer grasshoppers eaten, so grasshoppers increase. Snakes lose a food source, so they decline or eat other prey."],
["d", 5, "Mean dry mass per radish plant: 5 per pot 4 g, 10 per pot 2.5 g, 20 per pot 1 g. Which conclusion is best?", ["As density increases, competition for light, water and minerals reduces each plant's growth", "Crowded plants grow more, because they shelter each other", "Density has no effect; the differences are due to chance", "Total mass is the same in each pot, so competition doesn't matter"], "More plants, less each.", "With more plants per pot, each gets less light, water and minerals, so each one is smaller."],
["i", 5, "Why is the mean dry mass per plant used instead of the total mass per pot?", ["The total depends on how many plants were sown, so it hides the effect on each plant", "The total mass is too hard to measure accurately", "Dry mass cannot be added up for many plants", "Each plant must be the same size for a fair test"], "Compare like with like.", "A pot of 20 small plants could have a similar total mass to one with 5 big plants. The mean per plant shows the effect of competition."]
]);
KX("t18s2", [
["c", 2, "Which organisms return nutrients to the soil?", ["Decomposers, such as bacteria and fungi", "Producers, which take in nutrients and release them when they photosynthesise", "Herbivores, which return all the nutrients in plants by eating them", "Top predators, which release nutrients when they kill their prey"], "Breakdown of dead matter.", "Decomposers break down dead organisms and waste, releasing minerals and CO₂ for producers to use again."],
["d", 2, "Producers capture 10 000 kJ of energy and herbivores gain 1000 kJ. What percentage is passed on?", ["10%", "1%", "90%", "100%"], "1000 ÷ 10 000.", "1000 ÷ 10 000 × 100 = 10%."],
["c", 4, "Why is energy lost between trophic levels?", ["Heat from respiration, plus uneaten and undigested parts", "Energy is destroyed by each organism as it uses it to live", "Plants keep all the energy, so animals only get a little", "Consumers don't need much energy, so they pass less on"], "Where does it go?", "Organisms use energy for respiration (lost as heat) and some material is never eaten or is egested, so only a small fraction passes on."],
["d", 4, "Energy in a pyramid: producers 5000 kJ, primary consumers 500, secondary 50, tertiary 5. What is the efficiency of each transfer?", ["10%", "50%", "1%", "90%"], "500 ÷ 5000.", "Each level gets 1/10 of the one below, so about 10% is transferred each time."],
["i", 4, "Leaf litter is placed in mesh bags with coarse or fine mesh. Why?", ["Coarse mesh lets earthworms and insects in; fine mesh lets only microbes in, so their roles can be compared", "To keep the leaves dry, so that they don't rot too quickly in the rain", "To stop all decomposition, so the starting mass of the leaves can be measured", "To make the bags look different, so they are easy to find again later"], "Who can get in?", "Comparing the bags shows how much larger soil animals add to decomposition compared with microbes alone."],
["c", 5, "Why can more people be fed from a field of crops eaten directly than from the same field used to feed cattle?", ["Energy is lost at each trophic level, so eating plants directly avoids the loss in the cattle", "Cattle make energy", "Plants contain no energy", "Meat contains more energy than the crops"], "Count the levels.", "Cattle use most of the energy in their food for respiration and movement. Eating crops directly gives about 10 times more energy to people."],
["d", 5, "Leaf mass lost in 3 months: coarse mesh bags 60%, fine mesh bags 25%. Which conclusion is best?", ["Soil animals speed up decay", "Microbes do all the decomposing, so the mesh makes no difference", "Mesh size has no effect; the difference is due to the weather", "Fine mesh speeds up decay by keeping the leaves moist"], "What can get into each bag?", "Larger animals break leaves into small pieces, giving microbes more surface to work on. Without them, decay is much slower."],
["i", 5, "In the litter-bag experiment, why are the leaves dried before weighing?", ["Water content varies with weather", "Wet leaves are heavier to carry back to the lab", "Drying kills the leaves, so decomposition stops before weighing", "Decomposers need dry leaves, so drying helps them work"], "Water comes and goes.", "Wet mass would rise after rain and fall in the sun. Dry mass measures only the material broken down."]
]);
KX("t18s3", [
["c", 2, "What is a quadrat used for?", ["Sampling plants or slow-moving animals in a known area", "Catching flying insects", "Measuring temperature", "Counting fish"], "A square frame.", "A quadrat marks out a known area, so organisms inside can be counted to estimate population size or cover."],
["d", 2, "Ten 1 m² quadrats contained 40 daisies in total. What is the mean density?", ["4 per m²", "40 per m²", "10 per m²", "0.25 per m²"], "40 ÷ 10.", "40 daisies ÷ 10 m² = 4 daisies per m²."],
["c", 4, "Why does high biodiversity make an ecosystem more stable?", ["More alternative food sources", "There is less competition between species, so they all grow larger", "More species means fewer producers, so energy flows faster", "Animals stop eating each other when there are many species"], "Many links in the web.", "In a diverse web, if one species declines, consumers can switch food, so the whole system recovers more easily."],
["d", 4, "Mark-release-recapture: 40 snails were marked and released. Later, 50 were caught, 10 of them marked. What is the estimated population?", ["200", "100", "90", "400"], "N = (40 × 50) ÷ 10.", "(40 × 50) ÷ 10 = 200 snails."],
["i", 5, "In mark-release-recapture, why must the marks not harm the animals or make them easier to see?", ["So marked animals behave like the rest", "Marks wash off harmed animals more quickly, so they can't be recognised", "Marks make the animals heavier, so they can't move into the traps", "It is illegal to mark animals that might be harmed in any way"], "Marked animals must behave like the rest.", "The method assumes marked animals mix and survive like unmarked ones. If marks change survival, the estimate is wrong."],
["c", 5, "Why do conservationists build wildlife corridors between patches of forest?", ["More movement, mixing gene pools", "To stop animals moving between patches, so each group stays safe", "To make it easier to build roads through the forest without harming animals", "To reduce biodiversity in each patch so that fewer species compete"], "Connecting small islands of habitat.", "Isolated patches hold small populations at risk of inbreeding and local extinction. Corridors let animals move, feed and find mates."],
["d", 5, "Lichen species found on trees: 1 km from a city centre 2, 5 km 6, 10 km 15. Which conclusion is best?", ["Cleaner air further from the city", "Lichens prefer city conditions because there are more buildings to grow on", "Distance from the city has no effect on lichens; the numbers are random", "Lichens cause air pollution, so there are fewer of them in cities"], "Lichens are indicator species.", "Many lichen species cannot survive sulfur dioxide. More species further out suggests cleaner air there."],
["i", 4, "To study how plants change from a seashore to a woodland, why use a belt transect rather than random quadrats?", ["It follows the gradient", "It is faster to count than random quadrats in a large area", "Random quadrats are not allowed on beaches and woodland edges", "It finds the rarest plants, which random quadrats always miss"], "Change along a line.", "Placing quadrats at regular intervals along a line shows how species change as conditions like soil and light change."]
]);

/* ---------- Health and Diseases ---------- */
KX("t19s1", [
["c", 2, "What causes a communicable disease?", ["A pathogen", "A poor diet only, which weakens the body", "Ageing, which wears out the body's defences", "Genes alone, passed on from parents to children"], "It can spread between people.", "Communicable diseases are caused by pathogens that pass from one person to another."],
["d", 2, "Cholera cases in a town by drinking well: well A 50, well B 2, well C 3. Which well is the most likely source?", ["Well A", "Well B", "Well C", "All equally"], "Most cases.", "Most cases are linked to well A, suggesting its water carries the cholera bacteria."],
["c", 4, "How does handwashing reduce the spread of disease?", ["It removes pathogens from the hands before they reach the mouth, food or others", "It makes the skin produce antibodies", "It kills all viruses in the body", "It makes hands waterproof"], "Break the chain.", "Washing with soap removes many pathogens from hands, so fewer are passed to food, faces or other people."],
["d", 4, "Flu cases per week: 10, 40, 160, 300, 150, 60. In which week did cases peak?", ["Week 4", "Week 3", "Week 5", "Week 6"], "Largest number.", "300 cases in week 4 is the peak; cases then fall as people recover and become immune."],
["i", 4, "Paper discs soaked in different antiseptics are placed on agar covered with bacteria. What should be measured?", ["The diameter of the clear zone around each disc", "The colour of the agar", "The mass of the disc", "The number of discs"], "Where the bacteria can't grow.", "A larger clear zone means the antiseptic stopped bacterial growth over a wider area."],
["c", 5, "Why don't antibiotics work against viruses?", ["No cell walls or ribosomes to target", "Viruses are too big for antibiotics to get inside them", "Antibiotics only work in the gut, where most bacteria live", "Viruses are a type of bacteria, but with thicker cell walls"], "What do antibiotics attack?", "Antibiotics target structures like bacterial cell walls and ribosomes. Viruses lack these, so antibiotics do not affect them."],
["d", 5, "Clear zones: antiseptic A 4 mm, B 18 mm, C 10 mm, water 0 mm. Which statement is best supported?", ["B was most effective here", "B kills all the bacteria on the plate, because its zone is largest", "A is completely useless, so it should never be used as an antiseptic", "Water kills bacteria, because its disc also has a small clear zone"], "Don't claim more than the results show.", "B gave the largest clear zone here. The test cannot show it kills every type of bacterium, and A did have some effect."],
["i", 5, "In school labs, why are bacteria plates incubated at 25 °C, not 37 °C?", ["To reduce the risk of growing bacteria that cause disease in humans", "Bacteria do not grow at 37 °C", "To make the agar melt", "To make the bacteria grow faster"], "Body temperature suits human pathogens.", "Pathogens that infect humans grow best at body temperature. 25 °C makes them less likely to grow."]
]);
KX("t19s2", [
["c", 2, "What do antibodies do?", ["Bind to specific antigens", "They carry oxygen around the body in the blood plasma", "They digest food in the small intestine as part of the gut lining", "They help the blood clot at a wound, together with platelets"], "Made by lymphocytes.", "Each antibody fits a specific antigen. Binding marks or clumps pathogens so they can be destroyed."],
["d", 2, "Measles cases fell from 500 to 10 when vaccination rose from 50% to 95%. By how many cases did they fall?", ["490", "510", "45", "50"], "Subtract.", "500 − 10 = 490 fewer cases."],
["c", 4, "Why can a vaccine protect you for many years?", ["It makes memory cells", "It contains antibiotics that stay in the body for years", "It kills all future pathogens before they can enter the body", "It stays in the blood forever, attacking any pathogen it meets"], "Remembering the antigen.", "Vaccines trigger an immune response that leaves memory cells. On real infection, they make antibodies fast."],
["d", 4, "Antibody levels: after the first infection they peaked at 10 units after 14 days; after a second exposure they peaked at 100 units after 5 days. What best explains this?", ["Memory cells from the first infection give a faster, larger second response", "The pathogen was weaker the second time", "Antibodies were left from the first time", "The person was older"], "Faster and bigger.", "Memory cells recognise the antigen at once and quickly make many antibody-producing cells, so the pathogen is destroyed before illness develops."],
["i", 4, "Why are new vaccines tested on a small group of volunteers first, then on thousands?", ["To check safety and dose first, then to show it works and to find rare side effects", "To save money only", "Because small groups are more accurate", "To make the vaccine stronger"], "Safety first.", "Small trials check safety and dose; large trials show effectiveness and reveal rarer side effects."],
["c", 5, "Why do people need a new flu vaccine each year?", ["The virus's antigens change", "Memory cells die every year, so the immune system forgets every disease", "The vaccine is used up by the body each winter", "Flu becomes a bacterium over the summer, so the vaccine no longer works"], "Changing antigens.", "Flu viruses change their surface antigens often. A vaccine is updated to match the strains expected each year."],
["d", 5, "Measles needs about 95% of people vaccinated for herd immunity. A school has 80% vaccinated. Which is the best interpretation?", ["Coverage is too low to protect the unvaccinated, so an outbreak is possible", "Everyone is protected", "80% is above the threshold", "Measles cannot spread in schools"], "Compare with 95%.", "Below the threshold, the virus can find enough unprotected people to spread, putting unvaccinated students at risk."],
["i", 5, "A parent says, 'My unvaccinated child never caught measles, so vaccines are unnecessary.' What is the best evaluation?", ["One case isn't evidence (herd immunity)", "The parent is right: if vaccines were needed, every unvaccinated child would catch measles", "This proves vaccines are harmful, because the unvaccinated child stayed healthy", "This proves measles doesn't exist any more, so nobody needs protecting"], "Anecdote vs data.", "A single example cannot show what happens to a whole population. Large studies show vaccines greatly cut disease."]
]);
KX("t19s3", [
["c", 2, "Which of these is a non-communicable disease?", ["Type 2 diabetes", "Influenza", "Cholera", "Tuberculosis"], "It cannot be caught.", "Non-communicable diseases are not caused by pathogens and cannot spread between people."],
["d", 2, "BMI = mass (kg) ÷ height² (m²). A person is 80 kg and 2 m tall. What is their BMI?", ["20", "40", "160", "10"], "80 ÷ (2 × 2).", "80 ÷ 4 = 20, within the healthy range."],
["c", 4, "Why can a diet high in saturated fat increase the risk of coronary heart disease?", ["It raises blood cholesterol", "It lowers blood pressure, so not enough blood reaches the heart muscle", "It makes the heart bigger, which squeezes the coronary arteries shut", "It removes cholesterol from the blood, so the arteries become weak"], "Plaques in arteries.", "High cholesterol can lead to fatty deposits in artery walls. Narrowed coronary arteries supply less oxygen to heart muscle."],
["d", 4, "In a country, type 2 diabetes rose from 5% (2000) to 8% (2010) to 11% (2020), while obesity rose from 15% to 20% to 25%. Which conclusion is best?", ["Both rose together, suggesting a link, though this alone doesn't prove cause", "Obesity is caused by diabetes, so diabetes came first", "There is no link, as the numbers are in different units", "Diabetes will soon fall, as obesity levels off"], "Correlation.", "The two trends rise together, which supports a link. Other evidence (like trials) is needed to show cause."],
["i", 4, "A survey asks students about their exercise and snack habits. Why should it be anonymous?", ["So answers are honest", "To make the survey faster to complete", "To make the survey more fun for the students", "So that no one feels they have to take part"], "Honest answers.", "People may give 'better-sounding' answers if named. Anonymity gives more truthful data."],
["c", 5, "Why is type 2 diabetes more common in people who are overweight and inactive?", ["Cells respond less to insulin", "They make no insulin at all, because fat damages the pancreas", "They eat too little sugar, so their cells stop using insulin", "Exercise causes diabetes by using up blood glucose too fast"], "Insulin resistance.", "In type 2 diabetes, cells respond poorly to insulin. Excess body fat and inactivity raise this risk; exercise and weight loss help."],
["d", 5, "Skin cancer per 100 000: sunny country, mostly fair skin 30; sunny country, mostly darker skin 3; cloudy country, mostly fair skin 10. Which conclusion is best?", ["Both UV exposure and skin type affect skin cancer risk", "Only sunshine matters", "Only skin type matters", "Skin cancer is infectious"], "Compare pairs that differ in one thing.", "Sunny vs cloudy (same skin type): 30 vs 10, so UV matters. Fair vs darker (same sun): 30 vs 3, so skin type matters."],
["i", 5, "A study finds that people who eat more fruit live longer. What is the best next step to test whether fruit is the cause?", ["A randomised controlled trial where groups differ only in fruit intake", "Ask more people what they eat", "Look at one long-lived person", "Stop eating fruit"], "Control other lifestyle factors.", "Fruit-eaters may also exercise more or smoke less. A randomised trial controls these, so the effect of fruit alone can be seen."]
]);
