/* Lab section d: challenges for the existing coordination and response sims. */

const simchDone = (p, id) => Array.isArray(p.done) && p.done.includes(id);

SIM_CH.pupil = {
  title: "Pupil Reflex Guardian", mins: 15,
  story: "Protect the retina but keep the image bright enough. Use the light controls to prove how the iris muscles work.",
  missions: [
    { ic: "🎛️", name: "Control the pupil", tasks: [
      { type: "goal", ic: "🌑", do: "Press <b>🌑 Dark room</b>. Make the pupil dilate.", look: "Eye picture · pupil diameter", target: "Diameter ≥ 7 mm",
        check: p => p.light < 10 && p.diam >= 7 && p.radial === "contract", meter: p => ({ v: p.diam, min: 0, max: 8, lo: 7, hi: 8, unit: " mm", label: "Pupil diameter" }), hold: .4,
        why: "In dim light, radial muscles contract and circular muscles relax. The bigger pupil lets more light enter." },
      { type: "goal", ic: "☀️", do: "Press <b>☀️ Bright sun</b>. Make the pupil constrict.", look: "Eye picture · muscle panel", target: "Diameter ≤ 2.8 mm",
        check: p => p.light > 90 && p.diam <= 2.8 && p.circular === "contract", meter: p => ({ v: p.diam, min: 0, max: 8, lo: 0, hi: 2.8, unit: " mm", label: "Pupil diameter" }), hold: .4,
        why: "Bright light makes circular muscles contract and radial muscles relax. The pupil becomes smaller." },
      { type: "read", ic: "📏", do: "Read the pupil diameter in <b>☀️ Bright sun</b>.", look: "Pupil diameter under the bar",
        need: p => p.light > 90 && p.diam <= 3, needTxt: "Press <b>☀️ Bright sun</b> and wait for constriction.",
        fields: [["Pupil diameter", p => p.diam, .4, "mm"]], why: "A small pupil cuts down the amount of light reaching the retina." }] },
    { ic: "🎞️", name: "Protect and still see", tasks: [
      { type: "read", ic: "🎞️", do: "Measure light reaching the retina in <b>☀️ Bright sun</b>.", look: "Light reaching the retina bar",
        need: p => p.light > 90 && p.circular === "contract", needTxt: "Set <b>☀️ Bright sun</b> so the circular muscles contract.",
        fields: [["Light at retina", p => p.retina, 4, "%"]], why: "Even in bright sun, the constricted pupil keeps the retina reading low." },
      { type: "goal", ic: "💡", do: "Press <b>💡 Classroom</b>. Make a middle-sized pupil.", look: "Pupil diameter + retina bar", target: "Diameter 3.5–5.2 mm",
        check: p => p.light > 40 && p.light < 60 && p.diam >= 3.5 && p.diam <= 5.2, meter: p => ({ v: p.diam, min: 0, max: 8, lo: 3.5, hi: 5.2, unit: " mm", label: "Pupil diameter" }), hold: .4,
        why: "Moderate light gives a moderate pupil size: enough light for a clear image, not too much for the retina." },
      { type: "pick", ic: "🛡️", do: "Why does the pupil become small in bright light?", look: "Retina bar",
        need: p => p.light > 90 && p.diam <= 3, needTxt: "Press <b>☀️ Bright sun</b> again.",
        opts: ["Less light enters, helping protect the retina", "More light enters, making the retina brighter", "The lens changes shape to block light", "The optic nerve contracts"],
        miss: ["", "Look at the retina bar: it falls when the pupil is small.", "The lens focuses light; the iris changes pupil size.", "Nerves carry impulses; they do not contract like muscles."],
        why: "The pupil reflex is protective: high light → pupil constricts → less light reaches the retina." },
      { type: "pick", ic: "🌑", do: "Why does the pupil dilate in a dark room?", look: "Dark room pupil size",
        need: p => p.light < 10 && p.diam >= 7, needTxt: "Press <b>🌑 Dark room</b>.",
        opts: ["More light can enter, so the image is bright enough", "The retina is protected from too much light", "Circular muscles contract strongly", "The lens becomes thinner"],
        miss: ["", "Protection is the bright-light response. In darkness, the problem is too little light.", "In the dark, circular muscles relax; radial muscles contract.", "The lens is for focusing, not controlling light entry."],
        why: "In dim light, dilation helps collect enough light for vision." }] },
    { ic: "⚡", name: "Follow the reflex", tasks: [
      { type: "goal", ic: "🔦", do: "Press <b>🔦 Torch flash</b>. Catch the automatic reflex.", look: "Reflex arc steps", target: "Torch flash active",
        check: p => p.torch, hold: 0, why: "The flash is a stimulus. The reflex arc runs automatically, without conscious thought." },
      { type: "order", ic: "🔢", do: "Put the pupil reflex pathway in order.", look: "Reflex arc card",
        items: ["Retina detects bright light", "Sensory neurone carries impulses in the optic nerve", "Brain coordinates the response", "Motor neurone carries impulses to the iris", "Circular iris muscles contract"],
        why: "Receptor → sensory neurone → brain → motor neurone → effector. The iris muscles are the effectors." },
      { type: "fill", ic: "✍️", do: "Complete the reflex sentence.",
        text: "A pupil reflex is {involuntary|voluntary|learned}: it protects the {retina|lens|cornea} by changing the {iris muscles|optic nerve|eyelids}.",
        why: "The retina is protected because the iris muscles automatically change pupil size." }] },
    { ic: "🧠", name: "Explain the muscles", tasks: [
      { type: "fill", ic: "⭕", do: "Complete the antagonistic muscle rule.",
        text: "In bright light, circular muscles {contract|relax} and radial muscles {relax|contract}. In dim light, radial muscles {contract|relax}.",
        why: "Circular and radial iris muscles are antagonistic: when one set contracts, the other relaxes." },
      { type: "pick", ic: "✳️", do: "A classmate says: “Radial muscles contract in bright light.” What is wrong?",
        opts: ["Radial muscles contract in dim light, making the pupil bigger", "Radial muscles contract in bright light to protect the retina", "Radial muscles are in the lens, not the iris", "Radial muscles detect light"],
        miss: ["", "Test bright sun: the panel says radial muscles relax.", "Radial muscles are part of the iris.", "The retina detects light; muscles respond."],
        why: "Bright light uses circular muscle contraction. Dim light uses radial muscle contraction." },
      { type: "pick", ic: "👁️", do: "Which statement best describes the whole reflex?",
        opts: ["It balances seeing clearly with protecting the retina", "It focuses near and far objects on the retina", "It turns sound into nerve impulses", "It makes the lens more convex"],
        why: "The pupil reflex controls light entry: not too much for the retina, not too little for vision." }] }
  ]
};

SIM_CH.lens = {
  title: "Focus and Glasses Clinic", mins: 15,
  story: "Use the ray diagram to diagnose blurred vision, then choose the lens shape that puts the image on the retina.",
  missions: [
    { ic: "🔍", name: "Accommodation", tasks: [
      { type: "goal", ic: "📖", do: "Switch to <b>📖 Book (25 cm)</b>. Make the normal eye clear.", look: "Lens shape + image", target: "Near image clear; lens thick",
        check: p => p.obj === "near" && p.eye === "normal" && p.glasses === "none" && p.sharp && p.thick && p.accom >= 70, meter: p => ({ v: p.accom, min: 0, max: 100, lo: 70, hi: 100, unit: "%", label: "Accommodation" }), hold: .5,
        why: "For a near object, ciliary muscles contract, suspensory ligaments slacken and the lens becomes thicker." },
      { type: "read", ic: "📏", do: "Read the accommodation for the book.", look: "Task meter + lens information",
        need: p => p.obj === "near" && p.eye === "normal" && p.glasses === "none" && p.thick, needTxt: "Set <b>📖 Book (25 cm)</b>, <b>🙂 Normal</b>, <b>None</b>.",
        fields: [["Accommodation", p => p.accom, 8, "%"]], why: "A near object needs a high accommodation value." },
      { type: "goal", ic: "🌳", do: "Set <b>🌳 Distant tree</b>, <b>🙂 Normal</b>, <b>None</b>.", look: "Ray diagram + view card", target: "Clear distant image",
        check: p => p.obj === "far" && p.eye === "normal" && p.glasses === "none" && p.sharp && p.accom <= 8, meter: p => ({ v: p.accom, min: 0, max: 100, lo: 0, hi: 8, unit: "%", label: "Accommodation" }), hold: .5,
        why: "For a distant object, a normal eye needs little accommodation. The lens is thin and less convex." },
      { type: "pick", ic: "⭕", do: "What changed when focusing on the book?", look: "What's happening list",
        need: p => p.obj === "near" && p.eye === "normal" && p.thick, needTxt: "Set <b>📖 Book (25 cm)</b> with a <b>🙂 Normal</b> eye.",
        opts: ["Ciliary muscles contracted; suspensory ligaments slackened", "Ciliary muscles relaxed; suspensory ligaments tightened", "Radial iris muscles contracted", "The retina moved forwards"],
        miss: ["", "That is the distant-object pattern.", "Iris muscles control the pupil, not focusing.", "The retina stays at the back of the eye."],
        why: "Accommodation changes lens shape, not eyeball length." }] },
    { ic: "👓", name: "Short sight", tasks: [
      { type: "goal", ic: "👓", do: "Set <b>👓 Short sight</b>, <b>🌳 Distant tree</b>, <b>None</b>.", look: "Focus dot and retina", target: "Focus in front of retina",
        check: p => p.eye === "short" && p.obj === "far" && p.glasses === "none" && !p.sharp && p.focus === "front", hold: .5,
        why: "In short sight, distant rays focus in front of the retina, so the distant image is blurred." },
      { type: "pick", ic: "🎯", do: "What does <b>focus in front</b> mean for vision?", look: "What the pal sees",
        need: p => p.eye === "short" && p.obj === "far" && p.focus === "front", needTxt: "Show <b>👓 Short sight</b> looking at the <b>🌳 Distant tree</b>.",
        opts: ["Distant objects are blurred", "Near objects must be blurred", "The pupil is too small", "The cochlea is damaged"],
        miss: ["", "Short-sighted people usually see near objects better than distant ones.", "Pupil size controls brightness, not this focus error.", "The cochlea is in the ear."],
        why: "The image must form on the retina to be sharp." },
      { type: "goal", ic: ")(", do: "Add <b>Concave )(</b> glasses to correct short sight.", look: "Glasses + retina", target: "Image focused on retina",
        check: p => p.eye === "short" && p.obj === "far" && p.glasses === "concave" && p.sharp, hold: .5,
        why: "A concave lens diverges light before it enters the eye, moving the focus back onto the retina." },
      { type: "fill", ic: "✍️", do: "Complete the short-sight correction sentence.",
        text: "Short sight is corrected by a {concave|convex|flat} lens because it {diverges|converges|blocks} light rays first.",
        why: "Concave lenses spread rays out, helping a long/too-strong eye focus on the retina." }] },
    { ic: "🔭", name: "Long sight", tasks: [
      { type: "goal", ic: "🔭", do: "Set <b>🔭 Long sight</b>, <b>📖 Book (25 cm)</b>, <b>None</b>.", look: "Focus dot and warning", target: "Focus behind retina",
        check: p => p.eye === "long" && p.obj === "near" && p.glasses === "none" && !p.sharp && p.focus === "behind" && p.maxed, hold: .5,
        why: "The eye lens is already at its maximum, but a near object still focuses behind the retina." },
      { type: "goal", ic: "()", do: "Add <b>Convex ()</b> glasses to correct long sight.", look: "Glasses + clear view", target: "Near image sharp",
        check: p => p.eye === "long" && p.obj === "near" && p.glasses === "convex" && p.sharp, hold: .5,
        why: "A convex lens converges rays before they enter, so a near image can focus on the retina." },
      { type: "pick", ic: "🧪", do: "Why is a concave lens wrong for long sight?", look: "Try Concave )( with long sight",
        need: p => p.eye === "long" && p.obj === "near", needTxt: "Keep <b>🔭 Long sight</b> looking at the <b>📖 Book (25 cm)</b>.",
        opts: ["It spreads rays out, making the behind-retina focus worse", "It converges rays too much", "It changes the retina into a lens", "It repairs the ciliary muscle"],
        miss: ["", "Concave lenses diverge; convex lenses converge.", "The retina detects the image; it does not become a lens.", "Glasses bend light; they do not repair muscles."],
        why: "Long sight needs extra convergence, so it is corrected by a convex lens." }] },
    { ic: "🧠", name: "Explain it", tasks: [
      { type: "order", ic: "🔢", do: "Put accommodation for a near object in order.",
        items: ["Ciliary muscles contract", "Suspensory ligaments slacken", "Lens becomes thicker and more convex", "Light is refracted more", "Image focuses on the retina"],
        why: "This is the near-object chain: muscle → ligament → lens shape → refraction → sharp image." },
      { type: "pick", ic: "🙅", do: "A normal eye with no glasses sees the book clearly. Why?",
        opts: ["It accommodates by making the lens thicker", "It needs a concave lens for every near object", "The retina moves forward", "The pupil becomes the lens"],
        why: "A healthy eye focuses near objects by accommodation." },
      { type: "fill", ic: "✍️", do: "Complete the sight-defect comparison.",
        text: "{Short sight|Long sight|Normal sight} blurs distant objects and uses a {concave|convex} lens. {Long sight|Short sight} blurs near objects and uses a {convex|concave} lens.",
        why: "Short sight: distant focus in front → concave. Long sight: near focus behind → convex." }] }
  ]
};

SIM_CH.ear = {
  title: "Cochlea Sound Mapper", mins: 15,
  story: "Send sounds through the ear, map pitch along the cochlea and test why loud noise can damage hearing.",
  missions: [
    { ic: "🎵", name: "Sound pathway", tasks: [
      { type: "goal", ic: "🎵", do: "Press <b>🎵 Hear it</b>. Start waves and impulses.", look: "Ear diagram + auditory nerve", target: "Sound heard",
        check: p => p.played >= 1 && p.waves && p.heard, hold: .5,
        why: "Sound waves make the eardrum, ossicles and cochlear fluid vibrate, causing nerve impulses." },
      { type: "order", ic: "🔢", do: "Put the sound pathway in order.", look: "Highlighted pathway list",
        items: ["Pinna collects sound waves", "Ear canal carries waves to the eardrum", "Eardrum vibrates", "Ossicles amplify the vibrations", "Oval window passes vibrations into the cochlea", "Hair cells make nerve impulses", "Auditory nerve carries impulses to the brain"],
        why: "Hearing is a pathway: vibrations are changed into nerve impulses in the cochlea." },
      { type: "goal", ic: "⏸", do: "Press <b>⏸ Pause sound waves</b>. Stop hearing.", look: "Waves and impulse dots", target: "No waves; no hearing",
        check: p => !p.waves && !p.heard, hold: .5,
        why: "If the waves stop, hair cells are not stimulated and no impulses are sent." }] },
    { ic: "🎵", name: "Pitch map", tasks: [
      { type: "goal", ic: "🥁", do: "Press <b>🥁 Drum 100 Hz</b>. Find the low-pitch region.", look: "Uncoiled cochlea", target: "Apex region active",
        check: p => p.freq >= 80 && p.freq <= 140 && p.region === "apex", hold: .5,
        why: "Low-frequency sounds vibrate hair cells near the apex (tip) of the cochlea." },
      { type: "read", ic: "📏", do: "Read the drum frequency.", look: "Pitch label",
        need: p => p.freq >= 80 && p.freq <= 140, needTxt: "Press <b>🥁 Drum 100 Hz</b>.",
        fields: [["Frequency", p => p.freq, 20, "Hz"]], why: "Frequency is pitch: about 100 vibrations per second for the drum." },
      { type: "goal", ic: "🐦", do: "Press <b>🐦 Bird 4 kHz</b>. Find the high-pitch region.", look: "Uncoiled cochlea", target: "Base region active",
        check: p => p.freq >= 3500 && p.freq <= 4500 && p.region === "base", hold: .5,
        why: "Higher frequencies stimulate hair cells near the base of the cochlea." },
      { type: "pick", ic: "🐌", do: "Which pitch map is correct?", look: "Base/apex labels",
        need: p => p.region === "base" || p.region === "apex", needTxt: "Try <b>🥁 Drum 100 Hz</b> and <b>🐦 Bird 4 kHz</b>.",
        opts: ["High pitch → base; low pitch → apex", "High pitch → apex; low pitch → base", "All pitches stimulate the whole cochlea equally", "Pitch is detected by the ossicles"],
        miss: ["", "Try the drum and bird again, then watch the highlighted region.", "Only a region vibrates most strongly for each pitch.", "Ossicles amplify vibrations; cochlear hair cells detect pitch."],
        why: "The cochlea is tonotopic: different frequencies peak at different positions." }] },
    { ic: "🎧", name: "Loudness and damage", tasks: [
      { type: "goal", ic: "🔊", do: "Drag <b>Loudness</b> above 90 dB.", look: "Loudness label + impulses", target: "≥ 90 dB",
        check: p => p.db >= 90 && p.heard, meter: p => ({ v: p.db, min: 20, max: 100, lo: 90, hi: 100, unit: " dB", label: "Loudness" }), hold: .5,
        why: "Louder sounds stimulate hair cells more strongly, sending more impulses per second." },
      { type: "pick", ic: "📈", do: "What changes when sound gets louder?", look: "Auditory nerve impulse dots",
        need: p => p.db >= 90, needTxt: "Set <b>Loudness</b> above 90 dB.",
        opts: ["More nerve impulses are sent each second", "The pitch must become higher", "The cochlea changes into the eardrum", "The auditory nerve becomes an ossicle"],
        miss: ["", "Pitch depends on frequency, not loudness.", "The cochlea and eardrum are different structures.", "The auditory nerve carries impulses; ossicles are bones."],
        why: "Loudness is coded by the number of impulses, not by changing the pitch region." },
      { type: "goal", ic: "📱", do: "Press <b>📱 Ringtone 15 kHz</b> and tick <b>🎧 Hearing damage</b>.", look: "Base hair cells", target: "High pitch not heard",
        check: p => p.freq > 12000 && p.damage && !p.heard, hold: .5,
        why: "The high-pitch base hair cells are damaged, so this high sound produces no impulses." },
      { type: "pick", ic: "🛡️", do: "Why can very loud music cause permanent hearing loss?", look: "Grey damaged hair cells",
        need: p => p.damage && p.freq > 12000, needTxt: "Keep <b>🎧 Hearing damage</b> on with <b>📱 Ringtone 15 kHz</b>.",
        opts: ["Hair cells can be damaged and do not grow back", "The pinna falls off", "The eardrum becomes a cochlea", "Low volume destroys ossicles"],
        miss: ["", "The model shows damaged hair cells, not the pinna.", "The eardrum and cochlea remain different parts.", "Low volume is safer; very loud sound is the danger."],
        why: "Protect hearing by keeping volume low and limiting time with loud sound." }] },
    { ic: "🧠", name: "Explain hearing", tasks: [
      { type: "fill", ic: "〰️", do: "Complete the receptor sentence.",
        text: "Hair cells in the {cochlea|pinna|ear canal} are receptors. They change {vibrations|light|hormones} into {nerve impulses|air pressure|sound waves}.",
        why: "The cochlea contains the sound receptors. The auditory nerve carries their impulses to the brain." },
      { type: "pick", ic: "👂", do: "Which range is closest to human hearing?",
        opts: ["About 20 Hz to 20,000 Hz", "About 2 Hz to 20 Hz", "Only 500 Hz", "All possible frequencies"],
        why: "Humans hear roughly 20–20,000 Hz, and the high end often falls with age or damage." },
      { type: "pick", ic: "🦴", do: "What do the ossicles do?",
        opts: ["Amplify vibrations from the eardrum to the oval window", "Detect pitch at the cochlear base", "Carry impulses to the brain", "Equalise pressure in the throat"],
        why: "The ossicles are tiny bones that pass on and amplify vibrations." }] }
  ]
};

SIM_CH.tropism = {
  title: "Auxin Experiment Trail", mins: 15,
  story: "Follow Darwin, Boysen-Jensen, Paál and Went. Predict, run and use the evidence to explain phototropism.",
  missions: [
    { ic: "🌱", name: "Darwin: the tip detects", tasks: [
      { type: "goal", ic: "🤔", do: "On <b>Charles Darwin</b>, predict every set-up card.", look: "Prediction cards A–D", target: "4 predictions made",
        check: p => p.inv === "darwin" && !p.ran && p.predicted === p.setups, meter: p => ({ v: p.predicted, min: 0, max: p.setups || 4, lo: p.setups || 4, hi: p.setups || 4, unit: "", label: "Predictions" }), hold: .2,
        why: "Predict first: the experiment can now test your idea." },
      { type: "goal", ic: "💡", do: "Press <b>💡 Run the experiment</b> and finish Darwin.", look: "Coleoptiles after 2 days", target: "Darwin run complete",
        check: p => p.inv === "darwin" && p.ran && simchDone(p, "darwin"), hold: .5,
        why: "The covered tip grows straight, but the covered lower part still bends. The tip detects unilateral light." },
      { type: "pick", ic: "🎯", do: "What did Darwin show?", look: "Darwin conclusion card",
        need: p => p.inv === "darwin" && p.ran, needTxt: "Run <b>Charles Darwin</b> first.",
        opts: ["The tip detects the direction of light", "The base detects light better than the tip", "Light stops all coleoptiles growing", "The opaque collar blocks the light detector"],
        miss: ["", "The opaque collar below the tip still bends.", "The intact coleoptile grows and bends.", "The collar is below the tip, so the tip can still detect light."],
        why: "Tip covered → straight. Lower part covered → bends. Therefore the tip detects light." }] },
    { ic: "🧪", name: "Boysen-Jensen: the signal moves", tasks: [
      { type: "goal", ic: "🧊", do: "Open <b>Boysen-Jensen</b>. Predict all cards, then run.", look: "Agar and mica set-ups", target: "Boysen-Jensen run complete",
        check: p => p.inv === "boysen1" && p.ran && simchDone(p, "boysen1"), hold: .5,
        why: "Agar lets the signal pass, but mica blocks it. The tip sends a chemical signal downwards." },
      { type: "pick", ic: "🪟", do: "Why does <b>tip on mica</b> give no growth?", look: "Boysen-Jensen result D",
        need: p => p.inv === "boysen1" && p.ran, needTxt: "Run <b>Boysen-Jensen</b>.",
        opts: ["Mica blocks the chemical from moving down", "Mica contains extra auxin", "Mica detects light for the tip", "Agar blocks all chemicals"],
        miss: ["", "Mica is the blocking plate in the model.", "The tip detects light; mica is just a barrier.", "Agar allows the chemical through."],
        why: "The growth signal is chemical because it can pass through agar but not mica." },
      { type: "goal", ic: "🌗", do: "Open <b>Boysen-Jensen ②</b>. Predict both cards, then run.", look: "Mica on lit vs shaded side", target: "Part 2 run complete",
        check: p => p.inv === "boysen2" && p.ran && simchDone(p, "boysen2"), hold: .5,
        why: "Blocking the shaded side stops bending. The chemical moves down the shaded side." },
      { type: "pick", ic: "⬇️", do: "Which side needs the chemical for bending?", look: "Boysen-Jensen ② conclusion",
        need: p => p.inv === "boysen2" && p.ran, needTxt: "Run <b>Boysen-Jensen ②</b>.",
        opts: ["The shaded side", "The lit side only", "Both sides equally", "Neither side; light pulls the shoot"],
        miss: ["", "Blocking the lit side still allows bending.", "If both sides were equal, it would grow straight.", "The shoot bends because one side grows faster, not because light pulls it."],
        why: "More chemical on the shaded side makes that side elongate more, bending the shoot towards light." }] },
    { ic: "🔴", name: "Paál and Went: auxin causes bending", tasks: [
      { type: "goal", ic: "🌙", do: "Open <b>Árpád Paál</b>. Predict both cards, then run.", look: "Tip placed on one side in darkness", target: "Paál run complete",
        check: p => p.inv === "paal" && p.ran && simchDone(p, "paal"), hold: .5,
        why: "A side tip causes that side to grow faster, even in darkness. The chemical alone can cause bending." },
      { type: "pick", ic: "📈", do: "What did Paál prove in darkness?", look: "Paál conclusion",
        need: p => p.inv === "paal" && p.ran, needTxt: "Run <b>Árpád Paál</b>.",
        opts: ["Unequal chemical distribution causes unequal growth", "Light is required for every bending response", "Agar blocks auxin", "The root detects the light"],
        miss: ["", "Paál's set-up is in darkness.", "Paál uses the tip itself, not agar.", "The experiment is on coleoptile shoots."],
        why: "More chemical on one side → more elongation on that side → bending away from that side." },
      { type: "goal", ic: "🧊", do: "Open <b>Frits Went</b>. Predict all cards, then run.", look: "Agar blocks X and Y", target: "Went run complete",
        check: p => p.inv === "went" && p.ran && simchDone(p, "went"), hold: .5,
        why: "Went showed the growth chemical can soak into agar. The shaded-side block has more of it." },
      { type: "pick", ic: "Y", do: "In Went, why does the X|Y set-up bend left?", look: "Blocks X and Y result",
        need: p => p.inv === "went" && p.ran, needTxt: "Run <b>Frits Went</b>.",
        opts: ["Block Y has more auxin, so the right side grows faster", "Block X has more auxin, so the left side grows faster", "Plain agar makes the shoot bend", "No growth happens without light"],
        miss: ["", "The model labels Y as the shaded-side block with more auxin.", "The shoot bends because one side grows faster.", "Went's chemical can cause growth in darkness."],
        why: "More auxin on the right side makes right-side cells elongate more, pushing the shoot left." }] },
    { ic: "🧠", name: "Build the auxin model", tasks: [
      { type: "order", ic: "🔢", do: "Put the phototropism mechanism in order.",
        items: ["The tip detects unilateral light", "Auxin is produced in the tip", "More auxin moves down the shaded side", "Shaded-side cells elongate more", "The shoot bends towards the light"],
        why: "Tip detects light → auxin becomes unequal → unequal elongation → bending towards light." },
      { type: "fill", ic: "✍️", do: "Complete the exam sentence.",
        text: "{Auxin|Mica|Agar} collects more on the {shaded|lit} side. Those cells {elongate|shrink} more, so the shoot bends {towards|away from} the light.",
        why: "Auxin promotes cell elongation in shoots. More elongation on the shaded side bends the shoot towards light." },
      { type: "pick", ic: "🕵️", do: "A classmate says: “The lit side grows faster.” What is wrong?",
        opts: ["The shaded side grows faster because it has more auxin", "The lit side always has more auxin", "Both sides stop growing in light", "Only roots respond to light"],
        miss: ["", "Went and Boysen-Jensen ② show more auxin on the shaded side.", "The coleoptile grows and bends in the light.", "Shoots show positive phototropism."],
        why: "In shoots, auxin on the shaded side causes greater elongation, so the shoot bends towards the light." }] }
  ]
};
